### ISSUE TITLE
Callback URL with hash(#) conflicts with non angular HTML5 mode apps

### ISSUE THREAD

**Issue by mocsharp** [AzureAD/azure-activedirectory-library-for-js#100]
It looks like Azure returns the token as URL + /#/id_token=................ With html5 mode set to false, I can no longer have azure return the token back to, e.g. http://localhost/#/validate?id_token.

This used to work when Azure OpenIdConnect was in preview.  :( any workaround?

Thanks!

**Comment by omercs** [comment]
This is oauth2 implicit flow and tokens are returned in fragment after #. Client side does not have control for id_token return.

**Comment by mocsharp** [comment]
So oauth2 implicit flow does not allow the return uri to be something like http://my_app.com/#!/validateToken?  This means Azure should return the token back to http://my_app.com/#validateToken#/id_token=................. instead of removing the "#1/validateToken"

**Comment by omercs** [comment]
You could have custom returnUri created at the AAD portal. Token will be returned to yourredirectUri + #id_token=eyJ0eXAiOiJKV1QiLCJhbGciOi....JSUzI1NiIsIng1dCI6Ik1uQ19

You also need to specify redirectUri in the config if you dont want to use base address as the return uri.

**Comment by mocsharp** [comment]
@omercs Thanks, that's what I did but Azure would remove the hash from my redirectUri.
e.g. If my redirect URI is http://myapp.com/#!/validate-token, I would expect Azure to return the token to 
http://myapp.com/#!/validate-token#id_token=........... but Azure actually returns http://myapp.com/#id_token=........... 

So i'm not sure if this is a bug with azure, it used to work while AzureOpenIdConnect was in preview.

**Comment by omercs** [comment]
Did you specify redirectUri in the angular config to overwrite default? Adal-angular will use base page address as the redirecturi.

**Comment by mocsharp** [comment]
Yes redirectUri is set to http://myapp.com/#!/validate-token#id_token=...........  but Azure would remove "#!/validate-token"

**Comment by PavelPikat** [comment]
You can't have hashes (#) in the redirect URI, but what Azure AD returns doesn't conflict with the app in non-html5 mode and tokens are stored correctly (we've tried). It will return the token to http://app.com/#id_token
Maybe you will need handle the routing and prevent the app from trying to navigate to "id_token" and "access_token" states.

**Comment by tushargupta51** [comment]
@mocsharp I tested an app with a reply uri that has # in it, Azure would remove the hash when returning the token in the response. This is not something that we can control from ADAL, it is an AAD behavior, in the request sent out to AAD, adal includes the right redirect_uri (one that has the '#'). Closing this issue as this is out of scope of adal.

**Comment by viganella** [comment]
So the issue got closed just like this, with  no clear direction where to look at? Interesting.

**Comment by kalyankrishna1** [comment]
> So the issue got closed just like this, with no clear direction where to look at? Interesting.

Please use the [feature request] (https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/35581492-enable-the-option-for-adding-in-the-reply-url-fo) at the user voice page to request this functionality

**Comment by ryancerium** [comment]
I came up with a simple workaround.  I put in a static HTML file in the root, `/azure.html`, and set the redirect page to that:

```
<html>

<body>
    <script src="libs/msal/msal/dist/msal.min.js"></script>
    <script type="text/javascript">
        // Microsoft login redirects back to this page and requires this object before it closes the popup.
        // See https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/174
        if (location.hash.includes("id_token")) {
            new Msal.UserAgentApplication("Your_Client_ID", null, null);
        }
    </script>
</body>

</html>
```

**Comment by maxxt** [comment]
Are there any updates on this?
Do we have a workaround for SPA with '#'?

**Comment by ryancerium** [comment]
@maxxt You need to put in a nearly-empty static page that loads the JS library and set that as your redirect location.  That *is* the workaround.  You can't redirect to a SPA location with a '#' in it.

**Comment by maxxt** [comment]
@ryancerium How do you set a *.html path in Azure Redirect URIs without getting an error?

![image](https://user-images.githubusercontent.com/13865090/49569037-766c5d00-f93b-11e8-8dfd-8ba54c2c94ad.png)

**Comment by ryancerium** [comment]
You need the `s`, for "secure", in your URI.  `https://localhost:4200/assets/azure.html`

**Comment by maxxt** [comment]
Uri is valid if I keep http and remove .html so ssl is not the issue here

**Comment by ryancerium** [comment]
Then rename `azure.html` to `azure` and redirect to `http://localhost:4200/assets/azure`.  Otherwise, I'm just reading the friendly error message and the documentation.

https://docs.microsoft.com/en-us/azure/app-service/app-service-mobile-how-to-configure-active-directory-authentication

**Comment by maxxt** [comment]
@ryancerium That does not work either. 

If I put http://localhost:4200/assets/azure as the redirect uri then the page is taken straight to localhost:4200

**Comment by shabbir-dhangot** [comment]
Why issue is closed. I am still facing issues in 2021.
