### ISSUE TITLE
ui-router not working properly

### ISSUE THREAD

**Issue by omercs** [AzureAD/azure-activedirectory-library-for-js#104]
Stackoverflow:

I'm currently trying to hook in the Azure Directory Authentication Library (ADAL.JS) into UI-Router. I've got it wired in, and it redirects correctly, but it always chucks a 404 before the redirect. The redirect works, and then gets sent back to my application, which is showing the 404.

I've modified the state like so:

        {
            state: 'admin',
            config: {
                url: '/admin',
                templateUrl: 'app/admin/admin.html',
                controller: 'AdminController',
                controllerAs: 'vm',
                title: 'Admin',
                settings: {
                    nav: 2,
                    content: '<i class="fa fa-lock"></i> Admin'
                },
                requireADLogin: true
            }
I've got it working with the normal Angular RouteProvider, and no 404 is being thrown.
http://stackoverflow.com/questions/29428427/ui-router-404-when-redirecting-with-adal/29436722#29436722

**Comment by omercs** [comment]
Fix: update state handler

**Comment by levalencia** [comment]
can you please let me know how did you fix it? its not clear for me with your comment.  I have an infinite loop :+1:  http://stackoverflow.com/questions/30924318/infinite-loop-when-setting-requireadlogin-true-on-stateprovider

**Comment by levalencia** [comment]
if I understand correctly, will it work with 1.0.3 or 1.0.4, I ask it because CDN has only 1.0.0

**Comment by levalencia** [comment]
@weijjia mention :)

**Comment by Supratentorial** [comment]
https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/105 fixes this issue I think, and this bug report closed? I'll give 1.0.4 a try to see if the bug persists.

**Comment by levalencia** [comment]
for me the bug persists, my code is the SO question, help is really appreciated!

**Comment by levalencia** [comment]
code sample for config.js


function config($stateProvider, $urlRouterProvider, $ocLazyLoadProvider, IdleProvider, KeepaliveProvider, adalAuthenticationServiceProvider, $httpProvider) {

    // Configure Idle settings
    IdleProvider.idle(5); // in seconds
    IdleProvider.timeout(120); // in seconds

    $urlRouterProvider.otherwise("/dashboards/dashboard_1");

    $ocLazyLoadProvider.config({
        // Set to true if you want to see what and when is dynamically loaded
        debug: false
    });

    $stateProvider

        .state('dashboards', {
            abstract: true,
            url: "/dashboards",
            templateUrl: "views/common/content.html",

        })
        .state('dashboards.dashboard_1', {
            url: "/dashboard_1",
            templateUrl: "views/dashboard_1.html",
            requireADLogin: true,
            resolve: {
                loadPlugin: function ($ocLazyLoad) {
                    return $ocLazyLoad.load([
                        {

                            serie: true,
                            name: 'angular-flot',
                            files: ['js/plugins/flot/jquery.flot.js', 'js/plugins/flot/jquery.flot.time.js', 'js/plugins/flot/jquery.flot.tooltip.min.js', 'js/plugins/flot/jquery.flot.spline.js', 'js/plugins/flot/jquery.flot.resize.js', 'js/plugins/flot/jquery.flot.pie.js', 'js/plugins/flot/curvedLines.js', 'js/plugins/flot/angular-flot.js', ]
                        },
                        {
                            name: 'angles',
                            files: ['js/plugins/chartJs/angles.js', 'js/plugins/chartJs/Chart.min.js']
                        },
                        {
                            name: 'angular-peity',
                            files: ['js/plugins/peity/jquery.peity.min.js', 'js/plugins/peity/angular-peity.js']
                        }
                    ]);
                }
            }
        })

**Comment by imaji** [comment]
Hi,

I raised the original issue on SO listed above.  I'm still having trouble with hooking this into UI Router, how did you test the integration?  I can't see any tests in the repo that tested this with UI Router.

Many thanks,
John

**Comment by sarmut** [comment]
Any updates on this please?  I'm using ui-router as well and the authentication is not triggered :(

**Comment by sarmut** [comment]
never mind.. it is working.

**Comment by CodyMorris** [comment]
@sarmut i'm having this issue, what did you to to resolve it?

**Comment by sarmut** [comment]
@CodyMorris sorry for missing this ping.. it was long time back.. don't remember exactly what I did to fix it.  let me know if you still face the problem.

**Comment by CodyMorris** [comment]
@sarmut  thanks for the response!  I guess I'll go ahead and share what resolved it for me.

My issue was with using this plugin without HTML5 mode on.  As has been discussed many many times on a few different github issues, the /#/ that is in non-html5 mode angular apps causes significant problems with adalJs.

My final solution (although it wont work for people using a pure static app on a CDN) was to enable HTML5 mode, and enable html5 mode routing in NGINX.

Hope this helps someone else

**Comment by mderaeve** [comment]
Is there somebody with experience using the adalAuthenticationServiceProvider togehter with the new component router?

**Comment by LokeshBoran** [comment]
Hello, @levalencia ,
I got same issue this occurs when adal.expiration.key is expired then this goes into infinite loop. And ADAL not logging out the application.

If you find the solution please tell me.

**Comment by stuarthallows** [comment]
I was using html 5 mode and what fixed it for me was explicitly setting the hash prefix, i.e.

    $locationProvider.html5Mode(true).hashPrefix('!');

I had assumed that if the prefix was not set it would default to '!' so I'd left it off. See point 3 [here](https://github.com/AzureAD/azure-activedirectory-library-for-js).

**Comment by tushargupta51** [comment]
We have released 1.0.11 with fixes to some of the ui-router issues. Please use 1.0.11 and have a look here if you are still running into this issue: https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs
