### ISSUE TITLE
Token parsing breaks if using html5Mode.

### ISSUE THREAD

**Issue by martellaj** [AzureAD/azure-activedirectory-library-for-js#109]
If I configure my app to use html5Mode, login fails because ADAL JS parsing breaks. I'm assuming it needs to see that preceding "#" or it fails. This needs to be fixed or at the very least update the error that is thrown (as it was not helpful at all).

**Comment by omercs** [comment]
You can add html5 prefix as $locationProvider.html5Mode(true).hashPrefix('!');

**Comment by martellaj** [comment]
Cool - thanks for the info. I wasn't aware.
