### ISSUE TITLE
Fallback to 'id_token' field when refreshing the token

### ISSUE THREAD

**Issue by sdurandeu** [AzureAD/azure-activedirectory-library-for-js#110]
I'm using adal.js without the angular module. I've seen that when the token was expired and thus silently refreshed, the library was calling the acquireToken() callback with an empty error string and 'undefined' value for the token. I've inspected the requestInfo object in the handleWindowCallback method and found that the renewed token came in the 'id_token' field, instead of the 'access_token' field (case requestInfo.requestType === this.REQUEST_TYPE.RENEW_TOKEN)

![image](https://cloud.githubusercontent.com/assets/821193/7239960/111fdfde-e784-11e4-8349-816add9629d9.png)

I've made the following change in the handleWindowCallback() method:

![image](https://cloud.githubusercontent.com/assets/821193/7239983/3a616e8a-e784-11e4-8b51-747a2f19155c.png)

Please let me know if I'm missing something or I have some misconfiguration. 

Just for clarification I've also made the fix here: https://github.com/sdurandeu/azure-activedirectory-library-for-js/commit/9e84a1f44d0fa2385d562fd123bf7e7b87dd9b38

**Comment by omercs** [comment]
In angular related calls, it is doing as you suggested. Can you send a pull request to dev branch with your changes?

**Comment by sdurandeu** [comment]
Sure! Done. https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/112
