### ISSUE TITLE
redirecting to a protected resource throws route change error

### ISSUE THREAD

**Issue by bigerock** [AzureAD/azure-activedirectory-library-for-js#111]
when you use requireADLogin: true on a route, and redirect to it while not authenticated, it is throwing a route change error and then proceeds to properly redirect to the microsoft login page.

although it is ultimately working, is is throwing the error. it's as if it is not rejecting the route properly. is there anything i can do to prevent this error?

**Comment by omercs** [comment]
What is this route change error? Can you share the details?

**Comment by bigerock** [comment]
yes, i will try. it happens when the user is logged out, and clicks a link that is protected by requireADLogin. 

here's the error:

Error: [$compile:tpload] Failed to load template: /app/dashboard/dashboard.html
http://errors.angularjs.org/1.3.0/$compile/tpload?p0=%2Fapp%2Fdashboard%2Fdashboard.html

and here's the trace:

  at REGEX_STRING_REGEXP (angular.js:80)
    at handleError (angular.js:15773)
    at processQueue (angular.js:12914)
    at angular.js:12930
    at Scope.$get.Scope.$eval (angular.js:14123)
    at Scope.$get.Scope.$digest (angular.js:13939)
    at Scope.$get.Scope.$apply (angular.js:14227)
    at HTMLHtmlElement.<anonymous> (angular.js:11131)
    at HTMLHtmlElement.n.event.dispatch (jquery.min.js:3)
    at HTMLHtmlElement.n.event.add.r.handle (jquery.min.js:3)

Then, it does continue on to the microsoft login.

'app/dashboard/dashboard.html' is the page that is protected and the page we are trying to go to.

Please let me know if you need further details.

**Comment by omercs** [comment]
Interceptor in adal-angular.js cancels the request when login is started for this route.

**Comment by bigerock** [comment]
correct, but this throws a script error before performing the redirect. is there any way to catch or suppress this error?

**Comment by tushargupta51** [comment]
@bigerock we will add an even that you can listen to whenever a request is rejected.
