### ISSUE TITLE
Fetching multiple tokens in a row should be parallelized

### ISSUE THREAD

**Issue by brphelps** [AzureAD/azure-activedirectory-library-for-js#113]
I've observed behavior in the library where acquiring three different tokens is an operation that I have to manually serialize in order to "protect" the sanctity of the individual calls.  Serializing these three acquisitions is an obvious perf bottleneck -- is there any way that multiple iframes could be used in parallel instead of a single one which becomes interrupted as more acquireToken requests are processed?

**Comment by omercs** [comment]
@brphelps: This is an interesting issue. We could add a new iframe for different token requests.

**Comment by milkolori** [comment]
+1

**Comment by brphelps** [comment]
Did both of these issues get closed without a fix?

**Comment by tushargupta51** [comment]
@brphelps there is an open issue here: https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/177
