### ISSUE TITLE
Documentation that doesn't require IIS/.NET?

### ISSUE THREAD

**Issue by LIDJungle** [AzureAD/azure-activedirectory-library-for-js#115]
I've been trying to work with this library for two days. I am using a traditional LAMP stack, and trying to find docs that address this is pointless. The only sample you provide requires Visual Studio (a 14GB download!) and starts talking about the "web.config" file.

I'm still having trouble figuring out if this REQUIRES .NET or not. Some BS called OWIN?

I have done oAuth in many different languages... And I can't get anything to work using this library and documentation. It would be nice if you at least had a full example from the docs provided. #6 in the readme. Nowhere in this project do you show how the whole thing comes together, and the only demo code you have requires IIS and .NET.

You're asking me to switch editors, Web Servers, OS... Too much. At the very least be clear on what is required to use this.

**Comment by vibronet** [comment]
An official sample with a node JS backend is coming. In the meanwhile you can take a look at https://github.com/matvelloso/AADNodeJWT for a full no-.NET use of the product.
