### ISSUE TITLE
make available on NPM

### ISSUE THREAD

**Issue by zachcarroll** [AzureAD/azure-activedirectory-library-for-js#117]
this would be super useful and helpful.

**Comment by alrouen** [comment]
+1

**Comment by zachcarroll** [comment]
I'm trying to implement with gulp-browserify and having tons of trouble.

**Comment by zachcarroll** [comment]
has anyone implemented this library with gulp and browserify along with other npm modules? I'd really appreciate an example.

**Comment by alrouen** [comment]
In fact I just tried that today.  Basically I had to copy/paste the Adal.js file in my project (gulp/browerify/reactjs) and hack the source code : 
- first : comment the dependency injector (lines 24-35)
- second : add at the bottom of the file a module.exports = AuthenticationContext;
- third : in any other project file : var  AuthenticationContext = require('relative/path to/myadal.js');

Then you just need to create a new instance with conf object as constructor parameter.

So far it works.

**Comment by alrouen** [comment]
In fact... no it does not work properly, if part of browserify build. This lib must be loaded as an external resource.

**Comment by gustavgahm** [comment]
+1

**Comment by sondreb** [comment]
+1

Use NPM for all our client resources, avoid having two package managers is a good thing.

**Comment by wakurth** [comment]
+1

**Comment by sondreb** [comment]
Same here, please publish on NPM. Have stopped using Bower, most client libs are available on NPM.

**Comment by smastous** [comment]
+1

**Comment by tedvanderveen** [comment]
+1

**Comment by martellaj** [comment]
+1. I use this for all of [OfficeDev](www.github.com/OfficeDev)'s Angular samples and it's a real pain to update the CDNs in each branch of each project manually. NPM is where it's at while most people stray from Bower.

**Comment by Beanow** [comment]
+1

**Comment by stevenfollis** [comment]
+1

**Comment by wakurth** [comment]
necro bump. bueller?

**Comment by andrewconnell** [comment]
+1 ... the silence is disappointing on this issue. Would be nice if this was in the leading package distro today. Can even publish straight from this repo. Until then, I guess we can keep using this:

```shell
$ npm install AzureAD/azure-activedirectory-library-for-js
```

**Comment by ash-rain** [comment]
+1

**Comment by Mansyn** [comment]
+1

**Comment by tushargupta51** [comment]
Available on npm: https://www.npmjs.com/package/adal-angular
