### ISSUE TITLE
Multiple simultaneous request to the same endpoint got canceled when token is acquired for the first time

### ISSUE THREAD

**Issue by milkolori** [AzureAD/azure-activedirectory-library-for-js#120]
I have a page which displays multiple images stored in office 365. When the user logs in and there is still no token for the particular endpoint, then for each image a new acquireToken request is fired, which cause the cancelation of the previous acquireToken request and the page ends up with only the last image displayed. 
I think in adal-angular there should be a logic to caches the promise for acquireToken request and use this promise instead of new acquireToken call until the cached promise is resolved.

I created a simple wrapper for that purpose and it works as expected.

**Comment by BartVDACodeware** [comment]
Intresting. can you share your solution

**Comment by milkolori** [comment]
This is my wrapper service for adal authentication:

    AdalModule.factory('CachedAquireTokenService', ['adalAuthenticationService', '$q', function (authService, $q) {
        var resourceTokenPromises = {};

        function acquireToken(resource) {
            if (angular.isDefined(resourceTokenPromises[resource])) {
                return resourceTokenPromises[resource];
            }

            var delayedRequest = $q.defer();
            authService.acquireToken(resource).then(function (token) {
                delayedRequest.resolve(token);
                delete resourceTokenPromises[resource];
            }, function (err) {
                delayedRequest.reject(err);
                delete resourceTokenPromises[resource];
            });
            resourceTokenPromises[resource] = delayedRequest.promise;
            return delayedRequest.promise;
        }

        return {
            acquireToken: acquireToken
        };
    }]);

And after that in ProtectedResourceInterceptor instead of directly using "authService.acquireToken" I am using the wrapper "CachedAquireTokenService.acquireToken"

**Comment by weijjia** [comment]
This should have been fixed in the previous release, check it out please.
