### ISSUE TITLE
Release v1.0.1 

### ISSUE THREAD

**Issue by sergsalo** [AzureAD/azure-activedirectory-library-for-js#121]
https://github.com/AzureAD/azure-activedirectory-library-for-js/releases/tag/v1.0.1 this seems to indicate that there is new version of adal.js available. But two files adal.min.js and adal-angular.min.js are exactly the same for azure-activedirectory-library-for-js-1.0.1.zip and azure-activedirectory-library-for-js-1.0.0.zip releases.
Even the header of those files indicate that these are the same:
/*! adal-angular v1.0.0 2015-02-18 */

Am I missing something?

**Comment by ryanflowers** [comment]
+1

**Comment by omercs** [comment]
Fixed in new releases
