### ISSUE TITLE
Bower 1.0.1 version includes '|| ||' bug

### ISSUE THREAD

**Issue by ajbenton** [AzureAD/azure-activedirectory-library-for-js#126]
The bower distribution is currently broken (minified version not being updated notwithstanding).

The bug was fixed in this commit:
https://github.com/AzureAD/azure-activedirectory-library-for-js/commit/519826def94445f6cc960dbfda8b9cb19eaffa9d

**Comment by omercs** [comment]
Latest release fixes this issue, so i am closing this.
