### ISSUE TITLE
Loses query string parameters when token expires

### ISSUE THREAD

**Issue by Xatter** [AzureAD/azure-activedirectory-library-for-js#130]
Currently if you leave an ADAL enabled application open past the authentication timeout (token expires) and have parameters in your query string, it does not restore those query string parameters after redirecting back to the application on successful login

**Comment by juho-hanhimaki** [comment]
Same thing happens with the fragment parameters. At the moment there seems to be no way to preserve any parameters which makes this library very impractical to use.
