### ISSUE TITLE
Redirect to a protected route after login

### ISSUE THREAD

**Issue by mickael83** [AzureAD/azure-activedirectory-library-for-js#135]
Hi,

I have an angular app that is using ui-router to provide a public state and a private state (requireADLogin: true). When I navigate to the private state, the login process is triggered correctly however after the authentication process is done, the user is redirected to the public state instead of the private state.

I was expecting the user to be redirected to the requested state, is there any way to get this behavior?

**Comment by Supratentorial** [comment]
+1 I also have this issue. Can confirm that after authentication via Azaure AD the app does not redirect back to the protected route.

**Comment by weijjia** [comment]
You can specify the redirect uri in the config (if you do so, make sure you also set it in the Azure AD portal), otherwise we will use the app home uri as the redirect uri. Once authentication process is done, user will be redirect to the specified redirect uri.

**Comment by tushargupta51** [comment]
@mickael83 @Supratentorial can you guys share a repro or console logs (instructions on home page)? I do not see the behavior when I run app that uses ui-router locally. It redirects to the private state correctly after login.

**Comment by polita** [comment]
We can't repro this issue. Please let us know if you can help us repro, and we will look at it again.
