### ISSUE TITLE
only on IE10 => adal.js - 0x800a13af - JavaScript runtime error: Redeclaration of const property

### ISSUE THREAD

**Issue by nabilbo** [AzureAD/azure-activedirectory-library-for-js#136]
Hello, 

When i'm running Adal.js with IE10, i get this error :
`Unhandled exception at line 2, column 40 in https://secure.aadcdn.microsoftonline-p.com/lib/1.0.0/js/adal.min.js
0x800a13af - JavaScript runtime error: Redeclaration of const property`

I tested with Safari 8, IE11, Chrome 43, and Firefox38, and i don't get this error ...

thank you for your help !
Nabil

**Comment by roger-grayson** [comment]
at the beginning of both adal.js 1.0.0 and adal-angular.js you have the simillar blocks of code which are causing this issue (example from adal-angular.js):
```javascript 
    if (typeof module !== 'undefined' && module.exports) {
        var window, localStorage, angular, document, AuthenticationContext;
        module.exports.inject = function (windowInj, localStorageInj, documentInj, MathInj, angularInj, adalInj) {
            window = windowInj;
            localStorage = localStorageInj;
            document = documentInj;
            Math = MathInj; // jshint ignore:line
            angular = angularInj;
            AuthenticationContext = adalInj;
        };
    }
Specifically, IE does not like the fact that the code is declaring window, localStorage, and document in a var statement. 

I commented the entire block of code out of both libs in my test case (an angular app using adal.js and adal-angular.js to authenticate against AzureAd and then push and pull info out of a SharePoiint list) and that appears to fix the issue in IE without breaking the app in FireFox or Chrome. 

I'm sure this is not the optimal solution, but it works for now.

**Comment by M1Les** [comment]
Wrapping these blocks with IIFEs resolved this error for me. Like that:
https://github.com/M1Les/azure-activedirectory-library-for-js/commit/ba59f0afa05313afc6177dc92da6c77aca4f2c87

Not sure whether this breaks the tests or not though.
