### ISSUE TITLE
ProtectedResourceInterceptor causes conflicts when an app has mixed authentication types

### ISSUE THREAD

**Issue by RobARichardson** [AzureAD/azure-activedirectory-library-for-js#137]
I have an application that uses mixed modes of authentication.  One set of users can sign-in with Azure AD while another set uses ASP.NET Identity + Web API.  When a user is an Azure AD user, I want ProtectedResourceInterceptor to function as it should.  However, when the user is not an Azure AD user, I want the ProtectedResourceInterceptor to not interfere with the request at all.  Unless I'm missing something, that doesn't seem possible currently. What if ProtectedResourceInterceptor used  authService.userInfo.isAuthenticated and did nothing (completely bypassed all logic) when false?

**Comment by weijjia** [comment]
ProtectedResourceInterceptor will call acquireToken, and we will check if the user is logged in, if not, there will be error telling you to go through login.

**Comment by polita** [comment]
The interceptor will broadcast a NotAuthorized event if authService.userInfo.isAuthenticated is false. You can plug in your listener to that event for custom logic. Let us know if this doesn't resolve the issue for you.
