### ISSUE TITLE
Multiple Service calls cannot be queued during token renewal

### ISSUE THREAD

**Issue by mockorp** [AzureAD/azure-activedirectory-library-for-js#139]
The adal-angular library defers $http calls when the token has expired and retries them once the iFrame returns with a new token.  However, since only one callback is maintained in 1.0.0 (one per resource in the latest 1.0.3 code), only the last $http call will actually be resolved.  This will leave an http call "hanging" if a controller attempts to make multiple calls while a token is renewed.

A unit test to confirm the issue is available at:
https://gist.github.com/mockorp/aeedb60e44d3c2b8466f

**Comment by mockorp** [comment]
After looking a little more, it looks like the unit test does not confirm the issue on the master branch.  The callBacksMappedToRenewStates would theoretically handle this scenario since each renewal would have a different state.  However, the IFrame is limited to only one instance at a time, meaning that only the first state would ever make it to the IFrame and the subsequent calls would not trigger a renew, and thus their callback would still not be called.  

It appears that the solution should be to detect if there is an outstanding renewal for a given resource and build a list of callbacks for all calls waiting on that renewal until it completes.  Once the renewal is done, each callback should be called.  I got this working in 1.0.0 and will try to integrate the fix into master and submit a pull request.

**Comment by RobARichardson** [comment]
+1

**Comment by boettr** [comment]
Wish I had looked here before spending half a day coming to the same conclusion.

Are you still progressing with the pull request?

**Comment by weijjia** [comment]
This has been fixed in the latest release.
