### ISSUE TITLE
The line "var window, localStorage, angular, document, sessionStorage;" breaks adal.js for IE 10.

### ISSUE THREAD

**Issue by roger-grayson** [AzureAD/azure-activedirectory-library-for-js#141]
in adal.js 1.0.0 line number 24 
```javascript
    var window, localStorage, angular, document, AuthenticationContext;
```
and in adal-angular.js 1.0.0 line number 22 
```javascript
    var window, localStorage, angular, document, AuthenticationContext;
```
Cause the javascript error : "0x800a13af - JavaScript runtime error: Redeclaration of const property" in IE 10 because IE 10 does not like it when you try to declare window, document, etc. as vars.

Commenting out the block of code surrounding the offending var statement will make the libs work in IE 10, Firefox, and Chrome - but I'm guessing this is not the optimal solution.

**Comment by omercs** [comment]
Same as #136
