### ISSUE TITLE
Is this tool works with AngularJs in IE8 ?

### ISSUE THREAD

**Issue by AbdoDabbas** [AzureAD/azure-activedirectory-library-for-js#144]
I can't manage this to work with AngularJs in IE8, is there something wrong I'm doing ?

**Comment by dstrockis** [comment]
@omercs or @weijjia have we tested adal.js with IE8?

**Comment by dstrockis** [comment]
@AbdoDabbas if you want to provide some simple html in the comments here that specifically shows ADAL causing the app to break in IE 8, I'm sure it would help identify the problem more quickly.

**Comment by AbdoDabbas** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Sure, few hours and will provide you with one.
    
    
    On 6/23/2015 7:28 PM, Danny Strockis
      wrote:
    
    
      @AbdoDabbas if you want to provide
        some simple html in the comments here that specifically shows
        ADAL causing the app to break in IE 8, I'm sure it would help
        identify the problem more quickly.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by weijjia** [comment]
Any update to this? I'm going to close the issue, and please reopen it if you see this happened again.
