### ISSUE TITLE
adal:loginFailure and adal:notAuthorized are not firing

### ISSUE THREAD

**Issue by prashanthpp** [AzureAD/azure-activedirectory-library-for-js#146]
We wanted to track the login failures/not authorized logins in AAD landing page. Per say there is an error like username/password not found or active directory is not having access to the app "AADSTS50020" errors which gets showed on the AAD landing page, how the calling application will get to know these details. Tried with the below code but they are not firing. Please suggest

    $scope.$on("adal:loginFailure", function () {
        $scope.testMessage = "loginFailure";
        $location.path("/login");
    });

    $scope.$on("adal:notAuthorized", function (event, rejection, forResource) {
        $scope.testMessage = "It is not Authorized for resource:" + forResource;
    });

**Comment by weijjia** [comment]
This is the same as the same of this post: http://stackoverflow.com/questions/31128554/how-to-capture-aad-landing-page-errors/31129647

If it's error only displays on AAD landing page, and not redirected back to ADAL, i don't think you can catch the error with $scope.$on.

**Comment by weijjia** [comment]
Close for now. If you get any more questions, re-open it again or continue the discussion on stackoverflow.
