### ISSUE TITLE
Trying to call O365 APIs in Outlook App (AngularJS, AdalJS) - Error

### ISSUE THREAD

**Issue by matejv1** [AzureAD/azure-activedirectory-library-for-js#156]
![image](https://cloud.githubusercontent.com/assets/255273/8896003/79ca038c-33ee-11e5-96b9-0aa2fdbe6567.png)

![image](https://cloud.githubusercontent.com/assets/255273/8896005/7ddd0168-33ee-11e5-9607-456043781bef.png)

outlook-web-16:00.js - Uncaught Sys.ArgumentNullException: Sys.ArgumentNullException: Value cannot be null. Parameter name: conversationId

This is an error that I'm getting when I try to call any of the O365 APIs (outlook, sharepoint ..) inside of Outlook app. I've added some code to project created by andrewconnell in https://github.com/OfficeDev/TrainingContent - O3657/O3657-3 Building Office Apps for Outlo

My forked repository and changes https://github.com/matejv1/TrainingContent

added AnalJS, homeController, getFiles method inside of customerServices.js
If I remove manual bootstrapping of AngularJS inside of Office.initialize function + add ng-app directive on a DOM element this issue disappears but then we don't have an access to Office.js API since it is not yet initialized, which is critical in case you want to show something that is current email related.

Hopefully this is the best place to discuss this issue. PS:I've deleted the app with ID pushed in commit that I did - so no worries. I think.

**Comment by matejv1** [comment]
I've gone around this issue. Removed bootstrap late initialization of angular and moved Office.initialization inside of controller(added init() call inside). Ng-app directive is back in html also.

**Comment by pbjorklund** [comment]
I have the same problem. Could you share the code you used to get it workign_

**Comment by matejv1** [comment]
Check my repos - there is code. (reply from my phone)

**Comment by marks** [comment]
@matejv1 I am struggling with this issue - the diff in your repo seems quite large, can you help point me in the right direction?

**Comment by flyher** [comment]
@matejv1 
@marks 
Hi all, i met the same issue in outlook add-ins, could you help me?
I search the same issue by google, but i cannot get the answer.

https://github.com/OfficeDev/Word-Add-in-AngularJS-Client-OAuth/issues/6

https://social.msdn.microsoft.com/Forums/lync/en-US/592ea63a-dbe4-4c8c-9926-d9f3b3129cae/office-365-dialog-api-throwing-error-in-outlook-web?forum=appsforoffice

https://stackoverflow.com/questions/35358911/first-time-loading-outlook-web-add-in-error-on-console

https://stackoverflow.com/questions/29294751/office365-app-for-excel-web-value-cannot-be-null-parameter-name-conversation
