### ISSUE TITLE
adal.js fails to log in on Microsoft Edge with error "AADSTS50058: User account identifier is not provided"

### ISSUE THREAD

**Issue by vadimm** [AzureAD/azure-activedirectory-library-for-js#157]
When trying to log into our app using adal.js we get the following error pasted below.
Steps: 
1. Win10, Edge, new InPrivate browsing window
2. Navigate to my app, it redirects to AAD credentials input page
3. Type in user's email address (we tried several different accounts - same results as below for each one)
4. After typing email address page sais 'Redirecting to your org sign-in page'
5. ADAL does NOT show internal MS login page, does NOT ask for password.
6. It redirects back directly to the app.
7. However when the app attempts to read tokens via the JS library we get this error:
"adal.failed.renew":"AADSTS50058: User account identifier is not provided.\r\nTrace ID: 21ed6369-be13-474c-aa24-bd036f61b7a4\r\nCorrelation ID: 0cdbd174-3dfc-4c3c-ab54-dae2159a4769\r\nTimestamp: 2015-08-10 23:21:06Z",
"adal.error":"login_required",
"adal.error.description":"AADSTS50058: User account identifier is not provided.\r\nTrace ID: 21ed6369-be13-474c-aa24-bd036f61b7a4\r\nCorrelation ID: 0cdbd174-3dfc-4c3c-ab54-dae2159a4769\r\nTimestamp: 2015-08-10 23:21:06Z",
"adal.session.state":"bcab2540-cb7a-42fd-b8da-8c0b8ddfe85f",

Please contact vadimm@microsoft.com for full dump of localStorage and any additional repro information.

**Comment by lukianol** [comment]
Hi, we experience the same issue

**Comment by lukianol** [comment]
Workaround: add an authority page to trusted sites (e.g. IE->Internet Options->Security->Trusted Sites-> Sites -> Add)

**Comment by weijjia** [comment]
Are you still seeing the issue after adding authority site into trusted sites?

**Comment by weijjia** [comment]
I'm closing the issue, and please reopen it if you see this happen again.
