### ISSUE TITLE
Adal not working for IE9

### ISSUE THREAD

**Issue by danielarita** [AzureAD/azure-activedirectory-library-for-js#159]
Hi,

I was trying this integration with IE9 and didn't work. I saw the logs said this browser is not supported. Looking a little bit into the code saw that this was a problem because IE9 doesn't support window.atob.

I downloaded a library called "base64.js", http://www.movable-type.co.uk/scripts/base64.js 

I modified the code to use: Base64.decode(base64IdToken) instead of window.atob(base64IdToken), and this enabled IE9 to worked.

I think this library could be implemented or make a variation so IE9 keeps being supported.

**Comment by NerdPad** [comment]
I am having the same issue. Please do not use window.atob

**Comment by weijjia** [comment]
Thanks for pointing this out. Will add the support for this.

**Comment by sfgadjo** [comment]
+1

**Comment by weijjia** [comment]
please check the latest version.
