### ISSUE TITLE
locationChangeHandler() calls unsupported $window.location.origin in IE

### ISSUE THREAD

**Issue by maitre-matt** [AzureAD/azure-activedirectory-library-for-js#172]
Testing with IE 11, $window.location.origin returns undefined in this piece of code:

85                         if ($location.$$html5) { 
86                             $window.location = $window.location.origin + $window.location.pathname; 
87                         } else { 
88                             $window.location.hash = ''; 
89                         } 

It looks like this is not supported and the web has some workarounds:
http://tosbourn.com/a-fix-for-window-location-origin-in-internet-explorer/
http://www.w3schools.com/jsref/prop_loc_origin.asp

**Comment by weijjia** [comment]
Thanks @maitre-matt. We will add the support for future release.

**Comment by tushargupta51** [comment]
We removed that code in 1.0.11.
