### ISSUE TITLE
Token Signature Validation

### ISSUE THREAD

**Issue by Bartmax** [AzureAD/azure-activedirectory-library-for-js#175]
Is the token signature validated ?

**Comment by weijjia** [comment]
Nope, adal.js currently doesn't do token signature validation, but this is something we're planning to add in the library.

**Comment by Bartmax** [comment]
Thanks. I'm leaving this open for you to tracking. Feel free to close it.

**Comment by brentschmaltz** [comment]
adal does not validate tokens.
