### ISSUE TITLE
adal.js seems is super chatty

### ISSUE THREAD

**Issue by tonyblues** [AzureAD/azure-activedirectory-library-for-js#176]
adal.js seems to be super chatty. Can we somehow have a way to "mute" it?
Here is a screenshot of the Chrome console output.
![adajs-chatty-logs](https://cloud.githubusercontent.com/assets/1132864/10442518/d9b94c48-7107-11e5-8222-f9a295e4b67c.png)

**Comment by weijjia** [comment]
In the next version, we gonna log in the user specified way. That being said, if you don't want the logs, you can simply doesn't specify the logging method.

**Comment by weijjia** [comment]
closed for now, and please reopen it if you see it again.

**Comment by tonyblues** [comment]
That's awesome! Thank you!
