### ISSUE TITLE
Simultaneous Token Request After Login

### ISSUE THREAD

**Issue by PrisonerZERO** [AzureAD/azure-activedirectory-library-for-js#177]
Hi Vittorio,

We are excited about ADAL.  However, we just wanted to give you some feedback on some challenges we ran into while implementing ADAL JS.  

We have an application which talks to many other API solutions.  For example, our (main) Dashboard Solution has its own internal API, but it also talks to an Exceptions Management solutions API, and an Alarms Solution API etc.

Originally, upon successful login, we would attempt to acquire all the related token needed for this set of Data Service calls.  Oddly, we noticed only the last call in the collection would successfully execute.  As a result, we would (then) have to refresh the page multiple times before all the data would resolve.

Upon further investigation, we discovered you are using an IFRAME to resolve individual tokens.  When grouped as a deferred collection, one IFRAME overwrites the other.  As such, we decided to chain the list of calls individually, and it started working.  Initially, we thought using an interceptor might help, but quickly realized it wouldn't help because the single IFRAME would still get overwritten.

Anyhow...below is a sample of the code we use.  In the future, we are hoping you would offer-up a parallelized option.  Anyhow...we just thought you would like to know.

Thanks,

- Rob

NON-WORKING CODE EXAMPLE:
$q.all([
       adalAuthenticationService.acquireToken('https://someplace.com/a/api'),
       adalAuthenticationService.acquireToken('https://someplace.com/b/api'),
       adalAuthenticationService.acquireToken('https://someplace.com/c/api'),
       adalAuthenticationService.acquireToken('https://someplace.com/d/api')
]).then(function (token) {
	// Yay!
    $scope.adalLoginSuccess = true;
}, function (err) {
	// Do exception stuff	
});

WORKING  CODE :
adalAuthenticationService.acquireToken('https://someplace.com/a/api')
.then(function () { return adalAuthenticationService.acquireToken('https://someplace.com/b/api') })
.then(function () { return adalAuthenticationService.acquireToken('https://someplace.com/c/api') })
.then(function () { return adalAuthenticationService.acquireToken('https://someplace.com/d/api') })
.then(function () { $scope.adalLoginSuccess = true; });

**Comment by rohitnarula7176** [comment]
Hi All,
Starting with Adal version 1.0.4 , simultaneous token requests have been parallelized. Below are the two different scenarios that we handle:

1. If we send simultaneous token requests for the same resource, only one request is sent to AAD but callbacks for all the requests are registered. Whenever the request is completed, the result is sent to all the registered callbacks.

2. On the other hand if token requests are sent for "n" resources, "n" iframes will be created and "n" requests will be sent. After each request is completed, callback registered for that request/resource will be called with the response.

We are closing this issue for now. Please let us know if you face any issues.

Thanks,
Rohit Narula
