### ISSUE TITLE
problem logging into another resource, first time error, following times ok

### ISSUE THREAD

**Issue by MichelTaal** [AzureAD/azure-activedirectory-library-for-js#178]
Hello,

I have a problem logging into another resource. 
I have 2 applications in my active directory. (client and server).

In my adalAuthenticationServiceProvider i fill in the "clientId" of my client application.
In the "loginResource" parameter, i put the domain of the server application https://xxxx.onmicrosoft.com/Server

The problem is, if I request a page, the first time I get an authorization error. Then if I request the same page again, ADAL will call a renew token for the resource https://xxxx.onmicrosoft.com/Server. 

From this point, everything work good as I want it to work. How can I avoid this problem that the first request will result in an authorization error?

Thanks

**Comment by weijjia** [comment]
My suggestion would be, do the initial login, and then call acquire token with the resource.

**Comment by MichelTaal** [comment]
I tried that, but I am unsuccessful. In my home screen (the screen where I am redirected after login),
I put the command:     adalService.acquireToken(adalService.config.loginResource);

In my console I will get the error:
WARNING: The returned id_token is not parseable
WARNING: User login in required
ERROR: Error when acquiring token for resource: https://xxxx.onmicrosoft.com/Server
INFO: State status:true; Request type:LOGIN
INFO: State is right
INFO: Token is available for this url app/home/home.html


I also put the command:  adalService.acquireToken(adalService.config.loginResource); in my following page that will call the webapi. 
I will get the message:
INFO: Token is already in cache for resource:https://xxxx.onmicrosoft.com/Server

Then I will get the authentication error because the audience is not found. The next time I will call the page, it will refresh the token, and everything keeps working as expected.

What am I doing wrong?

**Comment by tushargupta51** [comment]
@MichelTaal Can you share your app.js file where you configure adal? Do the client and server share the same domain name? If not, then before you try acquiring the token for the server, you need to have an authenticated user established. From the log, it seems that the request to acquire the token is initiated before the login is completed, even though the acquiretoken command is on the redirect page.  Can you try listening to `loginSuccess` event and put the acquiretoken call inside it?
    
                   $rootScope.$on("adal:loginSuccess", () => {
                         adalService.acquireToken(adalService.config.loginResource);
                });

**Comment by tushargupta51** [comment]
Please try the latest version and let us know if you still run into this issue, I will re-open it.
