### ISSUE TITLE
B2C (dev_convergence) Cookie overflow

### ISSUE THREAD

**Issue by didenkov** [AzureAD/azure-activedirectory-library-for-js#179]
https://login.microsoftonline.com returns HTTP 400 with "The size of the request headers is too long." message after several login/logout cycles.

## Environment:
I use the dev_convergence branch. However I'm not sure the issue is specific for B2C only.
Chrome 45.0.2454

## Steps to reproduce:
1) log in to a B2C directory
2) log out
3) repeat steps 1-2 several times (in my case it is 32) within the same browser session. 

## Expected result:
No errors, successful login every time.

## Actual result:
HTTP 400 - http://prntscr.com/8s2vlc
Cookies list for for login.microsoftonline.com contains 25 items with GUID-like keys - http://prntscr.com/8s2wi5
### Work-around
Clear cookies for login.microsoftonline.com.

**Comment by weijjia** [comment]
Can you send me fiddler trace please?

**Comment by didenkov** [comment]
http://1drv.ms/1W2tahw (*.har - HTTPArchive format) shows 1 cycle. Number of QUID-like cookies increased from 7 to 8.

**Comment by weijjia** [comment]
hold on, are you talking about b2c? We only support convergence for now, and just FYI, the code branch is renamed to experimental.

**Comment by didenkov** [comment]
Yes, I use a B2C directory. I understand it is not in production, and the dev-convergence branch is an experimental one. So the issue is just a notice for your team.

**Comment by neerajyadav** [comment]
@didenkov are you able to successfully use it with B2C tenant? Could you please tell me which branch you used for that?

**Comment by didenkov** [comment]
I'm not sure it works 100%, but sign in and sign up lead to correct B2C pages and authenticate users. I've not tested token refresh.
It is v2.0.0-experimental (branch: experimental) with restored policy params (reverted https://github.com/AzureAD/azure-activedirectory-library-for-js/commit/81d834df8c0ba940f951e877c3c53b03c5242312). Note: I use Aurelia framework in that test project, so it works with adal.js directly (w/o adal-angular.js).

**Comment by sjwaight** [comment]
I'm also seeing this behaviour in .Net libraries (4.0.209160138). Going to hunt that project down in Github and raise an issue, but thought I'd weigh in here.

**Comment by tushargupta51** [comment]
Closing this issue as we are no longer making investments in experimental branch. We are channeling our efforts to next version of this library - MSAL.
