### ISSUE TITLE
How to login immediately when the user visit the page

### ISSUE THREAD

**Issue by sarmut** [AzureAD/azure-activedirectory-library-for-js#184]
Hi,  

How I can trigger the automatic login when the user comes to the site?  The below code invokes the login page on constant loop.

$scope.init = function () {
        if (!adalService.userInfo.isAuthenticated) {
            $scope.login();
        }
    };

    $scope.init();

**Comment by weijjia** [comment]
If you use angular, you can try to protect the route by setting requireADLogin to be true. This will trigger the login.

**Comment by sarmut** [comment]
Thank you for the reply.. But I'm using ui-router and the 'requireADLogin' doesn't trigger the login.

**Comment by sarmut** [comment]
Never mind.  it is working now.
