### ISSUE TITLE
Implement as React Component

### ISSUE THREAD

**Issue by zachcarroll** [AzureAD/azure-activedirectory-library-for-js#189]

**Comment by zachcarroll** [comment]
I'd like to see a helper file similar to the angular-specific one, that would generate a react component that can be used with the react-router, and to wrap api calls made with a library such as fetch.

**Comment by bradtwurst** [comment]
what I would find helpful is an example which helps clarify how adal.js fits into a react higher order component (HOC).  Right now, I am attempting to get this work by using info gleaned from various posts and repos, but the effort has been difficult for me.

links:

- https://github.com/mjrussell/redux-auth-wrapper
- https://blog.mastykarz.nl/building-office-365-web-applications-react/
- https://hjnilsson.com/2016/07/20/authenticated-azure-cors-request-with-active-directory-and-adal-js/
- http://www.cloudidentity.com/blog/2015/02/19/introducing-adal-js-v1/
- http://www.andrewconnell.com/blog/adal-js-cors-with-o365-apis-files-sharepoint
- https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi/blob/master/TodoSPA/App/Scripts/app.js
- http://www.cloudidentity.com/blog/2015/02/19/introducing-adal-js-v1/
- http://www.cloudidentity.com/blog/2014/10/28/adal-javascript-and-angularjs-deep-dive/

**Comment by ericnkatz** [comment]
@bradtwurst I wish I found some of those articles a few months ago, but what I have working right now is something like this but in my case I just forceAuthentication() immediately since my application doesn't really have an unauthenticated state. Using redux I than either display the application once the state of my authenticated user is loaded or I just display "please login".

```
const activeDirectory = adal.inject( azureConfig )
const user = activeDirectory.getCachedUser()

export function forceAuthentication() {
  if ( window.location.hash.includes( '#id_token=' ) ) {
    activeDirectory.handleWindowCallback()
    browserHistory.push( '/' )
  }

  if ( !user ) {
    activeDirectory.login()
    return dispatch => { dispatch( { type: 'NO_USER_YET' }, {} ) }
  }

  return dispatch => {
    dispatch( { type:  USER_LOGGED_IN, user } )
    dispatch( syncUser( user ) )

    dispatch( syncSkills() )
  }

}

export const CURRENT_USER = user
```

**Comment by tushargupta51** [comment]
We do not have any plans to add and support React wrapper for adal library. We are focusing our efforts towards next generation of adal library - MSAL, which will support AAD, MSA accounts as well as B2C. We will definitely consider React for that.

**Comment by lamuertepeluda** [comment]
@tushargupta51 is there any roadmap for a release of MSAL for JavaScript (with or without React support, which I agree would be a great plus) ?

**Comment by tushargupta51** [comment]
@lamuertepeluda Sorry, no timelines to share yet.

**Comment by salvoravida** [comment]
https://github.com/salvoravida/react-adal

**Comment by FDMatthias** [comment]
A bit late, but I've written a blogpost about this [here](https://www.appfoundry.be/blog/2018/11/24/authentication-with-adal-in-react-single-page-applications/) and put a sample of a React SPA with Adal on github [here](https://github.com/appfoundry/react-adal-authentication-session-sample/tree/Authentication-with-ADAL-in-React-SPA) (includes step by step commits and multiple branches).
