### ISSUE TITLE
SPA support specifically Angular JS?

### ISSUE THREAD

**Issue by wizjack** [AzureAD/azure-activedirectory-library-for-js#191]
Can same ADAL library 1.0.7 be used for an angularJS application. Because the URL being generated from the application (https://login.microsoftonline.com/blahblah) is different from what we have in the azure portal!

**Comment by martellaj** [comment]
Hey, @wizjack. You can check out the Office team's Angular samples [here](https://github.com/OfficeDev?utf8=%E2%9C%93&query=o365-angular). All of these samples use ADAL JS 1.0.7.

**Comment by wizjack** [comment]
Hi, @martellaj  thanks for a reply. The problem is, in using above samples and for e.g. samples located at https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi, I have a azure login URL which doesn't contain the p parameter in which I can supply a policy like p=B2C_1_user_SignIn. Though I've applied a fix to attach the parameter to the extraQueryParameter in the config. 
I'm especially targeting B2C domain don't know if I'm missing something. I'm using adal-angular-experimental v2.0.0-experimental.

**Comment by krushnachandra** [comment]
R u trying to implement ad b2c authentication...which library version of adal you r using..use experimental branch and in init function there is you can aopend this policy  parameter

**Comment by krushnachandra** [comment]
init function there you can append this policy  parameter

**Comment by wizjack** [comment]
I think relating to my first question the library is working for angular, right now, for me. So I'm closing this. I'm using adal-angular-experimental v2.0.0-experimental as of date for anyone who's concerned.
