### ISSUE TITLE
Console spammed with errors [$rootScope:infdig] 10 $digest() iterations reached.

### ISSUE THREAD

**Issue by sjaanus** [AzureAD/azure-activedirectory-library-for-js#192]
After adding the libraries to my project, I am getting this error. Any suggestions what is causing it?

Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [["fn: $locationWatch; newVal: 7; oldVal: 6"],["fn: $locationWatch; newVal: 8; oldVal: 7"],["fn: $locationWatch; newVal: 9; oldVal: 8"],["fn: $locationWatch; newVal: 10; oldVal: 9"],["fn: $locationWatch; newVal: 11; oldVal: 10"]]

**Comment by tandria** [comment]
i think it could be a redirect from adal to the default root url '/' retriggering redirects to '/' 
try changing this:

 $routeProvider
                .when('/', {
                    templateUrl: 'yourTemplate.html',
                    controller: 'yourController',
                    requireADLogin: true
                });

into this:

 $routeProvider
                .when('/newRootUrl', {
                    templateUrl: 'yourTemplate.html',
                    controller: 'yourController',
                    requireADLogin: true
                }).otherwise({ redirectTo: '/newRootUrl' });

**Comment by sjaanus** [comment]
What do you mean, I should remove root url? This is what I have at the moment

	.when('/', { redirectTo: '/attendancereport', requireADLogin: true })
	.when('/employee', { templateUrl: '/employee/home', controller: 'EmployeeController', requireADLogin: true })
	.otherwise({ redirectTo: '/' });

**Comment by venkateshappala** [comment]
I am also facing same issue. I have simple HTML with Login and Logout buttons. Attached HTML and JS files. Please help me!!
[ADAL-Angular.zip](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/101123/ADAL-Angular.zip)

**Comment by wizjack** [comment]
I tried changing otherwise from root location to a fixed route e.g.  '/example' and adding requireAD attribute to this and it's working okay.

**Comment by tushargupta51** [comment]
@sjaanus can you try using a fixed route instead of '/' in the .otherwise option to see if it makes any difference?

**Comment by sjaanus** [comment]
Changed it to 			.otherwise({ redirectTo: '/attendancereport' });
Still get this problem occasionally.
[http://imgur.com/p7hvDQP](url)

**Comment by yaegerbomb** [comment]
I had to put requireADLogin: true in my otherwise function for the app to stop its digest cycle.

**Comment by tushargupta51** [comment]
We have released 1.0.11 with fixes to some of the digest iterations issue. Please use 1.0.11 and have a look here if you are still running into this issue: https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs#q2-my-app-gets-into-an-infinite-loop-sometimes-leading-to-digest-iterations-error
