### ISSUE TITLE
After adding loginResource, the app goes into endless loop

### ISSUE THREAD

**Issue by sjaanus** [AzureAD/azure-activedirectory-library-for-js#193]
I must send resource parameter with authorization request, so I changed the code on frontend to.

So I added the loginResource, which matches the tenant on backend.

    adalProvider.init({
		instance: 'https://login.microsoftonline.com/',
		tenant: 'mytenant.onmicrosoft.com',
		clientId: 'myid',
		extraQueryParameter: 'nux=1',
        loginResource: 'myloginresource'
    }, $httpProvider);

Now the app is in endless loop, this is the error, it keeps renewing token:

adal.js:973 renewToken is called for resource:myloginresource
adal.js:973 Add adal frame to document:adalRenewFrame
adal.js:973 Renew token Expected state: 88fbcfbc-a83c-4e88-ad63-3a54b8758be1|myloginresource
adal.js:764 Navigate url:https://login.microsoftonline.com/mytenant.onmicrosoft.com/oauth2/authorize?re….onmicrosoft.com%2FTimeManagement&nux=1&x-client-SKU=Js&x-client-Ver=1.0.0
adal.js:973 Navigate to:https://login.microsoftonline.com/mytenant.onmicrosoft.com/oauth2/authorize?re…ch.com&domain_hint=foo.bar&nonce=94efb237-7d5d-4a95-863f-1a9f2260783e
adal.js:973 LoadFrame: adalRenewFrame

**Comment by tushargupta51** [comment]
@sjaanus Is the loginResource in the same domain as your app? Do you see the token in the browser cache?

**Comment by polita** [comment]
Please let us know if you can help us repro this on a recent release.
