### ISSUE TITLE
Log in problem with Ad b2c 

### ISSUE THREAD

**Issue by krushnachandra** [AzureAD/azure-activedirectory-library-for-js#196]
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!

It gives an error "Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!"
after login from Active directory.

I am not able to redirect to my dashboard page.

**Comment by krushnachandra** [comment]
I have used experimental branch for b2c its working fine for signin and sign up but the problem is after login redirect return url and make refresh the page which makes digest loop errors

**Comment by venkateshappala** [comment]
Facing same issue :-(

**Comment by krushnachandra** [comment]
If u r using the b2c experimental branch then to remove this 10 digest error just make an other unauthorize Rout to over come 10 digest error

**Comment by jjmschofield** [comment]
Is B2C still only available on the experimental branch?

**Comment by krushnachandra** [comment]
yes it is available only in experimental branch.

**Comment by tushargupta51** [comment]
Closing this issue as we are no longer making investments in experimental branch. We are channeling our efforts to next version of this library - MSAL.
