### ISSUE TITLE
A user may experience data loss when the refresh token is expired (every 14 days)

### ISSUE THREAD

**Issue by Valchris** [AzureAD/azure-activedirectory-library-for-js#197]
If I understand the details of refresh token vs access token correctly, an hourly access token is provisioned via iframe up until the refresh token is expired (14 days). If the refresh token is expired, the user must be navigated to the login page. If this occurs in the middle of the users session the state of the app may not be persisted which could lead to data loss!

I believe an appropriate mitigation for adal-angular.js would be a configuration in minutes where the user will be prematurely sent to the login page to renew the refresh token. This prefetch would be configured to only execute on $routeChangeStart.

Current scenario:
-User logs in on day 1
-During the users session on day 14 the users refresh token expires
-The user saves their workflow
-The api call is redirected to the login page
-App state is broken!

Proposed Scenario: 
-App is configured with prefetch 4 days.
-User logs in on day 1
-On the 10th day the users (refresh token time - prefetch) > now
-Api calls continue to work as normal for the remaining 4 days
-User navigates to a new route
-User is interrupted with the login page
-User logs in and refresh token time is moved out 14 days

**Comment by tushargupta51** [comment]
@Valchris We do not make use of `refresh_token` in adal.js. We always fetch a new `access_token` when it is expired (default is 1 hr). If a user makes a call to an API and app does not have a token, it will initiate a "renew token" request. I don't think app state would be broken by this. Am I missing something?

**Comment by Valchris** [comment]
@tushargupta51 At some point, Azure must require the user to re-enter credentials, a call to renew token will return with an error code that requires the user to see the sign-in page and re-enter credentials. I was under the impression that this period of time is 14 days based on comments [in this SO post](http://stackoverflow.com/questions/22043128/windows-azure-active-directory-expiration-of-refreshtoken). If that's true and a user loads a page minutes before the 14 day window expires then initiates a POST after the window the action will fail. The app would now be in an unauthenticated state and must visit the sign-in page. Is this correct?

**Comment by tushargupta51** [comment]
@Valchris The SO Post talks about `refresh_token` which has an expiration of 14 days. ADAL js does not use `refresh_token` to renew an `access_token`. It always fetches a new `access_token` using the session cookie that identifies a valid session between user and AAD.

The default expiration of `access_token` is 1 hr. Am not sure about the default expiration of AAD session cookie. When a request to a protected API is made and adal has an access token for that, it checks if it already expired or not. If token is expired or about to expire in config.expireOffsetSeconds (default is 2 minutes), it tries to renew the token. As long as, there is a valid session cookie present, ADAL will be able to renew the token without user intervention. But if the cookie expired, then AAD will not renew the token and redirect the user to sign in page. So, if user is not active for whatever is the expiration time of the cookie, user will have to sign back in again.

**Comment by tushargupta51** [comment]
If the cookie is expired (which happens when browsing session ends), user will be interrupted to log back in again. There is an issue, where adal is not able to redirect user back to the original page where the login started: https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/130.

Closing this issue as cookie is good enough for the duration of browsing session and adal will be able to renew token as long as session is alive, let us know if you have any concerns, will reopen it.
