### ISSUE TITLE
sharepoint non root site collections cannot be accessed

### ISSUE THREAD

**Issue by nigel-dewar** [AzureAD/azure-activedirectory-library-for-js#198]
sharepoint non root site collections cannot be accessed.

this guy figured out a workaround but would be nice if it worked out of the box.

https://rolandoldengarm.wordpress.com/2015/07/27/angular-adal-js-sharepoint-rest-api-in-non-root-site-collections/

cheers

**Comment by tushargupta51** [comment]
@nigel-dewar can you explain the issue? The website you mentioned has been deleted by the author.

**Comment by tushargupta51** [comment]
updated link: http://rolandoldengarm.com/index.php/2015/07/27/angular-adal-js-sharepoint-rest-api-in-non-root-site-collections/

**Comment by tushargupta51** [comment]
Closing this as dup of #155
