### ISSUE TITLE
Is CDN Link to minimized adal.min.js in README correct?

### ISSUE THREAD

**Issue by JimDaly** [AzureAD/azure-activedirectory-library-for-js#207]
The README says to use this URL:
https://secure.aadcdn.microsoftonline-p.com/lib/1.0.0/js/adal.min.js
But when I view the minimized code returned by that URL it begins with this comment:
/*! adal-angular v1.0.0 2015-02-18 */
I also find references to an angular variable which is not found in the code at this URL:
https://raw.githubusercontent.com/AzureAD/azure-activedirectory-library-for-js/master/lib/adal.js

**Comment by martellaj** [comment]
It's hard to understand what they're getting at here... if you look at [Releases](https://github.com/AzureAD/azure-activedirectory-library-for-js/releases), the "latest release" is 1.0.7, but the README is still calling out 1.0.0 as the "GA" version. 

I noticed this, too and submitted a PR to change the README to call out 1.0.7. It was accepted into the dev branch, but hasn't moved over to master yet.

**Comment by tushargupta51** [comment]
@JimDaly @martellaj The README has been updated with the correct CDN url. Reference to the angular variable exists in this file: https://raw.githubusercontent.com/AzureAD/azure-activedirectory-library-for-js/master/lib/adal-angular.js

**Comment by tushargupta51** [comment]
Closing this issue. Please feel free to re-open if you have any comments.
