### ISSUE TITLE
Experimental branch bug: Scope getting passed as string instead of array

### ISSUE THREAD

**Issue by martellaj** [AzureAD/azure-activedirectory-library-for-js#208]
Looks like scopes are supposed to be in an array. However, in adal-angular.js, there is a line of code (146) that passes the client ID as the scope in string form, which causes an error (Error: API does not accept non-array scopes) to get thrown. Creating an array with the same value as its only value fixes the issue.

**Comment by martellaj** [comment]
@dstrockis for awareness.

**Comment by weijjia** [comment]
Thanks for reporting this.

**Comment by tushargupta51** [comment]
Closing this issue as we are no longer making investments in experimental branch. We are channeling our efforts to next version of this library - MSAL.
