### ISSUE TITLE
adal.js fails to log in on Microsoft Edge with error "AADSTS50058: User account identifier is not provided

### ISSUE THREAD

**Issue by bveerendrakumar** [AzureAD/azure-activedirectory-library-for-js#209]
Hi,
we have an issue while using adal JS in edge and it's throwing  Renew token failed "AADSTS50058: User account identifier is not provided. I saw a resolution to add the authority URL to trusted sites, but this is not really an elegant solution that we can ask every customer to do so. Can you please provide some solution that will not require users to add URLs to trusted sites?

[UPDATE]

One interesting observation is, we did not add the site to trusted sites at all. When we cleared the cookies and tried it worked!!! 

Also this issue is not reproable every time, it happens only when gets to renew token loop i believe. We tried a solution to force re login and before that calling authcontext.clearcache() method. Still it doesnt help, is this something to do with cookies? 

Please help us getting underlying reason for this?

Thanks,
Veerendra.

**Comment by weijjia** [comment]
This is a known issue to ie/edge. Adding to trusted site is a way go get rid of this issue. This issue is related to how IE/edge handle cookie jars.

**Comment by tushargupta51** [comment]
Closing as dup of #102
