### ISSUE TITLE
Infinite Loop and Browser Lockup / Crash

### ISSUE THREAD

**Issue by jjmschofield** [AzureAD/azure-activedirectory-library-for-js#210]
Having an issue in 1.07 when a user is not authorized for a resource.

Instead of directing a user to login with another account the ADAL library seems to throw the browser into an infinite loop, consuming all available CPU and forcing the user to force quit their browser.

Didn't have this problem with version 1.00 in the exmaple Angualr setup, has something changed in this logic since then?

**Comment by weijjia** [comment]
is this happened during interceptor call?

**Comment by jjmschofield** [comment]
This is happening without making api calls I'm afraid. AD login is required
on the root URL.

**Comment by weijjia** [comment]
Can you attach a log? I'll have a more detailed look on what could possibly going wrong.

**Comment by jjmschofield** [comment]
Unfortunately as the browser goes into an infinite loop I can't get to console or connect the browser to a debugger.

I believe that I've found the cause, our redirect route was an abstract state with requireADLogin. The resultant child states also had requireADLogin enabled. By disabling requireADLoign on the abstract view the issue seems to be cleared.

I'll post back shortly to confirm.

**Comment by jjmschofield** [comment]
Unfortunately this doesn't clear the issue if the user is able to authenticate against our azure AD but is not authorized for the login resource.

**Comment by jjmschofield** [comment]
I tracked this down to route redirection for unknown routes. 

When the user isn't authorized for a resource "/error=access_denied_description=AADSTS50105" is dumped on the path.

The was triggering as an unrecognized route in ui-router and sending the user back to '/', which had requireADLogin - hence the loop.

For anyone else experiencing a similar issue try setting $urlRouterProvider.otherwise() to a non-AD required route.
