### ISSUE TITLE
Access token of the login app's API isn't refreshed

### ISSUE THREAD

**Issue by ischrei** [AzureAD/azure-activedirectory-library-for-js#214]
The token to my API isn’t refreshed when the token is expired. Following the code in adal-angular.js, I see the token isn’t refreshed because this condition isn’t met: “else if (authService.config && isEndpoint)” (line 305).
And indeed I haven’t specify my own API (which is the same client ID as my web app) in the endpoints list (haven’t noticed any documentation claiming I need to do it).

Since the code inside this condition scope can handle the case where the token is for my API (i.e. will refresh the id_token), I expect ADAL to recognize this case.
So as I see it there are 2 options:
I.	Bug in ADAL JS – will appreciate your communication regarding ETA for a fix.
II.	Wrong usage – I need to specify my API as “external” endpoint, but that raise other questions:
a.	I can’t specify the full server URL, as the calls goes to $http(“/api/…”), so such calls won’t be identified as “isEndpoint”.
b.	I don’t want to specify “/api/” as the external endpoint because then a wrong call may be treated as belongs to this endpoint.
c.	And that’s leave me with the option of specifying each and every one of my APIs in the endpoints list to lower the risk of collision with another calls.
So what is the best option for me?

Thanks!
Ido.

**Comment by tushargupta51** [comment]
@ischrei thanks for reporting the bug. we are looking into fixing this issue in the next minor release, though we do not have any dates yet. Should be able to update you with the dates soon.

**Comment by PavelPikat** [comment]
@ischrei Take a look at the proposed fix here, maybe it will help you: https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/240

**Comment by tushargupta51** [comment]
@ischrei The proposed fix as @PavelPikat pointed out has been merged to dev branch. This will be available in next release of ADAL: 1.0.9 though we have not decided the exact release dates yet.

**Comment by ischrei** [comment]
Hi!
Thank you @tushargupta51 and @PavelPikat for your responses!
However, I've found another issue which might be related to this issue\fix as well.
I’ve noticed ADAL JS adds the authorization header to $http calls which are made by Angular to retrieve html templates (i.e. when the directive's templateUrl is configured.)
It happens as Angular $TemplateRequestProvider uses $http.get to retrieves the html file, and adal.js, in the getResourceForEndpoint function, believes it should protect this call.

Correct me if I’m wrong but ADAL JS should protect only API calls, no?
As a side effect, when the ID token is expired + the SPA is refreshed, there is a bug where the html template http call fails, as ADAL rejects the call without properly refreshing the token, so the SPA loading fails.
Will be very glad to get your advice.

Thanks!
Ido.

**Comment by nigel-dewar** [comment]
I have this issue as well.
