### ISSUE TITLE
CLA link in guidelines for contributing is bad

### ISSUE THREAD

**Issue by Mike-Bell** [AzureAD/azure-activedirectory-library-for-js#217]
The guidelines for contributing tell me I have to go here https://cla.msopentech.com/. That link does not work. I assume it's really supposed to point here https://cla2.msopentech.com/

**Comment by tushargupta51** [comment]
@Mike-Bell Sorry for the inconvenience. It should be https://cla.microsoft.com/. Fixed in Contributing.md. Thanks!
