### ISSUE TITLE
User Authenticated but not Authorized 

### ISSUE THREAD

**Issue by jjmschofield** [AzureAD/azure-activedirectory-library-for-js#219]
We have a situation where a user can be authenticated against our AD but is not authorized to access an app using this library.

In this situation the reply address seems to get the following added to it "error=access_denied&error_description=AADSTS50105...". The resulting redirect looks like:

https://ourApp/error=access_denied&error_description=AADSTS50105...

Note the lack of a '?' designating this a query string. 

The effect is that ui-router tries to handle this as a route incorrectly.

Cheers!

**Comment by weijjia** [comment]
do you have a fiddler trace for this?

**Comment by jjmschofield** [comment]
Do you mean a trace from http://www.telerik.com/fiddler ?

I'm not sure if my employer would be ok with sending through that data.

We have implemented a hack to stop this issue breaking our application which may help:

//Handling errors in path produced by ADAL
    //The response from Microsoft adds properties to path without declaring them as a query string, this causes ui-router to try and change to an impossible route
    $urlRouterProvider.rule(function ($injector, $location) { //Intercept every location change
      var $state = $injector.get("$state");
      var path = $location.path();
      
      if (path.indexOf("error=access_denied") > -1) { //If Microsoft has added an error to the path handle it
        $location.path('403'); //Blank the path off as, if we don't do this, there is a chain reaction which causes infinite digest loops of death
        $state.go('403');
      }

      if (path.indexOf("access_token") > -1 || path.indexOf("id_token") > -1) { //If Microsoft has added a token to the path handle it
        $location.path('/');  //Blank the path off as, if we don't do this, there is a chain reaction which causes infinite digest loops of death
      }
    });

**Comment by jjmschofield** [comment]
Closing this as it looks like the issue is covered in https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/151
