### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by jjmschofield** [AzureAD/azure-activedirectory-library-for-js#221]
I'm not sure if this is a genuine issue or a PEBKAC, so apologies if this erroneous.

When attempting to unit test in jasmine/karma any component which has ADAL in it's dependency stack the following gets thrown to console and the component will not register correctly:

TypeError: 'null' is not an object (evaluating '_adal.config')

The call stack indicates this is being triggered by:

adal-angular.js:200 updateDataFromCache(_adal.config.loginResource);

This has the unfortunate effect of causing anything which consumes ADAL to become un-testable for us.

I suspect this is because ADAL has not been able to instantiate correctly, however I can't for the life of me think how to get it to behave in a test.

I was wondering if:
A) This was a real issue
B) If there is any documentation indicating how to test an application dependent on ADAL

Thanks!

**Comment by jjmschofield** [comment]
Answered my own question here, PEBKAC as suspected

```javascript
 beforeEach(module('yourModule',function($provide){
      $provide.factory('adalAuthenticationService', function() {
        this.logOut = function(){}; //Add any other exposed methods which you depend upon
        return this;
      });
 }));

**Comment by ghost** [comment]
Hi how can i use the code . I have the same problem as above
