### ISSUE TITLE
Can ADAL for JS be used with on-premise ADFS without Azure

### ISSUE THREAD

**Issue by NickAb** [AzureAD/azure-activedirectory-library-for-js#222]
Can this library be used with on-premise ADFS without Azure Connect and Azure AD or does it require Azure?

Basically I would like to have a setup similar to https://github.com/aspnet/Security/tree/dev/samples/JwtBearerSample (or using OWIN's ActiveDirectoryBearer), but with one of these two on-premise cases:
1. Windows Server 2012 R2 with ADFS 3 (what we have currenlty)
2. Windows Server 2016 and new ADFS

**Comment by vibronet** [comment]
As I mentioned in the issue https://github.com/aspnet/Security/issues/673 - adfs in 2012 r2 does not support the necessary oauth grants. The scenario does work with adfs on windows server 2016, though.

**Comment by ysrmmz** [comment]
@vibronet,
Do we have any sample project where adal js is being used with adfs 2016?

**Comment by DmytroLapshyn** [comment]
@vibronet 

>  adfs in 2012 r2 does not support the necessary oauth grants.

Would you please be so kind to elaborate a bit on which exactly oauth grants ADFS v3 does not support? If I correctly understand what's being said in this [comment](https://github.com/aspnet/Security/issues/673#issuecomment-176521496), it actually **is** possible to use ADAL JS with on-prem ADFS v3.

**Comment by av-virlan** [comment]
Is there an actual example somewhere around using ADFS 2016 + ADAL JS ? I've been trying to make a project work that way but I guess I'm just not very clear around the ADFS concepts. What I'm looking for is to authenticate via ADFS 2016 and use the token to access SharePoint APIs. Is that even possible ?

**Comment by nickgsoft** [comment]
Did any one find any assistance on this instance?? i am also looking for ADFS 2016 + ADAL JS to get authentication token done, so we can access other internal CRM API's??
Please assist if any clue??

**Comment by ImenTurki** [comment]
did any one find an example, am tring to get authentication token and use it to access SharePoint APIs.
any idea ?
