### ISSUE TITLE
ReferenceError: AuthenticationContext is not defined using systemjs loader

### ISSUE THREAD

**Issue by pierreUMAknow** [AzureAD/azure-activedirectory-library-for-js#223]
Using ES6 syntax to import ADAL libraries and systemjs to load the code, the AuthenticationContext gets wrapped into a module and is not visible from the global namespace in javascript resulting in that error.

Can adal be repackaged as an NPM module or some other way to avoid this issue?

for more details, see my stackoverflow question at 

http://stackoverflow.com/questions/35119451/adal-library-gets-mangled-when-used-with-systemjs-loader-referenceerror-authe

**Comment by Mansyn** [comment]
+1 

Attempted this pattern using webpack and coming up with this same error.

**Comment by cdennig** [comment]
+1

**Comment by rossholdway** [comment]
I also ran into this issue. Try using the following systemjs config.

```
meta: {
  'node_modules/angular/angular.js': { format: 'global', exports: 'angular' },
  'node_modules/adal-angular/dist/adal.min.js': { format: 'global', exports: 'AuthenticationContext' },
  'node_modules/adal-angular/dist/adal-angular.min.js': { format: 'global', deps: ['angular', 'adal'] }
},
paths: {
  'angular': 'node_modules/angular/angular.js',
  'adal': 'node_modules/adal-angular/dist/adal.min.js',
  'adal-angular': 'node_modules/adal-angular/dist/adal-angular.min.js'
}
```

**Comment by tushargupta51** [comment]
we plan to release 1.0.9 as a npm package.

**Comment by tushargupta51** [comment]
We have released this package on npm: https://www.npmjs.com/package/adal-angular, please let us know if you still have issues.
