### ISSUE TITLE
adal:loginSuccess, adal:loginFailure, adal:notAuthorized not called

### ISSUE THREAD

**Issue by wizjack** [AzureAD/azure-activedirectory-library-for-js#224]
The mentioned callback methods are not being called for me. I'm using in angularjs singlepageApp. I don't know where exactly to put them, on the page where i call the login function or the redirect URI. Right now I'm using it in the redirect URI.

**Comment by tushargupta51** [comment]
@wizjack can you share the code where you set the configuration for callbacks?

**Comment by wizjack** [comment]
Do you mean ADAL configuration? Do let me know. 
I'm using the following function to capture the event.

```javascript
// all code in index controller
        
// login function for the login button
        $scope.signIn = function () {
            adalAuthenticationService.login();
        };

//as given in the readme.md 
$scope.$on("adal:loginSuccess", function () {
        console.log("login success");
    });
```

**Comment by wizjack** [comment]
Sorry was accidentally closing it.

**Comment by nicoschmitt** [comment]
I have the same issue. I don't get the adal:loginSuccess event.

**Comment by tushargupta51** [comment]
@wizjack You should have the loginSuccess callback on the Ctrl you are calling the login function from. For example, considering this azure ad sample:https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp , if you add loginsuccess callback in homectrl, you should see the console statement logged.

If that is not the case, can you share you app.js init method and the controller code where you call login and loginsuccess callback.

**Comment by wizjack** [comment]
Controller code is given up above. However, the redirect uri is different from the indexCtrl route if it makes any difference.

Both login function and adal success callbacks are in the index Ctrl only. I have tried all sorts of variations. 

like
```javascript
        $scope.$on("adalService:loginSuccess", function () {
        $scope.$on("adalAuthenticationService:loginSuccess", function () {
        $scope.$on(adalAuthenticationService.loginSuccess, function () {
        $rootScope.$on("adalService:loginSuccess", function () {

```
index Ctrl injectors are as follows

    /* @ngInject */
    function indexController(adalAuthenticationService, adUtilityFactory, $state, $rootScope, $scope, $timeout, AzureADPolicies) 

Adal init config code is given below

```javascript
(function () {
    'use strict';

    angular
        .module('app')
        .config(config);

    /* @ngInject */
    function config(adalAuthenticationServiceProvider, $httpProvider, ngAuthSettings) {

        // Set options third-party lib

        var resourceApi = ngAuthSettings.resourceServiceBaseUri;
        var blobApi = ngAuthSettings.blobServiceBaseUri;
        var endpoints = {
            // Map the location of a request to an API to a the identifier of the associated resource
            // Cleared 
        };

        adalAuthenticationServiceProvider.init(
            {
                
                instance: 'https://login.microsoftonline.com/', 
                tenant: 'xxxxx.onmicrosoft.com',
                clientId: 'fdgdfgdfg-dfgdgfg-dfgdfgdfg-546fhfgh-rthhfgh',
                extraQueryParameter: 'nux=1&p=B2C_1_PeopleSignIn',

                //DEV
                //redirectUri: "https://mysitedev.com/",

                //PROD
                //redirectUri: "https://mysite.com/",

                //endpoints: endpoints,
                cacheLocation: 'localStorage' // enable this for IE, as sessionStorage does not work for localhost.
            },
            $httpProvider
            );
    }
})();
```
P.S. - I'm using 2.0.0 experimental version.

**Comment by nicoschmitt** [comment]
I also tried to listen to event in the ctrl I call login, not change.
I'm also using 2.0.0 experimental version.

**Comment by nicoschmitt** [comment]
And by the way, in which ctrl should I listen if login get called by the routing manager?

**Comment by ruisilva450** [comment]
I'm getting this problem on 1.0.8 also

**Comment by PavelPikat** [comment]
I managed to catch the event by routing manager inside of app.run

```
 $rootScope.$on('adal:loginSuccess', function() {
                
            });
```

**Comment by wizjack** [comment]
@PavelPikat  seems interesting: will check.

**Comment by rohitnarula7176** [comment]
You should add the login success callback on the Ctrl you are calling the login function from. Below is a code snippet you can add to your controller
and get the token/error respectively.
```
 $rootScope.$on('adal:loginSuccess', function (event,token) {
    });
```
```
 $rootScope.$on(adal:loginFailure, function (event,error) {
    });
```
If you want to listen for the event on a different controller other than the one you are calling the login function from, you need to add that controller as a child to the main controller as the broadcast event is dispatched from the parent level downwards to all child scopes. For instance, if the login is called from the "homeCtrl" and you want to listen for the event on the "todoListCtrl", you need to add the same event in "todoListCtrl" and make the following change in your index.html:
```
  <div ng-controller="homeCtrl">
            <div ng-controller="todoListCtrl">
            </div>
        </div>
```
