### ISSUE TITLE
1.0.8 isn't on the CDN

### ISSUE THREAD

**Issue by martellaj** [AzureAD/azure-activedirectory-library-for-js#229]
Y'all provide a link to 1.0.8, but it's not on the CDN. Either make sure it's uploaded or roll back the README to 1.0.7.

**Comment by barisbikmaz** [comment]
+1

**Comment by weijjia** [comment]
sorry about it. We rely on server side people to make the CDN update, who just got back from vocation. I've already made the request to update CDN, should be updated today.

**Comment by tushargupta51** [comment]
It seems 1.0.8 is now available on CDN: https://secure.aadcdn.microsoftonline-p.com/lib/1.0.8/js/adal.min.js. Closing this.
