### ISSUE TITLE
login() call to _getNavigateUrl should pass this.config.resource instead of null.

### ISSUE THREAD

**Issue by vladdoo** [AzureAD/azure-activedirectory-library-for-js#230]
Current:
var urlNavigate = this._getNavigateUrl('id_token', null) + '&nonce=' + encodeURIComponent(this._idTokenNonce);

Should be:
 var urlNavigate = this._getNavigateUrl('id_token', this.config.resource) + '&nonce=' + encodeURIComponent(this._idTokenNonce);

**Comment by tushargupta51** [comment]
@vladdoo Do we need a resource when requesting an `id_token`? We add `client_id` in the url before sending the request and that is why we are passing null as the value of the resource.

**Comment by vladdoo** [comment]
I thought we did but upon further investigation it looks like we don't need to do this.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Thu, Mar 3, 2016 at 10:20 PM -0800, "tushar gupta" <notifications@github.com<mailto:notifications@github.com>> wrote:


@vladdoo<https://github.com/vladdoo> Do we need a resource when requesting an id_token? We add client_id in the url before sending the request and that is why we are passing null as the value of the resource.

-

**Comment by tushargupta51** [comment]
Thanks @vladdoo . I will close the issue then.
