### ISSUE TITLE
Wrong redirect url after login in 1.0.8 in adal-angular

### ISSUE THREAD

**Issue by kf-radoslawmaziarka** [AzureAD/azure-activedirectory-library-for-js#232]
Hi.

Your last commit broke redirect mechanism after login, when you have nested states.

Let's assume you have such code:
```
$stateProvider
    .state('app', {
        url: '/app',
        abstract: true,
        controller: 'AppController',
        controllerAs:'appVm',
        templateUrl: 'app/app.html',
    });

$stateProvider
	.state('app.address', {
		url: '/address',
		templateUrl: 'app/address/template.html',
		controllerAs: 'atvm',
});
```
Then in _stateChangeHandler_ method in _adal-angular.js_ in 200 line you have:
```
 $location.$$url = toState.url;
```

With nested states property _toState.url_ it's only _'/address'_, not _'/app/address'_ so redirection fails because there is no state with just _'/address'_ path. 

I think that you should get absolute path like that: [http://stackoverflow.com/a/24502548](http://stackoverflow.com/a/24502548)

**Comment by nigel-dewar** [comment]
Hi there, I think I may be experiencing the same issue.

what happens is, when a user logs into my application for the first time, they get redirected to the home route

$stateProvider
// Get Home Page
.state("home", {
url: "/",
controller: "homeController",
controllerAs: "vm",
templateUrl: "app/modules/home/home.html",
requireADLogin: true
})

And there is no problems there at all.

BUT here is a strange behavior

My application sends emails to users, so they can click a url link, and be taken back to a specific location in my app.

something like this .
.state("sessionGroup", {
url: "/workshops/:workshopId/sessionGroups/:sessionGroupId",
controller: "workshopDetailsController",
controllerAs: "vm",
templateUrl: "app/modules/workshops/workshopDetails.html",
requireADLogin: true
})

which provides a URL path like so : http://localhost/#/workshops/2/sessionGroups/96

this works fine if you are logged in already when you click this link and goes straight to the desired URL,

BUT... If you are not logged in to the app and you try to go to this link,

Adal fires up and gets the user to login, and then boom! problem

the url path redirected after the adal login becomes

http://localhost/#/workshops/:workshopId/sessionGroups/:sessionGroupId?workshopId=2&sessionGroupId=96

which is not at all the route I specified. what do I need to do to ensure proper redirection after login?

Is this a bug? And is the same bug that @kf-radoslawmaziarka is experiencing?

**Comment by rmaziarka** [comment]
@nigel-dewar it is not the same that I am experiencing. Please check previous versions of adal.js if your error will occure there.

**Comment by PavelPikat** [comment]
@nigel-dewar This is 1.0.8 problem. We had the same and we had to fallback to 1.0.7
I belive in 1.0.8 this is caused by `$location.url(loginStartPage).search(loginStartPageParams);` because .search() will convert state params to query string.

**Comment by rmaziarka** [comment]
@PavelPikat @nigel-dewar I think that you should create another issue.

**Comment by PavelPikat** [comment]
@rmaziarka  #244

**Comment by nigel-dewar** [comment]
Hi Guys, Thank you @PavelPikat , you are correct, 1.0.7 solved the issue for me. Thank you very much for posting your help. I had an important meeting this morning and this was a major issue for me. I had made my way into the office at 4.30am in the morning thinking it was going to be a hard slog to solve. Cheers!!!!

**Comment by nigel-dewar** [comment]
@PavelPikat  I will create a new issue soon for this. I would like to see some detailed doco from the creators about refreshing tokens because I think there is a bug with this too. cheers

**Comment by PavelPikat** [comment]
@rmaziarka @nigel-dewar I've created it, check #244

**Comment by xuezhai** [comment]
can release the bit with this fix? we hit this issue from our app, and we need this fix asap, thanks

**Comment by tushargupta51** [comment]
@xuezhai The bits are released now.
