### ISSUE TITLE
Will not allow access to web api controller using  [AllowAnonymous] attribute

### ISSUE THREAD

**Issue by nigel-dewar** [AzureAD/azure-activedirectory-library-for-js#233]
Hi there, adal.js does not respect the allowanonymous attribute put on a controller.

Even when using the correct settings in adal.js such as requireADlogin : false, it is still being rejected

        .state("home", {
                url: "/",
                controller: "homeController",
                controllerAs: "vm",
                templateUrl: "app/modules/home/home.html",
                requireADLogin: false
            })
            // Get My Test
            .state("test", {
                url: "/test",
                controller: "testCtrl",
                //controllerAs: "vm",
                templateUrl: "app/modules/test/test.html",
                requireADLogin: true
            })

Is there something extra one must do to force adal.js to hit a controller point that is not expecting authentification?

my web api controller looks like this

   [AllowAnonymous]
    [EnableCors(origins: "*", headers: "*", methods: "*")]
    [RoutePrefix("api/pages")]
    public class PagesController : ApiController
    {
        private SEDContext db = new SEDContext();

       
        // GET api/pages
        [EnableQuery()]
        [Route("")]
        [HttpGet]
        //[Authorize(Roles="Admin")]
        public IQueryable<Page> Get()
        {
            var results = db.Pages.ToList().AsQueryable();
            return results;
        }

**Comment by PavelPikat** [comment]
I have a theory about it:
I might be because adal.js is constantly listening to $http requests with its interceptor and tries to acquire access token for the requested endpoints. If you configured adal with web api's endpoint, it will try to fetch the token on every request. Obviously, it can't know if the controller has the [Authorize] attribute or not, it will just complain that this endpoint need token.

**Comment by tushargupta51** [comment]
@nigel-dewar I don't think you need to specify "requireADLogin" for a controller that does not need authentication. From your code, it seems though that the "Get" action require authentication, if your request is routed to that action, then it would complain if user is not authenticated.
@PavelPikat If the interceptor is not able to find a token for an endpoint, I think it still sends the request but without `WWW-Authenticate` header. It would then depend on Web API to handle the request or not depending if it requires authentication.

**Comment by nigel-dewar** [comment]
Ok that makes sense. It must be that my api get action is expecting auth, even though I have told it not too. In which case this is nothing to do with adal.js, but its my problem with my web api. sorry for the hassle.
