### ISSUE TITLE
Provide a javascript library or example which doesn't need any infrastructure

### ISSUE THREAD

**Issue by ksimple** [AzureAD/azure-activedirectory-library-for-js#237]
I don't want to introduce the Angular into my project and an auth lib shoudn't include an application level library. It slows down the web page greatly.

**Comment by PavelPikat** [comment]
You don't have to user adal-angular.js if you're not using Angular in your application. Just include vanilla adal.js and it will work.

Also, there are samples with ADAL.js without using Angular. 
https://github.com/OfficeDev/O365-jQuery-CORS

**Comment by ksimple** [comment]
Thanks, please update the following link so it is easy to get it

https://graph.microsoft.io/en-us/code-samples-and-sdks

**Comment by PavelPikat** [comment]
Yeah, they need to make another section in Microsoft Graph samples with pure JavaScript without using any frameworks :)

**Comment by tushargupta51** [comment]
There is another sample on azure ad that uses adal js without Angular. Closing this issue.
