### ISSUE TITLE
The oauth parameter state is used and developer can't pass customized parameter to reply uri

### ISSUE THREAD

**Issue by ksimple** [AzureAD/azure-activedirectory-library-for-js#238]
I didn't find a way to pass a customized parameter to my reply uri to do different things after login. Config multiple reply uri in AzureAD is not feasible in many real cases. ADAL lib use state to save its own state and didn't leave anything to let developer can do the same thing.

**Comment by tushargupta51** [comment]
@ksimple You can take control of things after login in 2 ways:
1. config.redirecturi: AAD will redirect the response to this uri after login. default is windows.location.href.
2. config.callback: this function would be called after login

**Comment by ksimple** [comment]
Thanks for your reply, but it can't solve the issue in my case. I have different oauth flow and handle by one redirect uri. Pre oauth standard, I can use state passing my own parameters to handle the different server callback. It is impossible when I'm using ADAL.

What I can't agree with is why ADAL don't follow the standard spec fully. If it is a hard requirement or some big technique issue, don't use it exclusively at least.

**Comment by yihuacao** [comment]
I hit similar issue here. From my understanding, in oauth flow redirecturi and state is the only two places to get info pass through. Since redirecturi is restricted in many ways, state is the last place.
As @ksimple mentioned, the hard part is to interop with other auth flow library or server.
For my case, the workaround is I use a different format of state to distinguish whether it's from adaljs or other flow.

**Comment by tushargupta51** [comment]
@ksimple @yihuacao Thanks for your input, I agree in the current released version, we do not provide any extensibility to users to modify 'state', this is something we can definitely consider adding.

Though am trying to understand your scenarios better to see if I can suggest any workaround. If unauthenticated, Adal redirects the user to login. After successful login, AAD redirects user back to the "config.redirectUri" url. Do you want to take control of where AAD should redirect the user back without configuring multiple uris? I want to make sure I understand the kind of flexibility you want to have in the library.

**Comment by nigel-dewar** [comment]
Hi there, I think I may be experiencing the same issue. 

what happens is, when a user logs into my application for the first time, they get redirected to the home route 

   $stateProvider
            // Get Home Page
            .state("home", {
                url: "/",
                controller: "homeController",
                controllerAs: "vm",
                templateUrl: "app/modules/home/home.html",
                requireADLogin: true
            })

And there is no problems there at all.

BUT here is a strange behavior

My application sends emails to users, so they can click a url link, and be taken back to a specific location in my app.

something like this .
  .state("sessionGroup", {
                url: "/workshops/:workshopId/sessionGroups/:sessionGroupId",
                controller: "workshopDetailsController",
                controllerAs: "vm",
                templateUrl: "app/modules/workshops/workshopDetails.html",
                requireADLogin: true
            })

which provides a URL path like so : http://localhost/#/workshops/2/sessionGroups/96

this works fine if you are logged in already when you click this link and goes straight to the desired URL,

BUT...  If you are not logged in to the app and you try to go to this link,

Adal fires up and gets the user to login, and then boom! problem

the url path redirected after the adal login becomes

http://localhost/#/workshops/:workshopId/sessionGroups/:sessionGroupId?workshopId=2&sessionGroupId=96

which is not at all the route I specified. what do I need to do to ensure proper redirection after login?

Is this a bug?  And is the same bug that @ksimple is experiencing?

**Comment by tushargupta51** [comment]
Currently, we are focusing on next generation of adal library. We don't plan to make `state` extensible in adal and will consider this in the future library.

Though there are ways this can be achieved, though it will require some extra work and will work only for login and not for passing customizable state when acquiring token. There is an extensibility point that is called before user is redirected to login. It is called `displayCall`. Users can set this to a function and update the state property as they want. Though they also need to update the state saved in browser storage with this value so that adal will be able to validate the state returned in the response.

**Comment by nigel-dewar** [comment]
Thanks @tushargupta51 that sounds really cool.

'My opinion of course' is JavaScript is really important. Development for me now is often focused purely client side dev, using Angular 1, Angular 2, Ionic, NativeScript..etc...

Adal.js and any enhancements in the way I can interact with Identity and Authentication using JS naturally then is important to me. And I imagine I am not the only one as more and more non Microsoft developers start taking Microsoft Azure and Azure AD really seriously. Especially now Office 365 is turning out to be such an amazingly epic product.

Thanks for your hard work. Kind Regards, Nige.

**Comment by ewittry** [comment]
Seems to be related too https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/725 
Any updates on these issues? @polita @nigel-dewar @tushargupta51 @yihuacao @ksimple
