### ISSUE TITLE
1.0.8 converts state params to query string after login

### ISSUE THREAD

**Issue by PavelPikat** [AzureAD/azure-activedirectory-library-for-js#244]
#240 fix introduced ` $location.url(loginStartPage).search(loginStartPageParams);` which uses route parameters stored earlier, but .search() will apend these parameters as query string. 

However, there could be a setup, where route parameters are defined as part of the url, for example:
http://myapp.com/#/organization/department/employee/profile

.search() will convert everything to:
 http://myapp.com/#/?organization=&department=&employee=&profile=

**Comment by tushargupta51** [comment]
Thanks @PavelPikat for filing this issue. I will look into this.

**Comment by polita** [comment]
Duplicate root cause of #130
