### ISSUE TITLE
Add configuration option to bypass home realm discovery

### ISSUE THREAD

**Issue by gregjhogan** [AzureAD/azure-activedirectory-library-for-js#245]
Add a configuration option that is passed to the domain_hint query parameter in the login URL so that I can bypass home realm discovery when the user isn't authenticated.

For example:
```javascript
adalAuthenticationServiceProvider.init(
    {
        // Config to specify endpoints and similar for your app
        tenant: "52d4b072-9470-49fb-8721-bc3a1c9912a1", // Optional by default, it sends common
        clientId: "e9a5a8b6-8af7-4719-9821-0deef255f68e", // Required
        domain: "contoso.com", // optional, bypasses home realm discovery
        //localLoginUrl: "/login",  // optional
        //redirectUri : "your site", // optional
        //endpoints: endpoints  // If you need to send CORS api requests.
    },
    $httpProvider   // pass http provider to inject request interceptor to attach tokens
);
```

**Comment by PavelPikat** [comment]
Why can't you use tenant for that?

```
adalAuthenticationServiceProvider.init(
    {
        // Config to specify endpoints and similar for your app
        tenant: "contoso.com", // Optional by default, it sends common
        clientId: "e9a5a8b6-8af7-4719-9821-0deef255f68e", // Required
        //localLoginUrl: "/login",  // optional
        //redirectUri : "your site", // optional
        //endpoints: endpoints  // If you need to send CORS api requests.
    },
    $httpProvider   // pass http provider to inject request interceptor to attach tokens
);
```

**Comment by gregjhogan** [comment]
Assuming that will just put the tenant into the URL in place of the tenant GUID that does not seem to bypass home realm discovery:
https://login.windows.net/contoso.com/oauth2/authorize?response_type=id_token...

I believe to bypass home realm discovery you have to use a query parameter:
https://login.windows.net/{tenant-id}/oauth2/authorize?response_type=id_token&domain_hint=contoso.com...

We have an ADFS server outside of Azure AD, so when I land on the login page for the Azure AD tenant I have to type in an e-mail address before getting redirected to our ADFS server.  This is home realm discovery, and I would like support for bypassing it (which the query parameter domain_hint will do).

**Comment by tushargupta51** [comment]
@gregjhogan You can specify the `domain_hint` value like this:
```javascript
adalAuthenticationServiceProvider.init(
    {
        // Config to specify endpoints and similar for your app
        tenant: "52d4b072-9470-49fb-8721-bc3a1c9912a1", // Optional by default, it sends common
        clientId: "e9a5a8b6-8af7-4719-9821-0deef255f68e", // Required
        extraQueryParameter: 'domain_hint=contoso.com',
        //localLoginUrl: "/login",  // optional
        //redirectUri : "your site", // optional
        //endpoints: endpoints  // If you need to send CORS api requests.
    },
    $httpProvider   // pass http provider to inject request interceptor to attach tokens
);
```

**Comment by tushargupta51** [comment]
@gregjhogan Also, be default, domain_hint query parameter will be included and its value is extracted from username of the logged in user. adal extracts the part after '@' symbol in the username and use that as domain hint. for example if the username is xyz@contoso.com, domain_hint=contoso.com will be appended to the url string.

**Comment by gregjhogan** [comment]
@tushargupta51 I saw that it pulls it from the username in the code, but that doesn't help when a user first hits the site (and hasn't ever authenticated).

extraQueryParameter is exactly what I need.  If all users are guaranteed to be for a single domain, this is really helpful.  Thanks!
