### ISSUE TITLE
Simplify configuration to not require clientId

### ISSUE THREAD

**Issue by gregjhogan** [AzureAD/azure-activedirectory-library-for-js#246]
The endpoint /.auth/login/aad does some heavy lifting (generating a nonce, determining the clientId and tenantId, etc...) and if it can figure out the clientId and tenantId it would be nice if that could be leveraged to remove the requirement to specify it in the configuration.

Not sure if this is the right place to request this, but ideally /.auth/login/aad would support multiple other login related query parameters, such as:
https://&lt;sitename&gt;.azurewebsites.net/.auth/login/aad?domain_hint=&lt;domain&gt;&response_mode=fragment&prompt=none

**Comment by tushargupta51** [comment]
@gregjhogan I am not sure if I follow what you described. Azure portal generates the client id when you register the application but whenever an application is sending request to AAD for login or for renewing token, it needs to include its client id to identify itself with AAD.

**Comment by gregjhogan** [comment]
I want all my web app assets protected by authentication, but I also want to use the ADAL JS library for some of it's nice features.  If you configure Azure AD authentication in the portal you enter the client and tenant IDs in the portal.  Then I also have to enter it in the ADAL JS config.  Why doesn't the ADAL JS library pick up this information automatically?

When you hit:
https://sitename.azurewebsites.net/.auth/login/aad?post_login_redirect_url=/
it automatically redirects you to:
https://login.windows.net/{tenantid}/oauth2/authorize?response_type=id_token&redirect_uri=https%3A%2F%2Fsitename.azurewebsites.net%2F.auth%2Flogin%2Faad%2Fcallback&client_id={clientid}&scope=openid+profile+email&response_mode=form_post&state=%2F&nonce={generated-nonce}
so something already knows what the configured client and tenant IDs are.

It seems like if the ADAL JS library could use the /.auth/login endpoint built into every web app the configuration for my situation (single web app with authenticaiton configured) would be a lot simpler, and I thought this might be a common scenario, but right now that may not be possible because some of the query parameters do not seem to be supported, such as prompt=none

**Comment by tushargupta51** [comment]
@gregjhogan This endpoint is provided by azure websites and is not an AAD endpoint. We dont plan to add any support for this in adal js.

cc: @vibronet

**Comment by gregjhogan** [comment]
I see your point.  A better title would have been "Simplify configuration to not require clientId for Azure Web Apps".  I thought it was a lot more convenient to not have to modify a UI configuration file as I promote a deployment package through environments (since /.auth/login/... is constant across all environments).  But, there is still the problem of running on localhost.  This could be addressed by a OWIN pipeline component that mocks /.auth/login/... when the request URL is localhost, but if you use a CDN to host your UI none of this applies, so this isn't as elegant of a solution as I had initially thought.
