### ISSUE TITLE
Login fails with Invalid_state when running on Edge and when my portal and AAD are in a different security zones

### ISSUE THREAD

**Issue by ischrei** [AzureAD/azure-activedirectory-library-for-js#247]
Hi,

I've found that sessionStorage isn't preserved in Edge, when I'm trying to login using AAD to my portal, and when the sites are in different security zones (i.e. AAD login is in the trusted zone and mine is under Internet zone).

Since the storage isn't preserved, the login state value it gone, so login fails with Invalid_state error.
I know that according to the documentation my portal and AAD have to be in the same zone (due to other reasons as well), but I would like let the user know the exact issue and how to resolve it.
However, when this login fails, I don't get any adal:loginFailure event.
1. Why the event isn't sent?
2. Is there a recommendation how to identify the portal and AAD are in different security zones?

Thanks!
Ido.

**Comment by tushargupta51** [comment]
@ischrei I agree that we should broadcast a loginfailure event in case of state no found, but we cannot identify in adal that the state was not saved because of different security zones. The event will have description like "state not found" or "state not match".

**Comment by ischrei** [comment]
I agree this particular error can be caused by other root causes as well. However, since different security zones is a blocker to the ADAL framework, I believe you should help your users identify this case somehow, so their customers will be notified correctly.

Do you have an ETA for the event fix?

Thanks a lot in advance!

**Comment by tushargupta51** [comment]
@ischrei do you have the zoning issue on other browsers too? Chrome/Firefox?

**Comment by ischrei** [comment]
Only om IE & Edge
