### ISSUE TITLE
LOGIN_ERROR isn't set, as getRequestInfo doesn't set the requestType correctly

### ISSUE THREAD

**Issue by ischrei** [AzureAD/azure-activedirectory-library-for-js#249]
When there is an invalid_state error, the getRequestInfo  fails to set the requestType as the the state doesn't match.
The requestType valu is set only when there is a match, and is taken from the sessionStorage.

You should get the request type from the returned state parameter in the hash.

**Comment by tushargupta51** [comment]
@ischrei We set the request type based on what state the incoming request matches to. The state itself does not have any information about the request type. Also, the request is an invalid request if state does not match, in which case we should log an error. #247 will fix that.

**Comment by ischrei** [comment]
I've noticed a returned state for example does contains the resource. for example: "&state=55c916d9-5d1a-40eb-9069-f1cfb9af24a3|https://management.core.windows.net/"

If it is not set in another login\tokens renew flows maybe it is better to add it.

**Comment by tushargupta51** [comment]
@ischrei When we receive a response for which state does not match, we cannot identify the request type for the corresponding request. The request type in that case will be unknown. When this happens, adal will broadcast a 'stateMismatch' event (this will be available in 1.0.,9), which will have the error description: invalid state state: <whatever state was received in response>.

Also, state mismatch is not specifically a login error but a more general error that can happen even when renewing tokens.
