### ISSUE TITLE
All AcquireToken calls silently fail after ERR_NETWORK_SUSPENDED

### ISSUE THREAD

**Issue by stuartlong** [AzureAD/azure-activedirectory-library-for-js#250]
If the renew token response called in response to the user's cached access token being expired gets refused due to a **ERR_NETWORK_SUSPENDED** network error, then the acquireToken call silently fails and the callback we passed in remains registered to the auth context. 

In addition, any subsequent calls to acquireToken for the same resource also fail silently because the original callback is still registered so the authentication context instance decides to wait for the original call to complete (which will never happen at this point). 

Hit this issue in both 1.0.7 and 1.0.8.

**Comment by tushargupta51** [comment]
@stuartlong Is there any response sent back to application in case of this error? Or the request just dies with this. If so, then we need a mechanism to kill requests if a response is not received after certain time. I agree if there was no response received, callbacks will remain registered and further renew requests will just add another callback.

**Comment by stuartlong** [comment]
No, there's no response of any kind to the app. We have our own timeout in our app around auth calls, and we first noticed this error when those timeouts started getting hit, but we never saw any kind of response or error.

**Comment by tushargupta51** [comment]
@stuartlong I am fixing this issue in an open PR and have a follow-up question. How do you know that ERR_NETWORK_SUSPENDED error has happened? Where do you see that error? I am wondering if adal can look for this error somewhere and call the callback, instead of having a timeout.
