### ISSUE TITLE
Using library in Cordova app opens external browser

### ISSUE THREAD

**Issue by chazwoza** [AzureAD/azure-activedirectory-library-for-js#251]
Hi,
I'm trying to use this in a cordova app and have compiled/run in the windows UAP platform. Whenever i start authentication it opens a browser window in an external browser rather than the app itself.

**Comment by tushargupta51** [comment]
@chazwoza  You should look into this: https://github.com/AzureAD/azure-activedirectory-library-for-cordova. Adaljs is not designed with cordova in mind.
