### ISSUE TITLE
Requirements for iframe redirectUri content

### ISSUE THREAD

**Issue by sondreb** [AzureAD/azure-activedirectory-library-for-js#259]
I want to avoid loading the whole web application when the token is renewed in the iframe. There is a lot of JavaScript and processing happening in the main app (it's an SPA), and loading the whole thing in the iframe is something I want to avoid.

So what are the requirements for what to load in the redirectUri?

After user have logged on, I basically do this to change the redirect URL:

`authContext.config.redirectUri = window.location.origin + '/auth.html';`

My problem though is that reading the token from the cache does not work when I load my empty "auth.html" and not "index.html".

`authContext.getCachedToken(resource);`

I have tried to load adal.js, my libs (including jQuery), adal.angular.js, and some of my ADAL initialization code within the auth.html, but it never updates the token in the main frame (app) when loading is completed in the iframe.

So what are the requirements for code that runs in the iframe? Why are there requirements at all really, shouldn't ADAL.js simply read the token from the URL and update in the main app?

Is there any ADAL functions need to call within my auth.html?

Note: It works fine if I don't override the redirectUri, but that means it loads the whole SPA on token renewal.

**Comment by sondreb** [comment]
I duplicated my content from index.html into auth.html, then started removing code that was running. It appears that angular needs to be bootstrapped. Is there any way to avoid this? Right now we have enabled HTML5 mode, which in the current release (1.0.9) means it will do an extra redirect, so on every token renewal my app are loaded twice, and there are megabytes of JavaScript.

**Comment by PavelPikat** [comment]
The problem was raised in #151 and hasn't been fixed yet. As I can see, it was added to 1.0.10 milestone, so all we have to do now is wait :)

**Comment by sondreb** [comment]
Doesn't look like it is the same problem, but might be related. I don't get any errors or problems like that, it simply doesn't update the token cache after loading iframe unless the iframe loads the whole app and runs the Angular initialize for ADAL.

**Comment by sondreb** [comment]
I made a hack that seems to work fine, I would advice against using it, but this is what we are going to do until another solution is available. This is the code I have within my "auth.html", which is a very simple HTML file that only loads adal.js.

The code uses internal methods in ADAL.js, which is probably not smart to do, but had to do it to make it work.

I would like to add a feature request to support a scenario where the iframe loads a separate HTML file and not the whole app. I was expecting ADAL to read the id_token from the iframe when it was done loading, but it doesn't appear to do so? Is that what it's suppose to?

```js
// Create an instance of the ADAL object, window.config is the 
// instance/tentant and other configuration values for ADAL.
window.authContext = new AuthenticationContext(window.config);

// Get a reference to the current selected resource.
var resource = authContext.getResourceForEndpoint("");

// Read the token from URL.
var token = window.location.href.split('id_token=')[1];
token = token.split('&state')[0];

// Parse the token to get user profile and the expire (.exp) value.
var user = authContext._createUser(token);

// Save the token to storage.
authContext._saveItem(authContext.CONSTANTS.STORAGE.IDTOKEN, token);
authContext._saveItem(authContext.CONSTANTS.STORAGE.ACCESS_TOKEN_KEY + resource, token);
authContext._saveItem(authContext.CONSTANTS.STORAGE.EXPIRATION_KEY + resource, user.profile.exp);
```

**Comment by sondreb** [comment]
Few more notes on how we are using this. We have WebSocket communication between app (Angular) and gateway (SignalR) and not REST. We are sending the token when connection with WebSocket service is initiated and we don't need to keep sending the token on every request.

For this reason, we have a timer that checks if the token is in the browser cache every minute, when it is not available any longer, we trigger acquireToken. Since the callback for acquireToken is not working with the setup we have of custom iframe html page, we'll simply wait until next timeout and at that time we'll send the updated token to our WebSocket gateway.

As it triggers every minute, it can take up to 2 minutes for our app to recognize the new token, so we have configured the offset to 240 seconds:

expireOffsetSeconds: 240

Here is the code that keeps checking for valid token and renews when it's about to timeout in 4 minutes (240 seconds). The method is called upon successful connection to our gateway:

```js
var tokenIsNull = false;

function watchToken() {
    $timeout(function () {
        var resource = authContext.getResourceForEndpoint("");
        var token = authContext.getCachedToken(resource);

        if (token === null) {
            tokenIsNull = true;

            authContext.acquireToken(resource, function (msg, tok) {
                // With the current hack for ADAL, we are never seeing this callback...
                console.log('msg: ', msg);
                console.log('tok: ', tok);
            });
        }
        else
        {
            if (tokenIsNull)
            {
                tokenIsNull = false;

                // Send the updated token to our gateway.
                $scope.hub.server.updateToken(token);
            }
        }

        watchToken();

    }, 60000);
};
```

**Comment by tushargupta51** [comment]
@sondreb Currently, when adal tries to renew the token, it reloads the app and cache the token. We are investigating into how we can address that issue and understand that this reload can have some serious performance impacts for SPA apps. As @PavelPikat pointed, part of #151 talks about the same issue (there are another issues about renewal loop and console errors reported there).

**Comment by Neil665** [comment]
We had the same issue where the app was being completely reloaded inside the iframe, causing significant performance impacts. I have implemented a solution which redirects back to a simple html file (the approach also taken by @sondreb), but I have done this by introducing a new config setting called 'frameRedirectUri' so that the frame can be given a different redirect uri to the login page (the login page is still governed by the existing config setting 'redirectUri'). The new config setting defaults to the value of 'redirectUri' to preserve existing behaviour:

```javascript
  if (!this.config.frameRedirectUri) {
    this.config.frameRedirectUri = this.config.redirectUri;
  }
```

The usage of the proposed config setting within the adal.js library is as follows:
```javascript
    var redirectUri = (forFrame ? obj.frameRedirectUri : obj.redirectUri);
    str.push('redirect_uri=' + encodeURIComponent(redirectUri));
```

I have uploaded the adal.js file with the full changes in case you wish to use this solution (I had to put it in a zip file for the upload to be allowed: [adal.zip](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/247910/adal.zip)).

It took a bit of experimenting to get the 'simple html file' (see below) working correctly - note the two lines which I had to put in to stop angular going into an infinite digest loop. I don't know whether these would be necessary in all cases or if it was something particular about our application. Also note that adal-configure.js is just a custom file containing a function called adalConfigure which calls adalProvider.init(), and adal-settings.js just gets the adal library settings and puts them in the APP_MODEL object.

```html
<!DOCTYPE html>
<html ng-app="frameApp">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>
<body>
  <div ng-view /> <!-- If we don't have this, angular goes into an infinite digest loop -->

  <script src="bower_components/angular/angular.min.js"></script>
  <script src="bower_components/angular-route/angular-route.min.js"></script>
  <script src="js/adal/adal.js"></script>
  <script src="js/adal/adal-angular.js"></script>

  <script src="adal-settings.js"></script>
  <script src="adal-configure.js"></script>

  <script type="text/javascript">
    angular
      .module('frameApp', ['ngRoute', 'AdalAngular'])
      .constant('APP_MODEL', { adalSettings: adalSettings })
      .config(['$routeProvider', function ($routeProvider) {
        $routeProvider.otherwise({ redirectTo: 'x' }); // If we don't have this, angular goes into an infinite digest loop (although the path value can be anything)
      }])
      .config(['adalAuthenticationServiceProvider', '$httpProvider', 'APP_MODEL', function (adalProvider, $httpProvider, APP_MODEL) {
        adalConfigure(adalProvider, $httpProvider, APP_MODEL);
      }]);
  </script>
</body>
</html>
```

**Comment by polita** [comment]
Closing as dup of #151

**Comment by jonaseriksson84** [comment]
@neil665 This issue is causing some major headaches for us with many unnecessary xhr requests and what not. Your fix looks beautiful and we want to try it out asap, but having a hard time figuring out more exactly what adal-settings.js and adal-configure.js contain, could you provide an example?

**Comment by Neil665** [comment]
@jonaseriksson84
adal-settings.js and adal-configure.js have the structure shown below, but note that:
- the reason for them existing is just to set up the call to adalProvider.init()
- they are shared between our 'real' app and this iframe dummy app, so their design is influenced by various design considerations in our 'real' app and is thus more convoluted than if we were only using them in this very simple dummy app. Rather than following the structure of these two files, you should take whatever code you use in your 'real' app to set up the call to adalProvider.init(), factor it out into separate file(s) if it is not already, and call it from both your 'real' app and your iframe dummy app so that they both end up having the same configuration.
   
```javascript
var adalSettings = {
    clientId: "Insert your client id here"
    // Also any other settings you require
};
```

```javascript
function adalConfigure(adalProvider, $httpProvider, APP_MODEL) {
    var settings = APP_MODEL.adalSettings;

    var adalSettings = {
        clientId: settings.clientId
        // Also any other settings you require
    };

    adalProvider.init(adalSettings, $httpProvider);
}
```

**Comment by fairmutex** [comment]
Can someone create a sample of this for mere mortals?

**Comment by tushargupta51** [comment]
@fairmutex I have added a gist here with a possible solution: https://gist.github.com/tushargupta51/78ce0b6bce998f6851abd02d91eb3a95. This links to another gist that describe a different solution. Some explanation can be found here: https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs

**Comment by saransh944** [comment]
@Neil665, @tushargupta51  how can we achieve the same in Angular 5? Do you have updated index.html file that is for Angular 2+ applications?
