### ISSUE TITLE
Callback isn't called in locationChangeHandler when there is an error acvquiring the token

### ISSUE THREAD

**Issue by ischrei** [AzureAD/azure-activedirectory-library-for-js#260]
existing code:
if (requestInfo.parameters['access_token']) {
                                        _adal.callback(_adal._getItem(_adal.CONSTANTS.STORAGE.ERROR_DESCRIPTION), requestInfo.parameters['access_token']);
                                        return;
                                    } else if (requestInfo.parameters['id_token']) {
                                        _adal.callback(_adal._getItem(_adal.CONSTANTS.STORAGE.ERROR_DESCRIPTION), requestInfo.parameters['id_token']);
                                        return;
                                    }

------------

Suggested fix:
if (requestInfo.parameters['access_token']) {
                                        _adal.callback(_adal._getItem(_adal.CONSTANTS.STORAGE.ERROR_DESCRIPTION), requestInfo.parameters['access_token']);
                                        return;
                                    } else if (requestInfo.parameters['id_token']) {
                                        _adal.callback(_adal._getItem(_adal.CONSTANTS.STORAGE.ERROR_DESCRIPTION), requestInfo.parameters['id_token']);
                                        return;
                                    }
**else {
                                        $rootScope.$broadcast('adal:loginFailure', _adal._getItem(_adal.CONSTANTS.STORAGE.ERROR_DESCRIPTION));
                                        _adal.callback(_adal._getItem(_adal.CONSTANTS.STORAGE.ERROR_DESCRIPTION), null);
                                    }**

(not sure whether we need to "return" in this case).

Thanks,
Ido.

**Comment by ischrei** [comment]
Another issue:
when there is an error acquiring the token, a false 'adal:loginSuccess' is sent.
The locationChangeHandler method is called more than once for this single redirection, and in one of the calls, the 'adal.callback' is null.

**Comment by tushargupta51** [comment]
Thanks @ischrei . I will get it in the next release.

**Comment by tushargupta51** [comment]
1.0.10 fixes this. Please let me know, if you still see issues.
