### ISSUE TITLE
Interceptor problem on local requests coming from $templateCache

### ISSUE THREAD

**Issue by clembou** [AzureAD/azure-activedirectory-library-for-js#261]
adding and configuring the library breaks my app, even if no authentication is requested anywhere.

The interceptor intercepts `get` requests coming from `$templateCache` to angular template relative urls, treats them as local resources, and expect to be able to find a token for these, see [here](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal.js#L744).

As a result, a call to acquire a new token using the app `clientid` is generated [here](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal-angular.js#L322) if no token is found in the cache, but this fails because the user is not logged in and authentication has not been requested, see  [here](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal.js#L362)

Log:
```
Wed, 06 Apr 2016 17:39:20 GMT:843fe150-a8d0-4f30-bd2d-a6a6bd3f74c3-1.0.9-WARNING: User login is required
Wed, 06 Apr 2016 17:39:20 GMT:843fe150-a8d0-4f30-bd2d-a6a6bd3f74c3-1.0.9-ERROR: Error when acquiring token for resource: <CLIENTID>
stack:
undefined
Wed, 06 Apr 2016 17:39:20 GMT:843fe150-a8d0-4f30-bd2d-a6a6bd3f74c3-1.0.9-INFO: Getting error in the response
Error: [$compile:tpload] Failed to load template: scripts/components/myComponent.html (HTTP status: undefined undefined)
http://errors.angularjs.org/1.5.2/$compile/tpload?p0=scripts%2Fcomponents%2FmyComponent.html&p1=undefined&p2=undefined
    at angular.js:68
    at handleError (angular.js:18640)
    at processQueue (angular.js:15627)
    at angular.js:15643
    at Scope.$eval (angular.js:16895)
    at Scope.$digest (angular.js:16711)
    at Scope.$apply (angular.js:17003)
    at bootstrapApply (angular.js:1713)
    at Object.invoke (angular.js:4625)
    at doBootstrap (angular.js:1711)
```
I think this stackoverflow issue refers to the same problem:
http://stackoverflow.com/questions/35650241/adal-angular-js-error-failed-to-load-template

If I enable authentication on the home page route, I get the same problem on first load, but at some point the route change event is triggered which initiates the login and saves the token to sessionStorage. From that point refreshing the app fixes the issue.

**Comment by tushargupta51** [comment]
@clembou Thanks for reporting this. For the routes that are not protected, adal should not try to acquire a token. Currently, `getResourceForEndpoint` only checks if they is a relative url, and if so, it returns clientId as the resource Id which is later used to request an access token.

> If I enable authentication on the home page route, I get the same problem on first load

If the initial page requires authentication, then I don't think it will send "User login required" error. I see below logs when the home page is set to require authentication. 
````
Thu, 07 Apr 2016 18:27:49 GMT:4069a7ef-9103-49f1-8c06-6f5991341625-INFO: login already start. app.js:43:9
Thu, 07 Apr 2016 18:27:49 GMT:4069a7ef-9103-49f1-8c06-6f5991341625-INFO: Getting error in the response
````

**Comment by tushargupta51** [comment]
1.0.10 fixes this.

**Comment by sanderej** [comment]
Hi, I'm still seeing errors with the $templateCache and I've narrowed the issue down to adal angular 1.0.10. The error only occurs when I have the global config requireADLogin to false (for local development). When I am running my site on Azure with requireADLogin true, my template loads fine. My initialization code looks like this:

```
adalProvider.init({
    tenant: 'tenant.com',
    clientId: 'my-client-id',
    endpoints: endpoints,
    requireADLogin: false,
    anonymousEndpoints: []
}, $httpProvider);
```

The error I see is:

```
angular.js:13550 Error: [$compile:tpload] Failed to load template: help-popover.html (HTTP status: undefined undefined)
http://errors.angularjs.org/1.5.5/$compile/tpload?p0=help-popover.html&p1=undefined&p2=undefined
    at angular.js:68
    at handleError (angular.js:18978)
    at processQueue (angular.js:15961)
    at angular.js:15977
    at Scope.$eval (angular.js:17229)
    at Scope.$digest (angular.js:17045)
    at Scope.$apply (angular.js:17337)
    at done (angular.js:11572)
    at completeRequest (angular.js:11778)
    at XMLHttpRequest.requestLoaded (angular.js:11711)
```

I can work around this issue by deleting my initialization code locally, but I wanted to bring up the issue in case it affects others' production use cases.

**Comment by tushargupta51** [comment]
@sanderej You mentioned that the error occurs when you have `requireAdLogin` set to false globally which means your app is not using authentication. In that case, you can specify "/" in anonymousEndpoints, that should skip interceptor for all of the app's backend urls.

**Comment by harsh-ashtekar** [comment]
Hello all. This is what worked for us...

We modified the **ProtectedResourceInterceptor** in the **adal-angular.js** file to reference the **$templateCache** service. In the **request** method, we simply check if the URL being requested is defined in the **$templateCache**. If it is, we simply return the **config.url**.

Here are the modifications...

`AdalModule.factory('ProtectedResourceInterceptor', ['adalAuthenticationService', '$q', '$rootScope', '$templateCache', function (authService, $q, $rootScope, $templateCache)`

```
request: function (config) {
    if (config) {
        if (typeof $templateCache.get(config.url) !== "undefined") return config;
        ...
```

Of course, this assumes that anything you've explicitly put in the $templateCache shouldn't be authenticated.

Hope that helps!

**Comment by ylashin** [comment]
@harsh-ashtekar another option is to use **config.anonymousEndpoints**. This way you just need to list down all templates needed for your anonymous login/home page.

I had the same issue when I upgrade from 1.0.1 to 1.0.12 and the above worked fine with me

**Comment by danielarita** [comment]
@tushargupta51 with version 1.0.13 I still have this issue, the angular views on my project are getting the HTTP Status undefined undefined, only when the route is protected it works.

**Comment by dliu120** [comment]
I had this problem and solved it by adding anonymous endpoints for our templates. For example, we are using angular-ui-bootstrap components that have template's prefixed with "uib/....". Adding "uib/" to anonymous endpoints fixed the problem.

**Comment by danielarita** [comment]
thanks @dliu120! That is what I ended up doing too, just wished we didn't have to do that.
