### ISSUE TITLE
window.parent.AuthenticationContext is not a function

### ISSUE THREAD

**Issue by istrau3** [AzureAD/azure-activedirectory-library-for-js#262]
I am attempting to use this library with an Aurelia project using webpack. Webpack is a module loader and so adal.js is returning an inject function with the following code:

```javascript 
if (typeof module !== 'undefined' && module.exports) {
    module.exports.inject = function (conf) {
        return new AuthenticationContext(conf);
    };
}
```
I am successfully creating the authenticationContext using the inject function. I am able to login and logout etc. 

The issue arises when I try to use:
```
authContext.acquireToken()
```

Then, for some reason, the page is reloaded and this error is thrown.

**Comment by tushargupta51** [comment]
@istrau3 Can you try setting `window.parent.AuthenticationContext` to authenticationContext returned by the inject function.

**Comment by istrau2** [comment]
@tushargupta51 I don't think that would work because it needs to be the Type instead of the instance. I solved it like this

```javascript
this.authContext = inject(config);
window.AuthenticationContext = this.authContext.constructor;
```

**Comment by tushargupta51** [comment]
@istrau3 Is it ok to close this issue? If using adal without angular, one needs to set the authenticationContext like you did above.

**Comment by istrau3** [comment]
@tushargupta51 Yes, please close. Thanks.

**Comment by richarjain** [comment]
I am facing same issue. Adal Infinite redirection in Edge. Can anybody help me out in this
