### ISSUE TITLE
b2c experimental branch logout problem

### ISSUE THREAD

**Issue by krushnachandra** [AzureAD/azure-activedirectory-library-for-js#265]
I am using b2c experimental branch for identity management with angularjs.
Problem i was facing on logout function is not able to clear the cache properly from the browser.

It was working properly before few days ago.
For the first time login it is redirecting to login window after that if i logout and then again when i try to login it is not asking me the login Window .
It is redirecting to dashboard authenticate page .
I think some server side implementation is done for catching the user or something else

this is code for logout

 vm.logOut = function () {
            adalAuthenticationService.tokenCache.clear();
            adalAuthenticationService.logOut();
        };

**Comment by alaincroisetiere** [comment]
Try this whit v2.0 endpoint.

```javascript
AuthenticationContext.prototype.logOut = function () {
    this.clearCache();
    var tenant = 'common';
    var logout = '';
    this._user = null;
    if (this.config.tenant) {
        tenant = this.config.tenant;
    }
    
    if (this.config.instance) {
        this.instance = this.config.instance;
    }
    
    if (this.config.postLogoutRedirectUri) {
        logout = 'post_logout_redirect_uri=' + encodeURIComponent(this.config.postLogoutRedirectUri);
    }
    
    var urlNavigate = this.instance + tenant + '/oauth2/v2.0/logout?' + logout + '&' + this.config.extraQueryParameter;
    this._logstatus('Logout navigate to: ' + urlNavigate);
    this.promptUser(urlNavigate);
};
```

**Comment by krushnachandra** [comment]
thanks @alaincroisetiere it is working properly for me.
Experimental branch library need to update the logout function. 

When can we expect the stable library for adal b2c any IdeA?

**Comment by tushargupta51** [comment]
@krushnachandra We do not have any final dates yet for when we will have the stable version of adal B2C, will post once we have an update.

**Comment by martinoss** [comment]
Is development on v2 currently on hold?

**Comment by alaincroisetiere** [comment]
@krushnachandra, I also override _createUser method to get userName from emails claims

```javascript
AuthenticationContext.prototype._createUser = function (idToken) {
    var user = null;
    var parsedJson = this._extractIdToken(idToken);
    if (parsedJson && parsedJson.hasOwnProperty('aud')) {
        
        if (parsedJson.aud.toLowerCase() === this.config.clientId.toLowerCase()) {
            
            user = {
                userName: '',
                domainHint: '',
                profile: parsedJson
            };
            
            if (parsedJson.hasOwnProperty('preferred_username')) {
                user.userName = parsedJson.preferred_username;
            }

            if (parsedJson.hasOwnProperty('emails')) {
                user.userName = parsedJson.emails[0];
            }
            
            if (parsedJson.hasOwnProperty('tid')) {
                if (parsedJson.tid === this.CONSTANTS.MSA_TENANTID) {
                    user.domainHint = 'consumers';
                }
                else {
                    user.domainHint = 'organizations';
                }
            }
        } else {
            this._logstatus('IdToken has invalid aud field');
        }

    }
    
    return user;
};
```

**Comment by tushargupta51** [comment]
Closing this issue as we are no longer making investments in experimental branch. We are channeling our efforts to next version of this library - MSAL.
