### ISSUE TITLE
"use strict" statement should be inside an IIFE

### ISSUE THREAD

**Issue by rohitpagariya** [AzureAD/azure-activedirectory-library-for-js#269]
The 'use strict' statement in both the libraries is in the global scope, causing issues during minification for my app. While I have fixed the bug in the library, I am opening this issue as a best practice to keep the code encapsulated in an IIFE

**Comment by tushargupta51** [comment]
Thanks @rohitpagariya for reporting this issue. If I understand correctly, your recommendation is to use this pattern:

    (function() 
     {
        //existing adal code
        use strict;
        ....
        ....
     }();

**Comment by rohitpagariya** [comment]
Hi @tushargupta51, yes that's correct. This will ensure the "use strict" scope is restricted to the adal's code.
