### ISSUE TITLE
Option to disable ADAL

### ISSUE THREAD

**Issue by polysg** [AzureAD/azure-activedirectory-library-for-js#270]
We are in a situation where the same Angular app gets deployed both on Azure and on an on-premises web server. The Azure version talks to APIs on Azure and requires Azure Active Directory Authentication. The on-premises version, however, talks only to internal APIs that do not require ADAL.

It would be really nice if we could easily enable or disable ADAL, thus maintaining a single code base for our app.

We thought about creating our own stub ADAL module that does nothing and inject that when deploying on-premises but it doesn’t feel like the most elegant solution.

Another way to achieve this would be to not call `adalAuthenticationServiceProvider.init()` when not needed but this breaks everything because `_adal` from [adal-angular.js#L222](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal-angular.js#L222)  onwards will be null. 

You could of course add something like the following just above [adal-angular.js#L215](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal-angular.js#L215) but this isn't that elegant either.
```
if (_adal == null) {
   console.warn('adal not initialized');
   return {};
}
```

**Comment by gabbsmo** [comment]
You can easily solve this by either having two builds of your javascript bundle or configure adal from server side generated inline javascript. You can for example read web.config and add an if-else block to a Razor view if you are using .NET.

**Comment by JoshDavisMP** [comment]
Tangentially, we have the requirement of using anonymous service endpoints. With commit 2895778dbe1b399ee47f5338786592728a975bfb to fix #195 there is now seemingly no way to ignore certain endpoints.

**Comment by jonaseriksson84** [comment]
What about simply checking your url and conditionally enable ADAL conditionally?

**Comment by tushargupta51** [comment]
@polysg You can override the default event handlers by adding this

                $rootScope.$on('$routeChangeStart', function() {});

                $rootScope.$on('$stateChangeStart', function{});

                $rootScope.$on('$locationChangeStart', function{});

Also, do not pass httpProvider in the init so that adal does not plugin its interrceptor. Overriding the event handlers will not throw the null adal exception you get if you do not call `adalAuthenticationServiceProvider.init()`.

OR I think the better way would be to not inject AdalAngular module if running on premise. That is equivalent to disabling adal.

**Comment by tushargupta51** [comment]
I am closing this issue for now. If you still have this problem, let me know, I will re-open this.
