### ISSUE TITLE
$timeout to obtain saved url is not executing in IE on Windows 10

### ISSUE THREAD

**Issue by jthoni** [AzureAD/azure-activedirectory-library-for-js#271]
This is very similar to a number of issues that I have seen here, but mine seems to be much more specific.  Our app uses query parameters to populate data.  Example:

https://mySite.azurewebsites.net/#/items/?from=03%2F24%2F2016&to=04%2F22%2F2016&filters=%7B%22OcvSourceType.raw%22:%5B%22Customer%20Support%22%5D%7D&q=crash

The url is meant to be shared by users.  We have users reporting that when they click the link, if they are not logged in with an active access_token, after authentication, they will be redirected to the default page with no parameters.

I had not been seeing this, but after tracking it down, it only happens (for me) in Win10 IE.  A coworker is seeing it in Chrome on Win10 (though Chrome for me is fine, and IE works fine on my WS2013 box).  In debugging, I see that this $timeout is called:

$timeout(function () {
    updateDataFromCache(_adal.config.loginResource);
    $rootScope.userInfo = _oauthData;
    // redirect to login requested page
    var loginStartPage = _adal._getItem(_adal.CONSTANTS.STORAGE.START_PAGE);
    if (loginStartPage) {
        // Check to see if any params were stored
        var paramsJSON = _adal._getItem(_adal.CONSTANTS.STORAGE.START_PAGE_PARAMS);
        if (paramsJSON) {
            // If params were stored redirect to the page and then 
            // initialize the params
            var loginStartPageParams = JSON.parse(paramsJSON);
            $location.url(loginStartPage).search(loginStartPageParams);
        } else {
            $location.url(loginStartPage);
        }
    }
}, 1);

When the $timeout executes in my working environments, the adal.start.page (not adal.start.page.params, which is where I would have expected it) loads with the full correct URL.  In my problem environment, even though we called the $timeout, the function is never actually executed. As such, the url is never restored after authentication, and the default routing takes the user to the default page.

I see the same behavior with 1.0.7 and 1.0.8.

Thanks

**Comment by jthoni** [comment]
I pulled the code out of the $timeout, so I see it is getting hit, but that didn't help, so it seems the above is incorrect.  I will have to research further.  

I do notice that I come through locationChangeHandler() many more times in the environment that is not working without an actual url change.  The hash is:

"#id_token=eyJ0eXAiOiJKV1..."

And it loops through locationChangeHandler() 7 - 8 times (where on my other system it only goes through once for the id_token).

**Comment by jthoni** [comment]
I think what is happening is that the tab is crashing, and being reopened in my case. If that is the case then it make sense as to why the url gets cleared.  I am making this assumption due to the fact that if I have the dev tools open in IE, and I localStorage.clear(), then refresh, I get the regular login nav, but the dev tools close. If I reopen, I don't have the history in the console (even though I had specified not to clear on navigate).  This leads me to believe I am actually in a new tab.

So, I think there is something happening (perhaps related to #151) that this particular IE does not like and is crashing.  In any case, I believe that this issue can be closed as it is definitely not the $timeout at fault.

**Comment by tushargupta51** [comment]
@jthoni I believe you might be hitting this issue: https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/130. We intend to fix #130 in next release.

**Comment by tushargupta51** [comment]
@jthoni Closing this issue. Please follow #130 for status on this. Thanks.
