### ISSUE TITLE
Enable 'Keep me signed in' option (KMSI)

### ISSUE THREAD

**Issue by PavelPikat** [AzureAD/azure-activedirectory-library-for-js#272]
I've noticed that Microsoft's login page does not offer a 'Keep me signed in' check box when using ADAL.js. However it is visible when trying to log in to SharePoint directly, by going to *.sharepoint.com

This results in a UX where the user has to login each time after reopening the browser.

Is it possible to enable KMSI option maybe by passing some special parameters to adal?

**Comment by sandor11** [comment]
I am currently implementing a connected account feature within our web application. I was excited to see it is possible to use the Azure AD and Microsoft Graph API to let a user allow access to our web app, but it is highly disappointing that a user will have to re authenticate everytime they use our app which will lead to a very poor user experience.

Basically, this is not the common approach, many other OAuth services work in a more sensible way wherein my application will be able to access the users data when they are 1) logged in to the third party service (Microsoft Account in this case) and 2) have not revoked app permissions from within their Microsoft account.

I can see the app I have given permission to within my Office 365 Apps, so it makes me wonder why, unless I revoke that app, why I am constantly required to sign in. Basically, I want to be able to call an endpoint, and if the user is not signed in, then initiate the login cycle.

So I am with @PavelPikat and would like to see this feature, however, I want it to go further and be more seamless than requiring a check box. If the user has granted my app permission, then this should be respected without constantly asking them if they are sure. The can always revoke from their account page.

On a similar note, the login flow is clunky, cumbersome and disracting. I would like to see the ability to authenticate via the `$http` service in angular using a popup window whereby I can pass the response back to `adal` for parsing in the parent window. I am getting close to this myself, however searching for the token on every location change seems like using a sledgehammer to knock in a nail. We can be way more precise than that with the flow of events.    

Note: I also asked about other people experiencce on SO: http://stackoverflow.com/questions/36881429/microsoft-azure-ad-microsoft-graph-api-angularjs

**Comment by tushargupta51** [comment]
@PavelPikat @sandor11 Are you guys using SessionStorage? I just ran a sample app on my local machine with `cacheStorage = localStorage`. Reopening the browser window does not log out the user.

**Comment by sandor11** [comment]
@tushargupta51 I continued with testing and yes, I was mistaken. It appears as though (when using `localStorage`) the user is logged in again. However, this only works when the browser window is re opened within the token expiry interval. Once the token is expired the problems with the refresh token code, on the surface looks like the user needs to log in again. I will not repeat the whole issue here, I wrote https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/202#issuecomment-215142555 which describes the problem more accurately.

**Comment by nataliavalgepea** [comment]
@tushargupta51 Make sure that you don't have KMSI enabled in some other Microsoft portal, for example Azure or Sharepoint. 
As I said before, if you login to SharePoint or Azure with KMSI checked in, you will be logged in in your Angular app after reopening the browser as well. But if you uncheck KMSI, login to SharePoint, the open Angular app, reopen the browser, open Angular app again - you will have to login.

**Comment by PavelPikat** [comment]
@tushargupta51 Make sure that you don't have KMSI enabled in some other Microsoft portal, for example Azure or Sharepoint. 
As I said before, if you login to SharePoint or Azure with KMSI checked in, you will be logged in in your Angular app after reopening the browser as well. But if you uncheck KMSI, login to SharePoint, then open Angular app, reopen the browser, open Angular app again - you will have to login.

**Comment by PavelPikat** [comment]
@tushargupta51 
I tested it with cacheLocation: 'localStorage' and it magically works with this setup.
I guess this solves the issue.
