### ISSUE TITLE
How does one implement Single Sign On with adal.js being used

### ISSUE THREAD

**Issue by nigel-dewar** [AzureAD/azure-activedirectory-library-for-js#276]
Hi there, 

This is not an issue, but a query that has us stumped.

Does adal.js work with SSO?   We are using ADFS in our enterprise and we know we can get SSO working with Office 365, but how does it work when using ADAL.js?

I have found it really hard to find any doco on this.

Please help if anyone has any experience or knowledge on this.

cheers

**Comment by nigel-dewar** [comment]
Hi, I recieved no answer on this. Can adal.js be used with ADFS on Windows 2016?

**Comment by katagaStyle** [comment]
Technically you could do SSO with Azure AD pretty well. The usage of SSO APPS in Azure is a great thing.
In fact the hole thing in v.1.0.9 is really buggy. I suggest to not use this in production.

**Comment by jonaseriksson84** [comment]
Our site is protected by Microsoft SSO. When redirecting to the ADAL OAuth page, there is no need to sign in as the user is already authenticated. The user will just be redirected back.

**Comment by NickAb** [comment]
Is there any way to setup AzureAD on-premise?

**Comment by darrenparkinson** [comment]
Yes, I agree, documentation for this is, at best, sketchy.  There doesn't seem to be anything on using adal.js on it's own (i.e. without Angular).

**Comment by tushargupta51** [comment]
Apologies for the delay. We have informed ADFS team about this issue and they are working on a sample for demonstrating how adal-Js can be used with ADFS. Either I or someone from ADFS will update this space soon.

@darrenparkinson Have a look at this sample here: https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi. It uses plain adal JS (no angular wrapper).

**Comment by robv8r** [comment]
Has there been any progress with creating an ADFS 2016 On Premise example?

**Comment by tushargupta51** [comment]
Please find the details in this blog post: https://technet.microsoft.com/en-us/windows-server-docs/identity/ad-fs/development/single-page-application-with-ad-fs. You can set tenant: 'adfs' to make the SPA work with ADFS.

**Comment by robv8r** [comment]
Thanks.  That link explains how to use ADAL-JS with ADFS using WS-Federation.

Is there an example that shows how to use ADAL-JS with ADFS 2016 using OpenId Connect?

The following link shows how to use ADAL for the .Net Framework with ADFS 2016 using OpenId Connect.  I'd like to do something similar using ADAL-JS instead of ASP.Net MVC. 

https://technet.microsoft.com/en-us/windows-server-docs/identity/ad-fs/development/enabling-openid-connect-with-ad-fs-2016

**Comment by NickAb** [comment]
@tushargupta51 I followed https://technet.microsoft.com/en-us/windows-server-docs/identity/ad-fs/development/single-page-application-with-ad-fs. The login works as expected. But the logout does not work.

Logout link redirects to `https://<adfs2016-server-address>/adfs/oauth2/logout?post_logout_redirect_uri=https%3A%2F%2Flocalhost%3A44326%2F`
```
Service Unavailable

HTTP Error 503. The service is unavailable.
```

It seems that logout endpoint is not available or enabled by default.

**Comment by nigel-dewar** [comment]
Ok thanks Rob


Sent from Samsung Mobile


-------- Original message --------
From: Rob
Date:13/09/2016 12:30 (GMT+10:00)
To: AzureAD/azure-activedirectory-library-for-js
Cc: nigel-dewar , Author
Subject: Re: [AzureAD/azure-activedirectory-library-for-js] How does one implement Single Sign On with adal.js being used (#276)


If you look at ADFS's OpenID Connection configuration, you'll notice a lack of an end_session_endpoint as defined in the OpenID Connect Session Management<http://openid.net/specs/openid-connect-session-1_0.html> specification.

You can view your server's configuration with the below URL template.

https://<adfs2016-server-address>/adfs/.well-known/openid-configuration


Bear in mind that OpenID Connect Session Management is still in draft. At the time of this post, it was on Draft 27.

-

**Comment by nigel-dewar** [comment]
After all of this, I am still not sure if SEAMLESS single sign on is achievable with adal.js. I dont want my users having to login again to an app after already logging into thier windows machines inside the corporate network. After months of looking, and asking I still dont have the answer

**Comment by nigel-dewar** [comment]
After one obtains a token from ADFS, you cannot seem to use this token to call into O365 resources like sharepoint online. I setup the app in azure ad correctly also. 

Could you please provide an end to end tutorial of using adal.js with ADFS, and then calling O365 resources.

Cheers

**Comment by swathi04c** [comment]
Hi @tushargupta51, could you please tell me if I can use ADAL with Azure ACS for authentication in my angular application.

**Comment by Karthisubburaj** [comment]
HI @tushargupta51 , Will the given example get access token too for the onpremise ADFS scenario?
The response type passed during the login is ID_token, Do we need to add any additional parameter to get the access token? Will we be able to achieve the implicit flow without passing the token responsetype?

Can you please clarify ?

**Comment by Karthisubburaj** [comment]
HI @tushargupta51 ,

When the acquireToken is called to retrieve the accesstoken for a resource, I am getting the below error in response from adfs.

error=login_required&error_description=MSIS9621%3a+Unable+to+handle+the+OAuth+authorization+request+without+getting+user+input.

Please find the below configuration that I am using.

adalProvider.init(
    {
        instance: 'sts url',
        tenant: 'adfs',
        clientId: 'clientid', // your client ID of the
		redirectUri:'http://localhost/OAuthSample/index.html',
		extraQueryParameter: 'nux=1&scope=openid+user_impersonation&embed=yes',
		endpoints :{"http://localhost:1436/": "http://localhost:1436"}
    }

Can you please let clarify if I am doing something wrong or do I need to add any configuration to it?

Regards,
Karthik

**Comment by jelledruyts** [comment]
The extraQueryParameter should not contain the "openid" scope, in fact for AD FS it can just be left empty completely.

**Comment by Karthisubburaj** [comment]
Thanks for clarifying and it is issuing access token now. Will I be not able to pass any scope parameter ? In my example I want to pass the scope parameter as user_impersonation and if I pass the parameter it is not working.

**Comment by jelledruyts** [comment]
Whenever AD FS is refusing to issue tokens, please look in the event logs on the AD FS server (under Applications and Services logs / AD FS / Admin). Optionally enable the Operational logs for even deeper inspection. That's how I figured out that it wouldn't accept the "openid" scope at least.

**Comment by tmfahim** [comment]
Hi- I am trying to implement SSO without any home realm prompt using ADAL.js 1.0.15. However I am getting the prompt for home realm selection even after adding the "extraQueryParameter". I tried to add in 2 different ways shown below, however nothing seems working for me. Any help will be appreciated.

**First way: Try to add this in adalProvider.init** 

adalProvider.init(
        {
            instance: 'https://login.microsoftonline.com/', 
            tenant: 'test.onmicrosoft.com',
            clientId: '8df30a84-d676-415f-a96a-b3199df0ca95',
            popUp: false,
            extraQueryParameter: 'domain_hint=testkronos.com',
            //cacheLocation: 'localStorage', // enable this for IE, as sessionStorage does not work for localhost.
        },
        $httpProvider
        );


Second way: I added this into the ADAL.js config section like this, however still seems not working

AuthenticationContext = function (config) {
        /**
         * Enum for request type
         * @enum {string}
         */
        this.REQUEST_TYPE = {
            LOGIN: 'LOGIN',
            RENEW_TOKEN: 'RENEW_TOKEN',
            UNKNOWN: 'UNKNOWN'
        };

        /**
         * Enum for storage constants
         * @enum {string}
         */
        this.CONSTANTS = {
            ACCESS_TOKEN: 'access_token',
            EXPIRES_IN: 'expires_in',
            ID_TOKEN: 'id_token',
            ERROR_DESCRIPTION: 'error_description',
            SESSION_STATE: 'session_state',
            STORAGE: {
                TOKEN_KEYS: 'adal.token.keys',
                ACCESS_TOKEN_KEY: 'adal.access.token.key',
                EXPIRATION_KEY: 'adal.expiration.key',
                STATE_LOGIN: 'adal.state.login',
                STATE_RENEW: 'adal.state.renew',
                NONCE_IDTOKEN: 'adal.nonce.idtoken',
                SESSION_STATE: 'adal.session.state',
                USERNAME: 'adal.username',
                IDTOKEN: 'adal.idtoken',
                ERROR: 'adal.error',
                ERROR_DESCRIPTION: 'adal.error.description',
                LOGIN_REQUEST: 'adal.login.request',
                LOGIN_ERROR: 'adal.login.error',
                RENEW_STATUS: 'adal.token.renew.status'
            },
            RESOURCE_DELIMETER: '|',
            LOADFRAME_TIMEOUT: '6000',
            TOKEN_RENEW_STATUS_CANCELED: 'Canceled',
            extraQueryParameter: 'domain_hint=testkronos.com',
            TOKEN_RENEW_STATUS_COMPLETED: 'Completed',
