### ISSUE TITLE
LOGIN_REQUEST URL isn't used when login() is called explicitly 

### ISSUE THREAD

**Issue by ischrei** [AzureAD/azure-activedirectory-library-for-js#278]
We are using the Angular service to explicitly invoke login(). We have noticed that the LOGIN_REQUEST value which is saved before redirection to AAD, isn't used in this flow.
It is use in the pure JS version (in handleWindowCallback), and the Angular code only supports the START_PAGE value which is set during automated login which is triggered by a state change.

A suggested fix:
https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal-angular.js#L134:
```
} else {
	// Support manual login flow where _adal.login() was called explicitly from client code
	var loginRequestUrl = _adal._getItem(_adal.CONSTANTS.STORAGE.LOGIN_REQUEST);
	if (loginRequestUrl) {
		$location.$$parse(loginRequestUrl);
	}
}
```

**Comment by tushargupta51** [comment]
@ischrei Thanks for reporting this. I fixed it by calling `loginHandler()` instead of `_adal.login()` inside the angular login method. This saves the current url in START_PAGE value and rebuild the url when user is redirected back to adal after logging in.
