### ISSUE TITLE
1.0.10 initialize adal.config.anonymousEndpoints to []

### ISSUE THREAD

**Issue by tushargupta51** [AzureAD/azure-activedirectory-library-for-js#282]
Currently, users are forced to add `anonymousEndpoints: [],` to the init configuration. This array should have a default initial value. Add this to adal.js init method

    if (!this.config.anonymousEndpoints) {
        this.config.anonymousEndpoints = [];
    }

**Comment by dhodgin** [comment]
when i use 1.0.10 in a sandbox app i don't have to add anonymousEndpoints: [] to my init but when i dropped adal-angular into my business application i get errors about it being undefined and was forced to add it to the init call. I am using the exact same version in both applications. What's the scoop on this and is this landing in 1.0.11?

**Comment by tushargupta51** [comment]
@dhodgin This will be fixed in 1.0.11 so you don't have to specify default in your app.
