### ISSUE TITLE
Using the service in combination with the component router

### ISSUE THREAD

**Issue by mderaeve** [AzureAD/azure-activedirectory-library-for-js#283]
I use the new component router for angular 1. But I cannot get the adalAuthenticationServiceProvider to work. It works with the default route provider.
Is it possible to add an example? I just get this error:
angular.min.js:117 Error: [$compile:tpload] http://errors.angularjs.org/1.5.5/$compile/tpload?p0=%2Fapp%2Fcomponents%2Fazure%2FazureList.html&p1=undefined&p2=undefined

**Comment by tushargupta51** [comment]
@mderaeve What is the adal version that you are using? Can you provide console logs? Instructions to add logging are in README.md.

**Comment by mderaeve** [comment]
version is 1.0.10
Wed, 18 May 2016 06:33:59 GMT:de99873b-e443-4093-b2a6-7ccc598323a8-1.0.10-VERBOSE: Url: /app/components/azure/azureList.html maps to resource: 8fc04254-cdad-46ca-ba17-a5d3cb11dfa7
app.js:28 Wed, 18 May 2016 06:33:59 GMT:de99873b-e443-4093-b2a6-7ccc598323a8-1.0.10-WARNING: User login is required
app.js:28 Wed, 18 May 2016 06:33:59 GMT:de99873b-e443-4093-b2a6-7ccc598323a8-1.0.10-ERROR: Error when acquiring token for resource: 8fc04254-cdad-46ca-ba17-a5d3cb11dfa7
stack:
undefined
app.js:28 Wed, 18 May 2016 06:33:59 GMT:de99873b-e443-4093-b2a6-7ccc598323a8-1.0.10-INFO: Getting error in the response
angular.min.js:117 Error: [$compile:tpload] http://errors.angularjs.org/1.5.5/$compile/tpload?p0=%2Fapp%2Fcomponents%2Fazure%2FazureList.html&p1=undefined&p2=undefined
    at Error (native)
    at http://localhost:54489/nodes/js/angular.min.js:6:412
    at http://localhost:54489/nodes/js/angular.min.js:156:158
    at http://localhost:54489/nodes/js/angular.min.js:130:226
    at n.$eval (http://localhost:54489/nodes/js/angular.min.js:144:467)
    at n.$digest (http://localhost:54489/nodes/js/angular.min.js:142:47)
    at http://localhost:54489/nodes/js/angular.min.js:145:42
    at e (http://localhost:54489/nodes/js/angular.min.js:45:350)
    at http://localhost:54489/nodes/js/angular.min.js:48:275

Keep in mind that I'm using the @angular/router@0.2.0.
Component based router.

**Comment by tushargupta51** [comment]
@mderaeve Does the page `/app/components/azure/azureList.html` require authentication? It seems you are loading this page before user is authenticated. Can you share the code where you initialize adal? Also, try addding `/app/components/azure/azureList.html` to config.anonymousEndpoints like below:


    adalProvider.init(
        {
            instance: 'https://login.microsoftonline.com/', 
            tenant: 'Enter your tenant name here e.g. contoso.onmicrosoft.com',
            clientId: 'Enter your client ID here e.g. e9a5a8b6-8af7-4719-9821-0deef255f68e',
            anonymousEndpoints: [ '/app/components/azure/azureList.html' ],
            extraQueryParameter: 'nux=1',
            //cacheLocation: 'localStorage', // enable this for IE, as sessionStorage does not work for localhost.
        },
        $httpProvider
        );

**Comment by mderaeve** [comment]
Hi, I still get the same behaviour: 
Wed, 18 May 2016 08:31:27 GMT:d8075b7e-619e-4bb3-b659-55b666407fe6-1.0.10-VERBOSE: Url: /app/components/azure/azureList.html maps to resource: null
app.js:28 Wed, 18 May 2016 08:31:30 GMT:d8075b7e-619e-4bb3-b659-55b666407fe6-1.0.10-VERBOSE: Url: /app/components/azure/azureList.html maps to resource: null
app.js:28 Wed, 18 May 2016 08:31:31 GMT:d8075b7e-619e-4bb3-b659-55b666407fe6-1.0.10-VERBOSE: Url: /app/components/azure/serverList.html maps to resource: 8fc04254-cdad-46ca-ba17-a5d3cb11dfa7
app.js:28 Wed, 18 May 2016 08:31:31 GMT:d8075b7e-619e-4bb3-b659-55b666407fe6-1.0.10-WARNING: User login is required
app.js:28 Wed, 18 May 2016 08:31:31 GMT:d8075b7e-619e-4bb3-b659-55b666407fe6-1.0.10-ERROR: Error when acquiring token for resource: 8fc04254-cdad-46ca-ba17-a5d3cb11dfa7
stack:
undefined
app.js:28 Wed, 18 May 2016 08:31:31 GMT:d8075b7e-619e-4bb3-b659-55b666407fe6-1.0.10-INFO: Getting error in the response
angular.min.js:117 Error: [$compile:tpload] http://errors.angularjs.org/1.5.5/$compile/tpload?p0=%2Fapp%2Fcomponents%2Fazure%2FserverList.html&p1=undefined&p2=undefined
    at Error (native)
    at http://localhost:54489/nodes/js/angular.min.js:6:412
    at http://localhost:54489/nodes/js/angular.min.js:156:158
    at http://localhost:54489/nodes/js/angular.min.js:130:226
    at n.$eval (http://localhost:54489/nodes/js/angular.min.js:144:467)
    at n.$digest (http://localhost:54489/nodes/js/angular.min.js:142:47)
    at http://localhost:54489/nodes/js/angular.min.js:145:42
    at e (http://localhost:54489/nodes/js/angular.min.js:45:350)
    at http://localhost:54489/nodes/js/angular.min.js:48:275(anonymous function) @ angular.min.js:117
http://localhost:54489/azure Failed to load resource: the server responded with a status of 404 (Not Found)

My app.js looks like this:
(function (angular) {
    'use strict';

    angular.module('nav', []);
    angular.module('azure', []);

    angular.module('appAzure', ['ngComponentRouter', 'AdalAngular', 'nav', 'azure'])

        .value('$routerRootComponent', 'app')

        .component('app', {
            template:
              '<ng-outlet></ng-outlet>\n',
            $routeConfig: [
             { path: '/...', name: 'Home', component: 'homeComponent', useAsDefault: true },
              { path: '/azure/...', name: 'Azure', component: 'azureComponent' },
              { path: '/contact/...', name: 'Contact', component: 'contactComponent' }
            ],
        })

    .config([ '$locationProvider', '$httpProvider', 'adalAuthenticationServiceProvider', function ( $locationProvider, $httpProvider, adalAuthenticationServiceProvider) {
        //$locationProvider.html5Mode(true);
        $locationProvider.html5Mode(true).hashPrefix('!');

        Logging = {
            level: 3,
            log: function (message) {
                console.log(message);
            }
        };

        adalAuthenticationServiceProvider.init(
          {
              instance: 'https://login.microsoftonline.com/',
              tenant: '???.onmicrosoft.com',
              clientId: '???',
              anonymousEndpoints: ['/app/components/azure/azureList.html'],
              extraQueryParameter: 'nux=1',
              //cacheLocation: 'localStorage', // enable this for IE, as sessionStorage does not work for localhost.
          },
          $httpProvider
          );
    }]);

})(window.angular);

**Comment by tushargupta51** [comment]
@mderaeve I don't see `requireADLogin` attribute in the config. To give you some background on how adal works: by default, adal secures all calls to app's backend which includes html and js files. You can add exceptions in `config.anonymousEndpoints` which will let you access the specified urls and the child pages without authentication. The error you are getting is because user is not authenticated and your app is trying to load `/app/components/azure/serverList.html`, since user is not authenticated, adal throws the error "User login is required".

So, you have 2 ways to solve this problem:
1. Add `requireADLogin` attribute to your routes. And if you have some resources that you want to load without authenticating user, then add those resources to `anonymousEndpoints` array. For example, if you add `anonymousEndpoints: ['/app/components/azure/'],` to config, it will load all the resources that are located either at /app/components/azure/ or a child url.

2. If you don't want to add requireAdLogin attribute while you are testing, you can specify "/" as an anonymous endpoint which will let urls bypass the need of authenticated user. But you should not do this in your app as I assume you require authenticated user for some of your routes.

**Comment by mderaeve** [comment]
Hi, 

If I run the TodoSPA example, I only see requireADLogin on the link where login is required. The other links are not in the anonymousendpoints. I also expect when the user is not authenticated that the azurelogin page is shown, but I do not see it. If I run the todo example provided in this github, it works. But this is using the default Angular 1.5 router.
Where should I add the requireADLogin: true property?
eg.
.component('app', {
            template:
              '<ng-outlet></ng-outlet>\n',
            $routeConfig: [
             { path: '/...', name: 'Home', component: 'homeComponent', useAsDefault: true },
              { path: '/azure/...', name: 'Azure', component: 'azureComponent' },
              { path: '/contact/...', name: 'Contact', component: 'contactComponent' }
            ],
            requireADLogin: true
        })
Will this mean that all configured routes will require AD? I also tried all sub components. It still doesn't make sense why the login page doesn't popup.
Is it possible to create a small SPA with the new component model and router of Angular? I use Angular 1.5 and router angular_1_router.js. As I read about your lib, it seems that its just not compatible with the new component based router.

**Comment by tushargupta51** [comment]
@mderaeve I took a quick glance at the component router and it seems very different than the old angular router in terms of structure. Can you debug at this line: https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal-angular.js#L189 and share what the route object look like? Adal is expecting `requireAdLogin` property on that object.

**Comment by mderaeve** [comment]
He is not entering in this breakpoint. I debugged the init of the adalAuthenticationService in adal.agnular.js, this breakpoint works. But this function is never hit:
 function isADLoginRequired(route, global) {
                    return global.requireADLogin ? route.requireADLogin !== false : !!route.requireADLogin;
                }

**Comment by tushargupta51** [comment]
@mderaeve I looked more into component router docs and it has an entirely different lifecycle than the old routeProvider. It uses `CanActivate`, `OnActivate`, `CanDeactive` instead of `routeChangeStart`, `routeChangeSuccess` events. Adal currently only supports the old router. Support for this new router will show up when and if we move to angular 2: #194 . ATM, you cannot use component router with adal.

**Comment by fairmutex** [comment]
Do not go down this path. Component router is Deprecated https://docs.angularjs.org/guide/component-router
