### ISSUE TITLE
Does this Library support being used against ADFS

### ISSUE THREAD

**Issue by MarkDordoy-JustEat** [AzureAD/azure-activedirectory-library-for-js#285]
This is a question rather than an issue. I just want clarification on if this library can be used against an ADFS authority rather than an Azure AD authority. 

Thanks

**Comment by nherzalla2016** [comment]
I have the same question Does this Library support being used against ADFS

**Comment by tushargupta51** [comment]
@nherzalla2016 @MarkDordoy-JustEat Apologies for the delay. We have informed ADFS team about this issue and they are working on a sample for this. Either I or someone from ADFS will update this space soon.

**Comment by pauldendulk** [comment]
Same question here

**Comment by tushargupta51** [comment]
Please find the details on how can you use adal with ADFS in this blog post: https://technet.microsoft.com/en-us/windows-server-docs/identity/ad-fs/development/single-page-application-with-ad-fs. You can set tenant: 'adfs' to make the SPA work with ADFS.

**Comment by MarkDordoy-JustEat** [comment]
Thanks @tushargupta51
