### ISSUE TITLE
User login is required

### ISSUE THREAD

**Issue by Dismissile** [AzureAD/azure-activedirectory-library-for-js#286]
I am initializing ADAL for Angular like so:

```
adalProvider.init({
    instance: 'https://login.microsoftonline.com/',
    tenant: 'snip.onmicrosoft.com',
    clientId: 'snip',
    extraQueryParameter: 'nux=1'
}, $httpProvider);
```

I am not setting up any routing rules that require a user to be logged in. I just have a button that will call the login() method.

I am using OWIN self hosting for a web api on the same path that the angular application is on.

root url for angular: www.example.com/fabrikam/
root url for api: www.example.com/fabrikam/api/values

I am trying to make a call to my api and ADAL is rejecting the request requiring a user to be logged in. It looks like it is occurring because of the interceptor. How do I allow all requests to go through and make logins optional?

**Comment by tushargupta51** [comment]
@Dismissile By default, adal secures all calls to backend and external apis. If for some reason, you do not want adal to do that, you can specify `config.anonymousEndpoints` property. In your case, if you want to bypass all the requests, you can add this to init: `anonymousEndpoints = [ "\" ],`

Out of curiosity, why do you not want to secure the call to api? Interceptor attaches a token that will be send to the api. Does your api not require authentication?

**Comment by Dismissile** [comment]
This particular api does not require authentication. Actually the app itself is just a demo of a few things and I added the authentication as a small part of it. I noticed after adding ADAL that this piece of the app was now broken unless I was logged in.

**Comment by tushargupta51** [comment]
@Dismissile Does adding the anonymousEndpoints property on config fixed your issue?

**Comment by Dismissile** [comment]
@tushargupta51 yes that seems to have fixed the issue. Although i had to switch it from:
anonymousEndpoints: [ "\" ] to anonymousEndpoints: ["/"] since \ is an escape character

**Comment by tushargupta51** [comment]
Yeah, that was a typo. It should be "/". I will go ahead and close this issue then.
