### ISSUE TITLE
On Adal intialization in config funtion error is thrown

### ISSUE THREAD

**Issue by hentry** [AzureAD/azure-activedirectory-library-for-js#288]
Hi,
I am using adal in office addin to get the file attachment content. But, during my angular app config function execution, Adal is throwing javascript error like this.
`fs.js:2110TypeError: Cannot create property 'resource' on string 'User login is required'
    at q.then.p.$resolved (angular-resource.js:613)
    at angular.js:13189
    at l.$eval (angular.js:14401)
    at l.$digest (angular.js:14217)
    at l.$apply (angular.js:14506)
    at angular.js:1448
    at Object.e [as invoke] (angular.js:4185)
    at d (angular.js:1446)
    at tc (angular.js:1466)
    at Jd (angular.js:1360)
    at HTMLDocument.<anonymous> (angular.js:26176)
    at j (jquery.js:3099)
    at Object.k.fireWith [as resolveWith] (jquery.js:3211)
    at Function.n.extend.ready (jquery.js:3417)
    at HTMLDocument.I (jquery.js:3433)(anonymous function) @ fs.js:2110(anonymous function) @ fs.js:116(anonymous function) @ angular.js:11607(anonymous function) @ angular.js:8557(anonymous function) @ angular.js:13197l.$eval @ angular.js:14401l.$digest @ angular.js:14217l.$apply @ angular.js:14506(anonymous function) @ angular.js:1448e @ angular.js:4185d @ angular.js:1446tc @ angular.js:1466Jd @ angular.js:1360(anonymous function) @ angular.js:26176j @ jquery.js:3099k.fireWith @ jquery.js:3211n.extend.ready @ jquery.js:3417I @ jquery.js:3433
fs.js:2110TypeError: Cannot read property 'push' of undefined
    at n (adal-angular.min.js:2)
    at l.$broadcast (angular.js:14720)
    at Object.transitionTo (angular-ui-router.js?v=3.0.02:3140)
    at Array.<anonymous> (angular-ui-router.js?v=3.0.02:2318)
    at Object.e [as invoke] (angular.js:4185)
    at handleIfMatch (angular-ui-router.js?v=3.0.02:1822)
    at angular-ui-router.js?v=3.0.02:1877
    at check (angular-ui-router.js?v=3.0.02:1992)
    at update (angular-ui-router.js?v=3.0.02:2001)
    at l.$broadcast (angular.js:14720)
    at l (angular.js:11452)
    at angular.js:11438
    at l.$eval (angular.js:14401)
    at l.$digest (angular.js:14217)
    at l.$apply (angular.js:14506)
    at angular.js:1448
    at Object.e [as invoke] (angular.js:4185)
    at d (angular.js:1446)
    at tc (angular.js:1466)
    at Jd (angular.js:1360)
    at HTMLDocument.<anonymous> (angular.js:26176)
    at j (jquery.js:3099)
    at Object.k.fireWith [as resolveWith] (jquery.js:3211)
    at Function.n.extend.ready (jquery.js:3417)
    at HTMLDocument.I (jquery.js:3433)(anonymous function) @ fs.js:2110(anonymous function) @ fs.js:116(anonymous function) @ angular.js:11607(anonymous function) @ angular.js:8557l.$broadcast @ angular.js:14722transitionTo @ angular-ui-router.js?v=3.0.02:3140(anonymous function) @ angular-ui-router.js?v=3.0.02:2318e @ angular.js:4185handleIfMatch @ angular-ui-router.js?v=3.0.02:1822(anonymous function) @ angular-ui-router.js?v=3.0.02:1877check @ angular-ui-router.js?v=3.0.02:1992update @ angular-ui-router.js?v=3.0.02:2001l.$broadcast @ angular.js:14720l @ angular.js:11452(anonymous function) @ angular.js:11438l.$eval @ angular.js:14401l.$digest @ angular.js:14217l.$apply @ angular.js:14506(anonymous function) @ angular.js:1448e @ angular.js:4185d @ angular.js:1446tc @ angular.js:1466Jd @ angular.js:1360(anonymous function) @ angular.js:26176j @ jquery.js:3099k.fireWith @ jquery.js:3211n.extend.ready @ jquery.js:3417I @ jquery.js:3433
fs.js:2096Info: Changing route `

Please have a look on this.

**Comment by tushargupta51** [comment]
@hentry Can you share how you configure adal and routes/states? Also, if you can provide console logs, that will help investigate this further, instructions are in the readme. From the error, it seems you might have, `message.resource` in your code as it complains about `resource` property on the string "User login is required" cannot be created.

**Comment by hentry** [comment]
Hi @tushargupta51,
That problem is solved, now when i initiate a http call to graph api(https://graph.microsoft.com/v1.0/me), am always getting invalid access token error. I know what the problem is, In my application we are adding Authorization token to all the $http calls to contact with our api. so, for graph api also instead of adal token my application token is set in Authorization header. How can solve this problem..??

**Comment by hentry** [comment]
Even I tried to read the adal token in sessionStorage(adal.idtoken) and set in graph api call like this,
`$.ajax({
                type: "GET",
                url: "https://graph.microsoft.com/v1.0/me",
                dataType : 'json',
                headers : {
                    "accept": "application/json",
                    'Authorization' : 'Bearer ' + sessionStorage.getItem('adal.idtoken')
                },
                success: function (response){
                    console.log(response);
                }
            });`

But, still 401 is thrown from graph api side.
what might be the problem..??

**Comment by hentry** [comment]
My Adal Intialization in config is below,
`adalAuthenticationServiceProvider.init(
                          {
                              tenant: 'XXXXXXX.onmicrosoft.com',
                              clientId: '4504c396-65da-49af-ab58-XXXXXXXXX',
                              endpoints : {
                                "https://graph.microsoft.com/v1.0/me": 'https://graph.microsoft.com'
                              }
                              //cacheLocation: 'localStorage', // enable this for IE, as sessionStorage does not work for localhost.
                          },
                          $httpProvider
                        );`

**Comment by hentry** [comment]
My problem is similar to this problem https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi/issues/12

**Comment by hentry** [comment]
@tushargupta51  "Cannot create property 'resource' on string 'User login is required'" error occurs inconsistenly. Some times it happens and some time its not. I got the following traces,
<img width="1669" alt="screen shot 2016-05-20 at 2 33 31 am" src="https://cloud.githubusercontent.com/assets/16078396/15409674/813a8454-1e33-11e6-93d5-0a86f1ac75d3.png">


Following are the states in my module,
`function getRoutes() {
        return [
            {
                name: 'outlook',
                config: {
                    url: '/outlook',
                    templateUrl: 'app/components/outlook-addin/outlook-loading.html',
                    controller: 'outlookAddinController',
                    controllerAs: 'vm',
                    title: 'Loading',
                    data: {
                      authenticate: false,
                      footer: 0,
                      zopim: false
                    }
                }
            },{
                name: 'outlook.login',
                  config: {
                      url: '/login',
                      templateUrl: 'app/components/outlook-addin/outlook-login.html',
                      controller: 'LoginController',
                      controllerAs: 'vm',
                      title: 'Login',
                      data: {
                        authenticate: false,
                        footer: 0,
                        zopim: false
                      }
                  }
            },{
                 name: 'outlook.getStarted',
                   config: {
                       url: '/getStarted',
                       templateUrl: 'app/components/outlook-addin/outlook-get-started.html',
                       controller: 'OutlookGetStartedController',
                       controllerAs: 'vm',
                       title: 'Login',
                       data: {
                         authenticate: false,
                         footer: 0,
                         zopim: false
                       }
                   }
             },{
                   name: 'outlook.documentsList',
                     config: {
                         url: '/documentsList',
                         templateUrl: 'app/components/outlook-addin/outlook-documents-list.html',
                         controller: 'OutlookDocumentsListController',
                         controllerAs: 'vm',
                         title: 'Documents List',
                         params : {
                            action : ''
                         },
                         requireADLogin: true,
                         data: {
                           authenticate: true,
                           footer: 0,
                           zopim: false
                         }
                     }
               },{
                   name: 'outlook.actionCenter',
                     config: {
                         url: '/actionCenter',
                         templateUrl: 'app/components/outlook-addin/outlook-action-center.html',
                         controller: 'OutlookActionCenterController',
                         controllerAs: 'vm',
                         title: 'Choose Action',
                         data: {
                           authenticate: true,
                           footer: 0,
                           zopim: false
                         }
                     }
               },{
                   name: 'outlook.chooseRecipient',
                     config: {
                         url: '/chooseRecipient',
                         templateUrl: 'app/components/outlook-addin/outlook-choose-recipient.html',
                         title: 'Choose Recipient',
                         params : {
                             file : {}
                          },
                         data: {
                           authenticate: true,
                           footer: 0,
                           zopim: false
                         }
                     }
               },{
                   name: 'outlook.selfSign',
                     config: {
                         url: '/selfSign',
                         templateUrl: 'app/components/outlook-addin/self-sign.html',
                         title: 'Self Sign',
                         params : {
                             file : {}
                          },
                         data: {
                           authenticate: true,
                           footer: 0,
                           zopim: false
                         }
                     }
               },{
                   name: 'token',
                     config: {
                         url: '/token',
                         templateUrl: 'app/components/outlook-addin/outlook-token.html',
                         title: 'Token',
                         controller: 'OutlookTokenController',
                         controllerAs: 'vm',
                         data: {
                           authenticate: false,
                           footer: 0,
                           zopim: false
                         }
                     }
               }
        ];
    }`

**Comment by tushargupta51** [comment]
@hentry 
1. Regarding, "Cannot create property 'resource' on string 'User login is required'" , it seems this error is originating from the code in your app. "User login is required" is a warning message that adal throws. Some piece of code is trying to create a property on that.
2. Regarding, the other error where it says "push" is not defined, add `anonymousEndpoints= []` to your adal initialization code in `adalAuthenticationServiceProvider.init(`
3. For the token issue with graph, can you share the network trace showing the call made to graph and also in your resources tab, can you check if adal has saved a token for graph endpoint and if it is same as what is sent on network.

**Comment by tushargupta51** [comment]
@hentry Closing this issue for now. If you still running into this issue, let us know, I will re-open this.
