### ISSUE TITLE
Auto Renew Tokens for 2.0 Branch

### ISSUE THREAD

**Issue by nmiddendorff** [AzureAD/azure-activedirectory-library-for-js#289]
I noticed there has been quite a few bug fixes for 1.x.x concerning the auto-renew tokens. 2.0 has not been updated since October. Does 2.0 currently support auto-renew tokens? If not, is there a workaround?

**Comment by tushargupta51** [comment]
@nmiddendorff 2.0 is currently experimental. And it does support auto renewal of tokens.

**Comment by nmiddendorff** [comment]
Once I initialized our endpoints object, the token renewal process gets stuck in an infinite loop.

Console:

LoadFrame: adalIdTokenFrame
State: 4645961e-8ba5-45b4-xxxx-1840f774268b|81ebbf05-904a-45eb-xxxx-228fb61e94c5
State status:true
Request typeRENEW_TOKEN
State is right
renewing idtoken
renewIdToken is called
Add adal frame to document:adalIdTokenFrame
Renew token Expected state: 7c6c900c-c3fd-4d57-xxxx-0832af815092|81ebbf05-904a-45eb-xxxx-228fb61e94c5
.....

**Comment by tushargupta51** [comment]
@nmiddendorff Can you please share complete logs for the loop?

**Comment by nmiddendorff** [comment]
I believe I am setting up the endpoints correctly for B2C.
Console logs:

renewing idtoken
renewIdToken is called
Add adal frame to document:adalIdTokenFrame
Renew token Expected state: 894c01a9-29cb-4c95-xxxx-11b5e272dd68|81ebbf05-904a-45eb-xxxx-228fb61e94c5
Navigate url:https://login.microsoftonline.com/xxxx.onmicrosoft.com/oauth2/
Navigate to:https://login.microsoftonline.com/xxxx.onmicrosoft.com/oauth2/
LoadFrame: adalIdTokenFrame
Add adal frame to document:adalIdTokenFrame
LoadFrame: adalIdTokenFrame
Add adal frame to document:adalIdTokenFrame
renewing idtoken
renewIdToken is called
Add adal frame to document:adalIdTokenFrame
Renew token Expected state: 228db5da-b287-49d8-xxxx-f913cbce2a95|81ebbf05-904a-45eb-xxxx-228fb61e94c5
Navigate url:https://login.microsoftonline.com/xxxx.onmicrosoft.com/oauth2/
Navigate to:https://login.microsoftonline.com/xxxx.onmicrosoft.com/oauth2/
LoadFrame: adalIdTokenFrame
State: 894c01a9-29cb-4c95-xxxx-11b5e272dd68|81ebbf05-904a-45eb-xxxx-228fb61e94c5
State status:true
Request typeRENEW_TOKEN
State is right

**Comment by tushargupta51** [comment]
Closing this issue as we are no longer making investments in experimental branch. We are channeling our efforts to next version of this library - MSAL.
