### ISSUE TITLE
ADAL JS invokes http calls with expired access token

### ISSUE THREAD

**Issue by ischrei** [AzureAD/azure-activedirectory-library-for-js#296]
Some of our users get 401 error while calling a protected resource with the message: _"The access token expiry UTC time '5/25/2016 5:34:34 PM' is earlier than current UTC time '5/25/2016 5:39:30 PM'."_

I'm suspecting this bug may occur when the clock on the client machine isn't synced with the server's clock.
In this such cases the framework clears the resource's token from storage, and it's the app responsibility to retry the call. However it is better if such error doesn't occur at all.

Thanks!
Ido.

**Comment by tushargupta51** [comment]
@ischrei Adal relies on the client clock when checking if the token is expired or not. It cannot know about the server clock before attaching the token to the outgoing request. It saves the expiration time based on current time and the "expiresin" value sent in the token. I don't think adal can ensure that server and client clocks are in sync.

**Comment by ischrei** [comment]
Hi,
Of course adal can't sync the clocks, but maybe a heuristic may help in this case. 
If i'm not mistaking, AAD generate access tokens with expiration time of 1 hour (better of course if you verify it in your side). So ADAL can take the minimum value from the expiration time according to the expiresin value, OR 60 minutes. For the safe side, I would even say 55 minutes.

Theoretically, if there is a user with more than 1 hour time difference, the framework won't work for him at all. As every time it will try to use the token, it will think it is expired.

Thanks!

**Comment by tushargupta51** [comment]
>> ADAL can take the minimum value from the expiration time according to the expiresin value, OR 60 minutes

Not sure, I understand this. The access tokens have 1 hr expiration time, are you suggesting to use a lower value than what's present in expires in property? For example, if token will expire at 1:00 PM, save expiration as 12:55 PM. There is a setting on config `expireOffsetSeconds` which does a similar thing. Default if 120 seconds, which means if a token is about to expire in 2 minutes, it will renew it instead of using it.

**Comment by ischrei** [comment]
I agree I can use the expireOffsetSeconds setting. However a more generic solution in the framework sounds better. As i said, I have evidences for users who tried to use the token even after 1 hour and ~6 minutes.. (Maybe you can change the default value to more than 2 minutes?)
Your call.

**Comment by tushargupta51** [comment]
Closing this issue as the 2 minutes default is fine and is configurable if user wants to do so.
