### ISSUE TITLE
QuotaExceededError on PRIVATE Safari window

### ISSUE THREAD

**Issue by stuartlong** [AzureAD/azure-activedirectory-library-for-js#302]
ADAL JS keeps hitting a QuotaExceededError when trying to do pretty much anything in a _private_ window in Safari. 

Looks to be caused by trying to save data to local/sessionStorage. Can ADAL JS even work without storage support?

**Comment by maheshp9** [comment]
+1

**Comment by tushargupta51** [comment]
@stuartlong I haven't tried repro'ing it yet. But AdalJS require storage to work. Default is session storage.

**Comment by tushargupta51** [comment]
I was able to repro it. Unfortunately, Safari does not allow to write anything in local/session storage when running in private window. Adal requires write access to local/session storage to function. We recommend other browsers like Chrome, Firefox if you want to use private window.

**Comment by maheshp9** [comment]
Challenge with that is my app users don't understand all that difference and it is very hard to surface that error.

**Comment by stuartlong** [comment]
I agree, I have no issues personally with not using Safari. But I definitely have users who do use Safari. Do I need to start informing them to use something else for their private browsing needs or will adal.js eventually support them?

**Comment by tushargupta51** [comment]
@maheshp9 @stuartlong Its not really something that adal js can support, it requires write access to storage in order to operate and Safari private browsing does not allow to write anything to storage. Informing users to use other browsers for private browsing is the way to go.
