### ISSUE TITLE
The library is not working with the new dialog framework in Office Addins?

### ISSUE THREAD

**Issue by rolandoldengarm** [AzureAD/azure-activedirectory-library-for-js#304]
I'm trying to get ADAL JS working in an Angular Office Add-in, using the new Dialog framework to start the oauth flow. So, the oauth flow happens in a dialog.

What I'm experiencing, is that the oauth response (i.e. token) is not processed by my app. I've analyzed it with Fiddler, and I see the following:
- After logging in, login.microsoftonline.com responds with a HTTP/302 which includes the token.
![image](https://cloud.githubusercontent.com/assets/14539000/16066711/c9c10226-3309-11e6-83cc-59a231a9f3c5.png)
- The next thing is that my app is loaded from localhost,  however there is nothing in the query string!
![image](https://cloud.githubusercontent.com/assets/14539000/16066741/f4afc03a-3309-11e6-9372-002dd1de33a8.png)

I have absolutely no idea what is going wrong here.
Sorry if I shouldn't be using Github if this is support, but it seems a bug to me? Or an unsupported feature?

**Comment by tushargupta51** [comment]
@rolandoldengarm Is the app using adalJs provides full browser experience or does it load in a hosted browser on a native client?

**Comment by rolandoldengarm** [comment]
It is an Office Add-in, which essentially is a website hosted in a webview component (rendered by Internet Explorer).

**Comment by vibronet** [comment]
Hey Rolando,
The response you see in your screenshot is the correct behavior expected of ADAL JS.
ADAL JS is not designed to work inside a WebView - rather, it is meant to work with apps factored as single page applications, loaded in a full browser. The token is meant to be returned to one URL on your app, and if the app isn't actually being served by web server, that mechanism won't work. 
For the Office Add-ins, I believe there is specific guidance designed to work with that particular environment. https://msdn.microsoft.com/en-us/library/office/mt629180.aspx looks like a good starting point.
thanks
V.
