### ISSUE TITLE
Sporadic invalid_state errors during login

### ISSUE THREAD

**Issue by ischrei** [AzureAD/azure-activedirectory-library-for-js#305]
Hi,

Some of our customers fail to login our portal due to "Invalid_state" login error.
I claim this issue is sporadic, as I have evidences for users who got invalid_state error, but managed to login my portal successfully before and after this error.

I'm using the sessionStorage as ADAL JS's storage, and I'm suspecting sessionStorgae inconsistency, i.e. login states which aren't saved in sessionStorage before redirecting to AAD or erased when redirecting back to my portal.

For security reasons, I still want to use the sessionStorage, but a possible fix to this issue may be managing the auth states in localStorage while keeping tokens management in sessionStorage.
(We do need to consider multiple logins in several tabs in parallel).

What do you think?

Thanks,
Ido.

**Comment by tushargupta51** [comment]
@ischrei Do you have any data on which browsers customer are hitting this issue? If browser is inconsistently deleting the session storage, then its not just the auth states but other values like "login start page", "nonce", "session.state", if cleared from sessionStorage can cause different issues. I have had an issue reported with Edge, where it was deleting the "login.request" inconsistently resulting in users sometimes landing on an incorrect page after login.
