### ISSUE TITLE
document the minimum required version of angular for this library

### ISSUE THREAD

**Issue by dhodgin** [AzureAD/azure-activedirectory-library-for-js#306]
We are currently using angular 1.2.x because we have a requirement to support IE8 for a little while longer.

I realize integrating AAD into our app for SSO won't work with IE8 but we still plan to support IE8 with our own app login and just disable AAD SSO for IE8 users (degraded experience).

If this library requires angular 1.3.x+ it would be nice to know and I will have to take that to my business team to decide if we will either drop support for IE8 or postpone AAD SSO integration for our application.

either way it would be helpful to specify in the readme.md what the minimum version of angular required is and if it works with angular 2.0 or not.

**Comment by tushargupta51** [comment]
@dhodgin Our samples are written against 1.2.25/26 version of angular. This library works with 1.2.x version of angular. As Angular 2.0 is very different than angular 1.0, this library will not work with angular 2.0 (#194).
