### ISSUE TITLE
Redirect url

### ISSUE THREAD

**Issue by MrunalShidurkar** [AzureAD/azure-activedirectory-library-for-js#307]
What should be the redirect url if i want to it integrate with SharePoint hosted app. l. For SharePoint hosted app every time the app deployed the url will be changed. How should we make redirect url dynamic so that for every app url it will work

**Comment by tushargupta51** [comment]
@MrunalShidurkar Sorry for the delay in the response. Redirect url is an optional property and by default, adal sets the root address of the app as redirect uri. Does it work for you if you don't set the redirect uri?

**Comment by tushargupta51** [comment]
@MrunalShidurkar Let us know whenever you have more info or if you are still running into this issue, I will reopen it for further discussion. Thanks.
