### ISSUE TITLE
Infinite redirect loop when entering 1.0.11

### ISSUE THREAD

**Issue by ruisilva450** [AzureAD/azure-activedirectory-library-for-js#308]
For start, in 1.0.8 I'm not having any problems or errors about this issue
But knowing that 1.0.8 has issues with token renewal, I tried to upgrade for 1.0.11 release branch.
Now when I enter the webapp, it starts an infinite redirect loop that triggers several 
`10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []`
and crashes the browser.
Can't do anything from here.

What I found is that the library is always reporting that there is an error being thrown:
```
{
    "method": "GET",
    "transformRequest": [
        null
    ],
    "transformResponse": [
        null
    ],
    "url": "App/Resources/pt-pt.js",
    "params": "",
    "headers": {
        "Accept": "application/json, text/plain, */*"
    },
    "data": "User login is required"
}
```

I understand that Angular uses httpRequests to get other resources like scripts and in this case a translation js file. Don't know how this is even an issue.

PS: On Edge I don't get any angular errors but the app is always restarting.

Thanks

EDIT: I tracked down an message that was supposed to get to the console when we have the logging enabled:

```
Logging = {
    level: 3,
    log: function (message) {
        console.log(message);
    }
};
```

but we never get the messages to get to the console.
`Fri, 17 Jun 2016 15:44:41 GMT:640a30b7-f50b-43c8-8c90-e782bd3a3026-1.0.10-ERROR: Error when acquiring token for resource: 76486e99-42d8-4073-ba8d-590858c _xxxxx_ 
stack:
undefined`

**Comment by dhodgin** [comment]
I get the same problem. Seems to be a few cases where the library goes in an endless loop. this is the same error i get at the end of the loop between cycles. My application has our own traditional form of login and we are trying to bolt on AAD login as a second form of login. We only use a requestError interceptor to handle 401's and pop up a login box. adal-angular is a little different using both a request and requestError interceptor. It seems like this problem happens for me when either the login to AAD has timed out or I log out of our app using our traditional logout methods. Both methods give me the same problem. we are probably going to have to write our own interceptors. The thing is even if i leave the $httpProvider out of the init call i still get these infinite loops a lot after being inactive in the app for an hour or so.

**Comment by ruisilva450** [comment]
I have this problem since I updated the AdalJS to 1.0.11. I can't get my app to work in any cases. Just have to rollback to 1.0.8 for now and face the renewal token issue

**Comment by tushargupta51** [comment]
@ruisilva450 Where are you picking the 1.0.11 bits from? dev branch?

Could you provide some details about the error:
1. Are you using ui-router or ng-route?
2. Can you share routing configuration?
3. On which browser you are running into loop?
4. With the logging enabled, what are the messages that keep getting logged when the app runs into the loop? I see the stack: undefined message, that does not seem to an adal error message to be.

**Comment by ruisilva450** [comment]
1. ui-router
2. 
```
$stateProvider
        .state('login', {
            url: "/login",
            views: {
                '': {
                    templateUrl: "/app/views/login.html",
                    controller: 'AppController',
                    resolve: {
                        tenantId: function () {
                            return null;
                        }
                    }
                }
            }
        })
        .state('unauthorized', {
            url: "/unauthorized",
            views: {
                '': {
                    templateUrl: "/app/views/unauthorized.html",
                    controller: 'AppController',
                    resolve: {
                        tenantId: function () {
                            return null;
                        }
                    }
                }
            }
        })

        .state('tenant', {
            url: "/tenant",
            views: {
                '': {
                    templateUrl: "/app/views/tenant.html",
                    controller: 'AppController',
                    resolve: {
                        tenantId: function () {
                            return null;
                        }
                    }
                }
            }
        })
        .state('app', {
            url: "/{tenantId}/app",
            abstract: true,
            templateUrl: "/app/Views/master.html",
            controller: 'AppController',
            resolve: {
                tenantId: ['$stateParams', function ($stateParams) {
                    return $stateParams.tenantId;
                }]
            }
        })
        .state('app.config', {
            url: "/config",
            views: {
                '': {
                    templateUrl: "/app/Config/Views/config.html"
                }
            }
        })
        .state('app.home', {
            url: "/home",
            views: {
                '': {
                    templateUrl: "/app/Views/home.html",
                    controller: "HomeController"
                }
            }
        })
            .state('app.xpto', {
                url: "/xpto",
                abstract: true,
                views: {
                    '': {
                        templateUrl: "/app/XPTO/Views/master.html",
                        controller: 'XPTOController',
                        requireADLogin: true
                    }
                }
            })
```
3. Opera, Chrome, Edge, IE
4. Can't get much of the logs. Any of them get to the console because the browser crashes before that.

**Comment by ruisilva450** [comment]
You really should update the docs because this isn't mentioned anywhere.

**Comment by tushargupta51** [comment]
@ruisilva450 What is your otherwise route configured to? The anonymousEndpoints should only include the endpoints for which you do not require user authentication. Adding "app/" in that list means that any request that is sent to that url or a child url will succeed without a logged in user. This does not seem to be applicable for templateUrl: "/app/XPTO/Views/master.html" as the associated route requires authentication. So, am not sure if its the right solution.

You mentioned that you hit the loop as you enter the app, whats the url you enter into the browser to start with? Also, I think you might be able to get the logs if you can turn on debugging somehow as it will pause the loop. I am interested in knowing if it is getting into a transition loop between 2 states, I think you might be able to see it in console logs even if the app hangs.

**Comment by tushargupta51** [comment]
@ruisilva450 If the "otherwise" state is a protected state, I think you might be hitting this issue: https://github.com/angular-ui/ui-router/issues/2238 or https://github.com/angular-ui/ui-router/issues/600. Both are same actually, 2238 is the condensed version of 600. Resolution is to define a state with "/".

Something like this:

    $stateProvider.state("/", {
            url: "/",
            templateUrl: <could be home page or default page",
            requireADLogin: true,
        });

**Comment by ruisilva450** [comment]
Sorry for the delay.
In the otherwise I have:
`$urlRouterProvider.otherwise('/' + window.localStorage["tenantId"] + '/app/home');`
that leads to the home page of a given tenant (of a multi-tenant app)
I have a sort of landing first page that is the login page.

**Comment by tushargupta51** [comment]
@ruisilva450 I would need to look at the logs to debug this further. You can try something like this to capture logs:
1. Login with `var anonymousEndpoints = ["app/"];` configured.
2. Put breakpoints in the adal scripts or in your app.
3. Remove the `var anonymousEndpoints = ["app/"];` and re-login.
4. This should stop at the breakpoints you set.

**Comment by tushargupta51** [comment]
Closing this for now. Let me know if you still run into any issues with 1.0.11, I will re-open this. Please read the https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs and trusted zones remarks (if using IE/Edge): https://github.com/AzureAD/azure-activedirectory-library-for-js#trusted-site-settings-in-ie
