### ISSUE TITLE
Routing continues to page even after being directed to login

### ISSUE THREAD

**Issue by Neil665** [AzureAD/azure-activedirectory-library-for-js#316]
When adal-angular.js handles routing to a secured page, it passes control off to the loginHandler method, but as currently implemented it also lets the navigation to that page continue at the same time. This means that the page starts to get loaded when the user is not yet logged in. It seems to me that the preventDefault mechanism should be used by adding a single line as indicated below.

Is this correct?

```javascript
                var routeChangeHandler = function (e, nextRoute) {
                    if (nextRoute && nextRoute.$$route) {
                        if (isADLoginRequired(nextRoute.$$route, _adal.config)) {
                            if (!_oauthData.isAuthenticated && !_adal._renewActive) {
                                _adal.info('Route change event for:' + $location.$$url);
                                e.preventDefault(); // *** ADDED LINE ***
                                loginHandler();
                            }
                        }
                        else {
                            if (nextRoute.$$route.templateUrl && !isAnonymousEndpoint(nextRoute.$$route.templateUrl)) {
                                _adal.config.anonymousEndpoints.push(nextRoute.$$route.templateUrl);
                            }
                        }
                    }
                };
```

**Comment by tushargupta51** [comment]
@Neil665 Navigation to the page should not happen as adal interceptor rejects the request if login is in process: https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal-angular.js#L347. But I think it might be better to prevent the route/state change here itself, as its going to be rejected later by interceptor anyways. I will see if I can include this change to the PR I am working on. Thanks!

**Comment by tushargupta51** [comment]
@Neil665 We decided to not prevent the navigation at this stage as it does not push any notification to user from adal's side if they want to take any action. When the request is rejected in interceptor, adal broadcasts 'adal:errorResponse' event that users can listen and take any action if needed.
