### ISSUE TITLE
App is stuck and there is no indication from ADAL when AAD returns an error page within the iFrame

### ISSUE THREAD

**Issue by ischrei** [AzureAD/azure-activedirectory-library-for-js#318]
In some cases, AAD may return an error in the iFrame as an error page and not by redirecting back to the app with the #error parameter.
Is those cases, the app is stuck (in my case during loading, in other cases during http calls). The least ADAL can  do is to identify those cases and send an Angular event so the app will be able to catch it and respond accordingly.

**Comment by tushargupta51** [comment]
Adal JS implements implicit flow and in this flow, authorization server should always return the response (error or token) as a fragment: https://tools.ietf.org/html/rfc6749#section-4.2.2.1. If AAD is not returning the error as a fragment, it sounds like a bug in server.

**Comment by ischrei** [comment]
O.k. but anyhow I think ADAL JS should at least identify those cases and raise an event\ error trace.
And I guess it should be escalated to the AAD team to resolve their bug.
