### ISSUE TITLE
Running into MFA issues due to inability to specify resource in /authorize

### ISSUE THREAD

**Issue by yiil** [AzureAD/azure-activedirectory-library-for-js#319]
When using this library for a SPA app in a MFA-enabled tenant that has conditional access enabled for MS Graph, all users who sign in will get the following error:
Error description:AADSTS50079: The user is required to use multi-factor authentication.
This is resolved by adding a &resource=00000003-0000-0000-c000-000000000000 into first authorize request for the id_token. However, it doesn't look like adal.js supports adding this. Support for adding this resource is necessary in order for users (in a MFA-enabled tenant that has conditional access enabled for MS Graph) to sign in using adal.js.

**Comment by tushargupta51** [comment]
@yiil If I understood correctly, adding "&resource=00000003-0000-0000-c000-000000000000" in the login request prompts user for MFA, right?

If so, you can try something like this:
config.displayCall(urlNavigate): you can set this property to a function. It will take over the login redirect. adal passes the navigateUrl that it prepared to this method.

    config.display = function(urlNavigate) {
        if (urlNavigate) {
            urlNavigate += "&resource=00000003-0000-0000-c000-000000000000"; 
            window.location.replace(urlNavigate);
         } 
    }

**Comment by yiil** [comment]
Cool! This was able to add the 'resource' param to the login. However, it looks like MFA is still not getting triggered, even with this added. I'll follow up and file an issue with that the team that owns that experience, as it looks like this is not related to the adal.js. Thanks!
