### ISSUE TITLE
$window.location assignment in adal-angular.js overrides redirect to start_page

### ISSUE THREAD

**Issue by Jasper-Duan** [AzureAD/azure-activedirectory-library-for-js#321]
In the adal-angular.js file, assignment of window.location triggers a page redirect. Due to this, the page fails to land on the stored start_page.

Detail:
The webpage briefly (<100ms) redirects to the correct start_page, but then it redirects to our homepage.
IE: "site.com/home/xyz?123" -> {authentication} -> "site.com/home/xyz?123" -> "site.com/home/"

For the time being, my team has removed $window.location assignment:
                        if ($location.$$html5) {
                            $window.location = $window.location.origin + $window.location.pathname;
                        } else {
The site experience is now:
"site.com/home/xyz?123" -> {authentication} -> "site.com/home/xyz?123"
"site.com/home/" -> {authentication} -> "site.com/home/#"

**Comment by tushargupta51** [comment]
@Jasper-Duan I am going to remove the hash reset code in an upcoming PR. This will be fixed then.
