### ISSUE TITLE
ADAL.JS crashes when extracting ID token

### ISSUE THREAD

**Issue by ThorstenHans** [AzureAD/azure-activedirectory-library-for-js#33]
I know about the issue with reusing Windows Account in WAAD, but I think a lot of people will stumble upon the same issue. 

One of my azure subscriptions is related to my Windows Account (former LiveID) when trying to authenticate that user, ADAL.JS throws an error when it tries to extract the ID token within `_extractIdToken`

**Comment by omercs** [comment]
It works as expected with hotmail or similar MSA account. Idtoken parsing issue was also fixed.
