### ISSUE TITLE
When using multiple forms of authenitcation, the interceptor can break everything

### ISSUE THREAD

**Issue by dhodgin** [AzureAD/azure-activedirectory-library-for-js#333]
I have a use case that is probably common among other users who would implement AAD SSO.

We have a traditional login system for our existing users where they have a username and password for their account in our system. We use our own LocalStrategy (passport in node.js) on the server side with local credentials for those users.

We are adding in Azure AD single sign on for companies we choose to allow to authenticate that way. Those users still have to be loaded in our system with an email to connect them with their AAD account but we authenticate them with a Bearer token from AAD instead of using stored credentials in our system.

Our model is reactive rather than proactive like adal-angular's interceptor. We allow any request to be made to any api route on our server and the server authenticates the request and replies with a 200 if ok or 401 if not authenticated, or 404 if not authorized or page not found (we follow the github model of 404ing for 403's). This means we will never need to use `requireADLogin: true` for all our client side routes, we just allow any request to be made and let the server handle the security.

adal-angular uses a proactive model where it intercepts the **request** as it's going out and decides: if it should attach a token, renew and attach a token, **or reject the request if renewal fails**. this is a problem for anyone using multiple forms of authentication on their site and a **response** interceptor to trigger login rather than a request interceptor for triggering authentication.

When I load our application with the $httpProvider passed to the init() call for adal-angular, it will block all requests to the server if it can't find a token, no login has been triggered, and it can't renew the token in an iframe. 

This is very hard to debug and resolve because when the interceptor blocks the request it falls down into the promise that tries to renew the token, fails, and then **rejects** the promise. This results in the http request being dropped before it leaves the client so the network tab in the debugging tools doesn't even show a request being made and no request is received at the server to respond with a 200, 401, or 403.

I can fix all of this by simply changing the `delayedRequest.reject(config);` to `delayedRequest.resolve(config);` in the error handling function of the acquireToken() call.

When it's a `reject(config)` it will drop all requests before they have a chance to go anywhere and be dealt with server side. I suppose this reasoning is ok if your expecting AAD to be your only form of authentication and you were expecting a login to be triggered before you would try to renew the token. But if AAD is NOT your only form of authentication then it makes sense that if there is no token stored, and no login in progress, and no login error, that you might not want to necessarily reject that request. You might want it to continue and let the next middleware, or interceptor deal with it or handle the response later.

The code in the interceptor is really written in a way that it is expecting and assuming it is the only form of authentication an application might be using and as a result it's stomping on requests if it can't renew the token in the iframe and dropping the request. My entire website can't load any templates or make any XHR requests as a result.

We have our own interceptor attached to the response instead of the request and if the server replies with a 401 we pop a login, if it replies with 404 we send them to 404, and if it replies with 500 we send them to 500 and show a message if one was provided.

In this reactive vs proactive model of handling requests and responses to the server we are sort of stuck here when trying to use AAD for authentication.

both methods result in a session being established and a cookie used with each request. we don't plan to validate a token on every request yet but will at some point down the road so we can enable server to server integration's with our system and other systems. We accept that once a session is created if that user is locked out of AAD then they will remain logged into our system for the duration of the cookie. We can deal with that in a separate feature by kicking the user out if their token expires and can't be renewed or something later.

I'm wondering what would be the best approach to solve this issue and if other people would have a similar use case as me to warrant making a change to the code to allow a config value to be passed to init to support or let adal-angular know that other methods of authentication are being used on this site in tandem with it.

perhaps a config option of `multiAuthentication: true`, with a default false. And in the interceptor when the promise fails to renew a token in the iframe we can check the config option and reject if it's false and resolve if its true passing the config object back in both cases.

Happy to hear comments on this and will make a PR to support it if it makes sense. If I'm missing something here I'm also happy to hear comments. This could be somewhat related to issue #291 and #326 as well.

**Comment by dhodgin** [comment]
after closer inspection I realized just changing the reject to resolve would let the templates load and stop some requests from being dropped but it would still break other things. If I comment the entire else block that handles renewing the token I can also complete requests and load templates and make xhr data requests and I can also login with my standard form of authentication. If i only change the reject to resolve i start getting invalid json errors when posting to login. The overall design problem still exists and a change can still be considered. I'll continue to narrow this down more and update as I go.

I'd really like to avoid having to fork or write my own interceptor because it would be 95% the same and I'd have to maintain it every new release and keep up with bugs. So I'm hoping this use case is valid for more than just me.

**Comment by tushargupta51** [comment]
@dhodgin You can handle this in two ways:
1. Set `anonymousEndpoints=[ "/"]` in adal init (requires 1.0.10 or later). This will make interceptor skip checking all the requests send to backend. I still have to write a description of this property somewhere. Interceptor skips checking all urls (and child urls) specified in this property. For example. If you set it to [ "App/Views/" ]. It will skip checking tokens for requests made to App/Views or App/Views/Home etc. Specifying "/" as anonymousEndpoints mean that you want interceptor to skip checking for tokens for your entire app. NOTE: Use this carefully. In your case, as you already have some mechanism to login users in response interceptor, it will probably be fine in your case. 
2. Listen to "adal:errorResponse" broadcast: When adal interceptor rejects a request, this event is raised. You can listen to this event and initiate login if you want.

I think #1 might fix your issue better. Let me know if this doesn't work for you.

**Comment by dhodgin** [comment]
@tushargupta51 this is really helpful. just as i saw your response i was looking into some of the broadcasted events to see if that might provide a solution.

I think setting the anon endpoints to "/" would be similar to just not passing $httpProvider to the init call wouldn't it? by adding "/" to the anon endpoints i suppose the request interceptor will be skipped but the responseError interceptor will still be used and handle clearing the sessionStorage and broadcasting the errorResponse so i'll start with using "/" in my anon endpoints

This is our current flow without adal:

make client request,
receive request on server and authenticate it
if authenticated, check authorization
end up returning either 200 and data, 401, 404, or 500 status codes
on client if 401 is returned, show login modal dialog and push original request to a retry queue so after attempting login if successful, it will retry the request automatically for the user and modal disappears
if 404 redirect to /404 if 500 redirect to /500

so to integrate adal into this model i think i will make the following changes:
do like you suggest and add "/" to anon endpoints so the request interceptor is skipped
add my own request interceptor to my existing interceptor which only has responseError and make it do the following:
- check if there is a resource for this url
- check if there is a token for this resource
- if there is attach the token to authorization header and return the config
if no token just return the config

very simple and its only purpose would be to add the token to the header if one exists

then the server response can trigger 401 if no token or traditional credentials login

what i can do at that point is in the code where i would show the modal dialog have a button for "Login with AD" on that login form that can offer the alternative login method. I could also add a cookie or read one of the sessionStorage keys to detect if AAD has been used before in the past to login, if it has i could not even show the login modal and instead refresh the token and retry the request. and if i can't refresh the token, show the modal login popup with AD login button or traditional login form.

This will take a few days but i'll post back when I have tried a few options and maybe it can be used as a model for others who use multiple authentication methods.

**Comment by dhodgin** [comment]
hmm. I went looking at the code closer and realized getResourceForEndpoint() is what handles deciding if the url requested should return a resource and try to send a token. if my anon endpoints is "/" then resource returned will always be null

so i can't make my own request interceptor that uses `getResourceForEndpoint` and `getCachedToken` to supply the token because a null resource will be returned.

**Comment by tushargupta51** [comment]
@dhodgin Are you still having any issues? It seems, given your app model and requirement if skipping the request interceptor, you might be better off hooking up your own interceptor. In that case, you wouldn't need to set `anonymousEndpoints` to "/".

**Comment by dhodgin** [comment]
@tushargupta51 my solution has been to just leave out the adal interceptors all together and augment our own responseError interceptor. Our model is to be reactive to a 401 from the server and prompt the user with login, and retry the request rather than be proactive and hijack every request and prompt for authentication before making the request since we can have two methods of authentication. We rely on the server to handle authentication/authorizations and react accordingly.

We check for a stored token and post to login with it and only pass the bearer token when posting to login and our app continues to use client side encrypted sessions that are passed back with each request in the cookie. Our traditional LocalStrategy for passport on the server side with node.js uses username and password and a client session. Now we just add a new passport strategy for bearertokens and add it to the array of authentication strategies server side and everything else stays the same after authentication.

Simplifies things greatly. Down the road we will have a phase 2 integration so we can support a bearer token with every request for server to server communications but that's out of scope for this.

I think it's fair to close this ticket as invalid. But I do think a short note in the readme.md would be very helpful to let users know they can leave out the httpProvider in the init if they want to use their own form of interceptors and bypass the default ones you guys have provided if their use cases warrant it.

**Comment by tushargupta51** [comment]
@dhodgin Glad you got it sorted out. I will close this ticket now.
