### ISSUE TITLE
 Adal.js and Azure Signing Key Rollover

### ISSUE THREAD

**Issue by estene** [AzureAD/azure-activedirectory-library-for-js#335]
I know Adal.js doesn't validate the token, but relies on the webapi for this, but : 
As I can't find any official documentation on this, I'm posting it here just to be sure. 

Is this library in any way affected by the Azure Signing Key Rollover : https://azure.microsoft.com/en-us/documentation/articles/active-directory-signing-key-rollover/ ?

**Comment by estene** [comment]
I figure I should have posted this on stackoverflow instead, so here is the link for anyone interested: http://stackoverflow.com/questions/38117629/adal-js-and-azure-signing-key-rollover

**Comment by tushargupta51** [comment]
@estene As you said, adal js relies on web apis for token validation. If the web api is created using Visual Studio and uses Microsoft authored middleware for token validation, key rollover is handled by the token validation library that these APIs internally use.

**Comment by tushargupta51** [comment]
Closing this issue as web apis should take care of key rollover as token validation happens there.
