### ISSUE TITLE
401 causes loop

### ISSUE THREAD

**Issue by katagaStyle** [AzureAD/azure-activedirectory-library-for-js#336]
Hi. 

We use adal for the o365 video api. When a user has no permission for a resource then a 401 unauthorized will be returned. This causes an endless loop. 

INFO: Getting error in the response ...
INFO: Getting error in the response ...
--> LOOP

A quick workaround is to change status code of rejection on video api from 401 to e.g. 412. 

Any idea to sort this issue out or why this happens? 

Thank you in advance.

**Comment by tushargupta51** [comment]
@katagaStyle Can you provide verbose level logs?

**Comment by tushargupta51** [comment]
Let us know if you have more info, I will reopen the issue for discussion.
