### ISSUE TITLE
Perform Azure Active directory authentication using ADAL. js SharePoint Hosted app

### ISSUE THREAD

**Issue by ramarajusrinivas** [AzureAD/azure-activedirectory-library-for-js#338]
I need to implement AAD authentication using Adal.js in Sharepoint hosted app that is deployed in SPO site.  SharePoint removes the user token that is added on the header while making cross domain calls. can you suggest if the approach is correct  or this functionality is feasible or not. Quick help is very useful.

**Comment by tushargupta51** [comment]
@ramarajusrinivas Can you provide more details as to what functionality you are referring to? If SPO removes the token from the header that adal adds when making cross domain calls, then you will get a 401 error I think.

**Comment by tushargupta51** [comment]
Let us know if you have more info, I will reopen the issue for discussion.
