### ISSUE TITLE
We need a way to modify endpoints after init

### ISSUE THREAD

**Issue by nicoschmitt** [AzureAD/azure-activedirectory-library-for-js#339]
In a Office 365 world using multi-tenant, we can't know in advance the sharepoint tenant, or the Skype pool the user will need to access.
So we need to be able to add dynamically url to endpoints after login.

This is what I do for now, but it's not very elegant.

```
    function addToAdalEndpoints(url) {
        var adalendpoints = AuthenticationContext.prototype._singletonInstance.config.endpoints;
        
        var parser = document.createElement("a");
        parser.href = url;

        var endp = parser.protocol + "//" + parser.host;

        adalendpoints[endp] = endp;
    }
```

**Comment by nicoschmitt** [comment]
Digging up into the code, I've found that config is exposed by the service.
So this is nicer:
`adalAuthenticationService.config.endpoints[url] = url;`

Maybe exposing that in the doc would be good.

**Comment by tushargupta51** [comment]
@nicoschmitt We don't have API docs at the moment but will keep this mind if we get to that. Closing this issue as it seems you got the right property to use for this purpose.
