### ISSUE TITLE
v1.0.10 introduces bug 'Unable to get property 'push' of undefined or null reference' re: config.anonymousEndpoints

### ISSUE THREAD

**Issue by ChrisSchaller** [AzureAD/azure-activedirectory-library-for-js#342]
commit d0350f393f42a82308f46478d52aa34f2cefa05d introduces a new error: 

Exception was thrown at line 2, column 3629 in https://secure.aadcdn.microsoftonline-p.com/lib/1.0.10/js/adal-angular.min.js
0x800a138f - JavaScript runtime error: Unable to get property 'push' of undefined or null reference

The issue is that unless the developer manually creates the anonymousEndpoints array in the provider init, then their apps will no longer run.

I have manually solved this issue by creating the array if it is not there at the line where the error is raised, but I would prefer to see this sort of initialisation done within the provider layer rather than the implementation, this can't be the only like of code that uses anonymousEndpoints right?

> adal-angular.js - line: 238

> `if (toState.templateUrl && !isAnonymousEndpoint(toState.templateUrl)) {
    if (!_adal.config.anonymousEndpoints) _adal.config.anonymousEndpoints = [];
    _adal.config.anonymousEndpoints.push(toState.templateUrl);
}
`

**Comment by max-buecker** [comment]
This isn't even a bug. This is fatal disassembly of the library. It's not usable. How can this be a full release. This has not been tested at all.

**Comment by tushargupta51** [comment]
@ChrisSchaller @max-buecker This is a known issue: #282  and will be fixed in next release: https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/282.

**Comment by tushargupta51** [comment]
This is fixed in 1.0.11.
