### ISSUE TITLE
ADAL JS supporting client_credentials grant type?

### ISSUE THREAD

**Issue by frobozz67** [AzureAD/azure-activedirectory-library-for-js#348]
Can/will ADAL JS ever support grant type "client_credentials"? We have use cases where a Web App (Javascript) needs to call a Web API but use an application identity not a user identity. A user of the Web App does not login. The Web API is only checking that the request is from the Application Identity using an access token. The Web App would be using AJAX/javascript  calls to call the Web API. So would think that ADAL JS would be better suited to manage the JWT tokens then the ADAL .Net library. Is my thinking on this incorrect?

**Comment by tushargupta51** [comment]
Adal Js cannot support "client_credentials" grant_type as that grant_type is for confidential clients who can keep the client secrets secure whereas adal Js is meant for browser based public clients. You might want to use your web app's backend to make calls to the web api with the client credentials.

**Comment by tushargupta51** [comment]
Closing this issue, let me know if you have any further questions.
