### ISSUE TITLE
oauth2/logout?post_logout_redirect_uri="someUri" not working

### ISSUE THREAD

**Issue by max-buecker** [AzureAD/azure-activedirectory-library-for-js#353]
I'm using adal.js in my UWP/JS app.
When I use the `adalService.logout()` method, I get signed out, but stay on the screen, telling me something like "Sou've successfully signed out - We advise you to close all browser windows now". It's not the exact text, since I get the localized/german version of it.

Problem being now, that this is the location of the main view port, and navigation is blocked due to https. So I would like to get back to my app with the specified post_logout_redirect_uri thats being passed correctly.

But the markup of the signout page is not really doing much to make this redirect. Maybe there are some parameters missing, or AAD is not allowing this, though I don't know why there would be the post-logout-redirect-uri then.

So yeah. Calling logout() makes the user sign out and getting stuck at the AAD page, since there is no button or timeout, that enables for navigation somewhere else. What can I do?

EDIT: Is there a setting in the client manifest in azure maybe?

Heres a section of the logout page, thats being rendered. Despite the weird conditions in `if`s, `InitiatorRedirect` is called, but you can see it's as empty as my soul:
```javascript
<script type="text/javascript">
    
    function SetImageStatus(imageIndex, status) {
        
        if (imageStatusArray[imageIndex] === 0) {
            
            imageStatusArray[imageIndex] = status;
        }
    }

    
    function CompleteSignoutWhenImagesLoad(counter) {
        var imageLoadDone = 1;

        for (var i = 0; i < imageStatusArray.length; i++) {
            if (imageStatusArray[i] === 0) {
                imageLoadDone = 0;
                break;
            }
        }

        if (imageLoadDone === 1 || counter >= 2000 / 100) {
            CompleteSignout();
        } else {
            counter++;
            
            setTimeout(function() { CompleteSignoutWhenImagesLoad(counter) }, 100);
        }
    }

    function CompleteSignout() {
    
        var imageFailedToLoad = false;

        
        for (var i = 0; i < imageStatusArray.length; i++)
        {
            
            if (imageStatusArray[i] !== 1) {
                imageFailedToLoad = true;
                break;
            }
        }

        
            
            
            if (imageFailedToLoad)
            {
                    
                    RenderSignoutFailure();
                    
            }
            else
            {
                RenderSignoutSuccess();

                
                setTimeout('InitiatorRedirect()', 1000);
            }
            
    }

    function RenderSignoutSuccess() {
        User.UpdateLogo('', "Sie haben sich von Ihrem Konto abgemeldet.");
        var signoutStatusMessage = $('#SignOutStatusMessage');
        signoutStatusMessage.text("Es empfiehlt sich, alle Browserfenster zu schließen.");
    }

    function RenderSignoutFailure() {
        
        User.UpdateLogo('', 'Wir konnten Sie leider nicht abmelden.');
        var signoutStatusMessage = $('#SignOutStatusMessage');
        signoutStatusMessage.text("Sie sind möglicherweise noch bei einigen Anwendungen angemeldet. Schließen Sie Ihren Browser, um die Abmeldung abzuschließen.");

        
    }

    function WriteSignoutFailedCookie() {
        
        document.cookie = "SOS" + "=1; path=/";
    }

    function InitiatorRedirect() {
    }
</script>
```

**Comment by tushargupta51** [comment]
@max-buecker I tested this on my local app. This is what the log-out uri looks like: `GET /tushartest.onmicrosoft.com/oauth2/logout?post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A44327%2F HTTP/1.1` and the script inside the response AAD page has this

    function WriteSignoutFailedCookie() {
        
        document.cookie = "SOS" + "=1; path=/";
    }

    function InitiatorRedirect() {
            window.location = "http://localhost:44327/";
    }

What is the value of the post_logout_redirect_uri? You said: "that this is the location of the main view port, and navigation is blocked due to https" Is your app a hosted in a web view or something?

**Comment by max-buecker** [comment]
I'm within an edge browser of a UWP Windows 10 app. And the console says, that navigation history is disabled or something. That shouldn't matter however, since I'm providing the post_logout_redirect_uri just like you do. The request header to the logout page looks something like the following:
![image](https://cloud.githubusercontent.com/assets/19929742/17093240/5e5a3eb8-5248-11e6-9980-b45c49e94f3f.png)
And this is what I get as response body:
![image](https://cloud.githubusercontent.com/assets/19929742/17093272/89424346-5248-11e6-8947-52f774ab9d1a.png)
I'll try and see what happens, when my local language is set to English to see if this problem persists.

**Comment by tushargupta51** [comment]
@max-buecker Sorry for the delay in the response. I missed an important part of your issue: UWP/JS app. Adal JS only supports regular browser apps and does not support native apps with hosted browsers. So, using adal js with UWP is not the way to go. We have other adal flavors for this purpose. Check this out: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet

**Comment by tushargupta51** [comment]
Closing this issue as adaljs is not designed for hosted browsers and/or native apps.

**Comment by neelDev** [comment]
@tushargupta51 I am also facing the same issue. After logout its not redirecting to the URI given in the "post_logout_redirect_uri". I am not using any native apps here, its angular application.

Can you please let me know Do I need to configure anything in azure portal to make it works?

**Comment by walunjsachin** [comment]
Was this issue ever resolved?  I have SPA web application (adal logout) does not redirect at all in IE 11 but same works fine in Chrome.

**Comment by max-buecker** [comment]
@walunjsachin Not really. My project was cancelled by management shortly after due to other reasons. I recommend adding a new issue with your details and reference the issue in here.
