### ISSUE TITLE
Cleanup unused variables

### ISSUE THREAD

**Issue by tushargupta51** [AzureAD/azure-activedirectory-library-for-js#354]
In adal.js, we have few unused variables and constants defined. Remove those if they are not used. Below are the ones that I could find:

1. this.popUp in constructor 
2. this.frameCallInProgress in login()
3. ERR_MESSAGES.NO_TOKEN: 'User is not authorized': This constant is not used. Also, evaluate if we want to define error messages as constants at the top or continue defining them as we use them (the existing way).

In addition, scan both lib files for any stale code that we can remove.

**Comment by rohitnarula7176** [comment]
#356
