### ISSUE TITLE
Using implicit flow (response_type=id_token) with a resource specified doesn't trigger conditional access policies

### ISSUE THREAD

**Issue by yiil** [AzureAD/azure-activedirectory-library-for-js#359]
The bug is that when you use the implicit flow (response_type=id_token) and you specify a resource (resource=https://graph.microsoft.com), EvoSTS does not invoke the conditional access policies applied to Graph.  EvoSTS treats the client app as the resource, which doesn’t have the conditional access policy applied.

adal.js then tries to get a token using response_type=token and prompt=none, but the request fails because the conditional access policy is applied and MFA is required.

**Comment by tushargupta51** [comment]
For MFA to occur at the time of login, you need to add one more query paramater in the login request. In your current configuration, please add:
`extraQueryParameter: 'amr_values=mfa'`

In Azure AD portal, if you configured your app to access some resources and at least one of them requires MFA, then user will be prompted for MFA at the time of login.

If you haven't added the permissions to access MFA resource in your web app configuration in portal, you can specify the resource id at the time of login like this:
`extraQueryParameter: 'amr_values=mfa&resource=<resource app id>'`

**Comment by dstrockis** [comment]
Sorry, `amr_values` isn't an good enough solution to the problem.  This would require developers to know which tenants should & shouldn't require MFA for their app, which they can't possibly know.

I proposed two solutions in our email thread:

- When the library sends `response_type=id_token&resource=https://graph.microsoft.com`, conditional access policies should be invoked for the Microsoft Graph.  That's a server-side change, and requires that adal.js send the resource parameter on the authorize request.
- The library sends `response_type=id_token token&resource=https://graph.microsoft.com`, which will invoke conditional access policies for the Microsoft Graph.

@vibronet did not like the latter, and I tend to agree with him.  I think you should chase down the former proposal with the EvoSTS team.

**Comment by brentschmaltz** [comment]
@dstrockis Do you think this is still an issue?

**Comment by jmprieur** [comment]
We are working on releasing ADAL.js 1.0.15 which properly supports Conditional Access.
