### ISSUE TITLE
Separate Angular services/implementation from adal.js

### ISSUE THREAD

**Issue by mattmazzola** [AzureAD/azure-activedirectory-library-for-js#36]
I would understand that you want this library to be a single file that developers can easily use and be ready to go with Angular but having them coupled like this seems more confusing to me. 

I expect adal.js library to only be concerned with managing authentication and each Spa framework to provide their own file which levelerages apis from adal.js. You could easily move the angular specific services to angular.adal.js and start a convention that each framework: Ember, React, Backbone, etc have [name].adal.js as the filename.

Also, this repo would be specifically for iterating on the ADAL library, and use a separate repo (such as: SinglePageApp-DotNet) which demonstrates ADAL used with Angular and only that repo would have the angular specific information.  This would allow people to open issues only concerned with adal.js here, and other issues with the angular implementation somewhere else instead of having people unsure where to provide feedback.

**Comment by Sayan751** [comment]
A small question, is the `adal` part is already on npm as a separate package?

**Comment by tushargupta51** [comment]
@Sayan751 not as a separate pacakge. Both adal and adal-angular are wrapped in one pacakge.

**Comment by Sayan751** [comment]
@tushargupta51 Thanks for your reply. Is there any plan to make these two as two separate packages? 

I am looking for the type definitions for the same. I know that there is a typings available under [`@types/adal`](https://www.npmjs.com/package/@types/adal), which declares a module `adal`.
Does this means, that to use the typings we need to import `adal`? But at runtime, we need to import `adal-angular` npm package. I am little bit confused, about how to import the module for my TypeScript + Webpack project.

**Comment by FDMatthias** [comment]
A bit late, but I've written a blogpost about this [here](https://www.appfoundry.be/blog/2018/11/24/authentication-with-adal-in-react-single-page-applications/) and put a sample of a React SPA with Adal on github [here](https://github.com/appfoundry/react-adal-authentication-session-sample/tree/Authentication-with-ADAL-in-React-SPA) (includes step by step commits and multiple branches).
