### ISSUE TITLE
Is there a scope event for token renewal?

### ISSUE THREAD

**Issue by MaJaHa95** [AzureAD/azure-activedirectory-library-for-js#372]
I have a web call that I want to make every time a user becomes authenticated (essentially a "get notifications" type of thing).

My initial code looked something like this:

```
if ($rootScope.userInfo.isAuthenticated) {
    setup();
}
else {
    $rootScope.$on("adal:loginSuccess", () => {
        setup();
    });
}
```

Basically, if adal has magically found authentication information in `sessionStorage`, then we're good, otherwise, wait for the user to be authenticated.

This works well for most cases, but never renewals. From what I can tell, `adal:loginSuccess` doesn't occur after a renewal is successfully completed, so neither of these trigger.

I've resolved this with a total stop-gap of setting up a `$watch` on `userInfo.isAuthenticated`, but there must be a better way!

Does ADAL trigger an event for renewals, and if not, would that be a logical addition? I don't imagine it should be the same as initial login, but `adal:tokenRenewed` (or something to that effect) would be helpful.

**Comment by tushargupta51** [comment]
@MaJaHa95 Currently, adal does not broadcast events for token renewal operations. I want to understand your scenario a little better. I understand that you want to execute some actions when a user is authenticated, but why do you need to do the same when a token is renewed as that is not a new authentication, its renewing token for a user who was authenticated earlier.

**Comment by MaJaHa95** [comment]
I store some state in memory (it's Angular, if that wasn't assumed).

Basically,

1. User visits website
2. Adal checks for tokens, none found.
3. Initial setup continues, and `userInfo.isAuthenticated` is `false`, so we hold off.
4. Adal logs in, and calls `adal:loginSuccess`, thus queuing `getNotifications()`
 1. We store those results in `$scope`.
5. ...
6. User closes laptop and goes home (or whatever)
7. User comes back, website is revitalized, memory cleared.
8. Adal finds an expired token
9. Initial setup continues, `userInfo.isAuthenticated` is `false`, so we hold off again.
10. Adal runs through its iframe flow to renew a token
11. *Without a notification, I don't know that it's now time to call `getNotifications()` again.*

I could be misunderstanding some aspect of the flow of login--don't hesitate to correct me.

I will admit, I'm not sure of a time when `adal:loginSuccess` is necessary, but another for token renewal wouldn't be. So perhaps I am misunderstanding stuff.


Thanks!
Matthew

**Comment by rohitpagariya** [comment]
@tushargupta51, I have another scenario where events for tokenrenewal would be help. 

I have an app that requested a few permissions from the user. After a while, I decided to request more delegated permissions to the existing app. In this scenario, an existing user is seeing the following error message:

AADSTS65001: The user or administrator has not consented to use the application with ID '7aa700fa-3eb9-4ba5-bdcc-6ac35e9db291'. Send an interactive authorization request for this user and resource. Trace ID: 7229454e-a417-4d78-beda-0ca38643c2a7 Correlation ID: d28cab0e-2d86-463f-9161-ab2d3d7e77b6 Timestamp: 2016-09-14 17:44:36Z

I would have assumed adal.js would automatically show a consent page to the user but it doesn't. Instead it fails silently, which might be a bug as well. Not sure.

If there were token renewal success/failure events, it would be easy for me to redirect the user to the login page.

**Comment by tushargupta51** [comment]
Added `acquireTokenSuccess` and `acquireTokenFailure` events.
