### ISSUE TITLE
Login is not working when localLoginUrl is specified

### ISSUE THREAD

**Issue by mohanskumar** [AzureAD/azure-activedirectory-library-for-js#373]
adalAuthenticationService.login() function is not working when localLoginUrl is specified.  This is happening in 1.0.11 version.

**Comment by tushargupta51** [comment]
@mohanskumar What is the error or behavior when you call login() method without specifying localLoginUrl? What does your adal configuration code look like?

**Comment by mohanskumar** [comment]
No errors thought. ( nothing happens when the login method is called(); ), wondering the else part is not working in the adal-angular. 
 var loginHandler = function () {
                    _adal.info('Login event for:' + $location.$$url);
                    if (_adal.config && _adal.config.localLoginUrl) {
                        $location.path(_adal.config.localLoginUrl);
                    }
                    else {
                        // directly start login flow
                        _adal.info('Start login at:' + window.location.href);
                        $rootScope.$broadcast('adal:loginRedirect');
                        _adal.login();
                    }
                };

I am currently running v1.0.8 and trying to upgrade to the latest. 1.0.8 works fine so far.

**Comment by tushargupta51** [comment]
@mohanskumar In the config above, you do have a localLoginUrl. Did you comment it out and it didn't work? Can you try debugging to see if its even going to adal.login() method. Because, if its going to the adal.login method, it should redirect to AAD login page.

**Comment by mohanskumar** [comment]
Yes, It works when localLogin URL commented.

**Comment by tushargupta51** [comment]
@mohanskumar I am confused whether it works with localLoginUrl or without localLoginUrl.
Earlier you said this:
> adalAuthenticationService.login() function is not working when localLoginUrl is not specified. This is happening in 1.0.11 version.

In your comment above, you said this:
> Yes, It works when localLogin URL commented.

**Comment by mohanskumar** [comment]
Oops sorry that was a typo. It doesn't work when login url is specified.

**Comment by tushargupta51** [comment]
@mohanskumar What does your routing configuration looks like? Does the "/login" route has "requireADLogin" set to true?

The if block in the code:

    if (_adal.config && _adal.config.localLoginUrl) {
       $location.path(_adal.config.localLoginUrl);
    }

This will redirect the user to "/login" route. Do you see that happening? Please check the network trace in Chrome Developer tools to confirm that.

**Comment by mohanskumar** [comment]
Login route is not set with RequireADLogin to true. As i mentioned with my
issue log, My project works perfectly fine with 1.0.8. and I don't have any
other config/ route settings changed.

It is just keep getting redirected to login. the execution gets into if
block as the localLoginUrl is specified.  If you could share any example
project with localLogin enabled, that would be great.

**Comment by tushargupta51** [comment]
@mohanskumar The "/login" route should have the requireADLogin set to true for adal to redirect the user to AAD. This is what I am assuming:

You redirect the user to /login route if he/she is not authenticated. When a user is redirected to /login, you expect adal to redirect the user to AAD login page. For this to happen, requireADLogin attribute must be set to true for "/login" route. Let me know if this is not the user experience you want.

**Comment by mohanskumar** [comment]
Our login page has a button which calls "adalAuthenticationService.login()
method which in turn calls azure login. And it does not have the
requireAuthentication flag set. This is how it has been working with
version 1.0.8. I dont get why requireAuth should be set for the login.  (
the login view itself is not rendering when the flag is set).

**Comment by tushargupta51** [comment]
@mohanskumar Ok, I probably see the issue here. We made a change in 1.0.10/11 that `adalAuthenticationService.login()` now calls into `loginHandler()` instead of `_adal.login()`. The reason we made that change earlier was because there were some values that we used to save in loginHandler (login start page url, for example). Calling _adal.login directly skipped saving those values. Thats why we updated the `adalAuthenticationService.login()`  to go through loginHandler() instead of directly calling to _adal.login(). But, another change followed this where we removed saving the start page from loginHandler method and now it does not matter if _adal.login() is called directly or not.

I will fix this in adal-angular.js to call into _adal.login directly now since there is no added value to go through loginHandler(). This fix will appear in 1.0.12 which we plan to release soon (by end of this week).

Though one question, what do you gain by specifying localLoginUrl property? If you don't have it, loginHandler will call _adal.login and redirect the user to login automatically whenever they try to access a page that requires authentication. You can still have the login route the way it is with a button that calls `adalAuthenticationService.login()`. Clicking that button will work as adal will redirect the user to azureAd instead of localLoginUrl.

**Comment by mohanskumar** [comment]
Thanks for the update. We have a custom page for login which has the business logo and terms and conditions and copy right details. That's our standard. We can not skip that.

**Comment by rohitnarula7176** [comment]
@mohanskumar There are couple of ways you can navigate to your custom login page as explained below:
1. Do you have a login button on the main page which when clicked takes you to your custom login page?
2. Do you have a route on the main page which has requireADLogin set to true, which when activated takes you to your custom login page?
3. Or you just navigate to your login page by changing the route to ('/login') ?
If you can briefly explain which of the above methods you are using by sharing your app.js file, that will be great.

**Comment by mohanskumar** [comment]
Here is my settings Rohit.

Login is a dummy page with a custom icon and a login button. the button event calls adalAuthenticationService.login(); which redirects to azure AD login page. Login route doesn't have requireAuthentication flag set to true as we don't want to have the user login to adal before showing login page.  when the user logs out ( logout button is in the main page which is after login ) user should be redirected to the custom login page.

ISSUE: Login is not happening when localLoginURL is set in the config. Appreciate your guidance in this regard.

Here is the code sample that I am trying
https://github.com/mohanskumar/adaltest

**Comment by mohanskumar** [comment]
@rohitnarula7176, we would be able to set a live demo if needed.

**Comment by rohitnarula7176** [comment]
@mohanskumar Can you please confirm with the dev branch and see if that fixes your issue.

**Comment by tushargupta51** [comment]
Fixed in 1.0.13. Let us know if you still running into this issue.
