### ISSUE TITLE
NPM adal-angular 1.0.12 throws parse error in PhantomJS

### ISSUE THREAD

**Issue by abettadapur** [AzureAD/azure-activedirectory-library-for-js#377]
PhantomJS 1.9.8 (Windows 8 0.0.0) ERROR
  SyntaxError: Parse error
  at C:/agent/_work/11/s/app/adal/adal.js:1095

**Comment by abettadapur** [comment]
PhantomJS 1.9.8 (Windows 8 0.0.0) ERROR
  SyntaxError: Parse error
  at C:/agent/_work/11/s/app/adal/adal.js:1095

**Comment by rohitnarula7176** [comment]
@abettadapur This error is thrown on Safari and older versions of phantomjs (1.9.8) because of a function declaration in a nested statement. We have made a change in the code to fix this error. Could you use the dev branch and confirm if the issue is resolved for you.
