### ISSUE TITLE
Authentication when clientId and Resource are not the same.

### ISSUE THREAD

**Issue by jcc1983jcc** [AzureAD/azure-activedirectory-library-for-js#378]
Hello,

I'm using your adal authentication in javascript to use the token to connect to a WCF service.
The Client and the resource/Audience are not the same azure application in my system.

I get the token, but when I try to authenticate it against my WCF Service I get this error:

User connection not authorized
The exception error was 'IDX10214:Audience validation failed.
Audiences: '-------[clientId]'. Did not match:
validationParameters.ValidateAudience: 'http://....[loginResource]/' or validationParameters.ValidAudiences: 'null'".

That is, althought I'm setting the resource/audience on the config, when I get the token, the token is obtained against the "clientId" audience and not against the "loginResource"

I'm obtaining the token this way:
authContext._getItem("adal.idtoken")

Because this:
authContext.acquireToken(authContext.config.loginResource, function (error, token) {alert(token)})
is returning null.

Is there any option to do authentication with a clientId differente than the resource like I have in the c# implementation?
the c# implementation is this:
token = _authenticationContext.AcquireToken(_serverResourceId, _clientId, _redirectUri, PromptBehavior.Auto);

Thanks,

JC

**Comment by tushargupta51** [comment]
@jcc1983jcc The token is acquired for your "clientID", using it for WCF service (which has a different client id) will not work. AdalJs also provides acquireToken method which takes the application id of the resource as the parameter. You can use that method to request a token for WCF service.

If you are using angular wrapper, you don't even need to call acquireToken, you can specify a mapping of your WCF service url <=> WCF service application id in the "endpoints" array property and adal-angular interceptor will get the token automatically. Take a look at this: https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi/blob/master/TodoSPA/App/Scripts/app.js#L21

**Comment by tushargupta51** [comment]
I am closing the issue for now. Let us know if you are still running into issue, will re-open it.

**Comment by AlexanderLea** [comment]
Hi,

A question along the same lines - sorry if I'm missing the point...

I have an API, running on localhost:22222 validating audience against "https://testAudience/guid" as part of the authentication.

My endpoints section looks like:

 endpoints: {
        'http://localhost:22222/': 'https://testAudience/guid' 
}

But my API authentication fails.  If I change my API to validate the audience against clientId, the authentication works ok.

If I watch the request via Fiddler, I can see that it doesn't add the "resource=https://testAudience/guid" parameter to the AzureAd authenticate url, which I imagine is the issue.

Am I on the right track with my thinking? How would I make the angular-adal library add the resource parameter?
