### ISSUE TITLE
Where is ADAL for Angular 2?

### ISSUE THREAD

**Issue by nigel-dewar** [AzureAD/azure-activedirectory-library-for-js#379]
Hi there,

Is there not an adal-angular for Angular 2?

**Comment by chauey** [comment]
There is talk about it here some #194

**Comment by tushargupta51** [comment]
@nigel-dewar Currently, we do not have any active plans to move adal JS to angular 2. Though, there are some community members who have made some contributions for this. Please take a look at that issue. 

I am closing this issue as #194 is the active issue for this.
