### ISSUE TITLE
[1.0.12] Safari strict mode error causing script failure

### ISSUE THREAD

**Issue by damienpontifex** [AzureAD/azure-activedirectory-library-for-js#380]
Using adal.js from v1.0.12 Safari reports an error on https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/1.0.12/lib/adal.js#L1095 with "SyntaxError: Strict mode does not allow function declarations in a lexically nested statement."

**Comment by rohitnarula7176** [comment]
@damienpontifex This error is thrown on Safari and older versions of phantomjs (1.9.8) because of a function declaration in a nested statement. We have made a change in the code to fix this error. Could you use the dev branch and confirm if the issue is resolved for you.

**Comment by damienpontifex** [comment]
Looks good. Thanks @rohitnarula7176
