### ISSUE TITLE
Is it possible to suspend MFA with the ADAL library?

### ISSUE THREAD

**Issue by adamauckland** [AzureAD/azure-activedirectory-library-for-js#381]
Hi, I have a single-tenancy client app with an MFA AD directory. 

The suspend MFA settings in Azure are set to allow 1 days suspending, yet I do not get the "Don't ask me again for 1 days" checkbox when signing in.

I've got another app set up the same way but using SAML and that gives me the checkbox.

Is there a setting I have to pass in to the ADAL library to trigger the checkbox for the user?

Many thanks.

**Comment by godd4rd** [comment]
I'd really like to know the answer to this too.

**Comment by rohitpagariya** [comment]
Me 3.

**Comment by tushargupta51** [comment]
@adamauckland @godd4rd @rohitpagariya Sorry for the delayed response. I was trying to create a local repro and test the scenario. I can repro the bug, I do not see the "Dont ask me again for x days" checkbox either. I am following up with Azure AD team to understand what's happening. I will update this thread as soon as I get some more information.

**Comment by brentschmaltz** [comment]
@tushargupta51 is this still an issue?

**Comment by tushargupta51** [comment]
@brentschmaltz It's not really an issue from adal end. AAD does not show this checkbox when it thinks that the request is using brokered flows. That does not seem to be applicable to adal js. I have sent a reminder email to AAD folks last week to understand this more. Will update this issue once I hear back from them.

**Comment by tushargupta51** [comment]
I heard back from AAD, they are going to make changes to their service for this to work. I will close this issue as this is something AAD is going to fix.
