### ISSUE TITLE
AAD B2C support?

### ISSUE THREAD

**Issue by steve-torchia** [AzureAD/azure-activedirectory-library-for-js#382]
Now that Azure Active Directory B2C is out of preview and generally available, is there a timeline for when Adal.js will be able to officially support it?  (I know there is an experimental branch here I can look at in the meantime)

**Comment by vibronet** [comment]
Hi Steve,
we don't have an ETA at the moment. The service is still working on fully supporting all the protocol grants and parameters required to fully support the SPA scenario. The official support for this will likely come in MSAL JS, the successor library to ADAL JS which will work with Azure AD, MSA, ADFS and AAD B2C alike. As soon as we will have an ETA, we will announce on the team blog.
