### ISSUE TITLE
Adal creating nested iFrames on app load

### ISSUE THREAD

**Issue by rohitpagariya** [AzureAD/azure-activedirectory-library-for-js#384]
My app was going in a loop when adal tried to renew the token, so I implemented [this solution](https://gist.github.com/tushargupta51/78ce0b6bce998f6851abd02d91eb3a95)  as mentioned in the FAQs.

While my app works now, I am seeing that adal is creating two nested iFrames in my app on first load. And if I hit refresh, the subsequent app doesn't attach any iFrames to the DOM. 

Any ideas why this is happening? This is affecting the perf of the app when two iFrames are attached to the DOM.

**Comment by tushargupta51** [comment]
@rohitpagariya Can you share the id of the nested iframes? Even better, if you can copy the html with nested iframes?

**Comment by rohitpagariya** [comment]
Both the iFrames have the same id: adalRenewFrameMyAppId

I emailed you the html screenshot.

**Comment by rohitpagariya** [comment]
I implemented the frameRedirect solution listed [here](https://gist.github.com/tushargupta51/5fa6d000357120adbc8fd1d5c68853c4) and I don't see nested iFrames in the DOM anymore. 

But now, I am seeing that it doesn't in a private Edge window. I get prompted to login and then the browser is stuck on the url below and it doesn't load anything. 

**https://mysite.trafficmanager.net/frameRedirect#**/id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlliUkFRUlljRV9tb3RXVkpLSHJ3TEJiZF85cyIsImtpZCI6IlliUkFRUlljRV9tb3RXVkpLSHJ3TEJiZF85cyJ9.eyJhdWQiOiI3YWE3MDBmYS0zZWI5LTRiYTUtYmRjYy02YWMzNWU5ZGIyOTEiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDcvIiwiaWF0IjoxNDczMzYwMTY2LCJuYmYiOjE0NzMzNjAxNjYsImV4cCI6MTQ3MzM2NDA2NiwiYW1yIjpbInB3ZCJdLCJmYW1pbHlfbmFtZSI6IlBhZ2FyaXlhIiwiZ2l2ZW5fbmFtZSI6IlJvaGl0IiwiaW5fY29ycCI6InRydWUiLCJpcGFkZHIiOiIxMzEuMTA3LjE3NC42NSIsIm5hbWUiOiJSb2hpdCBQYWdhcml5YSIsIm5vbmNlIjoiMWFiNzY4NGMtMjE4NS00NGE0LThkZmItM2IyYWZjNTE2ZGYwIiwib2lkIjoiYTgxMzUzYmUtODI2Yy00Y2ExLWI3YTAtZWQwOWUwZTkwMmE1Iiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTIxMjc1MjExODQtMTYwNDAxMjkyMC0xODg3OTI3NTI3LTY4NTA1NzUiLCJzdWIiOiJPaW1Xb2NnOHo0dGVMbzNIa05VZkVfbGR6MndabVQ0dXg2VW5HQzdLbWZvIiwidGlkIjoiNzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3IiwidW5pcXVlX25hbWUiOiJyb2hpdHBhZ0BtaWNyb3NvZnQuY29tIiwidXBuIjoicm9oaXRwYWdAbWljcm9zb2Z0LmNvbSIsInZlciI6IjEuMCJ9.dh4BXT0T-rjZc5Jp8GE6Hzl1--vtN6YgumbPSiPGcknzsmHtyqJV3_MXXrzGYZFJ7wS9zNWTNsE3vyZ6iNoJNF6gkiDETOH9U3e6HTEuaCG0jWqXv-XszrdwZBszPwz0j3gVIrdjvuJIoQG3Peup8NB1DHXLq41Wim7QkQwNUBPYMCu7imIUduJ4Wis-SEWMt2_wGGEVfWlSP2jb8gpyHp9Or6tXdZbSXCxa2aZxuCKSRzoFZSd8W-ig0kZhYhluKY4bXHCeEIJ5vzw2A00Bsq75zbg9vvnwCcU0_lsi1_kK6KYKLCisEtx_WpXgqdA6_iTpzy71nrm9TBBxW-8kgw&state=d340b010-2e89-4148-9377-06e098bf052c&session_state=555cd489-7514-4e1a-84ee-e01b48481da4

This only happens in a private Edge window, it works fine on all other browsers including IE 11. Also, doesn't matter if the localStorage is enabled or not. Let me know if you need a live repro to debug.

**Comment by rohitpagariya** [comment]
Looks like this is the same issue [Tsunade90](https://github.com/Tsunade90) is mentioning at the end of this [gist](https://gist.github.com/tushargupta51/5fa6d000357120adbc8fd1d5c68853c4).

**Comment by tushargupta51** [comment]
@rohitpagariya A live repro will help debug this further. Can you please share that?

**Comment by rohitpagariya** [comment]
Sent you an email.

**Comment by rohitpagariya** [comment]
@rohitnarula7176, let me know if you need any help to debug this. I am anxious to get to the root cause here, since my app intermittently fails to work in Edge.

**Comment by rohitpagariya** [comment]
We switched to a different configuration and this doesn't reproduce anymore
