### ISSUE TITLE
Routes in angular do not work when using 1.0.12 script via CDN

### ISSUE THREAD

**Issue by nmallick1** [AzureAD/azure-activedirectory-library-for-js#387]
Routes in angular do not work when using 1.0.12 script via CDN. Reverting back to the script available in ToDo's demo makes the routing work.

**Comment by tushargupta51** [comment]
@nmallick1 What is the error you get? Can you give more details?

**Comment by nmallick1** [comment]
There is no error, that's the strange part. No error trying to add any module, nothing. With the ADALJS CDN version, the moment I add a call to init the provider Views stop working. If I remove the call to init they start working again. If I include the ADALJS scripts that are available in the ToDos demo, then everything works.

**Comment by rohitnarula7176** [comment]
@nmallick1 Can you please share your app.js (routing configuration) file to help debug the issue further.

**Comment by nmallick1** [comment]
'use strict';
angular.module('DependencyVisualizer', ['ngRoute','AdalAngular'])
.config(['$routeProvider', '$httpProvider', 'adalAuthenticationServiceProvider', function ($routeProvider,$httpProvider,adalProvider) {
    $routeProvider
    .when("/Home", {
        controller: "loginCtrl",
        templateUrl: "/Views/LoginView.html"
    }).otherwise({
        controller: "loginCtrl",
        templateUrl: "/Views/LoginView.html"
    });

    
    var endpoints = {
        "https://wawscus.kusto.windows.net/": "https://microsoft/kusto"
    };
    
    adalProvider.init(
        {
            instance: 'https://login.microsoftonline.com/',
            tenant: 'microsoft.onmicrosoft.com',
            clientId: 'dac94eea-af95-430b-a22a-006a5132f42b',
            extraQueryParameter: 'nux=1',
            endpoints: endpoints,
            cacheLocation: 'localStorage' // enable this for IE, as sessionStorage does not work for localhost.
        },
        $httpProvider
        );
}]);

var appCx = angular.module("AppDepVizCx", []);
var appCSS = angular.module("AppDepVizCSS", []);

**Comment by rohitnarula7176** [comment]
@nmallick1 If any of these routes in your app.js is protected and you expect adal-angular to redirect you to the authorization endpoint, then you need to explicitly set a property requireADLogin to true as shown below:
```
when("/Home", {
controller: "loginCtrl",
templateUrl: "/Views/LoginView.html"
**requireADLogin: true,**
});
```
If you are facing an issue other than the one mentioned above, it will be great if you could share a live repro and we would be happy to investigate further.

**Comment by tushargupta51** [comment]
Closing this for now. Please feel free to re-open if you are still encountering this issue.
