### ISSUE TITLE
Set response_type as config parameter

### ISSUE THREAD

**Issue by trenthogan** [AzureAD/azure-activedirectory-library-for-js#388]
Would you consider allowing the response_type to be set as a config parameter. It seems to be passed as a string when _getNavigateUrl is called. example here : https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal.js#L191

We would like the ability to use response_type="code" ... As showen here : https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-protocols-oauth-code/

Would be happy to submit a PR is this is something you would consider ?

**Comment by tushargupta51** [comment]
@trenthogan Adal Js only supports implicit flow and it does and should not support confidential flows. response_type = "code" is the confidential auth flow used by confidential client applications that are capable of keeping secrets or codes or refresh token in a secure place, and browser storage is not a secure storage.

**Comment by trenthogan** [comment]
Sure that makes sense thats for the quick reply.
