### ISSUE TITLE
logOut does not work on ADFS

### ISSUE THREAD

**Issue by NickAb** [AzureAD/azure-activedirectory-library-for-js#389]
When calling `logOut` against on-premise adfs browser is redirected to `https://<host>/adfs/oauth2/logout?post_logout_redirect_uri=<redirect_uri>` which is not supported by adfs (yet?).

The correct logout uri for adfs would be `https://<host>/adfs/ls/?wa=wsignout1.0`

What do you think about adding conditional logout uri depending on `tenant` being equal to `adfs` or not?

**Comment by MMM300** [comment]
@tushargupta51 This is still an issue in 1.0.13

Sent to /adfs/oauth2/logout?post_logout_redirect_uri and not to adfs/ls/?wa=wsignout1.0
when calling adalAuthenticationService.logOut();

Got 1.0.13 via bower.

**Comment by tushargupta51** [comment]
@MMM300 You have to set the `logOutUri` property on config to the logout uri for ADFS. The library only supports AAD logout be default.

**Comment by Squiggle** [comment]
Is this `logOutUri` property documented anywhere?

**Comment by c-yan** [comment]
> Is this logOutUri property documented anywhere?

It seems that it can not be configured in AD FS Management (GUI).
LogoutUri are appeared in (Get-AdfsApplicationGroup -Name 'XXXX').Applications.
