### ISSUE TITLE
window.Logging

### ISSUE THREAD

**Issue by ericnkatz** [AzureAD/azure-activedirectory-library-for-js#392]
https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal.js#L166
https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal.js#L1253

Not sure if this is something that should be fixed at the project level or my test runner. But using mocha even with jsdom this project breaks my testrunner. I have to manually connect `Logging = window.Logging`

**Comment by ericnkatz** [comment]
I see in the experimental branch you have this -> https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/experimental/lib/adal.js#L22

**Comment by ericnkatz** [comment]
@weijjia thought I'd tag you here since I don't have much context and you applied the changes to experimental.

**Comment by ericnkatz** [comment]
@rohitnarula7176 also tagging you since this recent update caused this issue to start occurring:  https://github.com/AzureAD/azure-activedirectory-library-for-js/commit/8ac0b4f5b22a496c16d6a1ba1a500bef2cc96b35

**Comment by tushargupta51** [comment]
@ericnkatz Are you getting a null exception at line#1253? Making sure I understand the issue correctly. To give you some background on the change, we moved to IIFE in a recent change since non-IIFE pattern was causing issues with bundling and all. In order to avoid breaking people(ironical?) who are relying on Logging to be available globally, we set the Logging object on window. This is what we did in our jasmine tests for this to work: https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/tests/unit/spec/AdalSpec.js#L29

**Comment by ericnkatz** [comment]
Thanks for responding @tushargupta51, my issue isn't tied to the IIFE but rather how adal is relying on window object to assign Logging and then referencing Logging explicitly. 

`ReferenceError: Logging is not defined` is what triggers my test error.

**Comment by ericnkatz** [comment]
Does that make sense?

**Comment by tushargupta51** [comment]
@ericnkatz Yes, your point makes sense. I am just wondering if `window.Logging` is defined then `if (level <= Logging.level) {` line should not throw an error as it will refer to the global object if there is no local declaration.

**Comment by ericnkatz** [comment]
@tushargupta51 Problem I'm getting is node even with https://github.com/tmpvar/jsdom running does not know that `(level <= Logging.level) {` is inferring based off the window global. This isn't an issue in the browser but the way the code is written now it seems to break right there and stop running my tests. Not sure if I'm writing my tests incorrectly or including adal as a dependency for one of the functions i'm including as causing the side affect - but it seems like this should probably not be written to assume global hoisting based off window.property declaration.

**Comment by tushargupta51** [comment]
@ericnkatz We declared the logging object globally so that it is independent of AuthenticationContext and users can set it from anywhere. Have you tried setting the `Logging` object globally in your tests?

**Comment by tushargupta51** [comment]
When writing tests in a non-browser environment, users need to set the window.Logging object. When running inside a browser, declaring Logging object at the global level should work.
Closing this issue, let us know if the above suggestion does not work.
