### ISSUE TITLE
Non-Angular Examples?

### ISSUE THREAD

**Issue by simkessy** [AzureAD/azure-activedirectory-library-for-js#393]
I'm having trouble figuring out how to use ADAL without Angular. It seems like all the examples are either with Angular or .NET. 

I'm trying to create a dropdown list of all users in my tenant. So I want to use 

`GET https://graph.windows.net/myorganization/users` 

I'm not sure how to proceed and the docs aren't really providing simple examples if you're new to this.

**Comment by tushargupta51** [comment]
@simkessy We have a sample without angular here: https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi.  Though it uses .net backend.

There is a sample here which uses angular but with nodeJS backend: https://github.com/matvelloso/angular-cors-adal-o365-node

**Comment by simkessy** [comment]
Thanks, I'll take a look but overall where's the documentation for this library? What are the APIs? Why is everything I'm seeing relating to Angular is it's suppose to be framework independent?

**Comment by airomero** [comment]
Hi, i don't use angular. I have an aspnet core  web api that is protected with azure ad. I do standard js  requests with jquery. I need to send the request as I do now  but sending the token. How can I do that?

**Comment by tushargupta51** [comment]
@simkessy  We do not have api guides for adal.js. But we do have samples for both angular and non-angular usages.

@airomero https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi. should give you better idea.
