### ISSUE TITLE
This application requires application permissions to another application. 

### ISSUE THREAD

**Issue by simkessy** [AzureAD/azure-activedirectory-library-for-js#396]
I am trying to create a dropdown with all the users in my Office365 tenant. I created an app in Azure AD and gave it all the necessary permissions. I gave it all the permissions for Microsoft Graph actually, app and delegated. All of them.
 
Then I wrote up my script to query all users with `https://graph.microsoft.com/v1.0/users`.
 
I had my tenant admin go in and accept the permissions then output the list of users in the UI. Works fine for them.
 
I'm not an admin but when I go to the page I get the following error:

>  
This application requires application permissions to another application. Consent for application permissions can only be performed by an administrator. Sign out and sign in as an administrator or contact one of your organization's administrators.

 
I need to know if this will work for users with even lower permissions. From what I understand the API request and the App is running under the permissions given to the application in Azure. So even if the user as Read Only, the request isn't running under the user, it's running under the Application I set up. So why would I get the error regarding permissions?

JS: 

```
(function () {
  "use strict";
  // Some samples will use the tenant name here like "tenant.onmicrosoft.com"
  // I prefer to user the subscription Id
  var subscriptionId = "metenant.onmicrosoft.com";
  // Copy the client ID of your AAD app here once you have registered one, configured the required permissions, and
  // allowed implicit flow https://msdn.microsoft.com/en-us/office/office365/howto/get-started-with-office-365-unified-api
  var clientId = "cccb1f2f-xxx-x-xxxxx-x-x-x-x-x-";

  window.config = {
    // subscriptionId: subscriptionId,
    clientId: clientId,
    postLogoutRedirectUri: window.location.origin,
    endpoints: {
      graphApiUri: 'https://graph.microsoft.com'
    },
    cacheLocation: 'localStorage' // enable this for IE, as sessionStorage does not work for localhost.
  };

  var authContext = new AuthenticationContext(config);

  // Check For & Handle Redirect From AAD After Login
  var isCallback = authContext.isCallback(window.location.hash);
  authContext.handleWindowCallback();

  if (isCallback && !authContext.getLoginError()) {
    window.location = authContext._getItem(authContext.CONSTANTS.STORAGE.LOGIN_REQUEST);
  }

  // If not logged in force login
  var user = authContext.getCachedUser();
  // NOTE: you may want to render the page for anonymous users and render
  // a login button which runs the login function upon click.
  if (!user) authContext.login();

  // Acquire token for Files resource.
  authContext.acquireToken(config.endpoints.graphApiUri, function (error, token) {
    // Handle ADAL Errors.
    if (error || !token) {
      console.log('ADAL error occurred: ' + error);
      return;
    }
    // Execute GET request to Files API.
    var filesUri = config.endpoints.graphApiUri + "/v1.0/users";
    $.ajax({
      type: "GET",
      url: filesUri,
      headers: {
        'Authorization': 'Bearer ' + token,
      }
    }).done(function (response) {
      console.log('Successfully fetched from Graph.');
      console.log(response);

      var container = $(".container")

      container.empty();

      $.each(response.value, function(index, item) {
        container.append($('<li>').text(item.displayName + " " + item.mail + " " + item.mobilePhone))
      })
    }).fail(function (response) {
      var err = JSON.parse(response.responseText)
      console.log('Failed:', err.error.message);
    });
  });
})();
```

**Comment by tushargupta51** [comment]
@simkessy The token sent along with the request to graph api represents the user and the permissions this specific user has.

> From what I understand the API request and the App is running under the permissions given to the application in Azure. So even if the user as Read Only, the request isn't running under the user, it's running under the Application I set up. So why would I get the error regarding permissions?

The permissions you set up at Azure Portal for your app allows you to configure you app upfront by specifying the resources it will need access to in advance. But your app is running under a user context, the current logged in user. And the api request is scoped to the permissions the associated token has.

**Comment by simkessy** [comment]
Is there any way to scope the api request to the permissions that the App has and not the permissions of the user? Isn't this why we have App Permissions and Delegate Permissions?

**Comment by tushargupta51** [comment]
@simkessy I think you require a different auth flow here: on behlaf of flow where you acquire token using client credentials instead of user creds (in this case user authentication cookie). The token you get back using client credentials has app level permissions. Adal.js is only designed for implicit flow and not for confidential flows/on behalf of flows. As the other flows require client secrets and passwords and adal.js, running in a browser, cannot keep those secrets secure.

**Comment by simkessy** [comment]
I see so client-side I'm stuck with ADAL and need to give the app permissions that do not require Admin privileges. That's fine, now that I know that, I've gone into the app and removed any permissions that required Admin and it seems to work. 

I have another question hopefully a quick one. My admin logged into the page where I call the API using the ADAL token etc. They had to accept permissions the app required. 

My non-admin user logged in, and they were also asked to accept those permissions. Is there anyway the app can be approved by the admin once and the users don't need to be asked to accept permissions the first time they load the page?

**Comment by tushargupta51** [comment]
@simkessy I don't think you can, that sounds insecure. If app is accessing user's information, then users should consent on their own.
