### ISSUE TITLE
Issues when not using popup

### ISSUE THREAD

**Issue by bondseid** [AzureAD/azure-activedirectory-library-for-js#401]
When integrating the base adal setup and calling adalAuthenticationService.login(), once returned to my replybackurl, no $rootscope emissions are captured and the adalservice is not authenticated. When using the basic configuration the authentication takes plac ein the same browser window. 

Also, using the standard route authentication has no effect: My route is resolved even if the adalservice is not authenticated.

```
angular.module('app').config ($routeProvider) ->
    $routeProvider
    .when('/app', {
        templateUrl: 'app.html',
        requireADLogin: true
    })

```

My configuration:

```
##
## Configuring ADAL
##
app.config ($httpProvider, adalAuthenticationServiceProvider) ->

    endpoints = {}

    adalAuthenticationServiceProvider.init({
        clientId: "clientid",
        redirectUri: "http://localhost:9999/adal-login",
        endpoints: endpoints,
    }, $httpProvider)

```

```
angular.module('app').controller 'LoginCtrl', ($rootScope, $scope, $location, adalAuthenticationService) ->

    $scope.loginWithAdal = () ->
        console.log 'loggin in'
        adalAuthenticationService.login()

    $scope.logoutWithAdal = () ->
        console.log 'loggin in'
        adalAuthenticationService.logOut()

    $rootScope.$on "adal:loginSuccess", () ->
        console.log 'success'
        AceLogin.loginWithAdal()


    $rootScope.$on "adal:loginFailure", () ->
        console.log 'fail'

    $rootScope.$on "adal:notAuthorized", () ->
        console.log 'not authed'
```

The solution i have found is by appending a popUp object property to the config. This triggers the azure authentication to take place in a popup:

```
 adalAuthenticationServiceProvider.init({
        clientId: "848ffbb4-b40d-490e-af67-a14cf29259bb",
        redirectUri: "http://localhost:9999/adal-login",
        endpoints: endpoints,
       popUp: true
    })

```

In this case however the route authentication still does not work.

This was all tested in a localhost environment. Browser: chrome, firefox on a mac.

**Comment by tushargupta51** [comment]
@bondseid It seems you are running into couple of issues. Can you help me understand this better?

> no $rootscope emissions are captured and the adalservice is not authenticated. 

Do you mean, "adal:loginSuccess" event is not being triggered? After user completes login, do you see tokens saved in browser storage? If not, can you send a network/fiddler trace that captures request sent to AAD and the response?

>using the standard route authentication has no effect: My route is resolved even if the adalservice is not authenticated.

Can you provide adal logs? Please see readme for logging instructions. Also, you can try setting up `requireADLogin` at global level to test if the attribute is taking any effect or not.

It seems you solved the first issue by use of `popUp:true` but still are running into second issue. Logs will help debug this further.

**Comment by bondseid** [comment]
> Do you mean, "adal:loginSuccess" event is not being triggered? After user completes login, do you see tokens saved in browser storage? If not, can you send a network/fiddler trace that captures request sent to AAD and the response?

Yes! In the case when i do not have "popUp: true" set on the config and the browser redirects back to the redirecturi, no rootscope events are being triggered at all.

One thing to note is that i am not injecting the $httpprovider during config. The reason for this is we have an existing authentication system and i need control over what tokens are being sent (ours or adals).  

> It seems you solved the first issue by use of popUp:true but still are running into second issue. Logs will help debug this further.

Yes however there is a bug with the popover. I am not sure if this comes from the library but whenever i trigger  adalAuthenticationService.login() the popup displays and the suddenly moves behind the current page. I need to minimize my current browser in order to get to the popup (using latest chrome on a mac).

Working on logs.

**Comment by bondseid** [comment]
Hey, have you had a chance to verify this bug?

**Comment by tushargupta51** [comment]
@bondseid Sorry for the delay.

Regarding the events not being triggered, when the redirect from AAD happens (popUp: false), does that redirect loads LoginCtrl? If not, then those listeners will not be executed.

With the popup, does the authentication work fine? Is the popUp going in the background only issue?

**Comment by tushargupta51** [comment]
Closing this for now. Please feel free to re-open this when you have more info.
