### ISSUE TITLE
adal.js authenticates to ADFS - but still cannot call SharePoint Online with token recieved

### ISSUE THREAD

**Issue by nigel-dewar** [AzureAD/azure-activedirectory-library-for-js#402]
Hi There,

I have followed your new article posted here https://technet.microsoft.com/en-us/windows-server-docs/identity/ad-fs/development/single-page-application-with-ad-fs and it works well. I setup a Windows 2016 server, and hooked up Azure Connect using the express settings.

 I setup ADFS manually as per instructions shown here http://www.cloudidentity.com/blog/2015/08/21/openid-connect-web-sign-on-with-adfs-in-windows-server-2016-tp3/

I followed your instructions and found adal.js performed nicely, obtaining a token from my adfs server. All looked well.

I setup an application on my azure AD so my SPA could call into my sharepoint online tenant and get some data from some lists. I was careful to ensure implicitflow was set to true on the manifest for this app. I also ensured that the endpoints were correctly added to the adal.js config. 

When I try to call into SharePoint I get nowhere. I get all these weird error messages I have not seen before.

I confirmed my code was correct for the http calls to Sharepoint online from my spa by swapping out the tenant and clientID for my application in azure AD and not to use ADFS. Everything then works fine.

I thought that federations with ADFS and AZURE AD meant that I could use a token obtained from my ADFS and then use this token to call into my Office 365 resources. Am I wrong in my understanding here?

Can one not use a token obtained from ADFS to then call into office 365 resources, or is just the case that I am doing something wrong and I dont know it yet.

I thought ADFS was trusted by Azure AD, so that any OAuth2 oidc token I recieved from my federated ADFS server should now be able to call my O365 resources.

Can anyone please elaborate on this.

Cheers

**Comment by vibronet** [comment]
This is not accurate:

> I thought ADFS was trusted by Azure AD, so that any OAuth2 oidc token I recieved from my federated ADFS server should now be able to call my O365 resources.

"Trust" means that you can exchange an ADFS token for an Azure AD one. It does not mean that resources will accept tokens from a different provider. 
Resources only accept Azure AD tokens: it is the responsibility of the caller to obtain the right token before hand. The federation allows you to use your ADFS to authenticate the user credentials, but ultimately the issued token must come from Azure AD for an Azure AD-protected resource to accept it. That is one of the architectural advantages of federation: by allowing tokens to be translated between identity providers, you can focus all your management and change handling in one node of the architecture instead of having to go after every resource and add costly multi-provider validation logic.
In ADAL JS we only support one authority at a time: that means that for your scenario you should not point ADAL JS to ADFS, but to the Azure AD tenant that is federated with ADFS.

**Comment by nigel-dewar** [comment]
Thanks Vittorio, but your answer confuses me.

In the case of Office 365, when when installs azure connect, and hooks up to ADFS, one can use thier local AD creds to sign in, and now they can access Office 365 online resources.

So how is it that the token once recieves from ADFS can be used with Office 365? based on what you have said. Is there some sort of token exchange happening behind the scenes to enable this?

**Comment by vibronet** [comment]
That's the standard flow occurring in **every** federation. To expand on it: the authentication flow requests a token from Azure AD; Azure AD sees that the user is a federated user, and redirects to the corresponding ADFS; the user authenticates with ADFS and obtains an ADFS token; the token is sent to Azure AD, which verifies that it is a valid token coming from the intended ADFS instance; upon successful validation, Azure AD issues an Azure AD token.
When accessing Office365, clients ALWAYS ask tokens to Azure AD, and ALWAYS receive tokens from Azure AD; the fact that in the process of acquiring the token the user visited an ADFS instance is fully transparent.
Does this help to clarify?

**Comment by nigel-dewar** [comment]
Yes thank you very much. Your answer right here "no joke" has finally answered a question that has plagued me for months.

Thanks Vittorio. You have a talent for putting complex things in laymens terms. I really appreciate that.

So i guess if one does want seamless single sign on using adfs, and also wants to query azure ad protected resouces using Javascript, then one would need to write a manual hookup right?

My assumption would be, use asp.net mvc app to authenticate against adfs and get a token. Then my javascript in my asp.net MVC grabs that token and makes a call to azure AD and exchanges that adfs token for an azure AD token. Then i can call Azure AD protected resources through JS. For the user the whole experience is seamless.

Is my assumption above correct? Does this sound like something that will work?




Sent from Samsung Mobile


-------- Original message --------
From: Vittorio Bertocci
Date:04/10/2016 08:11 (GMT+10:00)
To: AzureAD/azure-activedirectory-library-for-js
Cc: nigel-dewar , Author
Subject: Re: [AzureAD/azure-activedirectory-library-for-js] adal.js authenticates to ADFS - but still cannot call SharePoint Online with token recieved (#402)


That's the standard flow occurring in every federation. To expand on it: the authentication flow requests a token from Azure AD; Azure AD sees that the user is a federated user, and redirects to the corresponding ADFS; the user authenticates with ADFS and obtains an ADFS token; the token is sent to Azure AD, which verifies that it is a valid token coming from the intended ADFS instance; upon successful validation, Azure AD issues an Azure AD token.
When accessing Office365, clients ALWAYS ask tokens to Azure AD, and ALWAYS receive tokens from Azure AD; the fact that in the process of acquiring the token the user visited an ADFS instance is fully transparent.
Does this help to clarify?

-

**Comment by vibronet** [comment]
Hi Nigel,
thank you for your kind words.
You should not need to perform any manual step. You just need to set up the ADFS-Azure AD federation: from that moment onward, every authentication for users from the domain configured for the federation will follow the sequence I described, automatically. Your code will never see the intermediate ADFS tokens, only the final Azure AD tokens. HTH

**Comment by nigel-dewar** [comment]
Thanks Vittorio, Ahh I finally see!
I realized what you meant after I had a good think about it. "Azure AD sees that the user is a federated user, and redirects to the corresponding ADFS; the user authenticates with ADFS and obtains an ADFS token; the token is sent to Azure AD, which verifies that it is a valid token coming from the intended ADFS instance; upon successful validation, Azure AD issues an Azure AD token."

This really makes sense now. I feel like such a dummy after splitting hairs on this for months.

Thank you very much again Vittorio. Please keep up all the great work, yourself and your team. I see heaps of awesome doco and tools coming out of the azure ad team now, which is excellent because its a tough subject. I hard core follow your blog and work you do.

Cheers from Sunny Brisbane. Kind Regards, Nige.
