### ISSUE TITLE
Enhance to Support Additional Identity Providers

### ISSUE THREAD

**Issue by davewoodward** [AzureAD/azure-activedirectory-library-for-js#409]
I would like to see this library enhanced to support additional identity providers.  With some fairly minor adjustments this should be possible.

Specifically, I would like to see the following:

- Provide for more flexibility in the instance URL by allowing for a blank tenant and an alternate (or blank) context root (instead of the hard-coded oauth2 value).
- Allow optional scope and response type configuration parameters.
- Allow for identity providers that pass back the id_token as a query string parameter instead of a URL fragment.  This is fairly common with id_tokens; as opposed to responses that include access_tokens.

**Comment by tushargupta51** [comment]
@davewoodward Thanks for your PR! However, this library is designed to be used only with Azure Active Directory and is supposed to support only implicit flows where tokens are returned as fragments.
The response type is, by design, not customizable as we want to keep the sign in flow (response_type: id_token) and token acquisition (response_type: token) separate.
Id_token returned as query string parameters have security implications: http://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#Security.

@vibronet

**Comment by davewoodward** [comment]
Sorry, I must have missed that in the specification.  Thanks for the link.  I was aware that it was a "no no" to include the access token in the response as anything but a fragment but hadn't seen the same for the id_token.  I will have to circle back with our vendor to discuss why they have chosen to deviate from the specification in this area.  They are usually a stickler for the specification from what I've seen so I am kind of surprised.  In any case, I think this library will still work for us without the query parameter change as long as you are willing to support a configurable response type.  This would allow us to request an "id_token token" response type, which would result in the identity provider we are using passing the entire response back as a fragment.  Obviously it would allow additional response type options as well, which could prove useful in the future.  From what I've seen, ADFS 4.0 is going to support a larger cross-section of the specification so I thought might prove useful in that scenario.  To be honest, we are only using our existing identity provider as an "implicit flow" bridge to our current ADFS/SAML implementation until we are able to upgrade to Windows 2016 and ADFS 4.0.

**Comment by tushargupta51** [comment]
@davewoodward 
>This would allow us to request an "id_token token" response type, which would result in the identity provider we are using passing the entire response back as a fragment.

I am wondering why you cannot use "id_token" response type followed by call to `acquireToken` method? Are you using angular wrapper? If yes, then you don't even have to call acquireToken yourself, library will do that for you.

**Comment by davewoodward** [comment]
Great question.  That is where the rub comes in with the query parameter verses the fragment.  When I simply use "id_token" as the response type, the WSO2 identity manager platform returns the id_token as a query string parameter.  However, if the access_token is requested along with the id_token, the platform returns everything as a fragment.  I have opened a support ticket with WSO2 to see if I can find out why they chose to do it this way.  However, since multi-valued response type parameters are supported by the specification, I thought it made sense to support the option.  In addition to helping our company overcome our immediate issue, it would allow others to get both their id_token and access_token at once.

What are your thoughts on the changes to provide more flexibility in the URL or the changes to support a multi-valued "scope" configuration setting?  The latter seems like a no-brainer since it would allow the caller to request specific claim values (e.g. profile, email, address, phone).  Unfortunately, because of the way Azure Active Directory embeds the tenant in the middle of the URL, the URL change had to be done by adding an optional root context parameter.

I realize that all of these things represent broadening the scope of this library beyond its original intent so feel free to let me know if this isn't something that you want to entertain with this project.  If that's the case then I'll probably just take a cut, which might be best anyway since it would allow me to eliminate things like tenant and just go with a simple URL.

**Comment by tushargupta51** [comment]
@davewoodward As you said, the changes (both supporting external providers and making responseType configurable), broadens the scope of this library beyond its original intent, so unfortunately, we won't be able to add this support now. We will keep it in mind for next generation of this library. We do have some extensibility points for login, e.g., we have `displayCall` method which you can implement to take control over login process, but in that case, you might also need to handle responses that adal currently does not understand.
