### ISSUE TITLE
broadcast userInfo (_oauthInfo) instead of setting it on rootscope

### ISSUE THREAD

**Issue by ThorstenHans** [AzureAD/azure-activedirectory-library-for-js#41]
setting userInfo on the rootscope is a kind of misguiding. Services should not make changes to scopes without explicitly being asked for.

It would be a better option to `broadcast` once the `_oauthInfo` has changed, devs who are interested in accessing user information can register to the event and populate this to the required scope.

**Comment by RobARichardson** [comment]
+1

**Comment by tedvanderveen** [comment]
+1

**Comment by tushargupta51** [comment]
Setting things on `rootScope` is similar to setting things to `window` object. We added `userInfo` to rootScope to make it easier for developers to access the logged in user. I agree that it is not the best practice to modify things globally or on global scope. Closing this issue as unfortunately we cannot change this now, as this will be a breaking change. We will consider the feedback for our next generation of adal library (we are actively working on that right now).
