### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by tushargupta51** [AzureAD/azure-activedirectory-library-for-js#412]
Some of our public apis do not have proper/correct comments. Make sure all apis have comments in the right format that explain the parameters, return values and the purpose of property/method.

The second step will be to generate documentation using "jsdoc". We already have grunt task for that. We should be able to generate documentation using that and upload on github wiki.

**Comment by tushargupta51** [comment]
For reference: http://stackoverflow.com/questions/39261085/azure-ad-adaljs-how-to-use-this-library

**Comment by brentschmaltz** [comment]
@tushargupta51 if this PR was NOT committed, please get the PR in.

**Comment by tushargupta51** [comment]
Let's keep it open until we have this released in 1.0.14.
