### ISSUE TITLE
AADSTS50058 error when using "external" accounts in any browser. but not for internal accounts.

### ISSUE THREAD

**Issue by blagaisse** [AzureAD/azure-activedirectory-library-for-js#413]
Hello all,

One of our live apps using adal.js is suddenly broken without changing it, and gives the above error when users with an external account (e.g. bert@hotmail.be) are logged in. (it still worked a few weeks ago)

Our Azure AD tenant (ourtenant.onmicrosoft.com) has both internal and external accounts.
- some people have been added with their hotmail or outlook email address and authenticate themselves on the login page of that service. These account now suddenly generate the above error.
- people using internal accounts (bert@ourdomain.onmicrosoft.com, have no problems.

I found issues on this topic related to using IE or Edge, but this error also happens in Chrome for us.
What changed ? Did some web security policy get activated at the server side of Azure AD, did all browsers suddenly start enforcing stricter domain checking ? Is the old domainname "hotmail.be" the problem ? 

There is no problem in apps that use ADAL at the server-side (asp.net with OWIN)

Regards,

Bert Lagaisse

**Comment by blagaisse** [comment]
Note: problems started to appear beyond the scope of the the adal.js library, and the error is now also appearing when using pure server-side libraries (ADAL and OWIN) without any javascript involved.
So it's not a browser-related or javascript related problem.

**Comment by tushargupta51** [comment]
@blagaisse Since the problem started showing up without any changes to adal js, it seems to be an issue with service side, and not adal js related (as you mentioned). You should follow up with Azure Ad team on this.
