### ISSUE TITLE
requiredADLogin not triggering authentication using UI Router in ADAL JS 1.0.12

### ISSUE THREAD

**Issue by jpvelasco** [AzureAD/azure-activedirectory-library-for-js#415]
Hi there,

So I am not sure if this is just a miss-configuration on my end, but I figure I would ask just in case.
I created a sample AngularJS application that is secured with ADAL JS 1.0.12 and is using the AngularJS UI router for setting up routes. I have secured the routes by setting the 'requiredADLogin' attribute to true. However, when I click on a link (e.g. Contacts) that directs me to one of the authenticated routes, the login redirect to Azure AD is not getting triggered and I am able to see the 'authenticated' UI view without being logged in first... I would expect ADAL JS to intercept this route and redirect me to the login page instead.

Also, I enabled logging during my debug session on the routes at level 3 and I could see the following error:
"Error when acquiring token for resource: {client id}", where 'client id' is the id for my application in Azure AD

On an interesting note, when I click on the 'Login' button I setup on the app, I am able to login with Azure AD and the routes work as expected, what is more, I have an ASP.NET Core Web API configured on the same project that is secured by Azure AD and it uses JWT Bearer tokens. I tested that the authentication in the Web API is working, as I cannot communicate with the Web API unless I am first logged in and I can see the tokens being attached to the http calls to the Web API. Also, I validated that I can indeed see an authenticated principal when I am inside the Web API context, so that is good and working. 

Here is the configuration for my routes, from wwwroot/app/app.config.js:

angular
    .module('contactApp')
    .config(function ($stateProvider, $locationProvider, $urlRouterProvider, $httpProvider, adalAuthenticationServiceProvider) {
        $locationProvider.html5Mode(true).hashPrefix('!');
        $urlRouterProvider.otherwise("/");
        $stateProvider
              .state('home', {
                  url: '/',
                  templateUrl: 'app/contact/home.html',
                  controller: 'HomeController'
              })
            .state('contacts', {
                url: '/contacts',
                templateUrl: 'app/contact/contact-list.html',
                controller: 'ContactListController',
                requiredADLogin: true,
            })
            .state('viewContact', {
                url: '/contacts/:id/view',
                templateUrl: 'app/contact/contact-view.html',
                controller: 'ContactViewController',
                requiredADLogin: true,
            }).state('newContact', {
                url: '/contacts/new',
                templateUrl: 'app/contact/contact-create.html',
                controller: 'ContactCreateController',
                requiredADLogin: true,
            }).state('editContact', {
                url: '/contacts/:id/edit',
                templateUrl: 'app/contact/contact-edit.html',
                controller: 'ContactEditController',
                requiredADLogin: true,
            });
        adalAuthenticationServiceProvider.init(
            {
                instance: 'https://login.microsoftonline.com/',
                tenant: 'This is your Azure AD tenant, e.g. sampleapps.onmicrosoft.com',
                clientId: 'This is your client id from Azure AD, e.g. d1d425ce-28f4-4181-a351-982e2c3f41b2',
                extraQueryParameter: 'nux=1',
            },
            $httpProvider
            );
    }).run(function ($state) {
        $state.go('home');
    });

The application is configured in Azure AD using the implicit Oauth flow and I did make sure that the manifest file has this setting enabled.

The full source code for this sample I created can be found on my GitHub page: https://github.com/jpvelasco/angularjs-aspnet-web-api-core-azure-ad The sample code should be ready to run, anyone who wants to take a look at the issue just needs to replace the tenant and client id values in the client and server configuration files.

Please let me know if I indeed have a misconfiguration, I would like to understand exactly what I need to do to correct it.

I appreciate your feedback and thank you for your support,

JP Velasco

**Comment by tushargupta51** [comment]
@jpvelasco It's `requireADLogin`, not `requiredADLogin`. Let me know if that fixes your issue.

**Comment by jpvelasco** [comment]
@tushargupta51 I am laughing at myself for not catching such a silly mistake on my part... Thanks so much, that fix worked like a charm. 👍 I'm reminding myself that it is instances like these where I really should have used TypeScript. :) 
Thanks again for the excellent support, I appreciate your prompt response.
Cheers,
JP

**Comment by wy193777** [comment]
Got the same problem with 1.0.15, and I'm using `requireADLogin`. Here is my code:

```javascript
export default ($uiViewScrollProvider, $httpProvider, $logProvider,
    $locationProvider, $compileProvider, $stateProvider, 
    $urlRouterProvider, usSpinnerConfigProvider, 
    AppConstants, adalAuthenticationServiceProvider) => {
    'ngInject';

    $uiViewScrollProvider.useAnchorScroll();

    // $httpProvider.useApplyAsync(true);

    // disable debug info and .reloadWithDebugInfo() method
    $compileProvider.debugInfoEnabled(true);

    $logProvider.debugEnabled(true);

    // use the HTML5 History API
    $locationProvider.html5Mode(false);

    //default configuration for spinner
    usSpinnerConfigProvider.setDefaults(AppConstants.spinnersStyles.DEFAULT_SPINNER);

    // CSRF to intercept all requests and add special header
    // $httpProvider.interceptors.push(csrfInterceptor);

    $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|file|rdar):/);

    $stateProvider
        .state('app', {
            // abstract: true,
            // resolve: {},
            requireADLogin: true
        });

    $urlRouterProvider.otherwise('/', {requireADLogin: true});
    adalAuthenticationServiceProvider.init(
        {
            instance: 'https://login.microsoftonline.com/',
            tenant: "[tenant]", // Optional by default, it sends common
            clientId: "[client id]", // Required
            extraQueryParameter: 'nux=1',
            // popUp: true
        },
        $httpProvider
    );
};
```
And other routes loaded on other standalone files:

```javascript
export default ($stateProvider, $urlRouterProvider) => {
    'ngInject';
    $stateProvider
        .state('dashboard', {
            url: '/',
            parent: 'app',
            component: 'dashboard',
            title: 'Home',
            requireADLogin: true
        });
    $urlRouterProvider.otherwise('/');
};
```

**Comment by wy193777** [comment]
Opened a new issue #646
