### ISSUE TITLE
Add examples for plain JavaScript

### ISSUE THREAD

**Issue by con-ssc** [AzureAD/azure-activedirectory-library-for-js#417]
There is only an example for angular1 around and not for vanilla JavaScript. It would be nice if there would be one so it could be used without any special frameworks. And to grasp how it is actually used without other frameworks.

**Comment by rohitnarula7176** [comment]
Please refer to the sample below that demonstrates the use of ADAL for JavaScript for securing an single page app written independently of any frameworks, implemented with an ASP.NET Web API backend.
https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi

**Comment by con-ssc** [comment]
Well it depends on asp. Anyway, the sample is not working, I'm unable to log in.

**Comment by tarunchopra** [comment]
I've also published one: https://github.com/tarunchopra/Hacakthons/tree/master/O365-jQuery-CORS-master/O365-jQuery-CORS-master

**Comment by con-ssc** [comment]
That example looks very nice. Is it possible to skip the login window and use username/password within a config?

**Comment by tushargupta51** [comment]
@con-ssc No, adal js does not support confidential flows as it's loaded in browser and cannot keep secrets secure. Using password in a config file will leak it to everyone else.

I will close this issue as we have couple of samples to help with plain JS apps.

**Comment by con-ssc** [comment]
Ok so will there be a new adal version for ADFS4 and Windows Server 2016?

**Comment by tushargupta51** [comment]
@con-ssc I am not sure I understand the relation between supporting confidential flows and ADFS4. We have a walkthrough guide for using adal with ADFS: https://technet.microsoft.com/en-us/windows-server-docs/identity/ad-fs/development/single-page-application-with-ad-fs. Does that help you?
