### ISSUE TITLE
adal.js failing to parse Azure B2C AD token

### ISSUE THREAD

**Issue by 360oncology** [AzureAD/azure-activedirectory-library-for-js#418]
We have client code using "oid" for Azure B2C AD parsed by adal.js and it stopped working without any changes. We are suspecting that there might be an issue with token that we are getting from Azure AD. 
We noticed "fQ" instead of "}" in value for "kid" field in decoded AD token and probably because of that AuthenticationContext.prototype._decode() method in adal.js is returning junk for all values after kid in parsed object. Can somebody confirm if this can be a bug in adal.js or Azure AD team may need to fix generated token?

Below is Base64 decoded token, 
{"typ":"JWT","alg":"RS256","kid":"PftplvUMzdPZ8QgwW82Ss9Qbgxq5CgHbKYIH3dLkfsI"fQ.{"exp":1476485886,"nbf":1476482286,"ver":"1.0","iss":"https://login.microsoftonline.com/b84084c7-56bd-4593-8114-816f27b0c70f/","sub":"Not supported currently. Use oid claim.","aud":"93cc5b3f-a809-4efc-a12e-8432bbccd2ec","acr":"b2c_1_si","nonce":"622ccce0-0f36-4d7c-b41f-e62d42c53cc0","iat":1476482286,"auth_time":1476482286,"oid":"079e9ad2-cf5b-4c49-9da3-6891a86f7bb4"}

**Comment by tushargupta51** [comment]
@360oncology That seems like a discrepancy in the kid value. This is not an issue in adal js decoding, as the kid value in your example token is invalid json.
