### ISSUE TITLE
experimental branch renew token issue

### ISSUE THREAD

**Issue by pottabathini** [AzureAD/azure-activedirectory-library-for-js#420]
at line: 146 in adal-angular.js file written like
 _adal.acquireTokenSilent(_adal.config.clientId, null, function (error, tokenOut)

but if I look at adal.js acquireTokenSilent function it written to accept scope but not clientId.

Please check.

**Comment by pottabathini** [comment]
This branch exposed silentrenew function but it is not calling automatically. It is working fine when manually triggering the event.

Is it supports silent renew based on the expires_in or exp values? do we need to configure anything to this work.

**Comment by pottabathini** [comment]
We manually updated adal-angular.js _adal.acquireTokenSilent(_adal.config.clientId, null, function (error, tokenOut) call with scope instead of clientid.

Because of above modification it going infinite loop 👎

**Comment by tushargupta51** [comment]
Closing this issue as we are no longer making investments in experimental branch. We are channeling our efforts to next version of this library - MSAL.
