### ISSUE TITLE
Syntax Parse error in v.1.0.12

### ISSUE THREAD

**Issue by rdeslonde-eichleay** [AzureAD/azure-activedirectory-library-for-js#425]
Everything was working fine in 11. When I upgraded to 12 I get a parse error on line 1095.

The function decimalToHex function should not be defined inside the if statement and "_guid" function but instead should be outside of it.

**Comment by tushargupta51** [comment]
@rdeslonde-eichleay Thanks for reporting this. It's a known issue: https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/380 and we have fixed it in dev branch. This will be part of 1.0.13 release.

**Comment by tushargupta51** [comment]
https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/377
