### ISSUE TITLE
Token Refresh issue

### ISSUE THREAD

**Issue by BoyuanLi** [AzureAD/azure-activedirectory-library-for-js#430]
I found an issue that getCachedToken method always return null for me and "var token = this._getItem(this.CONSTANTS.STORAGE.ACCESS_TOKEN_KEY + resource);" token is always empty. Does anyone have similar issue? P.S. I'm using latest code.

**Comment by tushargupta51** [comment]
@BoyuanLi This `getCachedToken` will return null if there is no token for the specified resource in the cache. Can you check in the browser cache if there is a token for the resource?

**Comment by BoyuanLi** [comment]
@tushargupta51 Thanks for the reply. I usually see the token is null first (after 1 hour expiration), then second click will see the token with value. But somehow in this case resource always showing as the clientId and tokenStored is always null.

**Comment by tushargupta51** [comment]
@BoyuanLi The simple rule is that if there is a valid token in the browser cache, getCachedToken will return that otherwise null. If getCachedToken returns null, you can call `acquireToken` to get a new token. OR instead, just call `acquireToken` method as it will check the `getCachedToken` first.

**Comment by tushargupta51** [comment]
Closing this. Please let us know if you are still running into this issue, will reopen it. Thanks.
