### ISSUE TITLE
mapping properties to adalProvider init function

### ISSUE THREAD

**Issue by thdotnet** [AzureAD/azure-activedirectory-library-for-js#435]
I'm trying to setup my adal.js on an angular app, however I'm not sure how to specify a few parameters to the init function.

I have the following sample url which returns a JWT token. Then, I need to do another POST to get user Claims (this step I'm doing with POSTMAN).

https://ad.mytest.local/adfs/oauth2/authorize?response_type=code&client_id=86cb5a1e-9744-44fa-ab24-376f9c45e83d&resource=app-dev
&redirect_uri=http%3A%2F%2Flocalhost%3A7000%2Ftoken

So far, I'm only sure that cliend_id is the clientId property:

			adalProvider.init({
				instance: "https://ad.mytest.local/adfs/oauth2/authorize",
				tenant: "ad.mytest.local",
				clientId: "86cb5a1e-9744-44fa-ab24-376f9c45e83d",
				endpoints: endpoints
			}, $httpProvider);

the url to get the token should be provided into endpoints array?

**Comment by tushargupta51** [comment]
@thdotnet The url you specified will return a code, not a token. Please look at the sample: https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi. Also, we have added detailed comments in 1.0.13. The code in master branch has appropriate comments explaining what each property does.

**Comment by thdotnet** [comment]
Thank you!

**Comment by thdotnet** [comment]
@tushargupta51 The sample you said is not related to mine. Is there anyone that I could specify the url to authenticate, and then, the url to post the token and get the claims?

**Comment by tushargupta51** [comment]
@thdotnet The sample has all those values set as an example. `instance` refers to the authority url e.g. https://ad.mytest.local/. If you are authenticating against adfs, set `tenant` to adfs. `redirectUri` refers to the url where authority returns back the tokens.

Please look at the code comments in the master branch to learn more about what different properties do.
