### ISSUE TITLE
Is there an option to log in without redirecting to login page(login.windows.net)?

### ISSUE THREAD

**Issue by onmondo** [AzureAD/azure-activedirectory-library-for-js#436]

**Comment by tushargupta51** [comment]
In 1.0.12 and later versions, we have added support for pop up based login. You can set `popUp: true` in config, and instead of redirection, user will see the popUp.

**Comment by rguignard** [comment]
Hey

Is it possible to have an exemple of how to use the "popup" mode with Angular ? I tried this mode but my application result In an Infinite loop.

Thanks In advance

**Comment by tushargupta51** [comment]
@rguignard We do not have a sample for pop up yet. But really, you just need to set that property in order to turn on popup based authentication. Can you share logs/traces for the infinte loop?

**Comment by rguignard** [comment]
@tushargupta51: Thanks for your response. You can find below traces.

Wed, 16 Nov 2016 15:06:17 GMT:1.0.13-VERBOSE: Location change event from http://localhost:65532/#/home to http://localhost:65532/#/myFiles
app.js:113 Wed, 16 Nov 2016 15:06:17 GMT:1.0.13-INFO: State change event for:/myFiles
app.js:113 Wed, 16 Nov 2016 15:06:17 GMT:1.0.13-INFO: Login event for:/myFiles
app.js:113 Wed, 16 Nov 2016 15:06:17 GMT:1.0.13-INFO: Start login at:http://localhost:65532/#/myFiles
app.js:113 Wed, 16 Nov 2016 15:06:17 GMT:1.0.13-VERBOSE: Expected state: 5f92e94c-945e-43d3-9e86-6da97a842096 startPage:http://localhost:65532/#/myFiles
app.js:113 Wed, 16 Nov 2016 15:06:17 GMT:1.0.13-INFO: Navigate url:https://login.microsoftonline.com/common/oauth2/authorize?response_type=id_…d=0fb24393-51b1-4854-8640-d73a6f2b8832&x-client-SKU=Js&x-client-Ver=1.0.13
app.js:113 Wed, 16 Nov 2016 15:06:17 GMT:1.0.13-VERBOSE: Url: views/myFiles.html maps to resource: 63d665ad-4811-4fed-9211-a5f0b706a97f
app.js:113 Wed, 16 Nov 2016 15:06:17 GMT:1.0.13-INFO: Url: views/myFiles.html will be loaded after login is successful
Wed, 16 Nov 2016 15:06:17 GMT:1.0.13-VERBOSE: Url: views/myFiles.html maps to resource: 63d665ad-4811-4fed-9211-a5f0b706a97f
app.js:113 Wed, 16 Nov 2016 15:06:17 GMT:1.0.13-INFO: Url: views/myFiles.html will be loaded after login is successful
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-VERBOSE: Location change event from http://localhost:65532/#/myFiles to http://localhost:65532/#id_token=xxxxxxxxxx…-43d3-9e86-6da97a842096&session_state=f4bbb1b2-d7e6-4d75-957f-6861a66db4b8
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-VERBOSE: Processing the hash: #id_token=xxxxxxxxxx&state=5f92e94c-945e-43d3-9e86-6da97a842096&session_state=f4bbb1b2-d7e6-4d75-957f-6861a66db4b8
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-VERBOSE: State: 5f92e94c-945e-43d3-9e86-6da97a842096
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-INFO: State status:true; Request type:LOGIN
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-INFO: State is right
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-INFO: Fragment has id token
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-INFO: Login completed, sending request for views/myFiles.html
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-VERBOSE: Location change event from http://localhost:65532/#id_token=xxxxxxxxxx…-43d3-9e86-6da97a842096&session_state=f4bbb1b2-d7e6-4d75-957f-6861a66db4b8 to http://localhost:65532/#/id_token=xxxxxxxxxx…-43d3-9e86-6da97a842096&session_state=f4bbb1b2-d7e6-4d75-957f-6861a66db4b8
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-VERBOSE: Processing the hash: #id_token=xxxxxxxxxx&state=5f92e94c-945e-43d3-9e86-6da97a842096&session_state=f4bbb1b2-d7e6-4d75-957f-6861a66db4b8
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-VERBOSE: State: 5f92e94c-945e-43d3-9e86-6da97a842096
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-INFO: State status:true; Request type:LOGIN
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-INFO: State is right
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-INFO: Fragment has id token
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-INFO: Login completed, sending request for views/myFiles.html
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-VERBOSE: Location change event from http://localhost:65532/#id_token=xxxxxxxxxx…-43d3-9e86-6da97a842096&session_state=f4bbb1b2-d7e6-4d75-957f-6861a66db4b8 to http://localhost:65532/#/id_token=xxxxxxxxxx…-43d3-9e86-6da97a842096&session_state=f4bbb1b2-d7e6-4d75-957f-6861a66db4b8
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-VERBOSE: Processing the hash: #id_token=xxxxxxxxxx&state=5f92e94c-945e-43d3-9e86-6da97a842096&session_state=f4bbb1b2-d7e6-4d75-957f-6861a66db4b8
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-VERBOSE: State: 5f92e94c-945e-43d3-9e86-6da97a842096
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-INFO: State status:true; Request type:LOGIN
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-INFO: State is right
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-INFO: Fragment has id token
app.js:113 Wed, 16 Nov 2016 15:06:48 GMT:1.0.13-INFO: Login completed, sending request for views/myFiles.html

This infinite loop result in an angular exception:
angular.min.js:102 Error: [$rootScope:infdig] http://errors.angularjs.org/1.3.15/$rootScope/infdig?p0=10&p1=%5B%5D
    at angular.min.js:6
    at n.$digest (angular.min.js:124)
    at n.$apply (angular.min.js:126)
    at angular.min.js:139
    at e (angular.min.js:40)
    at angular.min.js:44(anonymous function) @ angular.min.js:102(anonymous function) @ angular.min.js:76$apply @ angular.min.js:126(anonymous function) @ angular.min.js:139e @ angular.min.js:40(anonymous function) @ angular.min.js:44
angular.min.js:6 Uncaught Error: [$rootScope:infdig] http://errors.angularjs.org/1.3.15/$rootScope/infdig?p0=10&p1=%5B%5D(…)(anonymous function) @ angular.min.js:6$digest @ angular.min.js:124$apply @ angular.min.js:126(anonymous function) @ angular.min.js:139e @ angular.min.js:40(anonymous function) @ angular.min.js:44

**Comment by tushargupta51** [comment]
@rguignard Sorry for the delay. Can you try 1.2.26 and 1.5.8 version of angular to confirm if that makes a difference?

cc: @rohitnarula7176

**Comment by brentschmaltz** [comment]
@rguignard if this doesn't work please reopen.
