### ISSUE TITLE
Hi - Where is Adal-Angular for Angular 2?

### ISSUE THREAD

**Issue by nigel-dewar** [AzureAD/azure-activedirectory-library-for-js#440]
Hi Guys,

Angular 2 official out for a bit now

Where is the official Microsoft library for Angular 2? 

I saw a video by Richard diZerega that shows how to hook up graph api for Ionic 2. For the life of my I cannot figure out why Im having so much trouble finding an official library for Angular 2 'Web app'

Cheers

**Comment by tushargupta51** [comment]
@nigel-dewar We do not plan to add support for angular 2 for adal library. But we are working on next version of adal library - MSAL, and will consider angular 2 for that. Currently, we don't have any dates for the release of the new library, things are in design phase right now.

**Comment by tushargupta51** [comment]
@nigel-dewar Though, I would like to mention that there are some angular 2 implementations contributed by community.

**Comment by nigel-dewar** [comment]
I gotta say, i find the thinking on this pretty odd.

I mean even Auth0 has a solid js implementation for angular2.

I know there are some bespoke implementations out there.

Im just really surprised at the priority level put on this.

Regardless thankyou for the reply.

Cheers

Sent from Samsung Mobile


-------- Original message --------
From: tushar gupta
Date:18/11/2016 04:56 (GMT+10:00)
To: AzureAD/azure-activedirectory-library-for-js
Cc: nigel-dewar , Mention
Subject: Re: [AzureAD/azure-activedirectory-library-for-js] Hi - Where is Adal-Angular for Angular 2? (#440)


@nigel-dewar<https://github.com/nigel-dewar> We do not plan to add support for angular 2 for adal library. But we are working on next version of adal library - MSAL, and will consider angular 2 for that. Currently, we don't have any dates for the release of the new library, things are in design phase right now.

-

**Comment by HJoost** [comment]
Are there any updates on this topic?
