### ISSUE TITLE
Add ability to specify anonymous 'sub-url' for a configured endpoint

### ISSUE THREAD

**Issue by SergeyLaptsevich** [AzureAD/azure-activedirectory-library-for-js#441]
Let's say I have the following config:
```
 adalProvider.init(
              {
                  instance: 'https://login.microsoftonline.com/',
                  tenant: '{my-id}',
                  clientId: '{my-id}',
                  endpoints: { 'https://my.domain/api': '{my-id}' }
              },
              $httpProvider);
```

And under the https://my.domain/api I have many sub-routes like '/users', '/comments', '/whatever' etc.
I just want to have a way to specify:
```
 anonymousEndpoints: [
                    'https://my.domain/api/whatever',
                  ]
```
and all the requests to https://my.domain/api/whatever will be anonymous. Currently this is not supported and to fix this I just had to move the following code to the beginning of AuthenticationContext.prototype.getResourceForEndpoint function:

```
 if (this.config && this.config.anonymousEndpoints) {
                for (var i = 0; i < this.config.anonymousEndpoints.length; i++) {
                    if (endpoint.indexOf(this.config.anonymousEndpoints[i]) > -1) {
                        return null;
                    }
                }
            }
```
also it would be useful to have an option where some url can be accessed both with authorization header (if user is authorized) and without it (if not).

**Comment by tushargupta51** [comment]
@SergeyLaptsevich Specifying a url in endpoints array imply that all requests to that domain (and possibly sub domains) need to be authenticated. If only part of your api requires authentication then you should specify only those urls in endpoints, e.g., `https://my.domain/api/protected`.

>also it would be useful to have an option where some url can be accessed both with authorization header (if user is authorized) and without it (if not).

I am not sure if this is a good idea. A resource (identified by an application url) is either protected or not. It can't be both. If a url can be accessed without token, then there is no need to pass tokens to that url.

**Comment by SergeyLaptsevich** [comment]
@tushargupta51 I see how it works now :) The idea is to minimize configuration work, let's say I have 100 microservices under https://my.domain/api (and each have it's own path like https://my.domain/api/microservice). And only 1 of 100 is anonymous (let's say microservice for login). It is a pain to specify 99 urls in endpoints and then maintain this list... I just want to say "protect everything in https://my.domain/api except https://my.domain/api/login". And don't want new developer who just joined the team and added new microservice and forgot to update the list to spend few hours trying to understand why token is not there :)

> I am not sure if this is a good idea. A resource (identified by an application url) is either protected or not. It can't be both. If a url can be accessed without token, then there is no need to pass tokens to that url.
This might be useful in some scenarios but you probably right, not so important. For example if user sends feedback it might be useful to know if it is logged in user on server side (but we still should have it open for anonymous users). But yea, there are other ways to achieve this.

**Comment by tushargupta51** [comment]
@SergeyLaptsevich I talked to my team members regarding this issue and it seems fair to allow configuring sub-urls for external apis to be anonymous. I have added this to next milestone. We will move up the check for anonymous endpoints.
