### ISSUE TITLE
Investigate updateDataFromCache method in adal-angular

### ISSUE THREAD

**Issue by rohitnarula7176** [AzureAD/azure-activedirectory-library-for-js#444]
we call getCachedToken() in adal to check if the user is authenticated which checks for the existence of the access token in the cache instead of the idtoken.

**Comment by tushargupta51** [comment]
Update: updateDataFromCache in adal-angular calls into getCachedToken method and updates the value of _oauthData based on the token returned by the call.

I think it makes sense that we update the state of the user based on the expiration of current id_token. For app's own backend, access token saved in the browser is actually an id token. So even if getCachedToken method looks into access token keys in browser storage, it is indeed returning whether the id_token is still valid or not.
