### ISSUE TITLE
Double "error" pipeline in the Angular acquireToken

### ISSUE THREAD

**Issue by ischrei** [AzureAD/azure-activedirectory-library-for-js#450]
Hi,

When an Angular $http request fails due to AAD error, the returned ".data" property get the form "error description | error | undefined".
It happens because both ADAL JS acquireToken and ADAL-Angular acquireToken add " | " + error to the error message.

Thanks,
Ido.

**Comment by tushargupta51** [comment]
Thanks @ischrei .

Update the reject handler in interceptor to this:

      function (error) {
              config.data =  error;
              delayedRequest.reject(config);
     }
