### ISSUE TITLE
A very useful library but lacks of documentation to be used with other SPA frameworks but only angular 

### ISSUE THREAD

**Issue by hitendramalviya** [AzureAD/azure-activedirectory-library-for-js#453]
I find this library very useful but also it lacks of documentation to be used with other SPA frameworks all examples comes for angular only.

**Comment by tushargupta51** [comment]
@hitendramalviya We only provide out of box support for angular and have no plans currently to extend this further. All the core apis are in adal.js and one can write a wrapper around these apis for any other SPA framework (React, Angular2) by following the adal-angular.js file. All the authentication logic exists in adal.js. We are going to add more detailed documentation for adal.js apis soon (#412)

**Comment by FDMatthias** [comment]
A bit late, but I've written a blogpost about this [here](https://www.appfoundry.be/blog/2018/11/24/authentication-with-adal-in-react-single-page-applications/) and put a sample of a React SPA with Adal on github [here](https://github.com/appfoundry/react-adal-authentication-session-sample/tree/Authentication-with-ADAL-in-React-SPA) (includes step by step commits and multiple branches).
