### ISSUE TITLE
ADAL Angular interceptor ignores $templateCache content and may fail cached requests

### ISSUE THREAD

**Issue by ischrei** [AzureAD/azure-activedirectory-library-for-js#454]
Hi,

We are using the ui bootstrapt third party library which initializes angular's $templateCache with some of its templates.
Adal tries to protect even a cached template.
In my case, the templates name's have the pattern "template/.../..html", so ADAL tries to protect the localResource. When ADAL fails to acquire token, he fails the templateUrl request, instead it to be served successfully from the $templaeCache.
I resolved it by adding "template/" to my anonymousEndpoint configuration, but it is fragile and only a workaround.

Thanks,
Ido.

**Comment by tushargupta51** [comment]
@ischrei Thanks for reporting this. I think exempting templates that are in templateCache from authentication sounds like a good idea. I will add this to next milestone.
