### ISSUE TITLE
Response_mode support for query and form

### ISSUE THREAD

**Issue by akanieski** [AzureAD/azure-activedirectory-library-for-js#455]
Hello All,

We noticed that ADAL.js is dependent on `response_mode=fragment`. There are issues with some of the front-end frameworks (Angular2, Ionic's DeepLinks and others) intercepting the hash logic before ADAL has a chance to process the callback.

Is there any plan to update to add support the other response modes? Namely query string?

**Comment by tushargupta51** [comment]
@akanieski Adal Js only support implicit flow (response_mode=fragment). Encoding tokens as query string parameters have security implications: http://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#Security

**Comment by akanieski** [comment]
Ah understood. Thanks.
