### ISSUE TITLE
Popup login issue with Edge

### ISSUE THREAD

**Issue by rohitnarula7176** [AzureAD/azure-activedirectory-library-for-js#457]
When logging in using a popup window, we first get redirected to the authorization endpoint and after successful authentication, get redirected back to the redirect uri with a token served in the url fragment. In Edge, we are not able to detect the change in in the url fragment using the specified interval of the setInterval method (20 ms). As a result, we are not able to process the received token. 
This behavior works perfectly in all other browers such as Chrome, Firefox, IE.

**Comment by jicailiu** [comment]
I'm getting this error in IE as well: 'Popup Window is null. This can happen if you are using IE'. How do you get it working for you on IE?

**Comment by tushargupta51** [comment]
@jicailiu You need to uncheck the "Enable protected mode" checkbox in IE for this to work. Are you using running app using "localhost" or on internet?

**Comment by jicailiu** [comment]
@tushargupta51 Thanks for the tip, it does the trick. I'm still trying things out in intranet.

**Comment by paonekumar** [comment]
@tushargupta51 I am also getting similar issue, it is working good after unchecking "Enable protected mode" in IE, do we have any other solution? we cannot request all our clients to change IE settings.

**Comment by tushargupta51** [comment]
@paonekumar Unfortunately, No. This is an IE/Edge specific behavior, probably related to security zones, where they do not allow opening new windows in different security zone.

**Comment by brentschmaltz** [comment]
@paonekumar we don't know of any other solution right now.

**Comment by mazhisai** [comment]
Is there a resolution on the original issue reported about popUp window not working on edge? are there any workarounds for that? thanks!

**Comment by ayoubchoudhury** [comment]
Did anyone find any solution for the initial pop up issue with only on Edge browser?

**Comment by rohitnarula7176** [comment]
@ayoubfc Do you have a repro for this issue. I will need to debug your code to see why this is happening as there can be multiple reasons for this behavior.

**Comment by bveerendrakumar** [comment]
Hi,

I am willing to work with you on this item, we have this issue on EDGE and IE and I can repro this on my machine. Please let me know the right time.

**Comment by rohitnarula7176** [comment]
@bveerendrakumar Can you please setup a time with me on skype anytime after 2 p.m. to go over this issue. It will be best if you can reproduce the issue during that meeting.

**Comment by pritamDas9191** [comment]
@rohitnarula7176 / @bveerendrakumar, Did you guys get any solution to this ? I am also facing the same issue. Specifically when i try to call adal._acquireTokenPopup() on Edge. Any help is appreciated :)

**Comment by paztek** [comment]
Hi,

I'm having the same issue on Safari OSX.

If I keep `popUp: false` (the default), the redirection works OK but if I set `popUp: true`, no popup is opened and I get the same error message.
