### ISSUE TITLE
userInfo.isAuthenticated is not set to true when http request goes before location change

### ISSUE THREAD

**Issue by SergeyLaptsevich** [AzureAD/azure-activedirectory-library-for-js#459]
Quite rare case but quite simple to fix :)
In my application for many ui-router states i have http request in controller constructor to load initial data. For case when adal token is expired it just calls acquireToken, the token is refreshed and data is succesfully loaded but _userInfo.isAuthenticated remains false. This happens because ProtectedResourceInterceptor is called before locationChangeHandler (and as a result locationChangeHandler skips token refreshing and do not set _userInfo.isAuthenticated to true).

My current workaround is:

```
$rootScope.$on('adal:acquireTokenSuccess', function () {
    if (adalAuthenticationService.userInfo) {
        adalAuthenticationService.userInfo.isAuthenticated = true;
    }
});
```

I believe the fix should be just moving the following code which is now in locationChangeHandler:
```
if (token) {
    _oauthData.isAuthenticated = true;
}
```
to acquireToken function so it looks like (I used '...' to hide code which is not important here):
```
acquireToken: function (resource) {
                          ...
                        _adal.acquireToken(resource, function (errorDesc, tokenOut, error) {
                            ...
                            if (error) {
                                ...
                            } else {
                                if (tokenOut) {
                                    _oauthData.isAuthenticated = true;
                                }
                                ...
                            }
                        });
                        ...
                    }
```

**Comment by torosmichele** [comment]
same here!
checked in angular .run() method

**Comment by tushargupta51** [comment]
@SergeyLaptsevich 

>For case when adal token is expired it just calls acquireToken, the token is refreshed and data is succesfully loaded but _userInfo.isAuthenticated remains false

Are you referring to acquireToken call inside the interceptor or inside the locationChangeHandler. `updateDataFromCache` method updates userInfo.isAuthenticated property and this method is called periodically.

**Comment by SergeyLaptsevich** [comment]
@tushargupta51 I'm referring to a case when acquireToken is called inside the interceptor. updateDataFromCache doesn't work here because I need _userInfo.isAuthenticated to be true immediately (I'm showing/hiding log in/log out buttons based on its value). As a result user sees that page/data is successfully loaded but menu on the top shows that he is not authenticated.

**Comment by tushargupta51** [comment]
@SergeyLaptsevich When acquireToken call is made inside the interceptor, the locationChangeHandler is still executed. It is executed inside the iframe where AAD returns back the response.

Sequence of steps:
1. Interceptor sends acquireToken request.
2.  AcquireToken method creates an iframe and sends request to AAD.
3. AAD returns back the response to iframe.
4. Adal instance running in iframe processes the response. This is where locationChangeHandler is executed, token is processed and set in cache, and updateDataFromCache method is called.
5. The callback is executed (call is made in step 4, specifically from the saveTokenFromHash method in locationChangeHandler)


It might be possible that by the time callback is executed, the rootScope changes have not been broadcasted yet, but as you already mentioned that is a rare case.

**Comment by tushargupta51** [comment]
Closing this. Let us know if the above does not hold true, I will more than happy to look into this again.

**Comment by saransh944** [comment]
Hi @tushargupta51 , the same thing is happening for me. I have the acquire token in two places:
1. Http interceptor
2. URL change detection

But, as mentioned above, the 'isAuthenticated' property is not getting updated to true even after acquireToken refreshes the token. Is there a way to toggle this property manually after the token refreshes?

**Comment by SergeyLaptsevich** [comment]
@saransh944 Does the workaround I posted in the first comment work for you (see below)?

```
$rootScope.$on('adal:acquireTokenSuccess', function () {
    if (adalAuthenticationService.userInfo) {
        adalAuthenticationService.userInfo.isAuthenticated = true;
    }
});
```
