### ISSUE TITLE
Supported response_type values

### ISSUE THREAD

**Issue by heikkilamarko** [AzureAD/azure-activedirectory-library-for-js#461]
When looking at the source code of `login()` function in `adal.js`, it seems that the `response_type` parameter value is hardcoded as `id_token`.

```javascript
...
var urlNavigate = this._getNavigateUrl('id_token', null) + '&nonce=' + encodeURIComponent(this._idTokenNonce);
...
```

I want to use `"id_token token"` as `response_type`. Is it possible to do that somehow?

**Comment by tushargupta51** [comment]
@heikkilamarko You can implement `displayCall` method. This takes authorization url as input. You can  replace "id_token" to url encoded value of "id_token token" in that and then set the window.location to url value.

**Comment by brentschmaltz** [comment]
@heidijinxujia if this doesn't work for you, please reopen.
