### ISSUE TITLE
Call displayCall method before using any default behavior in login method

### ISSUE THREAD

**Issue by AidaNow** [AzureAD/azure-activedirectory-library-for-js#462]
Hi,

I am trying to add '&prompt=admin_consent' to 'urlNavigate' to be able to get the IT admin consent. I am using the following code suggested [here](https://github.com/waldekmastykarz/sample-azure-adminconsent/blob/master/app/admin/admin.controller.js#L4-L5):

var adal = new AuthenticationContext();
adal.config.displayCall = function adminFlowDisplayCall(urlNavigate) {
urlNavigate += '&prompt=admin_consent';
adal.promptUser(urlNavigate);
};
adal.login();
adal.config.displayCall = null;

but it does not work for me because I am using the 'popup: true' flag when I initialize the adal library (I am using version 1.0.13). The reason is that in adal.js, we have the following block of code:

    /**
     * Initiates the login process by redirecting the user to Azure AD authorization endpoint.
     */
    AuthenticationContext.prototype.login = function () {
        // Token is not present and user needs to login
        if (this._loginInProgress) {
            this.info("Login in progress");
            return;
        }
        var expectedState = this._guid();
        this.config.state = expectedState;
        this._idTokenNonce = this._guid();
        this.verbose('Expected state: ' + expectedState + ' startPage:' + window.location);
        this._saveItem(this.CONSTANTS.STORAGE.LOGIN_REQUEST, window.location);
        this._saveItem(this.CONSTANTS.STORAGE.LOGIN_ERROR, '');
        this._saveItem(this.CONSTANTS.STORAGE.STATE_LOGIN, expectedState);
        this._saveItem(this.CONSTANTS.STORAGE.NONCE_IDTOKEN, this._idTokenNonce);
        this._saveItem(this.CONSTANTS.STORAGE.ERROR, '');
        this._saveItem(this.CONSTANTS.STORAGE.ERROR_DESCRIPTION, '');
        var urlNavigate = this._getNavigateUrl('id_token', null) + '&nonce=' + encodeURIComponent(this._idTokenNonce);
        this._loginInProgress = true;
        if (this.popUp) {
            this._loginPopup(urlNavigate);
            return;
        }
        if (this.config.displayCall) {
            // User defined way of handling the navigation
            this.config.displayCall(urlNavigate);
        } else {
            this.promptUser(urlNavigate);
        }
    };
	
	which checks the popup flag first and if it is true, it opens the popup and it does not go to the next if clause to check if there is a user defined config.displayCall. The fix is to first check for config.displayCall and then check for the popup flag.
	
Thank you.

**Comment by tushargupta51** [comment]
@AidaNow You can't use default popup behavior and displayCall method together. If user overrides the login redirection behavior using `displayCall` method, the default way will be skipped (both popup and redirect based login). So, even if we move the `displayCall` method above popUp (which we intend to do), this might not solve your problem as that will redirect the user since you are using `promptUser` method inside the `displayCall` method.

**Comment by AidaNow** [comment]
@tushargupta51 Thanks for your reply. You are right, I am using admin_consent only in some cases. Here is how I fixed the issue (I am always using popup):

In my login controller, I have:

var adal = new AuthenticationContext();
adal.config.displayCall = function adminFlowDisplayCall(urlNavigate) {
    urlNavigate += '&prompt=admin_consent';
    adal._loginPopup(urlNavigate);
};
adal.login();
adal.config.displayCall = null;


 **and I changed the adal library as follows:**

/**
     * Initiates the login process by redirecting the user to Azure AD authorization endpoint.
     */
       ...
        if (this.config.displayCall) {
            // User defined way of handling the navigation
            this.config.displayCall(urlNavigate);
        }
        if (this.popUp && !this.config.displayCall) {
            this._loginPopup(urlNavigate);
            return;
        }
        else if (!this.popUp && !this.config.displayCall){
            this.promptUser(urlNavigate);
        }
    };


**Does this make sense to you?**

**Comment by tushargupta51** [comment]
@AidaNow Yes, it does. I will update the subject of the issue to reflect that we need to move up the call to displayCall method. Thanks!

**Comment by AidaNow** [comment]
@tushargupta51 Thanks for your reply. Looking forward to see and use this in 1.0.14 version.
