### ISSUE TITLE
Plans for `oauth2/v2.0/authorize` and `oauth2/authorize` tokens

### ISSUE THREAD

**Issue by darcyparker** [AzureAD/azure-activedirectory-library-for-js#465]
The current `dev` branch is using `oauth2/authorize`, whereas the `experimental` uses `/oauth2/v2.0/authorize`.  I can see from comments such as in #420 that the `experimental` branch is not being worked on anymore (last touched Oct 2015), yet the older experimental branch is being used by [graph-explorer](https://graph.microsoft.io/en-us/graph-explorer#/).  What is `MSAL JS`? Where can I find it? Or when is it expected to be available?

Many endpoints (such as `https://graph.microsoft.com/beta/sharepoint/site`) require a JWT token acquired from `/oauth2/v2.0/authorize`.  And some endpoints aren't yet available for Azure AD v2.0 yet...  So it looks like I may need to fallback to using tokens acquired by `/oauth2/authorize` (I am not sure about this need yet).  Regardless, it seems I need a library that can construct JWT tokens with `/oauth2/v2.0/authorize` (so I can query info from sharepoint and use personal accounts).  I can do this with required scopes using [experimental branch](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/experimental/lib/adal.js#L866).  But it looks like this branch is dead...   What is recommended if the experimental branch is not being worked on and MSAL JS is not available?  Are people using the experimental branch in production for Azure AD V2.0 endpoints?

Related question:
In the dev branch, is there interest in having a `config.endpoints` dictionary that can be used to configure both:
* a dictionary of endpoint to resource for `oauth2/authorize`?
* and a dictionary of endpoint to scopes for `oauth2/v2.0/authorize`?

And use this `config.endpoints` to get/cache the various versions of JWT tokens?

**Comment by darcyparker** [comment]
I have seen reference to the upcoming MSAL JS in various blog posts from early 2016... but haven't found much more.  It seems the unified strategy of MSAL is what I need today... or some other approach to get by with that lets me use different versions of the JWT tokens.

**Comment by lamuertepeluda** [comment]
No good news for you, pal...

https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/189#issuecomment-262620390

**Comment by darcyparker** [comment]
@lamuertepeluda - thanks for sharing.  I'd love to hear a roadmap update from Microsoft on this.

**Comment by tushargupta51** [comment]
@darcyparker Sorry for the delay in response, we are still working on the roadmap, things are in early design phase right now, we will update this space once we have more concrete information about MSAL JS (library thats going to work against the v2 endpoint).

**Comment by darcyparker** [comment]
https://blogs.technet.microsoft.com/enterprisemobility/2016/03/31/microsoft-identity-at-build-2016/

>In the coming months we will release previews of MSAL for other platforms , with the goal of matching and surpassing the platform reach that ADAL offers today. That means that you can expect a native iOS MSAL, a native Android MSAL, a MSAL JS, and so on.

Many of us are eagerly awaiting to use the graph.microsoft.com api.  It looks like an unsupported experimental branch is our only option?  (or use another oauth2 framework or roll our own.)  I can understand there are delays... but it is disappointing to hear things are still in early design phase after reading an article from a year ago that it would be a few months away.  Is there an open issue that you or someone from Microsoft can notify us with an update?

My 2 cents: This seems like a very relevant issue to the community and worth keeping open until Microsoft is ready to communicate more.

**Comment by darcyparker** [comment]
FYI to those who may be watching this:

https://github.com/AzureAD/microsoft-authentication-library-for-js Microsoft Authentication Library Preview for JavaScript (MSAL.js) is available now!
