### ISSUE TITLE
Adal-1.0.13, Popup mode: The frame attempting navigation is sandboxed, and is therefore disallowed from navigating its ancestors.

### ISSUE THREAD

**Issue by rguignard** [AzureAD/azure-activedirectory-library-for-js#466]
Hey

I trying to use the last version of adal 1.0.13 in an Oulook add-in.
I configured adal.js to use the popup mode. (popup:true)
The authentication is working correctly on IE11 but I meet an error with chrome during authentication in the popup. You can find below the console trace: 

adal.js:274 Unsafe JavaScript attempt to initiate navigation for frame with URL 'https://host/appname/AppCompose/Home/Home.html' from frame with URL 'https://host/appname/AppCompose/Home/Home.html#'. The frame attempting navigation is sandboxed, and is therefore disallowed from navigating its ancestors.

Does someone have any idea on the problem ?

Romain

**Comment by rguignard** [comment]
Hey

Does anyone has already used adal.js in an add-in ?

**Comment by brentschmaltz** [comment]
@rguignard it may be helpful to post a question on StackOverflow.

Use tags: adal, msal, azuread.

**Comment by tushargupta51** [comment]
@rguignard Adal is intended to be used inside a regular browser mode. When using inside a hosted browser, things are not guaranteed to work as the browser behavior can be different.
