### ISSUE TITLE
Add adal.js to npm

### ISSUE THREAD

**Issue by eamodio** [AzureAD/azure-activedirectory-library-for-js#468]
I see there is an adal-angular version on npm, but why isn't the non-angular version on npm?

**Comment by tushargupta51** [comment]
@eamodio What are the issues you are facing in adding adal-angular npm as dependency? Does it ask you to install angular as well?

**Comment by eamodio** [comment]
@tushargupta51 there are no issues using the angular version, other than extra unneeded angular code that adds to the size of my bundle. But really the main issue is confusion. I wouldn't have chosen an angular version of something if I'm not building an angular app.

**Comment by tushargupta51** [comment]
Dup of #443 . Please follow that issue regarding pushing separate npm module for plain adal js.
