### ISSUE TITLE
Angualar Route 1.5.11, returns to the wrong route after logging in

### ISSUE THREAD

**Issue by tian100** [AzureAD/azure-activedirectory-library-for-js#470]
Adal.js and Adal-Angluar.js (V 1.0.13) doesn't save the intended return URL when login is triggered by route  change in Angular JS 1.5.11. 

For example, when the ToGo List route is marked by "requireADLogin: true" and user moves from "home" to "to go list", the return url should be the "To Go list page", rather than the "home page". However, the home page url is stored in session storage because in `adal.js AuthenticationContext.prototype.login`, therefore, when the user is redirected back to the site, they are on the home page, rather than the "to go list page".

`this._saveItem(this.CONSTANTS.STORAGE.LOGIN_REQUEST, window.location)`

in this case, in Angular Route 1.5.11, `window.location` points to home page, rather than the "intended page" -- the "To Go List" page. In Angular 1.2, `window.location` actually points to the intended page, "To Go list" in this case.

**Comment by rohitnarula7176** [comment]
@tian100 We have seen this behavior in angular version 1.5.8 and above and it is because they changed the way they handle the routeChange event. We will update our code to save the correct loginStartPage in our next release.

**Comment by rohitnarula7176** [comment]
@tian100 Can you please confirm whether you are seeing this behavior with popUp:true or with the default redirect flow or both.

**Comment by tian100** [comment]
I saw it with default redirect flow. Haven't tried the popup yet...
