### ISSUE TITLE
Only accepts clientId as audience

### ISSUE THREAD

**Issue by magnuf** [AzureAD/azure-activedirectory-library-for-js#472]
I have a SPA that uses an API hosted in Azure, using AzureAD.
I have been trying for some time now to get adal.js working, with little luck. I've tried several approaches, and one thing I am stuck on now is
`Bearer error="invalid_token", error_description="The audience is invalid"`

This led me down the path of figuring out which audience the token contains.
I can acquire a token using postman, and set that as `Authorization = Bearer <postmantoken>`. Using the API then works.

The audience of the postman token is the App ID URI set in azure portal.
The audience of the token I get from adal.js is the Application ID (in azure)  or the ClientId (in adal) (These two are the same as far as I have understood).

Looking at the code, https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal.js#L685 it says here that the only audience adal accepts on a token is the Client ID.

Now, I haven't been successful in using adal to acquire a token containing the App ID URI as audience, so I don't know if that fixes my problem.

What I am wondering, is this correct? That the only accepted audience for adal is the Client/Application ID? And if so, why am I getting the "The audience is invalid" error?

I am sorry if this just shows a lack of understanding on my part, but I am now running out of things to try to get this working.

**Comment by rohitnarula7176** [comment]
@magnuf Can you share your app.js file which has the configuration details. If you are trying to access an api which is not hosted on your domain, you will have to configure the endpoints property on the config object as shown below for adal to attach tokens to this request. 
```
 var endpoints = {
        // Map the location of a request to an API to a the identifier of the associated resource
        "https://localhost:44327/": "https://---.onmicrosoft.com/ToGoAPI",//This is the resourceID of the togoApi deployed on Azure
    };

```
 We will be able to investigate further once you send us your configuration file and error logs.

**Comment by magnuf** [comment]
Hi!

I am not using this in an angular app, and as far as I can see, the only usage of endpoints is in `getResourceForEndpoint`, which is only used in `adal-angular`.

I haven't found a way to use this function for my app.

My comment was more of a question of, is it correct that 
`if (parsedJson.aud.toLowerCase() === this.config.clientId.toLowerCase()) {` is the only valid scenario.

Sorry if this was unclear.

**Comment by Vivihung** [comment]
Hum... I'm not using adal.js in Angular, either. (used in react)
But everything works fine for me.
I'm curious about your configuration passed to adal, @magnuf

**Comment by magnuf** [comment]
I have solved the `audience is invalid` error. It was a misconfiguration on the backend API.

**Comment by derobiom** [comment]
Can you share what the misconfiguration on the backend API?  I think that I am making the same mistake.

**Comment by aspnerd** [comment]
What was the fix?

**Comment by rangedsp** [comment]
I tracked down a similar issue using [jwt.io](jwt.io) to check the 'aud' property in the jwt token, as it turned out I was using the wrong audience from the one I set in AAD.

**Comment by talbenbasat** [comment]
Hi @magnuf,

How did you manage to solve this issue?
