### ISSUE TITLE
Help with token issues

### ISSUE THREAD

**Issue by johanalkstal** [AzureAD/azure-activedirectory-library-for-js#473]
Sorry for the non descriptive title but I'm not sure what the problem is.

We have a basic setup of ADAL,
```
function adalConfig($httpProvider, adalAuthenticationServiceProvider, abacusConfig) {
        adalAuthenticationServiceProvider.init({
            tenant: abacusConfig.tenant,
            clientId: abacusConfig.audience,
            endpoints: {
                [abacusConfig.apiUrl]: abacusConfig.corsAppUri
            },
            anonymousEndpoints: ['template/'],
            cacheLocation: 'localStorage',
            requireADLogin: !abacusConfig.disableAuth
        }, abacusConfig.disableAuth ? null : $httpProvider);
    }
```

We also have this in our `app.js`,
```
if (window !== window.parent) {
        angular.module('app', [
            'abacusConfig',
            'coreModule',
            'templates',
            'translationsModule'
        ]);

        return;
    }

    angular.module('app', [
    // The full client app...
```
to serve a thin client for the ADAL iframe.

But we have a lot of problems with our users not being considered authenticated.
What we do is if `adal:acquireTokenSuccess` is broadcasted, we check `adalAuthenticationService.userinfo.isAuthenticated` and set a scope variable.

Sometimes `.isAuthenticated` returns false after a token has been successfully acquired.

And sometimes `adal:acquireTokenFailure` is called with a timeout error, which we don't handle properly.

And when the token has expired and the user visits our app url, nothing happens. Only when they refresh a second time after the token has expired is a new token acquired.

So there are a lot of things that are not working properly and I'm sure it's on our part (not doing things properly), so I would really appreciate some guidance and explanations on what's going on and what we could do better?

**Comment by Walk4Muscle** [comment]
What your application's structure looks like? Have you tried the first method of https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs#q1-my-app-is-re-loading-every-time-adal-renews-a-token?

**Comment by johanalkstal** [comment]
Not sure what structure would be interesting to know, that isn't in the code above?

Yes we have tried the first method in Q1 (and are using the second one).
Our issue isn't that it keep reloading (we had that issue before though), but that it doesn't reload at all.
Not sure it should reload even? Shouldn't the token be renewed in the background?
