### ISSUE TITLE
Authenticating automatically with external apps

### ISSUE THREAD

**Issue by FacundoGFlores** [AzureAD/azure-activedirectory-library-for-js#475]
I will try to describe the scenario.

1- Today, I have an application using adal.js library which authenticates with Azure using the implicit flow. So, when an user wants to enter to home, it is required to be logged in. So I have a function doing the following:

```
const hash = window.location.hash;
if (this.adal.isCallback(hash)) {
  const requestInfo = this.adal.getRequestInfo(hash);
  this.adal.saveTokenFromHash(requestInfo);
}
```

Everything is working OK.

2- Now, an external app (B) wants to access my app (A). So in the app B there is a link to my app, and it will open a new window in which I need to be already logged. Then, app A can access to the APIs of app A and B.

OK, I was thinking app B can send USER and PWD for azure encrypted and app A decrypt them, but it is quite unsafe.

How can I handle safe the second point in my javascript app?

PS: There will be many external apps which need to enter app A.

**Comment by Walk4Muscle** [comment]
Your app is secured by Azure AD, whose the authentication flow follow the OAuth 2.0. Any other applications want to access your application protected by AAD, need to authenticate and authorize from AAD and acquire an access token first. Then set the access token in HTTP request's authorization header against your application.

So, which require the app B generate the access token for your users, and set it in the header when direct to your app A.

**Comment by tushargupta51** [comment]
@FacundoGFlores 
@Walk4Muscle is correct. If App B wants to access App A's resources, it first needs to acquire a token from AAD.

>Then, app A can access to the APIs of app A and B.

app A needs to acquire tokens for both itself(id_token) and for app B(access token).

**Comment by tushargupta51** [comment]
Closing this for now. Let us know if you have any more questions.
