### ISSUE TITLE
How does 'adal.idtoken' get set in localStorage?

### ISSUE THREAD

**Issue by AmazingJaze** [AzureAD/azure-activedirectory-library-for-js#480]
Before [this line of code](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/8560eb01c9ac3c6510d03e6319b9a8588398c11c/lib/adal.js#L136) runs inside of the AuthenticationContext constructor function,

```localStorage.getItem('adal.idtoken')``` doesn't exist. 

Immediately after that line of code runs, 
```localStorage.getItem('adal.idtoken')``` returns a token.

But this only works in Edge and IE.  

Here is a reduced repro of the same behavior that I ran in the console while broken into the debugger at that same line

```JS
// unset “this.config” in case it already existed as a JS property setter. REALLY want to make sure its gone.
delete this.config;
this.config = {};
console.log(localStorage.getItem('adal.idtoken')); // prints null or undefined
this.config = {cacheLocation: 'localStorage'};
console.log(localStorage.getItem('adal.idtoken')); // prints a token
```
It seems that ```this.config = {cacheLocation: 'localStorage'};``` is somehow causing the token to appear in localStorage.

### Backround on this inquiry
We would like this behavior to also work in Windows 10 Hosted Web Apps, but it currently does not. Understanding what special behavior Adal.js takes advantage of in the Edge browser, will help us understand what we changes we need to make, internally in WWAHost.exe to make the same scenario work.

// @rohitnarula7176  @kirupa

**Comment by AmazingJaze** [comment]
Updated original issue for clarity

**Comment by tushargupta51** [comment]
@AmazingJaze I don't think there is any correlation between that line of code and `localstorage.getItem('adal.idtoken')` returning a value. When you set `cacheLocation` to localStorage, that means that adal will use localStorage to store tokens. Default is sessionStorage. So, when you do not set cacheLocation property, items will be stored in sessionStorage. But this setting should be provided when initializing adal. If you try to change it in console window, you won't see expected results.

**Comment by AmazingJaze** [comment]
Hi @tushargupta51, Can you help me understand where `adal.idtoken` token is first set in localStorage? I am on a domain joined machine, signed in via corpnet credentials. Is Adal.js doing anything to set it, or is this something Edge does automatically?

I agree it seems implausible that the token should be getting set the way I described above. But in execution it is very perplexing to me why ```console.log(localStorage.getItem('adal.idtoken'));``` does not return a token until immediately after ```this.config = {cacheLocation: 'localStorage'};```  has executed. For me it is a 100% repro. 

The problem real problem I see when debugging in the Hosted Web App environment is that the token never gets set, and Users still to login still even when running on a domain joined machine. For additional context, Hosted Web Apps are running EdgeHTML in an AppContainer, but they don't use the full Edge Client.

**Comment by tushargupta51** [comment]
@AmazingJaze Adal Js sets the `adal.idtoken` property, look into `saveTokenFromHash` method.

Adal Js does not support hosted web browsers, it only supports browsers running in regular mode.

**Comment by tushargupta51** [comment]
Issue was related to Integrated Auth in Edge.
