### ISSUE TITLE
Ability to detect if a user session is valid or not.

### ISSUE THREAD

**Issue by rohitnarula7176** [AzureAD/azure-activedirectory-library-for-js#486]
In the current code, there is no way to detect whether the user session is valid or not. In a case when a user signs in to the app, closes the browser and reopens it, the cookies get deleted. In this case, when adal tries to acquire a token , it results in a failure event ("adal:acquireTokenFailure") with the error "AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD" thrown to the app developer. With the current code, the developer has to listen to this event and call login explicitly. It will be best for adal to have some kind of way to check whether the user session is valid/invalid.

**Comment by tushargupta51** [comment]
Related to https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/471. Closing this since we do not plan to add "check_session" support in adal right now. Users are expected to listen to acquireTokenFailure event when they receive "login_required" error.
