### ISSUE TITLE
Token renewal operation failed due to timeout with Power BI API

### ISSUE THREAD

**Issue by aditya1984** [AzureAD/azure-activedirectory-library-for-js#491]
I am using ADAL.js(v1.0.13) to access Power BI reports using architecture as described [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code) and [here](https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-integrate-report-get-report/).

I could get the authorization code and ID token successfully but when I try to get the access token for Power BI API resource (https://analysis.windows.net/powerbi/api) I get "Token renewal operation failed due to timeout" error. 

I tried with modifying ADAL.js library also setting grant_type and code as URL parameters with values as 'authorization_code' and actual authorization code received earlier. I still get the same error.

Please help me resolving this error as I am stuck at this point and cannot proceed to access Power BI reports & datasets without the access token. Please me know if more information is required.

**Comment by aditya1984** [comment]
The navigation URL that is loaded into ADAL iframe is like below (**** are to hide specific values):

https://login.microsoftonline.com/*******.onmicrosoft.com/oauth2/authorize?
grant_type=authorization_code
&client_id=************************
&resource=https%3A%2F%2Fanalysis.windows.net%2Fpowerbi%2Fapi
&code=AQABAAAAAADRNYRQ3dhRSrm-4K-adpCJSYrOCejxkuXTXAMBqAB6wjCZQV2T47NyU4V81LSRWCBLrNYUaKd60KquMs0zt28UqFpSo8XDznbeH53TA0MkqqXD4eiweNbr94WFgPywoEM8Z0wvgAV1ihXnmNwblyRmMDQjsoek5kEFA1NVFMCHK_lESbbC6mVSe4I1WjQ4e8uzc2SaiypYxsI_8g612Bb9gS5T2MfCd5mTreYNDCbXpILVARBy3Ql4RpuGX1gcnFS460wFe_Xw9rnZ07aE9DBvfqm_VIYBleQxi5Bml2w6WscStA76iRzC77P9DfucRbqufie-iV38oO3tvuEIZ0pvhOHHrl9-T40jp-78UFyvsinvQr7PFc5QUqsn4DozhrV2Gpi8c4JnDfg5tPNxfZ7Dk4xs9gwRSskdes0CCRy_htuRvsYitOcpQT78gErVqnU5csJb84l8rx7CkI-MbAJk8uusrG3Jcs8wTOcuHmhrOMU8PTXCyUO9ii4bkYnUmGRNjeZLZmNi3_QVZ4LcqYoH0Omcnx9oVfGOJGvN1VsEs9f8NaVz5r-su2jMFl2Aepr3Er8rhwg7dIek67cXVb4_g91NHWlaimJ7MiAMFort5zU8GobHM0Gzru1ntJxFZwG6hqjdz7ZsfO_jG_8-l3vwa-l43Du9tjoFuU8ya-zOWKtcuz4X4YRGJ4NwhYIGm-vbXBMGuze7hf1Hmv1wZpxu1yGVIzVpMIH5GoWDc9Air92aEYds13Lr3XElSvUNlv1FnJQRXD1bqFDQma99blHWz8qZSHRvc0Q4zZT3KMqMTaYr7RNieE2odZSa41GttfsPLUR05MPhU3ae8Z5hPi_CpR_urrrMGxI4sX6wmu-M6g8f14tSBHcF4r8xcGswOVi9m_ewvPoFh32HiIgGEVEbpsjrsYc5_R6uh1DTXwV7wCAA
&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2FPowerBIDemo2%2Findex.html
&state=fff39a6d-bbdb-4634-9e4b-7a326bc593cf%7Chttps%3A%2F%2Fanalysis.windows.net%2Fpowerbi%2Fapi
&client-request-id=8e5ae0ad-7d77-4508-905d-a865a32b324b
&x-client-SKU=Js
&x-client-Ver=1.0.13

**Comment by tushargupta51** [comment]
@aditya1984 Adal Js does not support confidential flows, it only supports implicit flow. Please use other flavors of adal to use code based flows.
