### ISSUE TITLE
Adal Issue in the CRM Outlook Client (1.0.13)

### ISSUE THREAD

**Issue by asc-pz** [AzureAD/azure-activedirectory-library-for-js#492]
Hello Folks,

i wrote a test adal solution for Dynamics CRM.
I am using the popup-mode since webresources are being displayed in iframes which do not work with adal.

Everything is working fine in all browsers as i have access to popupwindow.location.hash.
When i am using the CRM Outlook Client which is connected to a online crm organisation the hash is simply there. 
Once the redirect happens i see the crm login message "Login successful, loading application..." for a short period of time. 

I guess that CRM is redirecting the url internally (is the Outlook Client loosing its crm session ?) and in this step the hash gets lost.

Can you guide me ?

**Comment by tushargupta51** [comment]
@asc-pz I am not sure I understand the issue with adal here. I am not too familiar with CRM outllook client and how is it using adal Js. You might want to check with Outlook folks on this.

**Comment by asc-pz** [comment]
@tushargupta51  The CRM Outlook Client is a tool that is using the internet explorer internally for displaying crm and it's plugins ( which are in my case html and js files. ). The problem is that i dont get tokens in the outlook client but in the internet explorer. Seems like the outlook client redirects the "redirecturi" internally - in this step the hash gets lost. Is there any other option for me to get the token?

**Comment by tushargupta51** [comment]
@asc-pz Do you know if outlook client is using a hosted web browser or is it using IE in regular mode? I am  guessing its the former. If outlook client is updating the redirecturi in a way that removes the hash before processing it, then there is little that adal can do here. If it has processed the url before changing it then you can query the browser storage to get the token.

**Comment by tushargupta51** [comment]
Closing this issue since this seems to be related to how outlook client is handling the redirect uri.
