### ISSUE TITLE
Logout issue

### ISSUE THREAD

**Issue by shivguddadmath** [AzureAD/azure-activedirectory-library-for-js#497]
The config parameter extraQueryParameter is not passed to logout url. Which was causing issue with logout for policy specific authentications. 

Work around: You can use config parameter logOutUri.

I have fixed my local copy by adding below lines in logout function

`if (this.config.extraQueryParameter) {
              logout = this.config.extraQueryParameter;
}

 if (this.config.postLogoutRedirectUri) {
                logout += '&post_logout_redirect_uri=' + encodeURIComponent(this.config.postLogoutRedirectUri);
            }`

**Comment by tushargupta51** [comment]
@shivguddadmath `logOutUri`  is intended to be used when users want to override the default log out uri. `extraQueryParameter` is for login and acquireToken requests.

Also, the change that you have made is similar to setting the `logOutUri` with the same value as `extraQueryParameter` unless you wanted to do `logout += this.config.extraQueryParameter`

**Comment by shivguddadmath** [comment]
@tushargupta51  Yes I understand the purpose of logOutUri, but for somebody who dont wnat to know what is the full logout url. 
And my change is not same as logOutUri but is adding the extraQueryParameter to the logout url. Code looks like suggesting its same as assigning to logOutUri because the variable definition in the current code is bad (sorry not blaming anyone). I just added my lines to match that.
