### ISSUE TITLE
event is undefined in processHash function

### ISSUE THREAD

**Issue by tjuni2** [AzureAD/azure-activedirectory-library-for-js#500]
I've been getting the "Cannot read property 'preventDefault' of undefined" error occasionally (can't figure out when/why)  in the line that calls event.preventDefault(); of the processHash function in adal-angular.js (version 1.0.14).

**Comment by lukas-gmuer** [comment]
@tjuni2 in pr #498 
I did the most straightforward fix of this problem.

**Comment by whozDougie** [comment]
seems related to #518

**Comment by valera-rozuvan** [comment]
Fix for this is in PR https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/523 .

**Comment by rohitnarula7176** [comment]
fixed in dev
