### ISSUE TITLE
AADSTS50020 - Users cannot recover from this error

### ISSUE THREAD

**Issue by peternied** [AzureAD/azure-activedirectory-library-for-js#501]
We are building a web app that only allows members from a set of tenants, not a single tenant, access our site.  We've noticed a common user mistake, where they accidentally use their current computer credentials or Microsoft Account credentials.  This leads users to a "AADSTS50020" error page with the following error message:

    AADSTS50020: User account 'foo@bar.com' from identity provider   
    'https://sts.windows.net/{GUID1}/' does not exist in tenant '{Tenant}' 
    and cannot access the application '{GUID2}' in that tenant. The
    account needs to be added as an external user in the tenant first. Sign out and sign in again with a
    different Azure Active Directory user account.

However, they are never redirected back to our application, and they are also never provided with an option to sign out on this page.  For many of our users this is confusing as they do not know how to restart the workflow since now they are signed in and are no longer offered a disambiguation page anymore.

Is there a way to prevent this common user mistake from creating a dead end in our user login experience by including an option on that page to restart the workflow?

**Comment by rohitnarula7176** [comment]
@peternied In this particular scenario, AAD does not return a response and just shows the html page with the error as you have mentioned above. Hence, as a library we cannot detect this condition.

**Comment by peternied** [comment]
Is there any parameter or setting that this library provides that could affect how this error is handled?  How/where would I report this issue on the website?

**Comment by tushargupta51** [comment]
@peternied This is controlled by AAD. No configurable setting or parameter that the library can send to AAD.

**Comment by MNF** [comment]
@peternied see related https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/6795635-fix-error-aadsts50020-when-logged-in-user-doesn-t   and possible workaround by specifying the 'domain_hint' parameter https://www.stephenmann.net/single-post/2016/11/03/Fix-Azure-AD-Error-AADSTS50020-when-logged-in-user-doesnt-have-permissions-to-selected-Application

**Comment by peternied** [comment]
@MNF Thanks for the suggested work around, and the uservoice, I voted!

Unfortunately, for my applications experience, we support many different AAD domains in our site, so we cannot restrict down to a single one during the initial sign in experience.  If anyone hasn't been properly federated, or if they accidentally choose their personal account then they get this experience.

**Comment by sajagekar** [comment]
@MNF I have implemented the same and passing query param as domain_hint still it is not restricting the different tenant.
