### ISSUE TITLE
Access denied for the popUp window 

### ISSUE THREAD

**Issue by riakhetan** [AzureAD/azure-activedirectory-library-for-js#503]
I am receiving an access denied when the popup screen tries to access the Url of the window to compare it with the redirectUri, the website in the popup loads fine on its own and is authenticated but an access denied error is thrown and the screen does not even close.

**Comment by tushargupta51** [comment]
@riakhetan Can you please share more error details as to what is the exception trace? The popup window should be able to access the url of its own window.
