### ISSUE TITLE
Public method to get cached id_token

### ISSUE THREAD

**Issue by EgoAleSum** [AzureAD/azure-activedirectory-library-for-js#504]
I'm developing an application that needs to have the actual id_token JWT. When using ADAL, there's no public method to get the token, and I need to find "hacky" ways to retrieve that.

Is there any reason why it's not possible to implement a method that returns the raw JWT?

**Comment by tushargupta51** [comment]
There is a `getCachedToken(resource)` method you can use to get the raw token.
