### ISSUE TITLE
Missing possibility to configure response_type at login time

### ISSUE THREAD

**Issue by HJoost** [AzureAD/azure-activedirectory-library-for-js#506]
We use Adal.js together with ADFS 4.0. To get all claims we need to set the ?response_type=token id_token. But in adal.js line 200 it's hard coded to request only id_token:
var urlNavigate = this._getNavigateUrl('id_token', null)...

I changed this line to this._getNavigateUrl('token id_token', null) and everthing works fine now. Would it be possible to make an additional parameter in the config for that?

**Comment by tushargupta51** [comment]
@HJoost  You can use the adal.config.displayCall method to update the "response_type" value without modifying the adal code. Keep in mind that using "token id_token" will return both tokens in the url and will hit the url limit for some browsers and cause unexpected behavior.
