### ISSUE TITLE
_LoadFrameTimeOut never call Callback

### ISSUE THREAD

**Issue by DadvDadv** [AzureAD/azure-activedirectory-library-for-js#507]
Hi,

I was issuing the same pb than [this](https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/391) issue and i had to modify the adal source like this to make it work : 

```
AuthenticationContext.prototype._loadFrameTimeout = function (urlNavigation, frameName, resource) {
        //set iframe session to pending
        this.verbose('Set loading state to pending for: ' + resource);
        this._saveItem(this.CONSTANTS.STORAGE.RENEW_STATUS + resource, this.CONSTANTS.TOKEN_RENEW_STATUS_IN_PROGRESS);
        this._loadFrame(urlNavigation, frameName);
        var self = this;
        setTimeout(function () {
            var expectedState = self._activeRenewals[resource];
            if (self._getItem(self.CONSTANTS.STORAGE.RENEW_STATUS + resource) === self.CONSTANTS.TOKEN_RENEW_STATUS_IN_PROGRESS) {
                // fail the iframe session if it's in pending state
                self.verbose('Loading frame has timed out after: ' + (self.CONSTANTS.LOADFRAME_TIMEOUT / 1000) + ' seconds for resource ' + resource);
              
                if (expectedState && window.callBackMappedToRenewStates[expectedState]) {
                    window.callBackMappedToRenewStates[expectedState]('Token renewal operation failed due to timeout', null, 'Token Renewal Failed');
                }

                self._saveItem(self.CONSTANTS.STORAGE.RENEW_STATUS + resource, self.CONSTANTS.TOKEN_RENEW_STATUS_CANCELED);
            }
            else {
                window.callBackMappedToRenewStates[expectedState](null, self._getItem(this.CONSTANTS.STORAGE.ACCESS_TOKEN_KEY + resource), null);
            }

        }, self.CONSTANTS.LOADFRAME_TIMEOUT);
    }  
```

Without this modification, a call to a renewToken never call back the token for the first call (after, it's the cached token that is return).

Could you validate if i'm rigth ?

In the original code nothing happen if the renew have been done in less than 6 seconds.

I've moved this line :

`var expectedState = self._activeRenewals[resource];`

and add this bloc :

```
 else {
                window.callBackMappedToRenewStates[expectedState](null, self._getItem(this.CONSTANTS.STORAGE.ACCESS_TOKEN_KEY + resource), null);
            }
```

Thank's for looking for

**Comment by DadvDadv** [comment]
Well, i realise that for the first call i need to wait 6s to have the final token....
Then i decide to add a interval to wait fot the result, and define the timeout for... the timeout case :

```
AuthenticationContext.prototype._loadFrameTimeout = function (urlNavigation, frameName, resource) {
        //set iframe session to pending
        this.verbose('Set loading state to pending for: ' + resource);
        this._saveItem(this.CONSTANTS.STORAGE.RENEW_STATUS + resource, this.CONSTANTS.TOKEN_RENEW_STATUS_IN_PROGRESS);
        this._loadFrame(urlNavigation, frameName);
        var self = this;
        var interval = setInterval(function () {
            var expectedState = self._activeRenewals[resource];
            if (self._getItem(self.CONSTANTS.STORAGE.RENEW_STATUS + resource) === self.CONSTANTS.TOKEN_RENEW_STATUS_COMPLETED) {
                window.callBackMappedToRenewStates[expectedState](null, self._getItem(this.CONSTANTS.STORAGE.ACCESS_TOKEN_KEY + resource), null);
                clearInterval(interval);
                clearTimeout(timeout);
            }
        },
            20); //TODO : Add a constant

        var timeout = setTimeout(function () {
            if (self._getItem(self.CONSTANTS.STORAGE.RENEW_STATUS + resource) === self.CONSTANTS.TOKEN_RENEW_STATUS_IN_PROGRESS) {
                var expectedState = self._activeRenewals[resource];
                // fail the iframe session if it's in pending state
                self.verbose('Loading frame has timed out after: ' + (self.CONSTANTS.LOADFRAME_TIMEOUT / 1000) + ' seconds for resource ' + resource);

                if (expectedState && window.callBackMappedToRenewStates[expectedState]) {
                    window.callBackMappedToRenewStates[expectedState]('Token renewal operation failed due to timeout', null, 'Token Renewal Failed');
                }

                self._saveItem(self.CONSTANTS.STORAGE.RENEW_STATUS + resource, self.CONSTANTS.TOKEN_RENEW_STATUS_CANCELED);
                clearInterval(interval);
                clearTimeout(timeout);
            }

        }, self.CONSTANTS.LOADFRAME_TIMEOUT);
    }
```

**Comment by tushargupta51** [comment]
@DadvDadv When the token request is not completed in 6 seconds (the else block that you added), what do we gain by calling the callback method? The access token is going to be null.

I am not sure I understand your second approach of differentiating between first call and subsequent ones.

**Comment by DadvDadv** [comment]
Hi,
actualy this callback : 
`window.callBackMappedToRenewStates[expectedState](null, self._getItem(this.CONSTANTS.STORAGE.ACCESS_TOKEN_KEY + resource), null);`

is the one mapped with the callback define by the user to retrieve the token. 

without this callback , you never send the token to the user, so you always come to the timeout.

the "else" in my first try was to make a choice at the timeout end : 
1- is the state is inprogress ? => send timeout error
2 - is the state is done? => send the callback with the token

But like you see, you have to wait the 6s of timeout before you take this choice.

So I change my mind and i decide to look for the state every 20ms with a interval.
If the state change to done before the 6s, then i send the token to the user, else we are in the timeout case, i raise an error.

Hope it could help

**Comment by nickaranz** [comment]
I have a similar timeout issue when using adal.js on in a SPFx web part when and only when called from a SharePoint page. I posted more details here https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/391#issuecomment-290171562
