### ISSUE TITLE
Redirect Issue

### ISSUE THREAD

**Issue by alyssaw90** [AzureAD/azure-activedirectory-library-for-js#509]
I am having an issue getting the `redirectUri` to redirect to the page I specified after I login. 

```
adalProvider.init({
	  instance: 'https://login.microsoftonline.com/',
	  tenant: <tenant-name>,
	  clientId: <client-id>,
	  redirectUri: 'http://localhost:3000/admin/edit-event',
	  postLogoutRedirectUri: 'http://localhost:3000/admin/login',
	  anonymousEndpoints: [
		  '/'
		]
  	}, $httpProvider)
```

I login with my credentials, it then redirects for a second to the specified `redirectUri` then it goes back to the login page. It does login me, but it is not staying on the page I am trying to redirect to. I had to force it to redirect to the page with the following code: 

```
$scope.login = function() {
      adalService.login();
      window.location='/admin/edit-event'
    };
```
Has anyone else ran into this issue?

**Comment by wvanderdeijl** [comment]
We has something similar and used the solution from the [FAQ](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs) to have a different returnURL than the original app.  We had the normal index.html single page app with protected routes (even the default one which probably causes the issue). We then use `adal.html` as the return URL which is a very basic app that does not use protected routes. This catches the return from Azure AD and then redirects you back to the original URL automatically.
Not sure if you are hitting the same problem though.

**Comment by tushargupta51** [comment]
@alyssaw90 You can set the adal.config.navigateToLoginRequestUrl  to false if you dont want the users to go back to the page from where login started. It will take the user to redirecturi and stop.

**Comment by HofmT** [comment]
@tushargupta51 I tried that approach but after redirecting I get a blank response page and I need to manually refresh to see the content of my page.
I am using webpack, do you think it has something to do with that?

I appreciate any input. Thanks!

**Comment by ffigu002** [comment]
Why is this closed? I'm having the same issue as the original post
