### ISSUE TITLE
Is there an Angular(2) version planned?

### ISSUE THREAD

**Issue by HJoost** [AzureAD/azure-activedirectory-library-for-js#510]
Hi,

we are building an Angular2 solution with ADFS and an Cors API. Is it planned to support those solutions in the future?

There are several third party solutions, but none of them is working right and also these are very bad documented :-(

Best Regards
Helmut Joost

**Comment by tushargupta51** [comment]
Currently, we do not have any plans to add angular 2 support for adal. Refer to this for more info https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/194
