### ISSUE TITLE
Using Adal-Angular v14 is pushing requests through templateCache that shouldn't be

### ISSUE THREAD

**Issue by brphelps** [AzureAD/azure-activedirectory-library-for-js#511]
We've run into an issue in the latest version of adal-angular -- it looks like some code was added that funnels all requests through the template cache before issuing a request.

https://github.com/AzureAD/azure-activedirectory-library-for-js/commit/4ee94f715b02048dfe3c4acf4793ec005cef4eba

This change alters the behavior of decorators we've configured on the templateCache itself, and altogether it seems like a really strange way of accomplishing the goal. We currently accomplish something similar with a specific configuration of "endpoints":

endpoints: {
                ".html": null,
                ".json": null,
                "http://localhost:18922/": clientId,
            }

Can this change be reverted or accommodated for in a more elegant manner? I think it's reasonable that the template cache would expect not to be hit unless resolving a template.

**Comment by tushargupta51** [comment]
@brphelps The idea of adding the templateCache is that the requests that can be resolved using templateCache do not need a token as they are fulfilled on the client side itself.

What you have in endpoints is more a workaround to achieve something similar. What issues does it cause for you in the decorators?

**Comment by brphelps** [comment]
I wouldn't say it's a workaround -- it's a configuration driven solution that doesn't involve hitting the $templateCache at inappropriate times. 

In angular, $templateRequest is the only thing that uses $templateCache -- you're funneling more requests through $templateCache than previously were being sent there. For anyone writing decorators to $templateCache, this is surprising behavior (you're basically violating an expectation of the design of $templateCache and/or $templateRequest). 

I would suggest a configuration driven solution, perhaps a callback to evaluate whether or not a given endpoint requires a token -- This is much more flexible and less surprising than checking the templateCache directly.
