### ISSUE TITLE
Token renewal operation failed due to timeout 

### ISSUE THREAD

**Issue by richardspence** [AzureAD/azure-activedirectory-library-for-js#512]
I receive the token renewal operation failed due to timeout occasionally in a SPA that we have built.  

After some investigation we determined it wasn't due to network to ADAL (600ms), but we elapsed the 6s defined timeout due to our token handler endpoint loading >100 scripts via requirejs before execution of the `handleWindowCallback()`.  

Obviously there's work on our side to not do that, and to move the handleWindowCallback to as early as possible.  Given that, is it also possible that the load timeout be more precise in it's scope so that only ADAL network is taken into account?

**Comment by DadvDadv** [comment]
Hi, you probably could use my fix : [here](https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/507)

**Comment by whozDougie** [comment]
This issue is plaguing my solution too; using 1.0.14

**Comment by tushargupta51** [comment]
@richardspence  You can set the interval to a different value when you initialize adal

`adal.CONSTANTS.LOADFRAME_TIMEOUT = <>;`

**Comment by richardspence** [comment]
I'm aware of modifying the timeout, but was hoping to avoid it.  

Another solution would be to host the callback webpage on login.microsoft.com, and use window.postmessage to communicate back up to the parent.  That would avoid inconsistent client code implementations (like ours) and allow the SDK to control the entire process.
