### ISSUE TITLE
Token not refreshing silently: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by murtazajafferji** [AzureAD/azure-activedirectory-library-for-js#513]
I have followed all the setup steps from the readme and I have set `oauth2AllowImplicitFlow` to true.

The authentication is working, but the token fails to refresh silently. An hour after a user loads the page, if the user takes an action that makes an internal AJAX request, I see the following error in the browser console:

```
XMLHttpRequest cannot load
https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oaut…QxLWJmY2ItMjgzNmY3YTUzZjFmMjQ0ZjYwYWMtMTVhYi00NjIzLTliY2UtODA0MmE3ODMyZWY2.
No 'Access-Control-Allow-Origin' header is present on the requested
resource. Origin 'https://xxxxxxx.partners.extranet.microsoft.com' is
therefore not allowed access.
```

The user must refresh the browser in order to continue using the site.

**Comment by tushargupta51** [comment]
@murtazajafferji Are you making the AJAX request to AAD? In the error it seems an ajax request is sent to login.microsoftonline.com. Adal does not do that. And AAD does not allow cross domain ajax requets.

**Comment by murtazajafferji** [comment]
No, we're not making the AJAX request to AAD. The error comes when the app makes any AJAX request to our backend when the user's token has expired.

**Comment by mathilde-pellerin** [comment]
@rohitnarula7176 we face the exact same issue: we try to access our API by an ajax call, which is redirected to the login and kicked out by cross origin while we would expect to have a silent refresh of the token.
Can you explain why you closed this issue? Are we missing something obvious?

**Comment by m4m4m4** [comment]
I have the same issue

**Comment by ramakrpr** [comment]
Hi, anyone managed to fix this? can you let me know how?
I am running behind this issue since 2 weeks. My Scenario being the same, the AJAX calls fails with the error after an hour of inactivity and the calls to login.microsoft.com fails with the same error.

**Comment by gyanesh-gupta** [comment]
Is there any resolution or workaround yet. We faced the same issue sometime back

**Comment by gyanesh-gupta** [comment]
Is there any resolution or workaround yet. We faced the same issue sometime back

**Comment by screen-saksrepo** [comment]
I have the same issue

**Comment by TianyuHou** [comment]
same issue, anybody has solutions?

**Comment by abdullah14** [comment]
I am struggling with the same issue, have some found any solution?
