### ISSUE TITLE
Broken link in main README.md file

### ISSUE THREAD

**Issue by valera-rozuvan** [AzureAD/azure-activedirectory-library-for-js#514]
The link of **Claims in Azure AD Security Tokens** in file [README.md](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/README.md) points to [https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-scenarios%23claims-in-azure-ad-security-tokens](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-scenarios%23claims-in-azure-ad-security-tokens). When you navigate there, the site reports an error.

**Comment by rohitnarula7176** [comment]
Fixed.
