### ISSUE TITLE
Provide login_hint

### ISSUE THREAD

**Issue by cincue** [AzureAD/azure-activedirectory-library-for-js#517]
It would be helpful if you can include in the init of AuthenticationContext the login_hint param to pre-fill the username field of sign in page

**Comment by tushargupta51** [comment]
@cincue You can use `extraQueryParameter` property of adal config object something like `extraQueryParameter: "login_hint=<hint>"`. But remember the same hint will be used for acquire token requests also.

We need to make a change on our end to not add login_hint property if one is provided by user. I will add this to our next milestone.

**Comment by cincue** [comment]
Great @tushargupta51 ! My company will appreciate this.

**Comment by rohitnarula7176** [comment]
fixed
