### ISSUE TITLE
ADAL 1.0.14 issue in Firefox 51.0.1 "event is not defined"

### ISSUE THREAD

**Issue by whozDougie** [AzureAD/azure-activedirectory-library-for-js#518]
When I load adal 1.0.14 in Firefox, I get this error:

"Error: event is not defined
this.$get</n@https://localhost:44300/App/scripts/plugins/adal/1.0.14/adal-angular.min.js:2:2028
this.$get</m@https://localhost:44300/App/scripts/plugins/adal/1.0.14/adal-angular.min.js:2:1681
vf/this.$get</m.prototype.$broadcast@https://localhost:44300/Scripts/angular.min.js:147:483
sf/this.$get</</<@https://localhost:44300/Scripts/angular.min.js:116:239
vf/this.$get</m.prototype.$eval@https://localhost:44300/Scripts/angular.min.js:145:103
vf/this.$get</m.prototype.$digest@https://localhost:44300/Scripts/angular.min.js:142:165
vf/this.$get</m.prototype.$apply@https://localhost:44300/Scripts/angular.min.js:145:399
Bc/c/<@https://localhost:44300/Scripts/angular.min.js:20:455
h/<.invoke@https://localhost:44300/Scripts/angular.min.js:41:374
Bc/c@https://localhost:44300/Scripts/angular.min.js:20:376
Bc@https://localhost:44300/Scripts/angular.min.js:21:163
ge@https://localhost:44300/Scripts/angular.min.js:19:484
@https://localhost:44300/Scripts/angular.min.js:315:135
x.Callbacks/c@https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.2.min.js:4:26031
x.Callbacks/p.fireWith@https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.2.min.js:4:26840
.ready@https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.2.min.js:4:3303
q@https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.2.min.js:4:715."

![image](https://cloud.githubusercontent.com/assets/11555622/23851731/a4326734-0838-11e7-8e82-217bd5c7d560.png)

The issue doesn't appear on Chrome or IE11.

Anyone else come across this before?

**Comment by tutujohngeorge** [comment]
I've got the same issue as well....a new method processHash was created in 1.0.14, which has the following code: 
event.preventDefault();

Firefox doesnt detect the event first time around; hence it's throwing a error. You can just pass the event parameter in processHash method to resolve this error.

![image](https://cloud.githubusercontent.com/assets/20303714/23866955/c272b58e-07f0-11e7-934d-786be0d88b97.png)

![image](https://cloud.githubusercontent.com/assets/20303714/23866978/d1e86284-07f0-11e7-9961-359d2daf8896.png)

**Comment by whozDougie** [comment]
@tutujohngeorge Thanks, that seemed to have gotten rid of that issue.

**Comment by whozDougie** [comment]
Think this issue is related to #500

**Comment by valera-rozuvan** [comment]
Fix for this is in PR https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/523 .

**Comment by tushargupta51** [comment]
Dup of #500
