### ISSUE TITLE
"Some of your tests did a full page reload!" when running Karma/Jasmine

### ISSUE THREAD

**Issue by justinzhong-honeywell** [AzureAD/azure-activedirectory-library-for-js#519]
Hi team,

I have an AngularJS (1.5) app which uses adal-angular for AD authentication.

There appears to be an issue when running Karma/Jasmine unit tests with the following error:

"Some of your tests did a full page reload!"

It appears that when the test is ran with a controller that is protected, the authentication check kicks in and eventually the following code snippet is been invoked inside adal.js:

```
    /**
     * Redirect the Browser to Azure AD Authorization endpoint
     * @param {string}   urlNavigate The authorization request url
     */
    AuthenticationContext.prototype.promptUser = function (urlNavigate) {
        if (urlNavigate) {
            this.info('Navigate to:' + urlNavigate);
            window.location.replace(urlNavigate);
        } else {
            this.info('Navigate url is empty');
        }
    };
```

I have currently applied a minor change and passed in the Angular's abstracted $window so that come when testing I can mock/spy/debug without that page reload error.

Would it be possible to consider passing some form of abstraction for the native global window object rather than directly referencing it which makes testing a bit difficult.

Thanks!

**Comment by tushargupta51** [comment]
@justinzhong-honeywell Can you share the change you made?
