### ISSUE TITLE
$stateChangeStart is not firing

### ISSUE THREAD

**Issue by sujameslin** [AzureAD/azure-activedirectory-library-for-js#521]
Its not working with angular-ui-router v1.0, because its depending on `$stateChangeStart` event of $rootScope. 

In angular-ui-router v1.0, `$stateChangeStart` is deprecated, DISABLED and replaced by Transition Hooks as of version 1.0 ([detail](https://ui-router.github.io/guide/ng1/migrate-to-1_0#state-change-events))

Would you guys please update following ui-router library change?

**Comment by tushargupta51** [comment]
@sujameslin  This is going to be a major change for us as this affects people who are relying on stateChange* events being handled by adal library. I will add this to future milestone and update the issue once we have more concrete plan on this.

**Comment by jmprieur** [comment]
@sujameslin do you know if ADAL.js 1.0.15 fixed your issue?
