### ISSUE TITLE
[Adal.js + ADFS] Can't get IdToken and AccessToken at once.

### ISSUE THREAD

**Issue by valera-rozuvan** [AzureAD/azure-activedirectory-library-for-js#525]
Right now it seems not possible to request both, an IdToken and an AccessToken at the same time. Why do we need to do this? Because we are working with Active Directory Federation Services (ADFS), and it expects both tokens at the same time when dealing with a remote API. For example, right now the Adal.js library creates the following request:

```
https://win-hd0pj7763ke.rootforest.local/adfs/oauth2/authorize?response_type=token&client_id=ab65c6e3-01bc-4b05-901f-e9b26455bba0&resource=web&redirect_uri=http%3A%2F%2Fwin-745b8imkd9d%2Fui%2Findex.html&state=4b0cf95d-4745-4f65-af66-2171793c6748%7Cweb&&scope=openid&client-request-id=f9a29128-eaca-4386-8828-0b2a7e579a90&x-client-SKU=Js&x-client-Ver=1.0.14&prompt=none&login_hint=spetrovich%40rootforest.local&domain_hint=rootforest.local
```

and this does not work. If we modify it to contain **response_type=id_token+token** and **nonce=XXXXXXXXXXXXXXXXXX**, like so:

```
https://win-hd0pj7763ke.rootforest.local/adfs/oauth2/authorize?response_type=id_token+token&client_id=ab65c6e3-01bc-4b05-901f-e9b26455bba0&resource=web&redirect_uri=http%3A%2F%2Fwin-745b8imkd9d%2Fui%2Findex.html&state=4b0cf95d-4745-4f65-af66-2171793c6748%7Cweb&&scope=openid&client-request-id=f9a29128-eaca-4386-8828-0b2a7e579a90&x-client-SKU=Js&x-client-Ver=1.0.14&prompt=none&login_hint=spetrovich%40rootforest.local&domain_hint=rootforest.local&nonce=XXXXXXXXXXXXXXXXXX
```

then ADFS accepts it.

Currently, we initialize Adal.js like so:

```
adalProvider.init({
    instance: 'https://WIN-HD0PJ7763KE.RootForest.local/',
    tenant: 'adfs',
    clientId: '2d7b469a-f8d8-47fc-95b1-00bfc0b405d7',
    extraQueryParameter: 'scope=openid',
    endpoints: {
      'sp_proxy': '00000002-0000-0000-c000-000000000000'
    }
  },
  $httpProvider
);
```

Looking at the Adal.js demos, we can't find an example of communicating with a remote API using Adal.js. For example, https://technet.microsoft.com/en-us/windows-server-docs/identity/ad-fs/development/single-page-application-with-ad-fs has the **Web Application** and **API** on the same machine.

Are we missing something? Or should the Adal.js library be modified in order for it to request IdToken and AccessToken at the same time?

**Comment by valera-rozuvan** [comment]
I have forked this repository, and create a commit which fixes the problem described in this issue. You can see it at https://github.com/valera-rozuvan/azure-activedirectory-library-for-js/commit/38aa00c35757e69b614eeff637ceadcc2acb4cdb . Can you please look over it, and provide feedback as to what else needs to be done in order for this change to land in the main Adal.js repository?

**Comment by valera-rozuvan** [comment]
@tushargupta51 , @rohitnarula7176 What do you think?

**Comment by rohitnarula7176** [comment]
@valera-rozuvan  We cannot add the response_type = 'id_token token" as part of the library as it might run the risk of hitting the authorization url limit. Moreover the purpose of login is just to establish user context by requesting an id_token. Adding the ability to request an access token for a resource at the time of login, might lead to a situation where the developer does not have permissions to access the resource and in that case the library would not be able to return an id_token as well. That said, if you have a single resource that you need an access token for at the time of login, you can still achieve this by adding the following code snippet to the displayCall property of the adal's config object. This will override the default login code of the library.
```
 adalProvider.init(
                {
                    displayCall: function (urlNavigate) {
                        var instance = self.AuthenticationContext.prototype._singletonInstance;
                        var resource = "https://rohit1.onmicrosoft.com/ToGoAPI";
                        instance.config.state = instance.config.state + '|' + resource;
                        instance._saveItem(instance.CONSTANTS.STORAGE.STATE_LOGIN, instance.config.state);
                        urlNavigate = instance._getNavigateUrl('id_token token', resource) + '&nonce=' + encodeURIComponent(instance._idTokenNonce);
                        window.location.replace(urlNavigate);
                    }
                },
                $httpProvider
            );
```
Closing this issue. Please try the above workaround and feel free to reopen the issue if this does not work for you.
