### ISSUE TITLE
can't catch adal:loginSuccess when not using popup

### ISSUE THREAD

**Issue by aline-almeida** [AzureAD/azure-activedirectory-library-for-js#530]
I have an angularjs SPA with ui.router.
in my module config I have:
```
        $locationProvider.html5Mode(true).hashPrefix('!');
        $urlRouterProvider.otherwise('/');
        $stateProvider
          .state('welcome', {
              url: '/',
              template: '<div><button type=\"button\" class=\"btn btn-primary\" ui-sref=\"login\"><i class=\"fa fa-sign-in\"></i>&nbsp;&nbsp;Login</button></div>',
          })
            .state('login', {
                url: '/login',
                template: '<h4> logging in ... </h4>',
                controller: 'LoginController',
                controllerAs: 'vm',
                requireADLogin: true
            })
            .state('loggedin', {
                url: '/loggedin',
                templateUrl: '/app/logged-in.html',
                requireADLogin: true
            })
            .state('logout', {
                url: '/logout',
                template: '<h4> logging out ... </h4>',
                controller: 'LogoutController'
            }) ;
       adalProvider.init(
       {
           instance: 'https://login.microsoftonline.com/',
           tenant: 'mytenant.onmicrosoft.com',
           clientId: 'myappid',           
           extraQueryParameter: 'nux=1',
           popUp: true,
           cacheLocation: 'localStorage' // enable this for IE, as sessionStorage does not work for localhost.
       },
       $httpProvider
       );
```

in LoginController:
```
    function loginController($rootScope, $state, adalService) {
        /* jshint validthis:true */
        var vm = this;
        vm.title = 'login';
        vm.activate = activate;
        activate();
        function activate() {
            adalService.login();
        }
        $rootScope.$on('adal:loginSuccess', function (event, token) {
            console.log('loggedin');
            $state.go('loggedin');
        });
    }
```

if I remove the popUp setting, I can't catch the adal:loginSuccess and so I always get back to default state (welcome screen).
Also, I know I can set the redirectUri, but I'm not sure how to do it. I've tried with http://myappurl/loggedin, trying to trigger the loggedin state, but it doesn't work.
Thanks

**Comment by rohitnarula7176** [comment]
@aline-almeida If you do not specify a redirectUri, the default value is taken as window.location.href which I guess will be your welcome page according to your app settings. You are not able to catch the loginSuccess event because login controller does not execute when you get redirected back to your welcome page. To catch the event, you can add the following piece of code after your init method.
```
app.run(['$rootScope', 'adalAuthenticationService', function ($rootScope, adalProvider) {
    $rootScope.$on("adal:loginSuccess", function (event, errorDesc, error) {

    });

    }]);
'''
or you can add a controller to your state 'welcome' similar to how you added one for state 'login' and you should be able to catch the event in that controller.

**Comment by aline-almeida** [comment]
@rohitnarula7176, I added a controller to the welcome state, but I can't seem to catch the event there. I can catch it in the app.run, but I've given up on that because the screen would flicker, showing welcome state and then going to loggedin state.  
Can you give me a hint on how to set the redirectUri in this scenario ? Thanks

**Comment by rohitnarula7176** [comment]
@aline-almeida Is it possible for you to send me your code sample so I can look into this?

**Comment by aline-almeida** [comment]
Sure @rohitnarula7176 ! Check it here:
https://1drv.ms/u/s!AlBevQQ5u1azkI4agMd2FickgQM6uA

**Comment by rohitnarula7176** [comment]
@aline-almeida I tried to run your code but could not compile it. Is it possible for you to deploy your app with non-minified versions of adal js and send me the url for it. I can then debug this further. We can also have a skype session and go over this.

**Comment by aline-almeida** [comment]
Hi @rohitnarula7176 , I find it strange that you cannot compile my code, I just ran it.  You just need to restore packages (nuget & npm) and change    `tenant: 'xxxxx.onmicrosoft.com',  clientId: 'xxxxxxxxx'  `in app.config.js. Let me know if this gets you runnig the demo app.

**Comment by rohitnarula7176** [comment]
@aline-almeida In your index.html, where you specify the ng-app, replace that line with the one below to catch the 'adal:loginSuccess' event. 
<div class="row body-content" ng-app="app" ng-controller="welcomeCtrl" ng-strict-di>

**Comment by aline-almeida** [comment]
I'm sorry @rohitnarula7176 , I'm not sure I get your point. 
You mean replacing this: `<div class="row body-content" ng-app="app" ng-strict-di>` ? With what ? Can you please provide a snippet ? Thanks

**Comment by rohitnarula7176** [comment]
@aline-almieda In the div that you wrote  just add another attribute ng-controller="WelcomeController" attribute next to ng-app="app".

**Comment by aline-almeida** [comment]
Hi @rohitnarula7176 !
I think you may have some issue with your comment, because some of the lines are not showing...
Anyway, I added the WelcomeController to the ng-app, as you suggested, with no luck. 
You got it working ?

**Comment by antoniocvaraujo1** [comment]
@aline-almeida , Oi Aline. Tudo bem ? estou tendo o mesmo problema que você. Estou usando angular 1.6 .Pode ajudar ? obrigado.

**Comment by aline-almeida** [comment]
Olá António!
Eu mudei entretanto para o Angular 4, mas envio-te o último teste que fiz. Não esquecer de no AD, adicionar a Reply URL http://localhost:<porta>, ativar o   "oauth2AllowImplicitFlow": true ( no manifest)
[adaljs_LATEST - Teste Adal1.0.15 _uiRouter1.0.6.zip](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/1634377/adaljs_LATEST.-.Teste.Adal1.0.15._uiRouter1.0.6.zip)
