### ISSUE TITLE
Can't call adalAuthenticationService.acquireToken

### ISSUE THREAD

**Issue by pwombwa** [AzureAD/azure-activedirectory-library-for-js#531]
Hi,

Am trying to call **adalAuthenticationService.acquireToken("https://graph.microsoft.com")** to retreive an access token from Ms Graph but the I keep on getting the folowing error:

![image](https://cloud.githubusercontent.com/assets/7061532/24449497/52384f50-146f-11e7-8123-98059b480189.png)

Am building an outlook addin in with angularJS and it references **office.js** version 1.1.0.12

**Comment by rohitnarula7176** [comment]
@pwombwa The one thing I want to point out is that acquireToken method takes 2 parameters, resource and a callback function and you are just providing one parameter to it. Can you try passing a callback function as a second parameter and see if your issue gets resolved. 
'''
.adalAuthenticationService.acquireToken("https://graph.microsoft.com",function(errorDesc,token,error{
});
'''

**Comment by rohitnarula7176** [comment]
@pwombwa Closing this issue for now. Please let me know if you have further questions.
