### ISSUE TITLE
CustomEvent constructor not supported in IE11

### ISSUE THREAD

**Issue by amareshbAtMicrosoft** [AzureAD/azure-activedirectory-library-for-js#534]
I see in adal.js, the following code where CustomEvent constructor is being used. But as I understand this is not supported in IE11. Please look here - http://caniuse.com/#search=customevent
====================================================================
AuthenticationContext.prototype._onPopUpHashChanged = function (hash) {
        var evt = new CustomEvent('adal:popUpHashChanged', { detail: hash });
        window.dispatchEvent(evt);
    };

**Comment by rohitnarula7176** [comment]
@amareshbAtMicrosoft Thank for pointing this out. We will make the change for this in our next release.

**Comment by rohitnarula7176** [comment]
Fixed in dev
