### ISSUE TITLE
Token renewing

### ISSUE THREAD

**Issue by oaicstef** [AzureAD/azure-activedirectory-library-for-js#535]
Hi,
because of a company requirement I need to disable the Auto Token renewing but I don't find a parameter to do that.

**Comment by rohitnarula77** [comment]
@oaicstef I am assuming you are using the adal-angular wrapper. If you navigate to a protected route , the library will check for a token in the cache and if it does not find it, it will attempt to renew the token. If you don't want your route to be protected, you can set the requireADLogin: false for that route as follows:
```
$routeProvider.
    when("/todoList", {
        controller: "",
        templateUrl: "",
        requireADLogin: false
    });
```

**Comment by rohitnarula7176** [comment]
@oaicstef I am assuming you are using the adal-angular wrapper. If you navigate to a protected route , the library will check for a token in the cache and if it does not find it, it will attempt to renew the token. If you don't want your route to be protected, you can set the requireADLogin: false for that route as follows:
```
$routeProvider.
    when("/todoList", {
        controller: "",
        templateUrl: "",
        requireADLogin: false
    });
```
