### ISSUE TITLE
ui-router's ui-sref + adal = return to the page your on.. not the page your going to..

### ISSUE THREAD

**Issue by jhandel** [AzureAD/azure-activedirectory-library-for-js#536]
I seem to have found an issue.. If I click on a link using ui-sref for a page that requires authentication then after authentication I return to the page I started at (not the page I want to go to).. I have confirmed that the issue is that adal.login.request is not storing my target page but my origination page.

If I manually type the URL in for the authenticated page then I do go to that page after login.. So I am pretty sure it has to how state is being handled vs. what ever step stores adal.login.request in the login pipeline.

Thanks
Josh

**Comment by rohitnarula7176** [comment]
@jhandel Thank you for pointing out this issue. It is now fixed in dev.
