### ISSUE TITLE
iOS browsers not able to login

### ISSUE THREAD

**Issue by lnalepa** [AzureAD/azure-activedirectory-library-for-js#538]
https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/18852925-ios-using-safari-chrome-firefox-not-able-to-get-ad

**Comment by rohitnarula7176** [comment]
@lnalepa Would you be able to share a code snippet for the repro for this issue.

**Comment by danieldobalian** [comment]
@rohitnarula7176 it's this sample code: https://identity.microsoft.com/Docs/Web
