### ISSUE TITLE
Adaljs iFrames downloading script bundles multiple times

### ISSUE THREAD

**Issue by validian** [AzureAD/azure-activedirectory-library-for-js#539]
We have an application using HTML5/angular front end and ASP.NET back end running on Azure. Our application uses adaljs to retrieve a number of auth tokens for the different services that we need access to. We are running into an issue that shows up primarily in Edge but can occasionally be reproduced in other browsers (Chrome, Firefox) where the browser in the developer tools shows multiple copies of our scripts. See the image below to see what I am talking about (in Edge): 
![dupfiles](https://cloud.githubusercontent.com/assets/4553904/24927989/aad4d886-1eb5-11e7-8245-d05ccc37c145.JPG)
Chrome shows what should be happening: 
![chromenodupfiles](https://cloud.githubusercontent.com/assets/4553904/24928005/bdfebd50-1eb5-11e7-8871-d083f1c3702e.JPG)

This shows up when adaljs creates an iFrame and navigates to get a token the redirects back to our homepage. When the iFrame redirects back to our homepage it re-downloads all our scripts. We have not been able to figure out a way to prevent the scripts from being re-downloaded and because of the duplicate scripts our site is having performance issues and other bugs.

when we init our adal provider these are the settings that we set:
clientId, endpoints, extraQueryParameter= "nux=1", popUp=false, requireADLogin=true, tenant.

Any help would greatly appreciated!

**Comment by jrwpatterson** [comment]
I have this problem too its very annoying I now have on the service that is waiting for the token this line of code as a work around:

`        this.$rootScope.$on("adal:acquireTokenSuccess", () => this.start(true));`

`    public start = (killIframe: boolean = false) => {
        if (killIframe) {
            let element = angular.element("[id^=adalRenew]")[0];
            if (element) {
                element.remove()
            }
        }
}`

**Comment by validian** [comment]
Thanks for the idea, we were able to resolve a different way though. Basically setup a login angular module then handled redirects manually checking session storage to see if we are authenticated.

**Comment by rohitnarula7176** [comment]
@jrwpatterson In adal , Looking at the snap, I am assuming your redirectUri is set to your app's root page. In that case, when token renewal happens in an iframe, the entire app gets re-loaded in the iframe but since the scripts have already been loaded, it should not try to download them again. It seems like a browser issue to me. In your workaround, you delete the iframe on token success which is something we do not do in our code. But the scripts would have already been re-downloaded before you deleted the iframe. Can you explain how deleting the iframe resolves your problem?

**Comment by rohitnarula7176** [comment]
@jrwpatterson closing the issue for now. Please reopen if you still face issues.

**Comment by ramesh-chandra** [comment]
I am also facing the same issue of multiple js files. Because of this issue, we are getting the issue in executing a 10 sec timer in a page.  The timer callback method is executing in (10/# of file copy) sec. I am able to repro this issue always. 
Could you please help me in fixing this issue.

**Comment by chetanc97** [comment]
@validian  @ramesh-chandra  . Yes . Try this out. Here's how  - 
Put a redirect.html file and add this

`  <script src="../lib/angular/angular.min.js"></script>`
`    <script src="../lib/adal/adal.js"></script>`
`    <script src="../lib/adal/adal-angular.js"></script>`

`<script type="text/javascript">`
`        var adalConfig = {`
`             instance: 'https://login.microsoftonline.com/',`
`             tenant: 'neudesic.onmicrosoft.com',`
`            clientId: 'abcd',`
`            cacheLocation: 'localStorage'`
`       };`
`        var authContext = new AuthenticationContext(adalConfig);`
`        authContext.handleWindowCallback();`

 `       if (window === window.parent) { window.location.replace(location.origin + location.hash); }`
`    </script>`

Cheers !
