### ISSUE TITLE
Status of Adal.js project

### ISSUE THREAD

**Issue by valera-rozuvan** [AzureAD/azure-activedirectory-library-for-js#540]
**Adal.js** library is a very awesome project. However, recently (in the past 6 months) we, the users, see little progress on the project. Issues do not get responses from developers, new releases do not come out, commits are very rare.

I think everyone from Adal.js community would like to know where this is heading. Is this project discontinued? What are the future plans for Adal.js?

If this project **REALLY IS** abandoned by Microsoft - can we fork it, and continue development in a separate actively maintained repository?

**Comment by rohitnarula7176** [comment]
@valera-rozuvan We have been hands down working on other projects and hence not being able to respond to issues reported in the last month or so. We will look into them starting next week.

**Comment by valera-rozuvan** [comment]
Thx! Looking forward to see Adal.js improve :)
