### ISSUE TITLE
adal-angular does not expose AuthenticationContext

### ISSUE THREAD

**Issue by jhandel** [AzureAD/azure-activedirectory-library-for-js#541]
I am trying to do some logic via displayCall in angular. However because the AuthenticationContext is not available via the angular module adalAuthenticationService I can't call AuthenticationContext.promptUser() or AuthenticationContext._loginPopup()...  Please add the AuthenticationContext to the service created by adalAuthenticationService.

**Comment by jhandel** [comment]
Another option (which is more down in the guts of adal.. Would be to enhance displayCall to not just include a URL but also include the AuthenticationContext.

**Comment by rohitnarula7176** [comment]
@jhandel You can still call displayCall by setting the displayCall function in the adalProvider.init method as follows:
```
 adalProvider.init(
        {
           instance: 'https://login.microsoftonline.com/',
            clientId: '',
            popUp: true,
            callback: function (error, token) {
            },
            displayCall: function (urlNavigate) {
            }
        },
        $httpProvider
        );
```
The init provider takes a config object where you set your clientID, redirectUri, e.tc. If you set displayCall on the config object as shown below, you can use inject your custom logic. Also if you want to call loginPopup, you just set popUp:true in the config object as shown above.
Please let me know if you have any other questions.

**Comment by rohitnarula7176** [comment]
@jhandel I am closing this issue for now. Please reopen the issue if you still face any problems after the following the above mentioned solution.
