### ISSUE TITLE
adal.js requires idtoken even for implicit grant flow where it's not needed

### ISSUE THREAD

**Issue by zeevm** [AzureAD/azure-activedirectory-library-for-js#545]
acquireToken() will not work if there's no 'user' object which was extracted from an idToken. To obtain an Idtoken adal will go through interactive login.

There are however legitimate flows of obtaining access tokens to other services that don't require idToken, I'm working on a SPA that is rendered in some O365 service.

My app needs to obtain access tokens to some services, it uses implicit grant flow and the assumption is the user is already logged into O365 (since the app is launched from within a O365 service) and so the browser has a valid AAD session cookie.

In this case adal should be able to silently obtain the access token I require even if it doesn't have an idToken for my client id (which I do not require) and indeed it does it if I use the debugger to set the 'user' object of adal auth context to anything other the null (thus passing the check in acquireToken).

This should be configurable, I don't want my SPA iframe to get redirected to AAD login where it's not required at all, nor can it do it since AAD won't allow login and consent screens in an iframe to fend off clickjacking attacks.

So I'm forced to open a new window for login where it's not even required.

**Comment by brentschmaltz** [comment]
@zeevm can you help us understand this a bit: since the app is launched from within a O365 service)

Are you on multiple tabs in a browser?

**Comment by zeevm** [comment]
Single tab, O365 service (say Onenote) in that tab, Onenote create an iframe within their tab and renders my app which adds some functionality to Onenote.

**Comment by rohitnarula7176** [comment]
@zeevm I agree its possible for you to obtain an access_token without having a signed in  user. This is because you have a valid session with AAD. But the library is designed in way where we need more control over the context as in we expect the user to sign in from the same single page app before he tries to acquire a token for a resource. We cannot make the user check configurable.

**Comment by rohitnarula7176** [comment]
Thank you for your pull request but as discussed, the library is not designed to have the user check configurable. Closing the issue for now. Please reopen if you have further questions.
