### ISSUE TITLE
changes in 1.0.14 with navigateToLoginRequestUrl interferes with logging a user in

### ISSUE THREAD

**Issue by dhodgin** [AzureAD/azure-activedirectory-library-for-js#546]
We had been using 1.0.11 for the last year or so and have recently upgraded to 1.0.14 and we have noticed that after doing that when we are redirected back from Microsoft, adal will reload the page and redirect to the original route the user left from to authenticate with Microsoft

This creates a couple problems...

One, on the client side we don't seem to have any specific way to wait for adal to finish doing its thing and then take the token and pass it along in a POST request to our server to log a user in. We cannot listen for adal:loginSuccess because that event is broadcast before the final redirect is done. This can result in POSTing to login on our server side before adal redirects and that cancels the login request and the user just ends up being told they have to login again after adal redirects them after broadcasting loginSuccess. the full page reload creates a race condition when we are trying to POST to our login route with the token. If we send that POST request just before ADAL redirects, it cancels the login POST and then redirects and sits there saying you have to login again even though you have a token and are authenticated with Microsoft.

right now if we set navigateToLoginRequestUrl to false it won't redirect but then we have another problem. The query string before leaving to authenticate is not preserved. When we are on mydomain.com/?q=foo and we click to authenticate with Microsoft, when we return, the querystring of q=foo is lost. It is stored in the sessionStorage as adal.login.request though.

I'm not sure what our best course of action is here. I'm thinking we should stick with navigateToLoginRequestUrl:false to avoid race conditions with login POST, and then client side before posting, grab the query string back out of sessionStorage and apply it to the POST request referer header before sending the POST. but that seems very ugly and hacky.

because navigateToLoginRequestUrl does not redirect back to the url we were on before leaving the page, when we post to our server side login route, the referer is missing the query string parameters.

It seems to be here in adal-angular.js
```
// resetting the hash to null
if ($location.$$html5) {
  $location.hash('');
}
```

Here is the typical flow of url and it should better explain what I mean:
visit mydomain.com/?q=foo
login with Microsoft button clicked, user authenticates
returned to mydomain.com/#id_token=eyJ0eXAiO...MbVsbQNHWjQ&state=1fd2b1ce...ebd373&session_state=4001afbc....9cef88
redirected to mydomain.com/#
sessionStorage: adal.login.request contains mydomain.com/?q=foo
POST to login, referer is mydomain.com/ NOT mydomain.com?q=foo

The client and server have no knowledge of any previous querystring parameters.

**Comment by rohitnarula7176** [comment]
@dhodgin I apologize for the late response. You are facing this problem because AAD does not preserve the query string parameters in the redirect response. You will have to stick to navigateToLoginRequestUrl:false and use the hack you mentioned above to solve this problem. We cannot do anything for this case in the library.

**Comment by dhodgin** [comment]
Our workaround was to store our own sessionStorage value which is the value of $location.url() before redirection. Similar to adal.login.request but that is the entire url. It's much easier to store the path+query because then it can be easily passed back in to $location.url() later to redirect without a full page reload.

**Comment by rohitnarula7176** [comment]
Please use the above workaround if you face this issue. Closing this issue for now.
