### ISSUE TITLE
 #! location introduced in Angular 1.6 causes adal.js to redirect incrorrectly

### ISSUE THREAD

**Issue by navyasric** [AzureAD/azure-activedirectory-library-for-js#551]
Angular 1.6 introduced '#!' as default prefix in URLs. See details here: https://docs.angularjs.org/guide/migration#migrating-from-1-5-to-1-6

This is interfering with how adal.js resolves the redirect URL. It is appending the id token to the URL and messing up the redirect. As a result, after completing the sign-in, user is redirected to the wrong location and the browser displays id token in URL.
This can be reproduced by adding ADAL.js to the angular-seed project. https://github.com/angular/angular-seed

**Comment by tomidix** [comment]
This can be 'solved' by setting the default $location hash-prefix to '', because the angular's default $location hash-prefix has been changed to '!' in v1.6.
`$locationProvider.html5Mode(false).hashPrefix('');`

**Comment by rohitnarula7176** [comment]
@navyasric Please use the above mentioned fix as mentioned by @tomidix in your app.js to resolve this issue. Closing the issue for now. Please reopen if you face further issues.
