### ISSUE TITLE
Release the source maps for adal.min.js and adal-angular.min.js

### ISSUE THREAD

**Issue by mmckenz** [AzureAD/azure-activedirectory-library-for-js#553]
Please generate and release the source map files for the minified versions of adal.js and adal-angular.js.

**Comment by jmprieur** [comment]
Hi @mmckenz . What do yo mean? I thought that source map files were only for TypeScript. msal.js is written in TypeScript, but ADAL.js is plain JavaScript. can you please explain what is your problem so that we help ?

**Comment by mmckenz** [comment]
The source map files I'm referring to have nothing to do with TypeScript. I'm talking about source map files for minified JavaScript that would allow one to map from the minified versions (ex. adal.min.js) to the un-minified original versions (ex. adal.js).

Here are some additional details on source maps:
https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

Releasing the source map allows users of your JS library to reference the minified version (maintaining all the benefits of referencing minified JS files) while still being able to debug against the un-minified code. A browser's debugging tools handles the mapping between minified and un-minified source using the provided source map.

JQuery is a good example of a library that releases their source map so consumers can reap these benefits:
https://code.jquery.com/jquery-3.2.1.js
https://code.jquery.com/jquery-3.2.1.min.js
https://code.jquery.com/jquery-3.2.1.min.map

Angular is another example:
https://code.angularjs.org/1.6.4/angular.js
https://code.angularjs.org/1.6.4/angular.min.js
https://code.angularjs.org/1.6.4/angular.min.js.map

I suspect there is a mechanism to generate this source map as part of the minification process. I'm asking for you to output this source map file as part of your build and release it along side your minified and un-minified JS files.

I expect to find the following files for an ADAL-JS release:
adal.js
adal.min.js
adal.min.map (missing today)
adal-angular.js
adal-angular.min.js
adal-angular.min.map (missing today)

Without the source maps, debugging against the minified ADAL-JS source is an unpleasant experience.

**Comment by jmprieur** [comment]
Thanks for this quick answer, @mmckenz .
I'll add that to the backlog.

**Comment by sameerag** [comment]
All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We would recommend to move to `msal js` for any advanced feature asks.
