### ISSUE TITLE
Register for error events using ADAL-Angular

### ISSUE THREAD

**Issue by RehanSaeed** [AzureAD/azure-activedirectory-library-for-js#556]
Is there some way we can hook into an event to get errors from adal-angular? 

E.g. I'd like to be notified of a the error below, so I can show a friendly error message to the user explaining the problem which is that the user has disabled third party cookies and was unable to access my site:

> AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com).

**Comment by rohitnarula7176** [comment]
@RehanSaeed 
You can register for the following events in your controller.
'''
$rootScope.$on("adal:acquireTokenFailure", function (event, errorDesc, error) {

    });
   $rootScope.$on("adal:acquireTokenSuccess", function (event, tokenOut) {

   });
'''

**Comment by jmprieur** [comment]
Closing since the question was answered. @RehanSaeed, feel free to re-open if you need more information
