### ISSUE TITLE
_supportsSessionStorage does not return correct values

### ISSUE THREAD

**Issue by AlexUrbanAc** [AzureAD/azure-activedirectory-library-for-js#558]
The description of _supportsSessionStorage (and _supportsLocalStorage) declare what values to expect:

**Returns true if browser supports sessionStorage, false otherwise.**

However, the value returned is neither always correct, nor always a boolean.

I am not sure whether this is the most recent version, so let me show the code I mean (sessionStorage, but the same holds for localStorage):

    AuthenticationContext.prototype._supportsSessionStorage = function () {
        try {
            var supportsSessionStorage = 'sessionStorage' in window && window['sessionStorage'];
            if (supportsSessionStorage) {
                window.sessionStorage.setItem('storageTest', '');
                window.sessionStorage.removeItem('storageTest');
            }
            return supportsSessionStorage;
        } catch (e) {
            return false;
        }
    };

- It does indeed return false, but never true, because supportsSessionStorage contains the session object. While the value returned is truthy, I think that you should return the type that one expects after reading the documentation.
- You never test whether the written value can be read again. If the storage's getItem method does return null instead of the value just written, like Edge does, the _supportsLocalStorage method still returns a truthy value.

The corrected code should be like this (localStorage, but the same holds for sessionStorage):

    AuthenticationContext.prototype._supportsLocalStorage = function () {
		try {
			if(!window.localStorage) return false; // Test availability
			window.localStorage.setItem('storageTest', 'A'); // Try write
			if(window.localStorage.getItem('storageTest') != 'A') return false; // Test read/write
			window.localStorage.removeItem('storageTest'); // Try delete
			if(window.localStorage.getItem('storageTest')) return false; // Test delete
			return true; // Success
		} catch (e) {
			return false;
		}
    };

**Comment by rohitnarula7176** [comment]
Fixed in dev.
