### ISSUE TITLE
increase oauth token expiry

### ISSUE THREAD

**Issue by ahadjiGladiator** [AzureAD/azure-activedirectory-library-for-js#563]
I believe the default is 1 hour, how can I increase it to 24 hours?

**Comment by pwalecha** [comment]
I believe you'll need to set the TokenPolicy for your AAD tenant and then associate with your application ID.
https://stackoverflow.com/questions/31162257/azure-oauth-how-to-change-token-expiration-time

**Comment by rohitnarula7176** [comment]
@ahadjiGladiator  token expiry is not configurable using the library. Closing this issue for now.
