### ISSUE TITLE
Renew token problem 

### ISSUE THREAD

**Issue by BadiuAlexandru** [AzureAD/azure-activedirectory-library-for-js#566]
I followed this example https://www.spjeff.com/2016/05/05/video-secure-webapi-with-azuread/ step by step, login works well but when I want to send a request to my API, I get the following error https://ibb.co/dWNHfv , can somebody help me? because in the given example it works well, and there are no differences between the sample
![capture](https://cloud.githubusercontent.com/assets/15923709/26777995/0c8c28ec-49e8-11e7-84b8-06f1f43a911a.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15923709/26778088/741d5de6-49e8-11e7-9e4e-9854059980ec.PNG)

 and my project

**Comment by angerwin** [comment]
is already known and fixed. See ticket  #543

**Comment by rohitnarula7176** [comment]
@BadiuAlexandru This issue is already fixed in dev. Closing this issue for now. Please reopen if you are still facing issues.

**Comment by BadiuAlexandru** [comment]
the problem is angular version... if you use angular 1.6 error still exists, if I downgrade to angular 1.5 it works well
