### ISSUE TITLE
Angular (2/4) Support?

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/azure-activedirectory-library-for-js#568]
Hello - what's the status of using ADAL in [Angular](https://angular.io/)?  I found [this blog post](https://blogs.msdn.microsoft.com/premier_developer/2017/04/26/using-adal-with-angular2/) and it looks like there's no official library at this point, is that correct?  Is one being worked on?

Thanks!

**Comment by denyo** [comment]
Duplicate of #194?

**Comment by spottedmahn** [comment]
yes, thanks @denyo, closing the issue
