### ISSUE TITLE
Logout redirect doesn't work for an Office Add-in

### ISSUE THREAD

**Issue by brandonkoch6** [AzureAD/azure-activedirectory-library-for-js#571]
I'm using the ADAL.js library to log users in through my Excel Add-in.  Login works fine and is redirected back to my application perfectly via the '/id_token'.  However, when a user logs out, a redirect does not occur back to the application within Office.  The redirect does occur in a native browser such as Chrome, just not in my Excel Add-in.  This seems like a strange discrepancy in behavior, and I'm having difficulty debugging it as it works perfectly in a native browser.  Does ADAL.js lack support for this within applications that host browsers such as Office Add-ins?

**Comment by jmprieur** [comment]
@brandonkoch6 : did you set the "Logout URL" property in your application settings in AAD?

**Comment by brandonkoch6** [comment]
@jmprieur Yes, I set a logout URL.  It redirects just fine in a native browser.  However, when the web app is hosted within Microsoft Excel as an Add-in, the redirect after logout doesn't occur.  It does redirect successfully on logging in from within the Excel Add-in.

**Comment by Hongbo-Miao** [comment]
I believe the reason causing this issue and the solution is same with the question you asked here https://stackoverflow.com/questions/44509900/how-to-use-addhandlerasync-from-office-js-with-angular/44730110#44730110

**Comment by jmprieur** [comment]
Closing this question which is answered on Stackoverflow see link above
