### ISSUE TITLE
requireADLogin without routing?

### ISSUE THREAD

**Issue by shahjinesh11** [AzureAD/azure-activedirectory-library-for-js#575]
It works fine with routing but I am not using ngRoute in my application. 

then how can i handle requireADLogin in .config?

**Comment by rohitnarula7176** [comment]
@shahjinesh11 The library requires ng-route or ui.router to handle requireADLogin. Thats the only way for us to know whether the route is protected and requires a token.

**Comment by jmprieur** [comment]
Closing as by design
@shahjinesh11 : did you try to use ADAL.js with plain JavaScript (without Angular?)

**Comment by shahjinesh11** [comment]
With Plain JavaScript, its working fine. But I wanted to use with angular only.

Thanks for the help.
