### ISSUE TITLE
adal:loginSuccess event does'nt fire until trying to move away to another page.

### ISSUE THREAD

**Issue by johnkattenhorn** [AzureAD/azure-activedirectory-library-for-js#58]
I'm pretty inexperienced with AngularJS so if I've done something wromg please forgive me; given this code snippet:

  $scope.signIn = function () {
    adalService.login();
   };

  $scope.signOut = function () {
    adalService.logOut();
  };

  // optional
  $scope.$on("adal:loginSuccess", function () {
    adalUserSvc.setUser();
  });

  // optional
  $scope.$on("adal:loginFailure", function () {
    adalUserSvc.loginFailure();
  });

  // optional
  $scope.$on("adal:notAuthorized", function (event, rejection, forResource) {
    adalUserSvc.notAuthorized(event, rejection, forResource);
  });

  $scope.$on("adalUserSvc:signedInChanged", function (event, args) {
    $scope.signedIn = adalUserSvc.info.signedIn;
    $scope.username = adalUserSvc.info.username;
  });

I find that the loginSuccess event does fire until I try to move away from this controller / view. I fell like I should have 'then' command after the login function call to make it update or something. Have I missed something simple ?

**Comment by omercs** [comment]
I am closing this. Please open if you repro.
