### ISSUE TITLE
AADSTS16000: Request is ambiguous: multiple user identities are available for the current request.

### ISSUE THREAD

**Issue by RobinHerbots** [AzureAD/azure-activedirectory-library-for-js#580]
Hi all,
Sometimes I got the error above and I can't recover from it by calling the logout on the authenticationcontext.  It happens when switching users, but I didn't yet found a clear path to reproduce the error.  

There seems not much info about this exact error on google.  So maybe someone can clarify?

**Comment by mike-nelson** [comment]
I've struck the same issue when signing in a second user. I think due to the way ADAL.js uses cookies, this library isn't able to handle multi-identify.

I am wondering if doing a signOut before switching users will fix this.

**Comment by mike-nelson** [comment]
I found logOut is required if you are trying to do a multi-identity app. I tried making multiple instances of ADAL (and giving them unique IDs in localStorage and unique iframeIDs) but the backend was confused - you can be signed in with two accounts at once but it throws an error getting the access_token.

Also I modified logOut to so it doesn't redirect the current window, since I didn't want to navigate away from my single page cordova app.

**Comment by petinho** [comment]
Hi
I'm having exactly the same behaviour when I'm signed in with two different accounts.
Im using the adal-angular4 wrapper, but the problem is the same. When I call login, the following screen appears to select an account:
![image](https://user-images.githubusercontent.com/9249768/37403201-4b405c78-278e-11e8-8b23-6b1038234e62.png)
I select the account and get the token correctly.
After this, if I call acquireToken I receive the following error:
`AADSTS70002: Error validating credentials. AADSTS16000: Request is ambiguous: multiple user identities are available for the current request.`

But if I sign out and "forgive" the account that's not needed, the previous account selection window is not appearing, and acquiretoken works...
![image](https://user-images.githubusercontent.com/9249768/37403427-247578ac-278f-11e8-82ce-eb88cbdd2d90.png)
Am I doing something wrong?

**Comment by alxsj** [comment]
Hi,
Same scenario, same error for me (with adal-angular5). Did you find a fix or workaround for this ?

**Comment by VenkateshLakamana** [comment]
Hello,
Did anyone find a solution for this?

**Comment by dabutvin** [comment]
Running into this issue when trying to use `prompt=none` parameter and I get a failure

 AuthenticationFailed. interaction_required

**Comment by petinho** [comment]
Hi
It's working for me now. I think my problem was that adal couldn't add the login hint.
On my profile I'm not getting the "upn" claim, and the following function doesn't add the login hint:

`    /**
     * Adds login_hint to authorization URL which is used to pre-fill the username field of sign in page for the user if known ahead of time.
     * domain_hint can be one of users/organisations which when added skips the email based discovery process of the user.
     * @ignore
     */
    AuthenticationContext.prototype._addHintParameters = function (urlNavigate) {
        // include hint params only if upn is present
        if (this._user && this._user.profile && this._user.profile.hasOwnProperty('upn')) {`

            // don't add login_hint twice if user provided it in the extraQueryParameter value
            if (!this._urlContainsQueryStringParameter("login_hint", urlNavigate)) {
                // add login_hint
                urlNavigate += '&login_hint=' + encodeURIComponent(this._user.profile.upn);
            }

            // don't add domain_hint twice if user provided it in the extraQueryParameter value
            if (!this._urlContainsQueryStringParameter("domain_hint", urlNavigate) && this._user.profile.upn.indexOf('@') > -1) {
                var parts = this._user.profile.upn.split('@');
                // local part can include @ in quotes. Sending last part handles that.
                urlNavigate += '&domain_hint=' + encodeURIComponent(parts[parts.length - 1]);
            }
        }

        return urlNavigate;
    }`

Tryed to chante the `upn` for the `email` claim (in my case they're both the same), and it started working. Both login_hint and domain_hint were added:

`/**
     * Adds login_hint to authorization URL which is used to pre-fill the username field of sign in page for the user if known ahead of time.
     * domain_hint can be one of users/organisations which when added skips the email based discovery process of the user.
     * @ignore
     */
    AuthenticationContext.prototype._addHintParameters = function (urlNavigate) {
        // include hint params only if upn is present
        if (this._user && this._user.profile && this._user.profile.hasOwnProperty('email')) {`

            // don't add login_hint twice if user provided it in the extraQueryParameter value
            if (!this._urlContainsQueryStringParameter("login_hint", urlNavigate)) {
                // add login_hint
                urlNavigate += '&login_hint=' + encodeURIComponent(this._user.profile.email);
            }

            // don't add domain_hint twice if user provided it in the extraQueryParameter value
            if (!this._urlContainsQueryStringParameter("domain_hint", urlNavigate) && this._user.profile.email.indexOf('@') > -1) {
                var parts = this._user.profile.email.split('@');
                // local part can include @ in quotes. Sending last part handles that.
                urlNavigate += '&domain_hint=' + encodeURIComponent(parts[parts.length - 1]);
            }
        }

        return urlNavigate;
    }`

P.D: Code is from v 1.0.15

**Comment by jason2211** [comment]
I also ran into this issue when attempting to access the application when signed on as two different users.

Using the concepts provided by @petinho, I modified the adal.js to use UPN if available then fall back to email.  Below is the code if anyone else needs it.  I can also submit this as a pull request, just let me know.

```
    /**
     * Adds login_hint to authorization URL which is used to pre-fill the username field of sign in page for the user if known ahead of time.
     * domain_hint can be one of users/organisations which when added skips the email based discovery process of the user.
     * @ignore
     */
    AuthenticationContext.prototype._addHintParameters = function (urlNavigate) {
        // include hint params only if upn or email is present
        if (this._user && this._user.profile && (this._user.profile.hasOwnProperty('upn') || this._user.profile.hasOwnProperty('email'))) {
            var loginHint;
            if (this._user.profile.hasOwnProperty('upn'))
                loginHint = this._user.profile.upn;
            else
                loginHint = this._user.profile.email;

            // don't add login_hint twice if user provided it in the extraQueryParameter value
            if (!this._urlContainsQueryStringParameter("login_hint", urlNavigate)) {
                // add login_hint
                urlNavigate += '&login_hint=' + encodeURIComponent(loginHint);
            }

            // don't add domain_hint twice if user provided it in the extraQueryParameter value
            if (!this._urlContainsQueryStringParameter("domain_hint", urlNavigate) && loginHint.indexOf('@') > -1) {
                var parts = loginHint.split('@');
                // local part can include @ in quotes. Sending last part handles that.
                urlNavigate += '&domain_hint=' + encodeURIComponent(parts[parts.length - 1]);
            }
        }

        return urlNavigate;
    }
```

**Comment by rdkleine** [comment]
As a workaround I've added the 'login_hint' to the config extraQueryParameter. This seems to work ok.
```
    // Add login_hint based on cached user
    var context = new AuthenticationContext(config);
    var user = context.getCachedUser();
    if (user) {
        context.config.extraQueryParameter = 'login_hint=' + user.userName;
    }
```

**Comment by asifma** [comment]
> I also ran into this issue when attempting to access the application when signed on as two different users.
> 
> Using the concepts provided by @petinho, I modified the adal.js to use UPN if available then fall back to email. Below is the code if anyone else needs it. I can also submit this as a pull request, just let me know.
> 
> ```
>     /**
>      * Adds login_hint to authorization URL which is used to pre-fill the username field of sign in page for the user if known ahead of time.
>      * domain_hint can be one of users/organisations which when added skips the email based discovery process of the user.
>      * @ignore
>      */
>     AuthenticationContext.prototype._addHintParameters = function (urlNavigate) {
>         // include hint params only if upn or email is present
>         if (this._user && this._user.profile && (this._user.profile.hasOwnProperty('upn') || this._user.profile.hasOwnProperty('email'))) {
>             var loginHint;
>             if (this._user.profile.hasOwnProperty('upn'))
>                 loginHint = this._user.profile.upn;
>             else
>                 loginHint = this._user.profile.email;
> 
>             // don't add login_hint twice if user provided it in the extraQueryParameter value
>             if (!this._urlContainsQueryStringParameter("login_hint", urlNavigate)) {
>                 // add login_hint
>                 urlNavigate += '&login_hint=' + encodeURIComponent(loginHint);
>             }
> 
>             // don't add domain_hint twice if user provided it in the extraQueryParameter value
>             if (!this._urlContainsQueryStringParameter("domain_hint", urlNavigate) && loginHint.indexOf('@') > -1) {
>                 var parts = loginHint.split('@');
>                 // local part can include @ in quotes. Sending last part handles that.
>                 urlNavigate += '&domain_hint=' + encodeURIComponent(parts[parts.length - 1]);
>             }
>         }
> 
>         return urlNavigate;
>     }
> ```

if using vue-adal (https://github.com/survirtual/vue-adal). Please add this modification into:
vue-adal\lib\bundle.js

**Comment by sameerag** [comment]
All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We would recommend to move to `msal js` for any advanced feature asks. 

This issue should be fixed with `msal js` and we recommend moving to the new library.

**Comment by Macro21** [comment]
In my case just IE11 faill with this error.

The fix for me was that IE11 need this extra config: 

![image](https://user-images.githubusercontent.com/24574303/83254268-cf265a00-a1ae-11ea-823f-be89c4a2a792.png)
