### ISSUE TITLE
SessionStorage lost when add STS site and reply URL in different security zone in IE and Edge

### ISSUE THREAD

**Issue by MSRY** [AzureAD/azure-activedirectory-library-for-js#582]
When use IE and Edge, add either one of STS site and reply URL into trust sites cause SessionStorage lost after use sign in and redirect back.
In Internet Explorer technical blogs, then mentioned “We most often see this problem with cookies, but technically, this could happen in any case where storage is partitioned by zone. For instance, the web browser cache is partitioned by Zone, as are the HTML5 sessionStorage and localStorage areas”

**Comment by rohitnarula7176** [comment]
@MSRY If session storage is lost during zone switching, it is a browser issue and the library cannot do anything to resolve it. Please take this up with the IE/Edge team.
