### ISSUE TITLE
Enforce password re-entry after token expiry

### ISSUE THREAD

**Issue by dgodwin1175** [AzureAD/azure-activedirectory-library-for-js#583]
I've had problems with the infinite refresh loop when using this library with the ui-router.  Even on the latest version I cannot get this to work, despite trying all of the suggested workaround solutions.

As a fallback plan, what I want to do is to redirect the user back to the azure login screen to re-enter their password, whenever their token expires (after 1 hour).  This is actually a preferable solution for us, as it is slightly more secure.

The trouble I'm having though, is that whenever I detect a token expiry, I call the login() method, but this appears to silently renew the token without the user having to log back in.
I notice that if I delete everything in the local storage cache, and try to access a secured route in my app, login() will also auto-renew the token.
I find if I clear the "cookies and other site data" (using Chrome settings), then this will redirect to the login screen, but how can I achieve the same, after adal.js detects that the token has expired?

Big thanks for any help!

**Comment by jmprieur** [comment]
I believe that cookies are storied both for your apps and for Azure AD. When you use the Chrome command, you delete the cookies everywhere, but the code in the app does not have right to delete (or read) cookies for another isolated storage (Azure AD's). This is by browser's design and for security and privacy reasons. Therefore I don't think you can do programmatically.
Did you try with ADAL.js 1.0.5?

**Comment by jmprieur** [comment]
Closing for now (the question is answered). Feel free to reopen;
