### ISSUE TITLE
Can i check if this library will be affected when MS apply this change?

### ISSUE THREAD

**Issue by trandinhnam** [AzureAD/azure-activedirectory-library-for-js#584]
I found that MS will change change on azure tls.
Anyone can help me to check whether this change will impact our library?
https://blogs.msdn.microsoft.com/azuresecurity/2017/06/12/azure-tls-certificate-changes/

Regards,
Hai Do

**Comment by jmprieur** [comment]
@trandinhnam : this should not. the libraries don't do certificate pinning.
