### ISSUE TITLE
adalservice.AcquireToken() failing for the first call

### ISSUE THREAD

**Issue by VimalKallem** [AzureAD/azure-activedirectory-library-for-js#585]
Am using active directory to authenticate user.
Here ng2-adal module is used to get active directory token.

Am  facing following issues with acquiring token through ng2-adal module.
•	AdalService.AcquireToken(resource) method gets timed out for the first time before token is stored in local storage.
-	Error Message - Token renewal operation failed due to timeout
•	Data binding to the component is breaked in middle
•	Some times it throws unspecified error without being catched in under catch statement 

can some help me in acquiring AAD token.

**Comment by jmprieur** [comment]
Hello @VimalKallem 
We only have an implementation of ADAL.js for Angular 2 - and we have requests for supporting Angular 2 and Angular 4.
The Microsoft identity team did not produce ng2-ada and we don't support l. 
I suggest you post an issue in their GitHub repository https://github.com/alenny/angular2-adal-example/issues
