### ISSUE TITLE
Authentication too slow for multiple endpoins.

### ISSUE THREAD

**Issue by makromat** [AzureAD/azure-activedirectory-library-for-js#587]

**Comment by makromat** [comment]
Hi There,

I have 6 endpoints and when user is not signed in ADALjs is gonna open up 6 iframes with current page (for each endpoint one).  This is big perfomance issue. Website is really slow and all my assets are downloaded 6 times. 
Is possible to avoid creating iframes per each endpoint? 
Is there any other workaround?
Thanks a lot

**Comment by dzhavat** [comment]
I face the same problem. It's very bad for performance!

Luckily, I just found this in the [Wiki](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs). Haven't tried it yet but seems like a some kind of solution.

**Comment by rohitnarula7176** [comment]
@makromat You can register a separate redirectUri other than your app's root page to avoid multiple reloads and increase performance. Iframe creation is by design and we cannot avoid it. Please refer to the wiki for instructions on how to achieve this.

**Comment by makromat** [comment]
thanks I did it. better now.
