### ISSUE TITLE
Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException when accessoing sharepoint through adal.js

### ISSUE THREAD

**Issue by russgove** [AzureAD/azure-activedirectory-library-for-js#589]
Hi,
I’m trying to use adal.js from an outlook add-in to read  items from a SharePoint online  list. When I issue my get request to read the listitems, I keep getting a 401 error with a ‘x-ms-diagnostics’ header that says ‘3000003;reason="Invalid audience Uri 'f8f8d2ad-7c9d-4aac-80eb-3f00a263c879'.";category="invalid_client".

The full text of the response is ::
`HTTP/1.1 401 Unauthorized
Content-Length: 123
Server: Microsoft-IIS/10.0
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
WWW-Authenticate: Bearer realm="6fe49e6a-6255-4ee0-b4e7-a8e3357dc55f",client_id="00000003-0000-0ff1-ce00-000000000000",trusted_issuers="00000001-0000-0000-c000-000000000000@*,https://sts.windows.net/*/,00000003-0000-0ff1-ce00-000000000000@90140122-8516-11e1-8eff-49304924019b",authorization_uri="https://login.windows.net/common/oauth2/authorize"
x-ms-diagnostics: 3000003;reason="Invalid audience Uri 'f8f8d2ad-7c9d-4aac-80eb-3f00a263c879'.";category="invalid_client"
SPRequestGuid: 9401049e-00dd-3000-1cb8-1ecdd1037ce1
request-id: 9401049e-00dd-3000-1cb8-1ecdd1037ce1
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
SPRequestDuration: 15
SPIisLatency: 2
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.6628
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
X-MSEdge-Ref: Ref A: 26F3949C7ECD453E936D93B713C4AD9A Ref B: BLUEDGE0911 Ref C: Mon Jul 10 12:14:17 2017 PST
Date: Mon, 10 Jul 2017 19:14:16 GMT

{"error_description":"Exception of type 'Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException' was thrown."}
`

I have registered my application id in azure-ad and given it permission to read and write items in all sitecollections (under both Application Permissions and Delegated Permissions), and edited the manifest to enable implicit flow. 

My adal.config looks like this:
`const adalConfig: adal.Config = {
 
  clientId: 'f8f8d2ad-7c9d-4aac-80eb-3f00a263c879',
  tenant: 'common',
  extraQueryParameter: 'nux=1',
  endpoints: {
    'https://mytenant.sharepoint.com': 'f8f8d2ad-7c9d-4aac-80eb-3f00a263c879'
  },
  postLogoutRedirectUri: window.location.origin,
  cacheLocation: 'sessionStorage',
  popUp: false,
  navigateToLoginRequestUrl:false

};

export default adalConfig;

`

The add-in (written in typescript) is currently running in my local desktop development environment (localhost:3000). And the source code looks like this: 

import * as React from 'react';
import { Button, ButtonType } from 'office-ui-fabric-react';
import { Header } from './header';
import { HeroList, HeroListItem } from './hero-list';
import * as pnp from 'sp-pnp-js';
import * as adal from 'adal-angular';
export interface AppProps {
    title: string;
}
import adalConfig from '../AdalConfig';
import { IAdalConfig } from '../../IAdalConfig';
export interface AppState {
    listItems: HeroListItem[];
    loading: boolean;
    error: string;
    signedIn: boolean;
}

export class App extends React.Component<AppProps, AppState> {
    debugger;
    private authCtx: adal.AuthenticationContext;
    constructor(props, context) {
        super(props, context);
        debugger;
        this.state = {
            listItems: [],
            signedIn: false,
            error: '',
            loading: false,
        };
        const config: IAdalConfig = adalConfig;
        this.authCtx = new adal(config);
        window['Logging'] = {
            level: 10,
            log: function (message) {
                console.log('ADAL MESSAGGE ' + message);
            }
        };
        
        if (!this.authCtx.isCallback(window.location.hash)) {
            this.authCtx.login();
        } else {
            console.log('user is ' + this.authCtx.getCachedUser().userName);
            this.authCtx.handleWindowCallback();
            this.authCtx.acquireToken('f8f8d2ad-7c9d-4aac-80eb-3f00a263c879', (error, token) => {
                if (error) {
                    console.log(error);
                    return;
                }
                let myHeaders = new Headers();
                myHeaders.append('Authorization', 'Bearer ' + token);
                let myInit = {
                    method: 'GET',
                    headers: myHeaders,
                    mode: 'cors' as RequestMode,
                    cache: 'default' as RequestCache
                };
                fetch("https://mytenant.sharepoint.com/cboxTest/_api/web/lists/getByTitle('ideas')/items", myInit).then((response) => {
                    debugger;
                    console.log('GOT WEBw ' + response);
                }).catch((error) => {
                    console.log('Error: ' + error);
                    debugger;
                });
            });
        }
    }
    
    render() {
        debugger;
        if (this.authCtx.loginInProgress()) {
            return <div>logging in , please wait.</div>
        }
        return (
            <div>logged in as {this.authCtx.getCachedUser().userName}</div>
        );
    };
};

I read elsewhere that I needed to decode the jawt token to see what the audience was. I did that and sure enough the audience was  f8f8d2ad-7c9d-4aac-80eb-3f00a263c879. I don’t know what that is telling me. Is it supposed to be something different? How do I change it?

I am getting valid tokens, and the ui shows that the user is logged in, but I keep getting that AudienceUriValidationFailedException exception. Anybody have any ideas how to fix this?

**Comment by jmprieur** [comment]
@russgove : are you sure that 'f8f8d2ad-7c9d-4aac-80eb-3f00a263c879' is the resource ID of the SharePoint API you want to call? this seems more like an AppId to me.

I've found this article on using ADAL.js with SharePoint: http://www.andrewconnell.com/blog/adal-js-cors-with-o365-apis-files-sharepoint. It's not very recent, but might help you?

Proposing to close this issue as external. Feel free to re-open if you disagree. you might want request help from https://stackoverflow.com with tags adal, JavaScript and SharePoint?

**Comment by jmprieur** [comment]
A colleague just told me that SharePoint only supports Url-based Resource requests and only validates when the Tenant Url is the Audience.
@russgove you are using the App Guid, which can work to request a Token in AAD, but it doesn’t mean that the Resource accepts it.
