### ISSUE TITLE
[B2C] postLogoutRedirectUri should also have an extraParams config

### ISSUE THREAD

**Issue by smil2k** [AzureAD/azure-activedirectory-library-for-js#592]
When using adal.js with Azure B2C, the post logout redirect works only if the profile was also included using "p=". 

Therefore as with login, it should be possible to add this parameter also using simple comfiguration.

**Comment by sameerag** [comment]
All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We would recommend to move to `msal js` for any advanced feature asks. 

Can you please raise this as a feature ask in `msal js`?
