### ISSUE TITLE
AAD infinite redirect loop - Microsoft Edge 40.15063.0.0

### ISSUE THREAD

**Issue by vule017** [AzureAD/azure-activedirectory-library-for-js#597]
Some of our users are experiencing an **infinite redirect loop** in Microsoft Edge during authentication. This issue just cropped up today. It appears to be primarily effecting users with Edge version 40.15063.0.0. Other browsers don't exhibit the same behavior and work fine. 

As some have suggested, we tried updating the **cacheLocation to 'localStorage'** under adalAuthenticationServiceProvider.init(), however, the problem still persists.

If we have the user add the site to the list of "trusted sites" under **Control Panel > internet options** on their machine, everything works again.

Our application is build using AngularJs v1.6.6 with adaljs 1.0.14

Any thoughts or advice would greatly be appreciated!

**Comment by rohitnarula7176** [comment]
@vule017 This is a known issue with this particular version of Edge. It is a browser issue and not a bug with the library. It should work in all other browsers and older versions of Edge.

**Comment by Vivihung** [comment]
@rohitnarula7176 Do you have the issue item tracking on Edge side. such as a bug/issue log in https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/?
Edge team said they take user votes/feedback in account when prioritize work items. If we have bug track there, all the AAD dev hit this issue can help to vote to push for a fix.
