### ISSUE TITLE
ReferenceError during testing on PhantomJS

### ISSUE THREAD

**Issue by pdimitratos** [AzureAD/azure-activedirectory-library-for-js#599]
Hello,

I'm using WebPack for testing a React/Redux single page app and I encountered a Reference Error on line 177 of adal.js during test initialization. PhantomJS may not be initializing the window object early enough. I did find that the reference error can be avoided by validating that the window has been defined before attempting to set Logging: [these changes](https://github.com/AzureAD/azure-activedirectory-library-for-js/compare/dev...pdimitratos:dev) allow my tests to run as expected, though I don't know whether the change could have undesirable side effects.

**Comment by rohitnarula7176** [comment]
@pdimitratos Thank you for your contribution. I have merged your changes.
