### ISSUE TITLE
scope claim not received by backend after user has consented and until he logs out once (using acquireTokenPopup or acquireTokenRedirect)

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/azure-activedirectory-library-for-js#603]
**Repro steps:**
1. Clone https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof.git
2. Create the AzureAD apps and modify the code. For this:
-  open PowerShell 
- from the folder where you cloned the repo, 
```
cd AppCreationScripts
```
- from this folder, run the following PowerShell snippet (after replacing yourPassword, youLogin and yourTenant)
```PowerShell
secpasswd = ConvertTo-SecureString "yourPassword" -AsPlainText -Force
$mycreds = New-Object System.Management.Automation.PSCredential (“yourlogin@yourtenant.onmicrosoft.com”, $secpasswd)
. .\Cleanup.ps1 -Credential $mycreds
. .\Configure.ps1 -Credential $mycreds
```
Note that if the user you login with exists (as a guest for instance) in several Azure AD tenant you will need to also find the tenant Id you are interested in (DirectoryId property in the Properties of the Azure Active Directory in the Azure portal), and use the full syntax
```PowerShell
. .\Cleanup.ps1 -Credential $mycreds -TenantId "yourTenantIdGuid"
. .\Configure.ps1 -Credential $mycreds -TenantId "yourTenantIdGuid"
```

3. Open the Visual Studio solution, and in the solution's context menu, choose "Set Startup Projects". 
- select "Start" for the 3 projects

4. In Visual Studio Debug | Start without debugging
5. In the brower, try to interact with the TodoListSPA.
- sign-in
- when requested to access the TodoListService-OBO, choose the user and accept the consent

**Expected**
This just works

**Actual**
Once you have accepted the consent, the backend no longer receive the scope claim, and therefore there the backend sends an error
(The Scope claim is not found)
![image](https://user-images.githubusercontent.com/13203188/28874315-a7b0cbd0-7791-11e7-8143-2d33ded8f735.png)

**User Work around**
This only happens the first time a user interact with the application. Then once the user has logged out and logs-in again, this does no longer happen.

**Comment by danieldobalian** [comment]
JM & I looked into this and the scope isn't coming back in the token. Either an app configuration issue or service, unlikely related to the library. Will continue investigating.

**Comment by rohitnarula7176** [comment]
@jmprieur @danieldobalian I can confirm that this is not a bug with the library.

**Comment by jmprieur** [comment]
@rohitnarula7176 do you have ideas of if we can change the code to have a better behavior? maybe signout the user before re-calling acquireToken with the claims ?
