### ISSUE TITLE
unable to logout using adal angular

### ISSUE THREAD

**Issue by vishalwalke** [AzureAD/azure-activedirectory-library-for-js#608]
I am facing the problem with ADAL logout. Azure AD is not redirecting to logout url when user logging out the current session. After logout it is redirecting to Azure logout screen and not to the given redirect url. Also its not clearing the cookies from the browser.

So next time when user attempts to access the application it is directly taking to the application without asking login credentials and using credentials from cookies. One user can see other users details without logging in. It might leads to security issues.

public get AdalConfig(): any {
        return {
            tenant: environment.tenant,
            clientId: environment.clientId, 
            redirectUri: https://localhost:4200,
            postLogoutRedirectUri: 'https://login.microsoftonline.com/<TenantId>/oauth2/logout?post_logout_redirect_uri=https://localhost:4200'
        };

**Comment by aciccarello** [comment]
Why are you using a `postLogoutRedirectUri` that contains `post_logout_redirect_uri=https://locahost:4200`? Do you intend for it to return to localhost after logging out?

**Comment by vishalwalke** [comment]
yes. 
I wnt to redirect to localhost on login screen 
I am above configrations are for development purpose. "https://localhost:4200" will be replaced by my actual app url hosted on azure.

**Comment by jmprieur** [comment]
Closing as duplicate of #617
