### ISSUE TITLE
TypeScript declaration

### ISSUE THREAD

**Issue by rosieks** [AzureAD/azure-activedirectory-library-for-js#61]
It would be nice if you could provide TypeScript declaration files for adal.js and adal-angular.js

**Comment by panesofglass** [comment]
:+1:

**Comment by omercs** [comment]
That is something new to me. I will look at that in detail and send them a pull request.

**Comment by htryggva** [comment]
+1
This would be awesome

**Comment by zsmorris** [comment]
+1
Surprising that this doesn't yet exist.

**Comment by Supratentorial** [comment]
+1 Would be very helpful.

**Comment by gustavgahm** [comment]
+1

**Comment by weinong** [comment]
+1

**Comment by tedvanderveen** [comment]
With Typescript 1.5 released and all the ES6 and AngularJS (Angular2 is developed in Typescript) goodies that comes with that, an upgrade of the source of this library to Typescript would be of advantage to anyone in my opinion.

**Comment by mmaitre314** [comment]
I took a first stab at it in PR DefinitelyTyped/DefinitelyTyped#8725. The API shape should be a good match but I am not sure I got the AMD export right (adal-angular requires shims to work with RequireJS, so it's a bit tricky to match that behavior in .d.ts).

**Comment by brphelps** [comment]
Doing an ambient install of this typing currently strips the adal .d.ts -- Is this a bug?

**Comment by darcyparker** [comment]
@brphelps - I observed the same problem.  When I installed with `typings install --save --global dt~adal-angular`, `adal.d.ts` is stripped out...  You probably worked around this. But in case it helps others, I worked around it by manually adding the `d.ts` files to my project.

**Comment by unindented** [comment]
The npm types don't match the module name, which breaks importing: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/adal (instead of adal-angular)

cc @RyanCavanaugh

**Comment by thewilsons13** [comment]
So I see there are now types out in DefinitelyTyped, but the documentation says they are for 1.0.6, while the actual adal JS library is up to 1.0.13.  Do I have to use the 1.0.6 adal library if I want to use Typescript, or will it work with 1.0.13?

**Comment by maitre-matt** [comment]
I don't believe there has been API breaking changes between 1.0.6 and 1.0.13, so it should be ok. The type definition may be missing newer APIs (when that happens the trick is to cast to `any`, or better: send a PR on the definition). There is also a packaging issue with ADAL putting two JS files in a single NPM package and DefinitelyTyped requiring two packages instead https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12586

**Comment by brentschmaltz** [comment]
@tushargupta51 @rohitnarula7176 can we get this into 1.0.14?

**Comment by rohitpagariya** [comment]
@tushargupta51 / @rohitnarula7176, any updates on this? It would be really nice to have this working.

**Comment by RehanSaeed** [comment]
Using the following import statement does not seem to play well with `@types/adal`:

```
import * as adal from "adal-angular/dist/adal.min";
```

I get errors saying the decleration file could not be found.

**Comment by grumar** [comment]
`@types` was changed from `adal `to `adal-angular` few days ago.
[DefinitelyTyped #22549](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22549)
[DefinitelyTyped #22565](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22565)

**Comment by sameerag** [comment]
All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is supported only for security fixes. We would recommend to move to `msal js` for any advanced feature asks. 

Closing this issue.
