### ISSUE TITLE
Calling logOut() does not force user to enter username/password next time

### ISSUE THREAD

**Issue by tparvi** [AzureAD/azure-activedirectory-library-for-js#610]
What I have tried:

- call logOut()
- call clearCacheForResource and clearCache

But when I go back to my app I can see the following in the dev console:

> Token is already in cache for resource: xxxxxxx

How can I log out user so that next time he must enter username/password?

**Comment by tparvi** [comment]
So the good thing is that logOut() works. Only issue is that it always redirects user somewhere.

So my case was actually more complex. The REST interface returns HTTP 403 + JSON that we used to detect that user is not authorized to use the site (this will be different from case where e.g. token has expired). What should happen is this:

1. Web UI detects HTTP 403
2. User is logged out automatically
3. User is redirected to page that shows "You are not authorized...." and asks user to login again

Unfortunately this does not work singe calling logOut() automatically redirects user to Microsoft's login page.

**Comment by jmprieur** [comment]
Did you set the **Logout URL** for the application?

![image](https://user-images.githubusercontent.com/13203188/29116378-dfd89cd6-7cfa-11e7-9912-71372d2f712e.png)

**Comment by jmprieur** [comment]
Closing the issue, this is working as expected. you can redirect to the page you want after logout using the Logout URL.
