### ISSUE TITLE
Adal.js (no angular) popup not closing with redirect URL with spaces

### ISSUE THREAD

**Issue by pkmelee337** [AzureAD/azure-activedirectory-library-for-js#611]
Hi,

Just found out that the the popup windows wasn't automatically closing when I set the redirect URL to an url with spaces in it. (don't ask me why it has spaces, not my choice. :-)) After some debugging I found the issue in the _loginPopup function. The URL set is matched against the popupWindow location.href, but this happens without encoding the redirect URL set in the config. (following code in the _loginPopup function)
`if (popupWindow.location.href.indexOf(registeredRedirectUri) != -1) {`

Spaces are encoded with %20 so this was always false in my scenario. Fixed it on my side by encoding the URL put in the adal config, but I think it will safe some people from a lot of debugging if this url is encoded in the adal.js itself. I currently do not have the time to create a branche and fix it myself, but it should be something like the following.
`if (encodeURI(popupWindow).location.href.indexOf(encodeURI(registeredRedirectUri)) !== -1) {`

With kind regards,
Henk ter Harmsel

**Comment by rohitnarula7176** [comment]
@pkmelee337 Thank you for pointing out this issue. Fixed in dev
