### ISSUE TITLE
IE - unable to acquire tokens for endpoints - infinite acquire token loop.

### ISSUE THREAD

**Issue by makromat** [AzureAD/azure-activedirectory-library-for-js#615]

**Comment by makromat** [comment]
I'm not able to get authentication working on IE 11. I'm using newest version of adaljs without angularjs. Everything is working correctly in chrome end everywhere else...but not in IE.
This is my code:
  
    (function () {
    window.config = {
        tenant: '<tenant>',
        clientId: '<id>',
        postLogoutRedirectUri: window.location.origin,
        cacheLocation: 'localStorage', // enable this for IE, as sessionStorage does not work for localhost.
        endpoints: {
        // Map the location of a request to an API to a the identifier of the associated resource
        // Format: API Url, Resource
            "https://graph.microsoft.com/": "https://graph.microsoft.com/"
        }
    };
    var authContext = new AuthenticationContext(config);

    // Check For & Handle Redirect From AAD After Login
    var isCallback = authContext.isCallback(window.location.hash);
    authContext.handleWindowCallback();

    if (isCallback && !authContext.getLoginError()) {
        window.location = authContext._getItem(authContext.CONSTANTS.STORAGE.LOGIN_REQUEST);
    }

    // Check Login Status, Update UI
    var user = authContext.getCachedUser();
    if (user) {
        var token = authContext.getCachedToken('https://graph.microsoft.com/');
        if (!token) {
            authContext.acquireToken('https://graph.microsoft.com/', function (err, token) {
                if (err || !token) {
                    console.log(err, token);
                    $('#response').text(JSON.stringify(arguments));
                    return;
                }
                loggedIn(token);
            });
        } else {
            loggedIn(token);
        }
    } else {
        console.log("error");
        authContext.login();
    }
    function loggedIn(token) {
        console.log(token)
        $.ajax({
             type: 'GET',
             url: 'https://graph.microsoft.com/v1.0/me',
             headers: {
                    'Authorization': 'Bearer ' + token,
                    'Accept' : 'application/json; odata.metadata=none',
                }
         }).done(function (data) {
                $('#response').val(JSON.stringify(data, ' ', 4));
         }).fail(function () {
                $('#response').val(JSON.stringify(arguments));
         });
    }
    $('#logout').on('click', function (e) {
        e.preventDefault();
        authContext.logOut();
    })
    }());

Sometimes I'm authenticated and then authentication is working some time. But after some time the issue occurs again. When it occurs I see several scenarios.
Sometimes I have infinite loop during the process of acquiring new token. I see also an error message: 
`Error :login_required; Error description:AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com).`
 But when I add login function when acquiretoken function fails I have infinite page reload...
Sometimes I have an error message: Token renewal operation failed due to timeout.
Sometimes it is working correctly even when I clear the cache, cookies and also localStorage wich is really weird.
I also add https://login.microsoft.com and https://login.microsoftonline.com into trusted sites but no luck again...
Thanks for any help or suggestions.

**Comment by makromat** [comment]
Also sometimes I see the HTTP call to authorization endpoint is still in pending status.... with no response from server...

**Comment by makromat** [comment]
could it be releated to [https://mertarauh.com/2016/09/05/adal-js-and-zones-in-ie-and-edge/](https://mertarauh.com/2016/09/05/adal-js-and-zones-in-ie-and-edge/) ?

**Comment by rohitnarula7176** [comment]
@makromat can you provide a code repro for this issue so I can debug this further.

**Comment by MatthiasDebaere** [comment]
I have the same issue. Works in all browsers except for IE 11 and returns the same error AADSTS50058.

**Comment by stas-kh** [comment]
Guys, we have the same issue on the project. We are really blocked by this bug.
We are using Angular 4 with the library for adal authentification: [adal-angular4](https://www.npmjs.com/package/adal-angular4)

The issue is the same as described above, we can login via adal but after success login we try to get user information from graph.microsoft.com and it comes to infinite loop in IE11 (all other browsers work as expected).

After some investigation we found out that it happens on 'acquireToken' calling for graph endpont.
We receive the same error (AADSTS50058).

We are looking forward to getting any updates on this.

**Comment by oleksandrstarov** [comment]
Hi All,
Same here on our side. The ADAL auth goes perfect, then we need to get data from graph - and this is the point - infinite loop comes for IE11 with this error 

> A silent sign-in request was sent but no user is signed in....

Seems to be en IE issue but this still works on some machines with IE. And works like a charm on Chrome, FF, Safari... 

Is there any way to handle this and prevent this infinite loop as currently for some users with respect to software policy only allowing IE usage this is major blocker?

**Comment by MatthiasDebaere** [comment]
Have you tried adding "graph.microsoft.com" to the "trusted sites" zone?

**Comment by stas-kh** [comment]
@MatthiasDebaere I added this sites to the trusted resources and seems it works for me.
But with this approach, I face another problem that each time users should press "Allow" button to trust the selected resource.

As a workaround - it works. But it will be much better to have this problem solved.

**Comment by MatthiasDebaere** [comment]
I agree, and a workaround every user has to perform at that,.. so in terms of "solved", we're not quite there yet. 

It's funny how an authentication library, provided by microsoft, can be so broken on a browser, again provided by microsoft.

**Comment by oleksandrstarov** [comment]
@MatthiasDebaere  Thanks for suggestion, this works for  some users, but some still experiences infinite reload on login... Looks really wired.

**Comment by stas-kh** [comment]
Guys, any updates on this?

**Comment by rohitnarula7176** [comment]
Closing this issue as it is browser specific and not related to anything in the library.

**Comment by austingriff** [comment]
This is still an issue.... and I would argue that is specific to the library, and more specifically, the way it caches tokens.

**Comment by miguelemosreverte** [comment]
This issue needs fixing. I am experiencing first hand right now, 12/11/2018.

**Comment by austingriff** [comment]
Yeah I agree. This is still an issue and i believe it is with acquireToken. I've been able to mitigate it by using HTML5, but there is some scenario (haven't figured it out yet) that keeps trying to acquireToken even after it has successfully acquired one.
