### ISSUE TITLE
Interceptor fires for backend query for non protected routes 

### ISSUE THREAD

**Issue by aplongh** [AzureAD/azure-activedirectory-library-for-js#616]
Hi, I have a site that has both public and private áreas. The private áreas routes are marked with 'requireADLogin: true' but the public routes are not. some of the private áreas require interaction with backend c# webAPI, but the interceptor blocks the request with a "User authentication required" or something like that. I solved this adding the array of "anonymousEndpoints", but I am wondering if this is a bug or this behaviour is by design.
thanks

**Comment by rohitnarula7176** [comment]
@aplongh this behavior is by design. If the route is added to the anonymous endpoints, adal will not try to acquire a token for that route.
