### ISSUE TITLE
Why is LOGIN_ERROR not cleared on logout

### ISSUE THREAD

**Issue by aciccarello** [AzureAD/azure-activedirectory-library-for-js#617]
Looking at the [`clearCache`](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal.js#L691) method, it seems that the [adal.login.error](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal.js#L82) value is not cleared. Is this intentional?

I realized this when testing a workaround for #463. In my app (using only the base adal.js library) I am checking for a token and the return value of `getLoginError`. However it seems that after the user has previously encountered a login error and logged out, I cannot get it to login normally because the login error is still in session storage. I am now clearing the cache value within my app on logout to avoid this issue. Even if #463 is resolved I would still expect that error to be cleared in `clearCache`.

I would be happy to submit a simple PR if it would make things easier.

**Comment by jmprieur** [comment]
@rohitnarula7176 I cannot think of a reason of keeping LOGIN_ERROR after logout succeeded. Or am I missing something?

**Comment by jmprieur** [comment]
See also #608

**Comment by rohitnarula7176** [comment]
@aciccarello Thank you for pointing out this issue. It is now fixed in dev. Please check and confirm.
