### ISSUE TITLE
Docs have wrong property, doesn't compile: "clientID" should be "clientId"

### ISSUE THREAD

**Issue by whitneyland** [AzureAD/azure-activedirectory-library-for-js#618]
If coding against these docs code won't compile because of the case mismatch:

v1.0.15:
@property {string} clientID - Client ID assigned to your app by Azure Active Directory.

Proposed:
@property {string} clientId - Client Id assigned to your app by Azure Active Directory.

**Comment by rohitnarula7176** [comment]
@whitneyland Issue is now fixed in dev. Please check and confirm.
