### ISSUE TITLE
Issue with the html5mode in angular 1.6.6, when the urls has the default prefix ('!'). Apparently on this version this featured is enabled by default.

### ISSUE THREAD

**Issue by ajota** [AzureAD/azure-activedirectory-library-for-js#620]
Hi, 

When I updated the angular in my application from 1.4.8 to 1.6.6 apparently the  angular  html5Mode is enable by default so this cause that all the urls contain a prefix ('!') after the traditional hash that is normally in angular routes. but when this is present, the adal library has not the ability to identify the 'id_token' to validate the data delivered from azure active directory.

**Comment by navyasric** [comment]
Please refer to similar issue #551 for a way to fix this.

**Comment by navyasric** [comment]
Closing as a duplicate. Please reopen if you find other issues.
