### ISSUE TITLE
Application not working on Edge

### ISSUE THREAD

**Issue by Raghavasg** [AzureAD/azure-activedirectory-library-for-js#622]
we are facing typical issue with Adal Js authentication with Edge. For some of the users application is working fine on edge but for few authentication is going infinite loop on edge.   

Note: App is working fine with other browsers without any issues
I tried some of the suggestions like trusted sites and cookies but nothing worked.
We are using Adal.js version AdalJS v1.0.14 and Cachelocation set to localstorage

**Comment by MatthiasDebaere** [comment]
Could you check the network tab in the Developer Tools and see if there are any more details about the network call(s)? (I'm also having issues and maybe it's the same..)

**Comment by Raghavasg** [comment]
I added login.microsoftonline.com as trusted sites and our site as well, how ever now luck.  I am not able to get the network trace because application reloading repetedly

**Comment by rohitnarula7176** [comment]
@Raghavasg Can you share a code repro for this issue so we can investigate this further.

**Comment by MatthiasDebaere** [comment]
You can try and get the error code by disabling the "Clear on navigate" button. It looks like this:
![image](https://user-images.githubusercontent.com/6587006/30375358-84af8cda-9888-11e7-8cd2-7fd7a932e065.png)

Our application was also becoming unresponsive so you'll have to have some patience until you can finally get your hands on the error code..

**Comment by Raghavasg** [comment]
Hi,

Please find the attached code and event viewer log.  
[Code.txt](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/1304317/Code.txt)
[EventViewer.txt](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/1304340/EventViewer.txt)

**Comment by rohitnarula7176** [comment]
@Raghavasg You have attached just the config file. if you open session storage, do you see something like invalid_state as error. Can you please share your entire code that might help us reproduce the issue?

**Comment by Raghavasg** [comment]
[ADAL_trace.zip](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/1312539/ADAL_trace.zip)
HI,
we are able to get the traces, I am attaching the traces file for your reference. Please let me know whether it helps for your debugging.

thanks,

**Comment by navyasric** [comment]
@Raghavasg In the even viewer log you attached, I noticed the error is about not meeting the MFA conditional access requirement during login. Please refer to [this article](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-conditional-access-developer) to see if it helps with your issue?

**Comment by Raghavasg** [comment]
@navyasric,

we checked our code as per the article but our implementation looks same. I am attaching our code for your reference, request you to help us.

[IndigoWeb.zip](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/1328361/IndigoWeb.zip)
