### ISSUE TITLE
Some users are no longer able to login...

### ISSUE THREAD

**Issue by foconnor-DS** [AzureAD/azure-activedirectory-library-for-js#624]
Just wanted to put this out as a placeholder, in case others are experiencing this. Since the new "Microsoft" sign on experience, we've had some users unable to login using ADAL.js. Even if they go back to the old sign on experience it's not working. We thought it was a Chrome 61 bug, but we've reproduced it on 60, 61 and canary 63. So we're putting aside the chrome thought for now. We're not using popup mode.

We hope to get logging enabled for ADAL on a production VM snapshot that has the error and have more information soon.

**Comment by foconnor-DS** [comment]
Looks like the issue was tied to "Adal-Request.js" which is a gist from another group. Not a Library issue. Closing.

**Comment by rohitnarula7176** [comment]
@foconnor-DS Thank you for the update,
