### ISSUE TITLE
APP Reloads when user is idle for some time and Make a Api Call

### ISSUE THREAD

**Issue by saravana13** [AzureAD/azure-activedirectory-library-for-js#626]
When user is idle for some time and make a API call App is reloading leading to data being lost in the Form. Adal Error is "Nonce is not same as undefined". Please suggest a work around . Happens in all browser

**Comment by rohitnarula7176** [comment]
@saravana13 Can you share the adal logs and fiddler traces for this issue?

**Comment by saravana13** [comment]
@rohitnarula7176 in local its working as expected only in deployed version we are facing the issue. From deployed version i am not able to get the logs (since i have to go thorough several members to get that done).Anything else u want which might be help?. Also i have a debut, since it possible to manually call renewtoken function. i am planing a set a watch based on that call the renew token function even if user is idle. Please suggest as i am facing this issue for like a month. Thanks

**Comment by saravana13** [comment]
@rohitnarula7176 Please find the attachment for logs. Just removed urls from the logs. Please let me know if you need anything. Any Help would we much appreciated.
[adal-log.txt](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/1341964/adal-log.txt)

**Comment by rohitnarula7176** [comment]
@saravana13 Can you please provide a code repro for this issue.

**Comment by rohitnarula7176** [comment]
@saravana13 Closing this issue as no code repro was provided. Please reopen if you still have issues.
