### ISSUE TITLE
adal.js response_type=id_token+token

### ISSUE THREAD

**Issue by aXiniXe** [AzureAD/azure-activedirectory-library-for-js#629]
It seems to me the current version of this library does not support response_type=id_token+token, is there a reason for this or am I missing something?

Thanks.

**Comment by navyasric** [comment]
@aXiniXe What is the authentication use case you are building? id_token is already a token. Did you mean response_type=id_token+code?

**Comment by aXiniXe** [comment]
Hi,

Thank you for the response,

I do mean using 'id_token+token' as a response type with the goal of receiving an id_token and access token for a recourse in 1 request. See the documentation on https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-implicit under section 'Send the sign-in request'

Thanks.

**Comment by rohitnarula7176** [comment]
@aXiniXe The response type id_token token is not supported by the library since the start. Please see a similar request #525 . Can you explain why you need to request id_token and access_token at the same time.

**Comment by aXiniXe** [comment]
Hi,

The reason to request the id_token and access_token in 1 request is purely for efficiency reasons. We have a front-end which allows users to authenticate with Azure AD using OpenID connect and a back-end API which is also protected using Azure AD. Currently we have to perform 2 requests: first 1 to get the OpenID connect id_token with the authorize end point, and a second 1 to retrieve an access_token for the resource back-end API using the token endpoint. Using response type id_token+token we can retrieve the id_token and access token for the back-end in 1 request. One of the first actions the front-end will make after succesfull login is contacting the back-end to request information.

Thanks.

**Comment by rohitnarula7176** [comment]
@aXiniXe If you just need to call your own backend, you can just use your idtoken. If not you can still call acquireToken to request an accessToken and if you have a valid session with AAD, you should not face any issues. Did you try using your id_token to retrieve data from your backend?

**Comment by rohitnarula7176** [comment]
@aXiniXe We cannot add the response_type = 'id_token token" as part of the library as it might run the risk of hitting the authorization url limit. Moreover the purpose of login is just to establish user context by requesting an id_token. Adding the ability to request an access token for a resource at the time of login, might lead to a situation where the developer does not have permissions to access the resource and in that case the library would not be able to return an id_token as well. That said, if you have a single resource that you need an access token for at the time of login, you can still achieve this by adding the following code snippet to the displayCall property of the adal's config object. This will override the default login code of the library.
```
 adalProvider.init(
                {
                    displayCall: function (urlNavigate) {
                        var instance = self.AuthenticationContext.prototype._singletonInstance;
                        var resource = "https://rohit1.onmicrosoft.com/ToGoAPI";
                        instance.config.state = instance.config.state + '|' + resource;
                        instance._saveItem(instance.CONSTANTS.STORAGE.STATE_LOGIN, instance.config.state);
                        urlNavigate = instance._getNavigateUrl('id_token token', resource) + '&nonce=' + encodeURIComponent(instance._idTokenNonce);
                        window.location.replace(urlNavigate);
                    }
                },
                $httpProvider
            );
```

**Comment by deregtd** [comment]
The above workaround posted by Rohit should do what you want.  It jumps straight into 2FA flow for me when I request a resource with it based on the code above.  Unfortunately it appears to not work correctly for 1st party apps, but it should be fine for third party apps.

**Comment by vishwanathsunkari** [comment]
Hi , i want to use this adal services for code authorization flow , using angular 7. now i can able to get the token in implicit way but is there anyway to set the response_type="code" so that i can turn implicit way to code flow .
if not can you please guide me, how we can achieve azure ad sign in using code flow (not implicit way)
Thanks in advance
