### ISSUE TITLE
Error when logout and re-login with another user

### ISSUE THREAD

**Issue by phantomis** [AzureAD/azure-activedirectory-library-for-js#630]
There is a problem on the library when you try to login with another username/password when you previously logged in and logged out with one username.

To replicate: 
1. Try to use ADAL and perform a login with user1
2. Put your credentials, and then go to your application
3. Press the logout button, and then, go and re - login 
4. Select another email user2 and use it to force the credentials prompt
5. You will be redirect to the application as an autenticated user, but using the token of user1

That looks like there is some cookies saved on the microsoft login page, that cannot be clean when you press logout on your own application.

**Comment by sorbonad** [comment]
The workaround mentioned by tamerlan seems to be working. I am testing.

**Comment by rohitnarula7176** [comment]
@sorbonad @phantomis I am not able to reproduce this issue using 2 test accounts on Chrome. Can you please specify the version of adal and Chrome you are using and provide us with a code repro.

**Comment by phantomis** [comment]
After some investigation with the Microsoft Suport on site, we found that was a problem with the ADFS inside our company. Thanks a lot for your help
