### ISSUE TITLE
Non-Angular example

### ISSUE THREAD

**Issue by CBuntrock** [AzureAD/azure-activedirectory-library-for-js#632]
Will there be a new (non deprecated) example for usage of ADAL.js without any framework?

**Comment by jmprieur** [comment]
There are a few samples using plain JavaScript.
For instance please see https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof-ca/tree/master/TodoListSPA

**Comment by CBuntrock** [comment]
Thanks for response. Unfortunately the mentioned example requires Visual Studio. Even when ignoring that: It also requires .NET. I am looking for an example I can run with VS code using jquery (or react). But I would prefer to have a plain Javascript example that just shows me how to connect to SP online.

**Comment by FDMatthias** [comment]
A bit late, but I've written a blogpost about this [here](https://www.appfoundry.be/blog/2018/11/24/authentication-with-adal-in-react-single-page-applications/) and put a sample of a React SPA with Adal on github [here](https://github.com/appfoundry/react-adal-authentication-session-sample/tree/Authentication-with-ADAL-in-React-SPA) (includes step by step commits and multiple branches).
