### ISSUE TITLE
adal.js with Angular JS returns infinite loop while login after idle time out

### ISSUE THREAD

**Issue by d-saravanan** [AzureAD/azure-activedirectory-library-for-js#633]
We have a very strange issue in the recent days, like after the user has left the application idle out for approx 1 hour, when the user tries to access the app again, the app redirects the user to the login page and then from AD, it receives the response as "Invalid State" and it logs this message in the localStorage. However, a fresh request is constructed and then tries to redirect back to AD and again fails with the same error.

When I checked the Chrome > Developer Tools > Application > LocalStorage, I see that the state ids are getting generated newly and requests are made and then fails with the same error messages.

This behvaiour is consistently working in all the browsers and the user is not able to use the application untill logout from Azure AD and then re-login. I am not sure why this happens in the recent times. Kindly suggest the right way to handle this.

I think that state token generated at the client side and sent to the Azure AD is getting lost in AD or invalidated due to some other reason and that is why, it repeatedly rejects the login session request for a new id_token. Hence, when I logout and then re-login, I am able to successfully login and continue. To be a hack, I can store the number of retries in localStorage and if its > 3, I can force logout, but does not give a good UserExperience

**Comment by rohitnarula7176** [comment]
@d-saravanan Can you please provide a code repro for the above issue. The only reason for the 'invalid state' error is when the values stored in the browser cache by adal are lost when you receive a redirect response from AAD with the id/access_token/error.

**Comment by rohitnarula7176** [comment]
@d-saravanan Closing this issue due to lack of logs or code repro. Please reopen once you have that information available.
