### ISSUE TITLE
Infinite redirect loop on access_denied error

### ISSUE THREAD

**Issue by fikkatra** [AzureAD/azure-activedirectory-library-for-js#635]
Closely related to #463 , which I believe was incorrectly closed.

When a user does not have permission to access an app (because no role was assigned to his account), an infinite login loop occurs.

Our approach: when an `access_denied` error is received from Azure AD, we redirect the user to an error page. This error page is anonymously accessible (`requireADLogin: false`). We do this by listening to the `adal:loginFailure` event in the `run `config of the angular app:
```
.run(['$rootScope', '$state', ($rootScope, $state) => {
	$rootScope.$on('adal:loginFailure', (event, rejection, reason) => {
		if (reason === 'access_denied') {
			// user is logged in but does not have access to the application. Redirect to error page
			$state.go('error');
		}
	});
}])
```
The user is redirected to the error page, but somehow immediately afterwards, a new redirect to the login page occurs, resulting in an infinte error-login-error loop.

Adal setup:

```
adalAuthenticationServiceProvider.init(
	{
		instance: 'https://login.microsoftonline.com/',
		tenant: <tentant>,
		clientId: <client id>,
		endpoints: {...},
		anonymousEndpoints: [...]
	},
	$httpProvider
);
```

If we set this property in the adal setup:
`navigateToLoginRequestUrl: false`
it works fine and no infinite loop occurs. However, we do not want to set this flag to false, as we want to redirect the user to the original page after login (not necessarily the redirectUrl configured in AzureAD).

This issue occurs with adal-angular v1.0.14 and v1.0.15

**Comment by rohitnarula7176** [comment]
@fikkatra I do not understand why the second redirect would occur after you are redirected to your error page. Can you please provide a code repro for this so I can investigate this further.

**Comment by fikkatra** [comment]
@rohitnarula7176 
[Here's a repo](https://github.com/fikkatra/AdalInfiniteLoop-SystemJs) illustrating the problem. It uses SystemJs as a module loader. Repro steps:

- npm i
- in the Azure portal, create an app with the 'user assignment required' setting set to 'True'
- insert azure tenant and client id in app.ts
- run app (e.g. with lite-server) and login with a user that does not have a role for the application

The app redirects to the login page, but if you are already logged in, it keeps on looping. The error page doesn't show (although depending on browser and network, I've seen it pop up briefly). When you set the navigateToLoginRequestUrl flag to false, everything works fine.

When I tried to remove SystemJs to simplify the code, interestingly I couldn't reproduce the issue anymore because my secured state just loaded without being logged in. Even though  `requireADLogin `was set on the state, I'm not redirected to the login page. [Here's the simplified repo](https://github.com/fikkatra/AdalInfiniteLoop-Simple).

**Comment by rohitnarula7176** [comment]
@fikkatra for the second repo, you are using ui router version 1.0.3. State change events are deprecated in ui router release>1.0 and hence you are not redirected to login page even when requireADLogin is set to true. If you use ui router to 0.3.1 for instance in your simplified repo, it should work as expected.

**Comment by rohitnarula7176** [comment]
@fikkatra In order to avoid the infinite loop, you have to use navigateToLoginRequestUrl:false and redirect to the error state on 'adal:loginFailure' event. If you don't set this flag to false and try to login with a user who is not assigned a role for your application, you are bound to get into an endless loop loop as your root page requires authentication and ADAL will take you to your root page after processing the token/error from the redirect response from AAD as it is not safe to leave the token in the url. Can you explain what is the issue, if you just set this flag to false and redirect to your custom error page because that works as expected. You can't do both, adal can either take you to your loginStartPage or to your custom error page.

**Comment by fikkatra** [comment]
The issue occurs for example when we send an email to a user containing a link to a particular page. After the user is logged in, we want to redirect to that page, not to the home page. That's why we can't set the flag to false.
I will try to make it work with an anonymous home page url, and get back to you with results. Thanks for looking into it.

**Comment by fikkatra** [comment]
@rohitnarula7176 as setting the `navigateToLoginRequestUrl` flag to false, is not an option for us, and we don't really have a home page that can be accessed anonymously (users should immediately be redirected to the login page), I tried using an anonymously accessible 'adal' page as the root page. 

I got it working by checking the `loginError` property on the userInfo object. If the user is not allowed access, I redirect to the error page, otherwise to the (secured) home page. I don't check the `loginFailure` event anymore. The code:

```
var app = angular.module('adalApp', [uiRouter, 'AdalAngular'])
    .config(['$httpProvider', 'adalAuthenticationServiceProvider', function ($httpProvider, adalAuthenticationServiceProvider) {
        adalAuthenticationServiceProvider.init(
            {
                instance: 'https://login.microsoftonline.com/',
                tenant: '<tenant>',
                clientId: '<client id>'
            },
            $httpProvider
        );
    }])
    .config($stateProvider =>
        $stateProvider
            .state('error', {
                url: '/errorpage',
                template: '<h2>Error</h2>'
            })
            .state('adal', {
                url: '/adal',
                controller: ($state, adalAuthenticationService) => { 
                    if (adalAuthenticationService.userInfo.loginError && adalAuthenticationService.userInfo.loginError.startsWith('AADSTS50105')) {
                        $state.go('error');
                    } else {
                        $state.go('home'); 
                    }
                }
            })
            .state('home', {
                url: '/home',
                template: '<h1>Home</h1><ui-view></ui-view>',
                requireADLogin: true
            })
    )
    .config($urlRouterProvider => $urlRouterProvider.otherwise('/adal'));
```

This works, although it does feel a little dirty to check the login error string. Otherwise, does this workaround seem a valid solution to you?

**Comment by rohitnarula7176** [comment]
@fikkatra Currently the login method in adal does not send any prompt value with the request. The only way to prevent the infinite loop is either by setting the navigateToLoginRequestUrl to false and handling your own navigation in the callback in case you receive the above error. In the next release, you can set the property 'extraQueryParameter = 'prompt=select_account' on the config object which will give the user an option to sign in using a different account if you get this error.
