### ISSUE TITLE
redirectUri makes application stuck on redirecting between microsoft login page, redirected page and home page forever.

### ISSUE THREAD

**Issue by gunner13** [AzureAD/azure-activedirectory-library-for-js#643]
I'm facing another issue after adding the redirectUri. I followed this guide https://gist.github.com/tushargupta51/5fa6d000357120adbc8fd1d5c68853c4 to fix the issue that page refresh many times after login.
At the beginning, it fixed my problem, at that time my application's url was something like this myapp.com.
Then i had to configure my application to work with multi tenants, and url became something like subdomain1.myapp.com, subdomain2.myapp.com,  subdomain3.myapp.com (sub domains are dynamic and managed by db) and then my application kept redirecting between microsoft login page, redirected page and home page in an infinite loop.
The only way for me now is removing the redirectUri and suffer the old issue. 
Is it a bug or i'm missing something?

**Comment by cottinghamj** [comment]
I'm facing the exact same issue. I'm making the call to acquireTokenSilent. It seems like when I call that function when my token has expired, it makes an inner call to the renewToken function. That code makes an iframe in your html and does adal magic to renew your token. Unfortunately, sometimes the returned source code that the iframe receives from the url requires a refresh. That refresh happens to the parent (The entire webpage) when it should only happen to that iframe it seems.

Here's a Fiddler Trace of what I experience:
![image](https://user-images.githubusercontent.com/5620266/31911194-b4e8aab8-b7f4-11e7-8423-41270ddb8ec2.png)

**Comment by cottinghamj** [comment]
I just realized the page I get redirected too has my graph access token in the url, so the code does refresh and get the graph token...it just should inject the formatted graph token url into the iframe, not the web page url

**Comment by rohitnarula7176** [comment]
@cottinghamj @gunner13 You should not see the token in the main page when you call acquireToken. It should take place in the iframe. Can you please provide a code repro for this issue?

**Comment by rohitnarula7176** [comment]
@cottinghamj @gunner13 Closing this issue due to lack of a code repro. Please reopen if you are still facing issues.
