### ISSUE TITLE
Endpoint Only Requests Do Not Issue Refresh Token

### ISSUE THREAD

**Issue by brianyingling** [AzureAD/azure-activedirectory-library-for-js#65]
Authentication works well when navigating around Angular routes (using requireADLogin) but when attempting to access an endpoint, I'm not issued a refresh token if it has already expired. The request is submitted without an idtoken in the header and I receive a 401 unauthorized response. I tried adding the endpoints flag in the provider, but still no authorization.

Any reason why refresh tokens are properly issued with Angular routes (requireADLogin) but not when sitting idle for awhile and then attempting to hit an endpoint that requires said token?

Thanks.

**Comment by zachcarroll** [comment]
@omercs agreed with @brianyingling I'm seeing the same issue.  Tried versions 0.0.4, 5, and the 5 angular version.

**Comment by omercs** [comment]
is this endpoint on a route that is not protected? 
Is endpoint for CORS api?

ProtectedResourceInterceptor will do iframe request if token is expired.

**Comment by brianyingling** [comment]
It is a CORS API.

Adding the endpoint to the endpoints object in the adalAuthenticationServiceProvider doesn't seem to solve the issue for me. I also don't see the iframe request happening.

**Comment by brianyingling** [comment]
Basically, when the token expires I never get to this point in the ProtectedResourceInterpreter: 

else if (authService.config && resource !== authService.config.clientId) {
                                // external endpoints
                                // delayed request to return after iframe completes
                                var delayedRequest = $q.defer();
                                authService.acquireToken(resource).then(function (token) {
                                    config.headers.Authorization = 'Bearer ' + token;
                                    delayedRequest.resolve(config);
                                }, function (err) {
                                    delayedRequest.reject(err);
                                });

                                return delayedRequest.promise;

**Comment by zachcarroll** [comment]
its a requireADLogin: true route, with all CORS API calls.

**Comment by brianyingling** [comment]
resource !== authService.config.clientId

Basically, the abovementioned is preventing me from getting to access the endpoint. In this case the clientId and the resource are one and the same. Removing this condition causes it to constantly refresh the page.

**Comment by omercs** [comment]
Ok. I will update the logic on this.

**Comment by brianyingling** [comment]
Pull request: https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/66

**Comment by vibronet** [comment]
One point of confusion I have on this: in ADAL JS we don't ever receive or use refresh tokens. I am sure it's just a matter of terminology, but wanted to make sure this is called out to prevent any confusion.

**Comment by brianyingling** [comment]
Apologies for the confusion; I'm referring to the token that expires after an hour of inactivity.

**Comment by omercs** [comment]
Thank you for the contribution.
