### ISSUE TITLE
What's the meaning of "extraQueryParameter: 'nux=1'" When initialize the adal?

### ISSUE THREAD

**Issue by wy193777** [AzureAD/azure-activedirectory-library-for-js#652]
No document mentioned this.

**Comment by rohitnarula7176** [comment]
@wy193777 This is just for the purpose of telemetry. It not a required parameter.

**Comment by TryingToImprove** [comment]
can you elaborate about what you mean by telemetry? Who's telemetry? @rohitnarula7176

**Comment by adrichema** [comment]
Is it legacy to display the correct mobile UX?
