### ISSUE TITLE
Requests after login don't contains Authentication header field

### ISSUE THREAD

**Issue by wy193777** [AzureAD/azure-activedirectory-library-for-js#654]
I'm using dev branch with ui-route 1.0.0-rc1

Here is the code for initialization:
```javascript
adalAuthenticationServiceProvider.init(
        {
            instance: 'https://login.microsoftonline.com/',
            clientId: "[client id]", // Required
        },
        $httpProvider
    );
```

After poking around, I found that the last method `// Interceptor for http if needed` not attach the token. 

```javascript
            return {
                request: function (config) {
                    if (config) {
                        
                        config.headers = config.headers || {};
                        
                        // if the request can be served via templateCache, no need to token
                        if ($templateCache.get(config.url)) return config;
                        console.trace();
                        var resource = authService.getResourceForEndpoint(config.url);
                        authService.verbose('Url: ' + config.url + ' maps to resource: ' + resource);
                        if (resource === null) {
                            return config;
                        }
```
The `url` attribute on object `config` doesn't contain any resources.

Is this related to `endpoints` property when initialize the application?

**Comment by wy193777** [comment]
I need to specify backend addresses and let the same client ID as the key of the endpoints object, then the header will contains the Authentication field. Not understand why it works this way.

```javascript
adalAuthenticationServiceProvider.init(
        {
            clientId: "aaaa-bbbb-cccc", // Required
            endpoints: {'http://localhost:5000/golden-api/v2/': "aaaa-bbbb-cccc"}
        },
        $httpProvider
    );
```

**Comment by rohitnarula7176** [comment]
@wy193777 getResourceForEndpoint(URL) checks to see if the URL is your apps own backend or some other domain which is listed in the end points array. If your app root URL is https://localhost:5000, then an API like https://localhost:5000/api will be considered your backend and an API in any other domain should be listed in the end points array. Adal will take clientID as resource for backend apis and the value of the endpoint array as resource for the others. adal will attach a token to the request only if it satisfies the above 2 conditions.

**Comment by rohitnarula7176** [comment]
@wy193777 Closing this issue for now. Please reopen if you still have issues.
