### ISSUE TITLE
NodeInvocationException: Prerendering failed because of error: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by karthik-15** [AzureAD/azure-activedirectory-library-for-js#658]
Created a basic application which uses this package.

I am getting an error after running the application called as "NodeInvocationException: Prerendering failed because of error: ReferenceError: window is not defined".

I am using web pack. The error which i am getting is in the file "main-server.js". Below is the code which is causing the issue.

```
window.Logging = {
        level: 0,
        log: function (message) { }
    };
```

After removing the package and its dependencies from the code, the application is working fine and the above code is not present in the "main-server.js".

Is any one else getting this issue? If Yes, is there any work around?

**Comment by rohitnarula7176** [comment]
@karthik-15 Are you using this repo or the adal-angular4 package? You posted the same issue on adal-angular4 repo which is not supported by Microsoft. This error happens when window object is not defined. You should replace the above code in adal-angular4 with the snippet below:
 ```
   if (typeof window !== 'undefined') {
        window.Logging = {
            level: 0,
            log: function (message) { }
        };
    }
```

**Comment by rohitnarula7176** [comment]
@karthik-15 Closing this issue for now as this is not an issue with the library. Please use the solution above and reopen the issue if the problem persists for you.

**Comment by Hadis-Fard** [comment]
@rohitnarula7176 I'm trying to use adal.js in my node application and don't intend to use it in angular environment where window is defined.

``` js
const adal = require('adal-angular');
```
raises  window not found at loading the module:
```
C:\***\node_modules\adal-angular\lib\adal.js:177
    window.Logging = {
    ^

ReferenceError: window is not defined
    at C:\***\node_modules\adal-angular\lib\adal.js:177:5
    at Object.<anonymous> (C:\***\node_modules\adal-angular\lib\adal.js:1664:2)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\***.js:21:14)
```
How do you load this module in node backend env?
