### ISSUE TITLE
Please Split this Repository into adal-angular and adal.js

### ISSUE THREAD

**Issue by RehanSaeed** [AzureAD/azure-activedirectory-library-for-js#659]
The SPA world has moved on from Angular 1. There are now a myriad of frameworks out there. This project should be split into two repositories, `adal-angular` and `adal.js`. 

For any developer coming from React, Vue.js, Aurelia, Ember, Polymer etc. taking one look at the ReadMe for this repo, they'd be forgiven for thinking that they'd arrived at the wrong place. All the documentation is specific to Angular. I really want to see a simple ReadMe for `adal.js` I can read in 5 mins and get going quickly.

As well as the repository, the NPM package should also be split. To import just adal.js in my code I have to write this magic incantation:

```
import "adal-angular/dist/adal.min";
```

Instead of:

```
import "adal";
```

Finally, this even causes issues with TypeScript (See https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/61). I'm trying to use `@types/adal` (The code in this repo should really be written in TypeScript but that is another matter) but the type decleration files get mixed up because adal and adal-angular both exist in there.

**Comment by ralexand56** [comment]
Yes, this is common sense

**Comment by unindented** [comment]
@rohitnarula7176 any progress on this?

**Comment by eelkram** [comment]
This would be a huge help!

**Comment by grumar** [comment]
+1

**Comment by hkusulja** [comment]
I am also interested in having separate, MS ADAL Angular5 supported library

**Comment by talorlik** [comment]
I've been battling with this like crazy.

There's also very confusing bits of information and explanation how to go about this process.

I'm **most** interested in an Angular 5 implementation.

**Comment by aciccarello** [comment]
This would help with getting TypeScript definitions (see DefinitelyTyped/DefinitelyTyped#12586)

**Comment by thdotnet** [comment]
I think this project has been abandoned, they are using and improving msal nowadays

**Comment by nitrix-reloaded** [comment]
I agree this needs a split into two repos.

**Comment by Shenrak** [comment]
I can't even launch my app because 'angular' isn't defined in my react project...

Needs a split.

**Comment by aciccarello** [comment]
@shenrak, you should be able to use the pure JS file that doesn't require angular. Splitting the repo is more about convenience than technical limitations.

**Comment by TedPattison** [comment]
If you are not using angular.js, it is really difficult to to decide the best way to consume adal.js from TypeScript. It seems like your team spent the energy to create d.rs support for angular.js and now you have run out of energy to provide TypeScript support for adal.js in anything else including just using adal.js by itself. It doesn't seem like it would be a bigger effort to create an official adal.d.ts file and it would make adoption of this library sooooooo much easier.
 
Your response that "you should be able to use the pure JS file that doesn't require angular. Splitting the repo is more about convenience than technical limitations." Yes, I agree it would be very convenient not to spend 2 days going testing out and experimenting with the with d.ts files and TypeScript support in packages such as from adal-angular, modular-adal-angular, adal-ts and the depricated @types/adal.

The confusion and lack of Microsoft guidance about using adal.js with typescript and webpack when not using angular.js is more than a lack of convenience. It is a serious roadblock to adoption.

**Comment by ralexand56** [comment]
I believe they are putting their development work into the msal.js library. It certainly would be nice if there was some guidance though.

**Comment by TallOrderDev** [comment]
+1 No comment from anyone from Microsoft yet? 8 months and we should at least have an idea of whats happening by now. Please please, can we at least get some feedback.

**Comment by baywet** [comment]
Pinged a Microsoft PM by email today, hopefully that should help get an answer at least.

**Comment by navyasric** [comment]
Thank you all for the feedback. We are investing future efforts in the MSAL.js library and will be creating separate packages for supporting frameworks.

**Comment by mlynam** [comment]
Hey @navyasric has this issue been abandoned?

**Comment by baywet** [comment]
@mlynam this has been addressed in msal as you can see here https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib

**Comment by mlynam** [comment]
Thank you @baywet. I was confused by the ADAL Microsoft docs. They pointed me at the adal-angular library instead of msal.

**Comment by baywet** [comment]
do you still have the link? don't hesitate to open issues on the docs as well (all the way at the bottom, they also open github issues)

**Comment by mlynam** [comment]
Yeah I got it from here: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-libraries. I admit that I glanced over the note asking if I was looking for Azure 2.0 (MSAL)...

**Comment by baywet** [comment]
thanks. yeah this page is probably going to stay like this as it already has a note pointing to msal

**Comment by sameerag** [comment]
All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. 

For this specific question, we have structured `msal js` better and there is a split between `msal-core` and `msal-angular`, please checkout our repo.
