### ISSUE TITLE
while using multi tenant it's not allowing to login.

### ISSUE THREAD

**Issue by ChebroluSuresh** [AzureAD/azure-activedirectory-library-for-js#665]
As per my application requirement I have to login with Microsoft work(example @Microsoft.com) and school accounts(@outlook.com). Am following library recommendations for multi tenant passing tenant as "common", but it's not working for Microsoft school accounts. Please help me ASAP

Please find below for the issue description:

Sign In Sorry, but we are having trouble signing you in. We received a bad request. 

Additional technical information:Correlation ID: 59196e79-5cb3-462a-9340-b063bd74ee76Timestamp: 2017-11-14 13:49:46ZAADSTS50020: User account 'liveuser777@outlook.com' from identity provider 'live.com' does not exist in tenant 'Microsoft' and cannot access the application 'fea7c090-f1f9-4e0f-bab4-8e8e945c5edf' in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account. | Additional technical information: | Correlation ID: 59196e79-5cb3-462a-9340-b063bd74ee76 | Timestamp: 2017-11-14 13:49:46Z | AADSTS50020: User account 'liveuser777@outlook.com' from identity provider 'live.com' does not exist in tenant 'Microsoft' and cannot access the application 'fea7c090-f1f9-4e0f-bab4-8e8e945c5edf' in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

**Comment by nehaagrawal** [comment]
Hi @ChebroluSuresh ,
It's quiet late but if you are still struggling with issue, can you please try the steps in below link. 

https://www.stephenmann.net/single-post/2016/11/03/Fix-Azure-AD-Error-AADSTS50020-when-logged-in-user-doesnt-have-permissions-to-selected-Application
