### ISSUE TITLE
Allow users to enter their own client_id and tenant_Id

### ISSUE THREAD

**Issue by faissaal7** [AzureAD/azure-activedirectory-library-for-js#667]
We are developing a SaaS solution using AngularJS for front end, for this we need to allows users to enter there own client_id and tenant_Id, but the current Angular-ADAL implementation require to add configuration in the config block of angularJS.

What is the perfect way to do this?

**Comment by rohitnarula7176** [comment]
@faissaal7 Sorry for the delayed response. Unfortunately, we cannot change anything in the library to achieve this. You should be able to create an input config and pass that to the angular init function programatically though.

**Comment by rohitnarula7176** [comment]
@faissaal7 Closing this issue as it not something we can add to the library source code.
