### ISSUE TITLE
ADAL login doesn't work fine if I didn't  put the controller in the body

### ISSUE THREAD

**Issue by faissaal7** [AzureAD/azure-activedirectory-library-for-js#669]
If i didn't mention  the ng-controller in the body for html login fails

this is my config:

```
.when('/login', {
                        templateUrl: 'login.tpl.html',
                        controller: 'LoginCtrl'
                    })
```
login.tpl.html contains a button with an action in the controller `loginWithAdal`

```
$scope.loginWithAdal = function(){
             adal.login
}
```

ADAL will work fine if i put controller in the body : `<body ng-controller="LoginCtrl">`

But when I use `<body>` adal will not work and return a message saying that _The returned id_token is not parseable._

**Comment by rohitnarula7176** [comment]
@faissaal7 Can you please provide a code repro for this issue.
