### ISSUE TITLE
$routeParams lost during authentication2

### ISSUE THREAD

**Issue by zachcarroll** [AzureAD/azure-activedirectory-library-for-js#67]
@omercs looks like when adal-angular.js was broken out from adal.js, this issue was not copied over: https://github.com/AzureAD/azure-activedirectory-library-for-js/commit/daf67c993b1599482725ba19607a3c3f91ede7ac

I'm now seeing the same dynamic routing lost variable issue as that merged issue.

**Comment by omercs** [comment]
Oops. I will update that.

**Comment by omercs** [comment]
I updated that and push changes to master in this week.
