### ISSUE TITLE
Calling acquireToken returns different "issuer" value compared to issuer on id_token

### ISSUE THREAD

**Issue by joaopgrassi** [AzureAD/azure-activedirectory-library-for-js#670]
I've been for days now trying to integrate an Angular 2 SPA + ASPNET core API through ADFS. In our case, the SPA and API are completely separated applications (very different from the demos and documentation...). Anyway, after several problems I finally got to a point where I can login on ADFS and get the id_token back.

First issue: The id_token returned contains the "aud" of my spa. I expected this to be the aud of the API in the beginning. But, after looking into the code, I found I needed to call the acquireToken passing the resource (the API clientId registered). Didn't make much sense but.. worked. Now I have 2 tokens, one id_token with `aud: spa` and a refresh token with `aud: api`

Second Issue: The refresh token for the API is returned with a issuer of: `"iss": "http://sts/adfs/services/trust"`. Of course the call to the API fails due to the invalid issuer. API expected the issuer to be "https://sts/adfs".

So I'm really lost here. Not sure if this is a set up problem on ADFS or it is a configuration problem on my side. It is really hard to work with this since the documentation doesn't help at all and most of the times it is just for azure. Does anyone have any ideas?

**Comment by sameerag** [comment]
All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We would recommend to move to `msal js` for any advanced feature asks. 

Can you try this on `msal-js` and let us know if it still an issue? Please raise a new one in the `msal-ja` repo if that is not fixed.
