### ISSUE TITLE
Silent sign-in request was sent but no user is signed in

### ISSUE THREAD

**Issue by sandeepb6** [AzureAD/azure-activedirectory-library-for-js#671]
I'm using ADAL framework to authenticate the users in a Single page application(Angular 1.4.8). When i'm requesting api call through $http, api call is not initiating because token was not generated to the respective resource. In localStorage below error is getting logged.

Error: AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com).

I thought that whenever adal trying to acquiring the tokens for the resources, it is failing due to cookie gets deleted/expired. Hence tokens are not generating.

I have tried one approach like whenever i'm getting this error i redirected to login page (ex: authContext.login()),but which leads to infinite loop of authentication.

I'm getting above error in ie, edge, chrome, safari, mobile browses as well.
This is sporadic issue and not able to reproduce it.

In IE and Edge, we did some workaround to fix this by adding site urls (https://xyz.azurewebsites.net and https://login.microsoftonline.com) to trusted sites zone. But this fix is not working for some users in edge browser. Need to fix in other browsers as well. I dont want my users to add the sites urls to trusted sites zone always. Need a proper fix for this issue.

Adal library versions we are using
Adal.js v1.0.10
Adal-angular v1.0.7.

I saw same issues raised here  [#456](https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/456) , [#323](https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/323).

**Comment by liambolling** [comment]
Our team is having the same issue with this. Any updates on this?

**Comment by anpetral-msft** [comment]
Interested in hearing a recommendation too. Seeing this occasionally on clients with cached data that is old.

**Comment by rohitnarula7176** [comment]
@sandeepb6 @liambolling @anpetral-msft Can anyone provide a fiddler trace for the above issue which has two 302 responses , one for the login request (responseType = id_token) and another for the acquireToken (responseType = token and prompt = none) request.

**Comment by rohitnarula7176** [comment]
Closing this issue. Please reopen once you can provide a fiddler trace for this issue.
