### ISSUE TITLE
In chrome browser also getting AADSTS50058: A silent sign-in request was sent but no user is signed in. 

### ISSUE THREAD

**Issue by sandeepb6** [AzureAD/azure-activedirectory-library-for-js#675]
Hi,

Error: AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com).

I'm getting above error in chrome browser, mobile browser(safari) etc. but in the above error message mentioned that this issue will occur in IE/ Edge. 

frameRedirectUril is not renewing/creating the tokens for endpoints which are included ?

Please tell me how to fix this issue?

**Comment by rohitnarula7176** [comment]
@sandeepb6 Can you provide a code repro for this issue. You can get this error when you try to acquire a token silently in a hidden iframe and the cookies used to represent the user session are not sent with the request.

**Comment by sandeepb6** [comment]
@rohitnarula7176 

In angular config section 
`  adalAuthenticationServiceProvider.init(
                {
                    instance: config.Instance,
                    tenant: config.Tenant,
                    clientId: config.ClientId,

                    extraQueryParameter: 'nux=1',
                    endpoints: endpoints,
                    cacheLocation: 'localStorage',
                    frameRedirectUri: window.location.protocol + "//" + location.host + "/IFrame.html"
                }, $httpProvider); ` 

In IFrame.html i have below code
      `   adalProvider.init(
                    {
                        instance: adalSettings.instance,
                        tenant: adalSettings.tenant,
                        clientId: adalSettings.clientId,
                        extraQueryParameter: 'nux=1',
                        endpoints: adalSettings.endPoints,
                        cacheLocation: 'localStorage', // enable this for IE, as sessionStorage does not work for localhost.
                    },
                    $httpProvider
                );
          `

**Comment by rohitnarula7176** [comment]
@sandeepb6 Closing this issue for now. Please reopen once you have the fiddler trace as discussed over skype.

**Comment by DanielLitvak** [comment]
> @sandeepb6 Closing this issue for now. Please reopen once you have the fiddler trace as discussed over skype.

please see the errors others are facing. this happens when cross-site cookies are blocked: https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/323#issuecomment-601932294
