### ISSUE TITLE
add id_token_hint to logout url

### ISSUE THREAD

**Issue by Arikael** [AzureAD/azure-activedirectory-library-for-js#677]
When using on-prem ADFS 2016 with adal the postLogoutRedirectURI may not work.
ADFS complains with the event id 554 
`The specified redirect URL did not match any of the OAuth client's redirect URIs. The logout was successful but the client will not be redirected. ` 
which is a bit misleading because the redirect-URI itself is not the issue.

ADFS expect that you provide `id_token_hint` as an url parameter. If it is present ADFS redirects correctly.
I'm no ADFS expert but it may be related to the ADFS Behavior level ( https://msdn.microsoft.com/en-us/library/mt223852.aspx ).
Since I can't fiddle around with the behavior level, I need to find a solution on my side.

the value of id_token_hint has to be the token recieved by ADFS. It is stored in SessionStorage (by default) and can be read like
`sessionStorage.getItem('adal.idtoken')`

My suggestion is to either always append id_token_hint or have the possible to add it via config.

Or is there an already built in way to deal with this problem?

**Comment by Arikael** [comment]
I forked the repo and it works as described above
https://github.com/Arikael/azure-activedirectory-library-for-js

I will test a little further and then make a PR

**Comment by rohitnarula7176** [comment]
@Arikael I apologize for the late response. Adding id_token to the authorization request would lead to a lot of data on the wire and can cause issues like exceeding the url length limit for older browsers. You should be able to pass just the upn through extraQueryParameter in the config to achieve this behavior. I will talk to the ADFS team and revert back to you.

**Comment by Rickinio** [comment]
@rohitnarula7176  do you have any updates on the above? I'm having the same issue and following @Arikael 's solution at the moment. Is there any official way to solve it?
Many thanks in advance to both of you for your help and efforts.

**Comment by Arikael** [comment]
as far as I know `extraQueryParameter` won't be added to the logout url. So this is not viable solution. 
Correct me if I'm mistaken

**Comment by rohitnarula7176** [comment]
@Arikael @Rickinio You are correct. extraQueryParameter does not get added to the logout url. We do have a property you can pass to the config (public property of adal) called logOutUri which you can use to create a custom logout url along with id_token_hint or login_hint whichever is required. 
```
adalInstance.config.logOutUri = 'xxx'
```
Can you please use that as a solution for now and let me know if it works. I did not get a chance to talk to the adfs team yet and will do that next week. Please see the property you are supposed to assign below to achieve the same:
https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/9d24c364e59424cf4378faba565a79b4b2313d16/lib/adal.js#L860

**Comment by rohitnarula7176** [comment]
@Arikael Please use the solution above and reopen the issue if you still have problems.

**Comment by Rickinio** [comment]
@rohitnarula7176 i'm really sorry for my late response. I tried the above solution without success.

**Comment by ghost** [comment]
@rohitnarula7176 `logOutUri ` is not the right solution, when you use and on-prem AD (ADFS) with openid and as per openid document they recommended to bind the id_token_hint in logout url.

http://openid.net/specs/openid-connect-session-1_0.html#RPLogout

So, I think we should update the **AuthenticationContext.prototype.logOut** function and bind the id_token_hint when we call logout function.

`AuthenticationContext.prototype.logOut = function () {
        var idTokenInfo = this._getItem(this.CONSTANTS.STORAGE.IDTOKEN); // New Line
        this.clearCache();
        this._user = null;
        var urlNavigate;

        if (this.config.logOutUri) {
            urlNavigate = this.config.logOutUri;
        } else {
            var tenant = "common";
            var logout = "";

            if (this.config.tenant) {
                tenant = this.config.tenant;
            }

            if (this.config.postLogoutRedirectUri) {
                logout = "post_logout_redirect_uri=" + encodeURIComponent(this.config.postLogoutRedirectUri);
                logout += "&id_token_hint=" + idTokenInfo; // New Line
            }

            urlNavigate = this.instance + tenant + "/oauth2/logout?" + logout;
        }

        this.infoPii("Logout navigate to: " + urlNavigate);
        this.promptUser(urlNavigate);
    };`  
and above solution is for V.10.17 and it's inspired from - https://github.com/Arikael/azure-activedirectory-library-for-js/blob/dev/lib/adal.js   

and above solution is working for me as expected.

**Comment by Arikael** [comment]
sorry, I kinda lost track of this issue, although it still persists. We just chose to ignore it for the time being (our product is still in development).

but @rohitnarula7176 solutio seems cumbersome.
I would have to implement a way to automatically read the token info (is that even possible through adal.js). and add it to the logout url.

Is it even possible to add dynamic data (after initialization of adal) to adals config like suggested?

Even if it is possible, the best way would be to optionally enable the appending of the token hint via config.
