### ISSUE TITLE
Sporadic invalid_state errors during login

### ISSUE THREAD

**Issue by geetikasharma26** [AzureAD/azure-activedirectory-library-for-js#679]
Hi,
I am having the same issue as mentioned below reported by someone else as well. The earlier reported  issue number is #305.

Some of our customers fail to login our portal due to "Invalid_state" login error.
I claim this issue is sporadic, as I have evidences for users who got invalid_state error, but managed to login my portal successfully before and after this error.

I'm using the sessionStorage as ADAL JS's storage, and I'm suspecting sessionStorage inconsistency, i.e. login states which aren't saved in sessionStorage before redirecting to AAD or erased when redirecting back to my portal.

I have attached screenshots for the console and session storage errors.
![adal error 1](https://user-images.githubusercontent.com/8762706/33952998-627f69ee-dfe8-11e7-8180-b6427c9faf13.PNG)
![adal error](https://user-images.githubusercontent.com/8762706/33952999-629456d8-dfe8-11e7-929e-d2e70d33dd24.PNG)

** In the second screenshot, last line of console shows that it tried to access token from the session storage but something unexpected happened here and that was saved in the session storage.

**Comment by rohitnarula7176** [comment]
@geetikasharma26 There is known issue with IE/Edge browser where the local/session storage values are dropped when you redirect across zones during login. The invalid state error is thrown by adal when it tries to match the state received in the login response with the state saved in the storage. In this case since the state value is cleared during redirection, adal throws an error. You should not face this issue with Chrome. Can you please confirm if this works with Chrome?

**Comment by geetikasharma26** [comment]
It is there in Chrome as well. I have only tested my application in chrome and this is an intermittent issue there.

The system gets the token successfully for the client_id from Azure BUT when it tries to retrieve the same token from session storage, it gives the invalid state error

**Comment by rohitnarula7176** [comment]
@geetikasharma26 Can you please provide a code repro for this issue so I can look into this further.

**Comment by rohitnarula7176** [comment]
@geetikasharma26 Closing this issue for now. Please reopen once you have a code repro for this issue.
