### ISSUE TITLE
How to Stop aquireToken Forcing a Second Login

### ISSUE THREAD

**Issue by RehanSaeed** [AzureAD/azure-activedirectory-library-for-js#681]
This is the flow in my Vue.js SPA:

1. User visits site for first time, `login` is called in ADAL.js.
2. Redirect to Azure to login.
3. Azure redirects back to site, user is now logged in.
4. Site makes a GET request using `aquireToken`.
    - This works for Azure admin users who have granted permission.
    - Azure admin users who have not granted permission are erroring (AADSTS65001) and complaining about a consent screen, so I call `acquireTokenRedirect` but now the user is redirected back to a login screen and additional consent screen. The user is then redirected back to site and site can now perform GET requests.
    - Normal users get the error AADSTS90094 `the grand requires admin permission`

I have hit the 'Grant Permissions' button in the Azure portal and ideally I never want my users to see a consent screen. Is there a way I can perform a single login from the start and have all the permissions I need to perform GET requests?

According to the [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-conditional-access-developer#scenario-single-page-app-spa-using-adaljs):

> `login()` obtains an ID token through an interactive sign-in request but does not obtain access tokens for any service (including a conditional access protected web API). 

How can I force the `login` to also obtain access tokens for all services?

Here is the full TypeScript code I am using to perform login, logout and getting a token to make requests:

```
// @ts-ignore:
import AuthenticationContext from "adal-angular/dist/adal.min";
import AuthenticationStatus from "../../models/AuthenticationStatus";
import IUser from "../../models/IUser";
import Store from "../../stores/Store";
import ILoggerService from "../logger/ILoggerService";
import ISettingsService from "../settings/ISettingsService";
import IAuthenticationService from "./IAuthenticationService";

export default class AuthenticationService implements IAuthenticationService {

  public status: AuthenticationStatus = AuthenticationStatus.LoggedOut;
  private readonly authenticationContext: any;

  constructor(
    private readonly loggerService: ILoggerService,
    private readonly settingsService: ISettingsService) {
    this.settingsService = settingsService;
    const config: any = this.getConfig();
    this.authenticationContext = new AuthenticationContext(config);
    this.completeLogin();
  }

  public getToken(clientId: string): Promise<string> {
    return new Promise<string>((resolve, reject) => {
      this.authenticationContext.acquireToken(clientId, (errorDescription: string, token: string, error: string) => {
        if (error) {
          // reject(new Error(`${error}: ${errorDescription}`));
          this.authenticationContext.acquireTokenRedirect(clientId, null, null);
        } else if (token) {
          resolve(token);
        }
      });
    });
  }

  public login() {
    const user = this.authenticationContext.getCachedUser();
    if (!user) {
      this.status = AuthenticationStatus.LoggingIn;
      this.authenticationContext.login();
    }
  }

  public logout() {
    const user = this.authenticationContext.getCachedUser();
    if (user) {
      this.status = AuthenticationStatus.LoggingOut;
      this.setUser(undefined);
      this.authenticationContext.logOut();
    }
  }

  private completeLogin() {
    if (this.authenticationContext.isCallback(window.location.hash)) {
      this.authenticationContext.handleWindowCallback();
    }

    const user = this.authenticationContext.getCachedUser();
    if (user) {
      this.status = AuthenticationStatus.LoggedIn;
      this.setUser(user);
    }
  }

  private onLoggedIn(errorDescription: string, token: string, error: string) {
    if (error) {
      this.status = AuthenticationStatus.LoginError;
      let formattedError = JSON.stringify(error, null, 4);
      if (formattedError.length < 3) {
          formattedError = error;
      }
      const message = "Error calling " + errorDescription + ": " + formattedError;
      alert(message);
      this.loggerService.log(new Error(message));
    } else {
      this.status = AuthenticationStatus.LoggedIn;
      // The other case (redirect) is processed in the section guarded by the
      // authenticationContext.isCallback(window.location.hash) condition (see above)
    }
  }

  private getConfig(): any {
    const config: any = {
      clientId: this.settingsService.azureActiveDirectory.clientId,
      // endpoints: {
      //   [this.settingsService.academiesApi.url]: this.settingsService.academiesApi.clientId,
      //   [this.settingsService.appLoggingApi.url]: this.settingsService.appLoggingApi.clientId,
      //   [this.settingsService.employeeAttendanceApi.url]: this.settingsService.employeeAttendanceApi.clientId,
      //   [this.settingsService.employeesApi.url]: this.settingsService.employeesApi.clientId,
      //   [this.settingsService.tenantsApi.url]: this.settingsService.tenantsApi.clientId,
      // },
      redirectUri: window.location.href,
      tenant: this.settingsService.azureActiveDirectory.tenant,
    };
    config.callback = this.onLoggedIn;
    return config;
  }

  private setUser(value: any) {
    let user: IUser | undefined;
    if (value) {
      const profile = value.profile;
      user = {
        email: profile.email,
        familyName: profile.family_name,
        givenName: profile.given_name,
        name: profile.name,
        roles: profile.roles,
        uniqueName: profile.unique_name,
        userName: value.userName,
      };
    }
    Store.commit("user/user", user);
  }
}
```

**Comment by RehanSaeed** [comment]
Some additional information about my resources:

- SPA Application
  - 'User assignment Required' set to 'No'
  - I have hit the 'Gran Permissions' button in the Azure Portal for this and all API's below too
  - Has 'Application Permissions' to:
    - API 1
    - API 2
    - API 3

I have assigned no users to my SPA. I want every user in my AD to have access.

**Comment by rohitnarula7176** [comment]
@RehanSaeed There is no way to grant permissions to all the resources at the time of login as login method is just used to establish user context and not to obtain access_token for resources. There is a way to specify resource in the login url but since you can only pass a single resource (you cannot receive multiple access tokens in a single request), it is not extensible and hence is not included as part of the library.

**Comment by RehanSaeed** [comment]
So the only way is to use delegated permissions? This means that I have to set up a group containing all users in the directory and then add the required permissions. What makes me really sad is that permissions added to groups are not transitive, so I can't add permissions to an 'All users' group and then add an existing 'Sales users' group to it.
