### ISSUE TITLE
Bug: ADAL iFrame's Border is Visible

### ISSUE THREAD

**Issue by RehanSaeed** [AzureAD/azure-activedirectory-library-for-js#682]
Immediately after logging in, the iFrame is visible at the bottom of the page because it has a border width of `2px`, you should add a style to remove that. I'm using Bootstrap 4, so maybe the CSS reset doesn't cover this style.

![iframe](https://user-images.githubusercontent.com/2270364/34002428-788b842c-e0ea-11e7-947a-80bd54498642.png)

**Comment by rohitnarula7176** [comment]
@RehanSaeed The iframe border in the code is set to 0px as shown here https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal.js#L1677. Can you please explain how it is changed to '2px' in your code.

**Comment by RehanSaeed** [comment]
Not sure what's causing this issue.
