### ISSUE TITLE
how to use MFA to access outlook info : calendar, voicemail, contacts, calllogs  

### ISSUE THREAD

**Issue by michaelllh** [AzureAD/azure-activedirectory-library-for-js#685]
I want to develop a application to access outlook info with MFA account, But I did not found any develop info in microsoft websites, So I want to ask is there some development technical documentation about this?

**Comment by rohitnarula7176** [comment]
@michaelllh Please refer to the following link to get started. https://docs.microsoft.com/en-us/azure/active-directory/develop/guidedsetups/active-directory-javascriptspa
