### ISSUE TITLE
const keyword in adal code brakes my Angular build

### ISSUE THREAD

**Issue by tscislo** [AzureAD/azure-activedirectory-library-for-js#687]
In v 1.0.16 in line 1313 there is
`            const requestInfo = self.getRequestInfo(hash);`
this line makes adal output code not compatible with ES5 which is currently supported by PhantomJS, which makes it difficult for unit testing.

**Comment by grumar** [comment]
In my case, lib that I used had value `'adal-angular': ^1.0.15` in `package.json`.
After `npm install`  it was automaticlly upgraded to 1.0.16.
BTW using code not compatible with ES5 and upgrading only patch number was probably not a good idea.

**Comment by rohitnarula7176** [comment]
@tscislo @grumar Thank you for pointing out this issue. I have made a fix for this issue in the dev branch. Can you please test it and confirm if it resolves your issue. We will release an official version Jan first week due to holidays.
