### ISSUE TITLE
Error acquiring token

### ISSUE THREAD

**Issue by aXiniXe** [AzureAD/azure-activedirectory-library-for-js#689]
Hi,

My application upgraded adal-angular to version 1.0.16 and the logic to acquire token stopped working with the following error message:

adal.min.js:2 Uncaught TypeError: Cannot read property 'length' of undefined
    at AuthenticationContext.getRequestInfo (adal.min.js:2)
    at AuthenticationContext.handleWindowCallback (adal.min.js:2)

Upon investigation it seemed that the error is throw on the following line:

                for (var e = window.parent.renewStates, f = 0; f < e.length; f++)

-> where window.parant.renewStates seemed to be empty, causing the e.length to throw an error.

When reverting back to 1.0.15 the error doens't occur.

This issue could be related to other issues posted in the last days but I didn't seen any matching errors, besides the fact that there also is a token timeout log, but this is prolly normal.

Maybe also worth mentioning, I use the adal-angular4 library which in turn uses the adal-angular library.

**Comment by rohitnarula7176** [comment]
@aXiniXe I am not aware of the adal-angular4 library. We removed the renewStates property from window and added it as a private property (renamed to _renewStates) to avoid polluting the global namespace on the adalInstance.  I am guessing whoever is maintaining the adal-angular4 library would need to update his code to adapt to the newer version of adal. If you use the adal-angular package from the repo, you should not face any issues with token renewal. Please see this line in in the latest version https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/ea44890c606786a21f979addf9dfc27dfd3a9861/lib/adal.js#L1066
