### ISSUE TITLE
Unable to redirect to the given postLogoutRedirectUri when logging out on unauthorized login

### ISSUE THREAD

**Issue by geetikasharma26** [AzureAD/azure-activedirectory-library-for-js#694]
I am having issues while trying to log out of my application using adal.logout() method that eventually calls 'https://login.microsoftonline.com/common/oauth2/logout?post_logout_redirect_uri=<return‌​Url>'. When the user enters unauthorized credentials, it does log out properly but gets stuck on the logout window with this message ' You are signed out of your account. It's a good idea t close all the browser windows' but doesn't redirect to the postLogoutURL specified.

The redirection is fine if a user has logged in successfully and then signs out.

**Comment by rohitnarula7176** [comment]
@geetikasharma26 Can you please attach the fiddler trace for the case when it does and for the case it does not redirect to the postLogoutRedirectUri.

**Comment by geetikasharma26** [comment]
[FiddlerTrace_NoRedirection.zip](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/1616716/FiddlerTrace_NoRedirection.zip)
[FiddlerTrace_WithRedirection.zip](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/1616717/FiddlerTrace_WithRedirection.zip)

Attached are the fiddler traces for the two scenarios :
1.  No Redirection - When an unauthorized user tried to log in and signs out.
2.  Redirection successful - When a authorized user logs in and signs out.

**Comment by geetikasharma26** [comment]
Closed by mistake.

**Comment by rohitnarula7176** [comment]
@geetikasharma26 Can you elaborate on what you mean by an unauthorized user. How is he able to log in to your app without proper credentials?

**Comment by geetikasharma26** [comment]
So the unauthorized user is not logged on to the system , but he is given an option to logout because these credentials might be cached from any other application that might have been opened in the same session. So this unauthorized user, when logs out using the 'https://login.microsoftonline.com/common/oauth2/logout?post_logout_redirect_uri=<return‌​Url>', is not redirected back to the post_logout_redirect_uri specified after he is successfully logged out of any cached data.
