### ISSUE TITLE
Where to call acquireToken in AngularJS environment?

### ISSUE THREAD

**Issue by wy193777** [AzureAD/azure-activedirectory-library-for-js#695]
If I use AngualrJS and ADAL js like showed on reademe.md, how could I call acquireToken? It's not available on adalAuthenticationServiceProvider or this.context.

And there is no document mentioned this.

**Comment by rohitnarula7176** [comment]
@wy193777 If you see the point 7 in Readme, it shows how to register a controller and get an instance of adalAuthenticationService of adal-angular.js.  Please see below for a code sample.
```
app.controller('homeController', ['$scope','$rootScope', 'adalAuthenticationService', function ($scope, $rootScope, adalAuthenticationService) {

  $scope.acquireToken= function () {
            adalAuthenticationService.acquireToken(resource);
         };
  $scope.$on("adal:acquireTokenSuccess", function (event, token) {
        console.log(token);
        });
   $scope.$on("adal:acquireTokenFailure", function (event, errorDesc, error) {
        console.log(error);
        });

}]);
```
Please ensure that you are logged in first before you attempt to acquire a token for a resource.

**Comment by wy193777** [comment]
adalAuthenticationService isn't available on app.config() function. If I want to use the new token as  `Authorization` field or as query parameters on every request, I cannot find a convenient way to achieve this except to insert individually for every requests.

**Comment by nsksaisaravana** [comment]
What we have to pass for resource?

```
 $scope.acquireToken= function () {
            adalAuthenticationService.acquireToken(resource);
         };
```

**Comment by StevenLiekens** [comment]
@nsksaisaravana the resource is displayed in the azure portal under active directory/app registrations.
