### ISSUE TITLE
Angular 4: Acquire token to access either Azure AD Graph API or Microsoft Graph API after successful authentication

### ISSUE THREAD

**Issue by pmaluchuru** [AzureAD/azure-activedirectory-library-for-js#697]
We have Angular 4 SPA hosted in Azure and had included ADAL JS for authenticating against Azure AD (followed the steps mentioned in the following [blog](https://blogs.msdn.microsoft.com/premier_developer/2017/04/26/using-adal-with-angular2/)). We would like to make a call to Graph API (either Azure AD Graph API or Microsoft Graph API) to retrieve additional info of the signed in user.
--------------------------------------------------------------------------------------------------
In Azure AD, the App has the following permissions set:
Microsoft Graph API: 
Delegated permissions: View users' basic profile, View users' email address, Sign users in, Read directory data, Read all groups, Read all users' basic profiles, Read and write access to user profile, Sign in and read user profile

Windows Azure Active Directory : Application Permissions - Read directory data, Read all hidden memberships
Delegated permissions- Read all hidden memberships, Read directory data, Read all groups, Read all users' basic profiles, Sign in and read user profile
--------------------------------------------------------------------------------------------
We tried the following options after the user is authenticated and called handleCallback() method from Angular App:
1. Invoking acquireToken method by setting"https://graph.windows.net" as resource 
2. Invoking acquireToken method by setting"https://graph.microsoft.com" as resource 

In both instances, we got **undefined** object for the token and noticed the following in session storage:
1.  adal.token.renew.status6050eae0-fb21-418a-9fb8-b24193f6107a:"Completed" --> This is set for the app registered in Azure AD and upon login
2. adal.token.renew.statushttps://graph.microsoft.com:"In Progress"
3. adal.token.renew.statushttps://graph.windows.net:"In Progress"

The method used in the ADAL wrapper:
```
    public get acquireToken() {
        var newToken;
        this.context.acquireToken('https://graph.microsoft.com', function (error, token) {
            if (error) {                
                return newToken = null;
            }
            else {               
                return newToken = token;
            }
        });
        console.log("Acquired Token: ", newToken);
        return newToken;
    }
```
Is this the correct approach to invoke Graph API from Angular 4 App? 
Does ADAL JS only support Azure AD Graph API and not Microsoft Graph API due to different Azure AD endpoints  for login (versions v1.0 vs v2.0)?

**Comment by rohitnarula7176** [comment]
@pmaluchuru You can use adal to acquire a token for both. I see a couple of problems with your code. Since the acquireToken function is asynchronous, your code will jump to your console statement before the the completion of acquireToken and since newToken is undefined at that time, it will print undefined on the console. Please use the code pattern below:
```
 adalService.acquireToken('https://graph.windows.net', function (errorDesc, token, error) {
                console.log(errorDesc);
                console.log(token);
                console.log(error);
            });
```
In your case, the session storage should still have the session token. Can you open fiddler to see if the request is going out and if you get any response from AAD. Check for the response code 302 in fiddler. If your problem persists, please provide a code sample that I can run and debug.
