### ISSUE TITLE
The returned id_token is not parseable

### ISSUE THREAD

**Issue by manospasj** [AzureAD/azure-activedirectory-library-for-js#70]
I have followed your instructions but authentication fails and prints the following to the console:

<code>The returned id_token is not parseable.</code>
<code>Route change event for:/</code>
<code>Start login at:https://localhost:44308/#</code>
<code>Navigate url:https://login.windows.net/myapp.onmicrosoft.com/oauth2/authorize</code>
<code>Navigate to:https://login.windows.net/myapp.onmicrosoft.com/oauth2/authorize</code>
<code>TypeError: Cannot read property 'data' of undefined</code>

Then my web app redirects to its home page, authenication fails again and redirects again to homepage... infinitely...

**Comment by omercs** [comment]
Hey @manospasj ,

I suggest to follow the https://github.com/AzureADSamples/SinglePageApp-DotNet with your config initially. If you still have an issue, you can share your app js config.

**Comment by manospasj** [comment]
Hello @omercs ,

I have followed these instructions but didn't solve my problem.
After a lot of hours trying to debug it I found that it doesn't happen with all users. Let me explain...

The Azure Active Directory synchronizes its users with a local Active Directory and all synchronized users get this error.
If I create a user directly on Azure Active Directory (this user is not synchronized), the user can login to the application without any problem.

**Comment by eloekset** [comment]
@manospasj, do you know if the fix you're mentioning is merged? I get the same error in my console, and I've got special Norwegian characters in my name, but I'm not sure if my issue is about something else, because I get it when I logon with a test user without any special characters in the name also.

**Comment by manospasj** [comment]
@eloekset this has been merged for Greek characters (I don't know if there is something more to be done for Norwegian characters), but it's probably not your case. I had this issue only with accounts that had Greek characters. Other accounts could login normally. In any case, I suggest you to retrieve the token, try to decode it by yourself and then compare it with the decoded token from adal.js

**Comment by eloekset** [comment]
@manospasj, I found that the issue isn't related to the token itself. After debugging the adal code, I found that the problem is an exclamation mark before the id_token parameter in the return URI from Azure AD, so I opened #485.
