### ISSUE TITLE
I want to keep all parameters of a url 

### ISSUE THREAD

**Issue by Afdz1020** [AzureAD/azure-activedirectory-library-for-js#700]
I have the following url https://contoso.sharepoint.com.co/sites/sitename?wa=signin1.0, when I enter the site with this parameter ("wa" with value "signin1.0"), the page executes the adaljs library, the parameter disappears from the query string, and a hash appears "#" at the end of the url.  For example, the previous URL changes into https://contoso.sharepoint.com.co/sites/sitename#

I want to keep all parameters of a url.

**Comment by rohitnarula7176** [comment]
@Afdz1020 Adaljs using implicit flow where all tokens are received via a redirect response (302) and AAD does not preserve query string parameters on redirection. Unfortunately, this is by design.

**Comment by Afdz1020** [comment]
Thanks

**Comment by husseinkorly** [comment]
I know this is old, but I think adal.js will set the `loginStartPage` to `window.location.href` before it goes to AAD for authentication, and it will be returned to it after authentication by calling `handleWindowCallback` !

it looks like it is keeping the query parameter for me when I use Chrome, Edge, and Firefox (with having the developer tools open, I know this is funny but it is happening)
