### ISSUE TITLE
Call to acquireToken fails with "Set-Cookie header is ignored in response from url... Cookie length should be less than or equal to 4096 characters"

### ISSUE THREAD

**Issue by oviorus** [AzureAD/azure-activedirectory-library-for-js#702]
In my code I successfully call authenticationContext.login() a few lines later I call authenticationContext.acquireToken(...). The call to acquireToken fails with the message "Set-Cookie header is ignored in response from url... Cookie length should be less than or equal to 4096 characters"

Two requests are performed, one to get the id_token and the other to get an access_token, in both cases the http response contains a series of Set-Cookie headers (some values replaced for <**size in chars**>):

Set-Cookie: AADSSO=; expires=Wed, 17-Jan-2018 00:04:08 GMT; path=/; secure; HttpOnly
Set-Cookie: ESTSAUTHPERSISTENT=<**760 chars**>; domain=.login.microsoftonline.com; expires=Wed, 18-Apr-2018 00:04:09 GMT; path=/; secure; HttpOnly
Set-Cookie: ESTSAUTH=<**160 chars**>; domain=.login.microsoftonline.com; path=/; secure; HttpOnly
Set-Cookie: ESTSAUTHLIGHT=<**37 chars**>; path=/; secure
Set-Cookie: ESTSSC=00; path=/; secure; HttpOnly
Set-Cookie: buid=<**206 chars**>; expires=Sat, 17-Feb-2018 00:04:09 GMT; path=/; secure; HttpOnly
Set-Cookie: x-ms-sts-inner=1; expires=Sat, 17-Feb-2018 00:04:09 GMT; path=/; secure; HttpOnly
Set-Cookie: SignInStateCookie=<**2000 chars**>; path=/; secure; HttpOnly
Set-Cookie: SignInStateCookie1=<**1220 chars**>; domain=.login.microsoftonline.com; path=/; secure; HttpOnly
Set-Cookie: x-ms-gateway-slice=estsfirst; path=/; secure; HttpOnly
Set-Cookie: stsservicecookie=estsfirst; path=/; secure; HttpOnly

The second request fails, presumably due to the large amount of cookies already present.

CallStack:
(anonymous) @ adal.js:617
setTimeout (async)
AuthenticationContext._loadFrame @ adal.js:613
AuthenticationContext._loadFrameTimeout @ adal.js:585
AuthenticationContext._renewToken @ adal.js:516
AuthenticationContext.acquireToken @ adal.js:679
isAuthenticated.then @ AdalHelper.ts:200
_fulfilled @ q.js:854
(anonymous) @ q.js:883
Promise.promise.promiseDispatch @ q.js:816
(anonymous) @ q.js:570
runSingle @ q.js:137
flush @ q.js:125
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
nextTick @ q.js:180
Promise.then @ q.js:876
ensureLoggedIn @ AdalHelper.ts:152
_onLoad @ AppStart.tsx:34
Object.defineProperty.value @ AppStart.tsx:89
__webpack_require__ @ bootstrap 5d920cf1de51a5d08fac:19
(anonymous) @ main.js:28794
__webpack_require__ @ bootstrap 5d920cf1de51a5d08fac:19
Object.defineProperty.value @ bootstrap 5d920cf1de51a5d08fac:62
(anonymous) @ bootstrap 5d920cf1de51a5d08fac:62

**Comment by oviorus** [comment]
Turns out the issue was with my browser, clearing all cookies from all websites (not just localhost as I have been doing) solved the problem.

**Comment by caesarsol** [comment]
Hi, I am getting this error too. 
I guess clearing the cookies could clear it but doesn't mean it does not happen...

**Comment by ormico** [comment]
want to 2nd that. I'm getting this error also.

**Comment by olefrank** [comment]
Me too! Sounds wrong that I have to clear all cookies in browser, doesnt it?

**Comment by zackwithak13** [comment]
Has anyone found a resolution to this that doesn't involve clearing all cookies. It seems to be a recurring issue.

**Comment by epiphanizer** [comment]
I'm seeing this, and it's preventing the user from being able to properly authenticate whatsoever without opening an incognito window?
