### ISSUE TITLE
Use KMSI from microsoft app

### ISSUE THREAD

**Issue by johannes-z** [AzureAD/azure-activedirectory-library-for-js#705]
I ran into a problem using adal.js on a microsoft app that already requires signing in with a user. More specifically, I want to access the MS graph API via javascript in a sharepoint environment. However, I can't seem to figure out a way to use the currently logged in user in sharepoint for adal.js, resulting in two logins: one for sharepoint itself (which has KSMI checked), and one for authenticating via adal.js. 

Is there a workaround for this?

**Comment by rohitnarula7176** [comment]
@johannes-z You can achieve this in the latest version of AdalJs 1.0.16. In the case where user already has an existing session with AAD and you just want to acquire a token for a resource for the same user using Adal, you can set extraQueryParameter:'login_hint=xxx' in the adal config and directly call acquireToken without calling login first. In this scenario, adal will send the request with responseType = 'id_token token' in a hidden iframe to receive both an id_token to estabilish user context as well as an access_token for the specified resource.
This feature allows silent login as opposed to showing a UI in the case where the user has an existing session with AAD.

**Comment by johannes-z** [comment]
I added `extraQueryParameter: 'login_hint=<my_user_email>'` to the config I create the `AuthenticationContext` with. `authContext.login()` now lets me login silently without redirection/popup, but simply calling `authContext.acquireToken` without `.login()` did not work. This is the error I get:

> Token renewal operation failed due to timeout

Do you need more information for this issue?
