### ISSUE TITLE
ADAL JS Logout 

### ISSUE THREAD

**Issue by walunjsachin** [AzureAD/azure-activedirectory-library-for-js#707]
I am trying to logout of web application (HTML and Java script), i see below url generate in adal logout function to navigate.

**https://login.microsoftonline.com/common/oauth2/logout?post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Flogout.html%3Fautoaction%3Ddone**

It works fine in **Chrome consistently** and redirects me to my page mentioned in post logout redirect url but it **fails consistently in IE 11 or Edge browser**.

During testing, I am seeing below MS page loaded (which mentions that logout was successful)
_extract of the page shown...._

                    <div class="row text-title" id="login_workload_logo_text" role="heading">You signed out of your account</div>
                    <div class="row text-body text-block-body">
                        <div id="SignOutStatusMessage">It's a good idea to close all browser windows.</div>
                    </div>
                    <div class="row text-body text-block-body" id="InitiatorRedirectOption" style="display: none;">
                    </div>
But i noticed.. that function is signing out and calling InitiatorRedirect function but that function is empty... does not have any code to redirect... is there anything wrong with my redirect uri or any configuration?

function CompleteSignoutRender(signoutSuccessful) {
            signoutSuccessful = signoutSuccessful && true;
            if (!signoutSuccessful) {
                RenderSignoutFailure();
           }
            else {
                RenderSignoutSuccess();
              setTimeout('InitiatorRedirect()', 1000);
            }
        }
....
        function InitiatorRedirect() {
        }

Please help....

**Comment by rohitnarula7176** [comment]
@walunjsachin Closing this issue as this is not an issue with the library.
