### ISSUE TITLE
Adal JS with custom login page

### ISSUE THREAD

**Issue by oumaroudickoorckestra** [AzureAD/azure-activedirectory-library-for-js#709]
Hello,
Is it possible to use adal js with a custom login page. 
We would like to make our custom login page and then forward the user's information to azure for the authentication.

Thanks

**Comment by walunjsachin** [comment]
I understand it is not possible to have it in your application to take credential inputs to pass on to azure.  Instead it allows limited customization to login page for your organization branding.

Reference:
https://docs.microsoft.com/en-us/azure/active-directory/customize-branding

**Comment by rohitnarula7176** [comment]
@oumaroudickoorckestra It is not possible to have your custom login page. Please refer to the answer above.

**Comment by oumaroudickoorckestra** [comment]
Thanks your answer.

**Comment by amanaks** [comment]
I already have a custom login page which i can authenticate with my api. But its not allowing me call the api and its returning that 'User login is required|login required' . Can i stop the authentication for my own custom login.

Thanks
