### ISSUE TITLE
SPA ADFS and roles

### ISSUE THREAD

**Issue by thepill** [AzureAD/azure-activedirectory-library-for-js#711]
hi people,

i cant get my head around a simple SPA accessing a aspnet web api usding adaljs and (on-premise) ADFS 4.0.

I would like to show different things on the SPA using roles, but the access_token nor the Id_token are containing any role claims.

The adfs application is configured to return the role claims based on groups.
Am i miss understanding something crucial or must the role be present in the id_token/access_token?

Thanks in advice

**Comment by navyasric** [comment]
@thepill  As mentioned [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-token-and-claims#idtokens), for the role claims to be present in the id_token, the appRoles property must be defined in the application manifest. Here is an AAD [sample](https://github.com/Azure-Samples/active-directory-dotnet-webapp-roleclaims#step-2-define-your-application-roles) of a .Net app which has some instructions you and can follow for your SPA as well.

**Comment by thepill** [comment]
hi @navyasric thank yout for you information, but i think the provided link to `appRoles` does only belong to Azure Active Directory not to ADFS?

**Comment by rajsolanki73** [comment]
any update on this ?
