### ISSUE TITLE
Retrieving All Delegated Roles using ADAL.js

### ISSUE THREAD

**Issue by RehanSaeed** [AzureAD/azure-activedirectory-library-for-js#713]
I have the following scenario:

#### SPA Application
- User - Has a role with this name.

#### API Application
- Resource.Read.All - Has a role with this name

#### SPA Group
- Has the User and Resource.Read.All roles added as delegated permissions.

When I login using ADAL.js, the user object only contains the roles for the SPA:

```
const user = this.authenticationContext.getCachedUser();
const roles = user.roles; // Returns [ "User" ]
```

Is it possible to also retrieve the roles for the API application?

**Comment by navyasric** [comment]
@RehanSaeed Can you clarify about the SPA Group? Is it a single application registration with a SPA and an API component? In order to receive the roles claims, you will need to configure your application manifest. Here is a .net [sample](https://github.com/Azure-Samples/active-directory-dotnet-webapp-roleclaims) which shows how the configuration steps which may apply to your app.

**Comment by RehanSaeed** [comment]
It's as I've written above, two application registrations and a group in the Azure portal.

**Comment by RehanSaeed** [comment]
To be clear. The API is a separate application to the SPA application and has separate application roles.

**Comment by nehaagrawal** [comment]
@RehanSaeed can you please explain your user case. Why do you need the roles for both the SPA Application and the API?

**Comment by RehanSaeed** [comment]
I was wondering if I could use the API roles to perform hide/show parts of the SPA instead of duplicating the role in both the SPA and API.

**Comment by AWR14** [comment]
I want to show a different navigation items if the user is assigned to a certain group.

i can get the user but can't see where i get the groups, any working example of this?

`const user = this.authenticationContext.getCachedUser();`

**Comment by sameerag** [comment]
Please check https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1143 for this issue.

All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We would recommend to move to `msal js` for any advanced feature asks.
