### ISSUE TITLE
"const" keyword in adal.js file

### ISSUE THREAD

**Issue by davemcmanus** [AzureAD/azure-activedirectory-library-for-js#714]
Please remove the "const" keyword in the adal.js file. This is preventing my unit tests from running in PhantomJS because it does not recognize ES2015 syntax.

**Comment by alexander-zheglov** [comment]
+1

**Comment by lworkman** [comment]
I agree. It's currently breaking my script when it runs on websites set to IE10 mode (as in SharePoint online)

**Comment by rohitnarula7176** [comment]
@davemcmanus @alexander-zheglov @lworkman The const keyword has been removed in the dev branch. It will be part of our next release sometime next week.
