### ISSUE TITLE
Sign out a specific user account.

### ISSUE THREAD

**Issue by JimmyBoh** [AzureAD/azure-activedirectory-library-for-js#715]
Is there a way to sign out a specific user based on their id (email in our case)? I implemented an auto-sign out functionality but it sits at the "Which User Account" page rather. I'd like to decide which user account it should log out of, is that something I can specify? Thank you!!

**Comment by rohitnarula7176** [comment]
@JimmyBoh We currently do not have a way of doing this in the library.
