### ISSUE TITLE
Unecessary token renewal after valid token returned, causes invalid_state

### ISSUE THREAD

**Issue by seel93** [AzureAD/azure-activedirectory-library-for-js#717]
I am trying to run a SPA(angularjs, webpack) deployed with azure app service, but non of the API calls are triggered.

After login I'm redirected back from Microsoft, the Adal token in session storage is valid, but as soon as i change the route, the token is invalid and nothing works. 

The API calls are not running and there are no xhr request in the network tab. I am clueless as to why this i happening, please help!

Running this app in localhost is no problem. The source code on the server and my local machine are identical.

**Comment by rohitnarula7176** [comment]
@seel93 Can you please attach a code repro for this issue so I can investigate this further.

**Comment by nehaagrawal** [comment]
@seel93 is there any exception in the console? Also if you are not comfortable sharing your repo, is it possible for you to create a very basic sample application with just the adal library usage.

**Comment by seel93** [comment]
The problem was related to this issue: 
https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/523

But it has been fixed in the latest version of adal. Everything works now. Apologies for late answer
