### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by kov-hans** [AzureAD/azure-activedirectory-library-for-js#718]
Hi!
I'm coding an Angular5 app and I'm using the adal-angular4 wrapper and I can't get aquireToken to work.
After debugging this is what I think is happening.
1. I call aquireToken. 
2. An authorize request is sent and when the token is returned my app is restarted.
3. The restart starts with that I initialize my adal-angular4 service which calls the inject method to create the AuthenticationContext object. At this point there is no information about onging token renewals in the context object and the service cannot match the incomning token and therfor discards it.
4. If I wait a few seconds and debug the AuthenticationContext object the information about the token renewal is there, but at this time the wrapper has discarded the received token so nothing will happen.

My question is if there might be a delay before the AuthenticationContext object is populated with the token renewal information and if there is a way for me or the wrapper to wait for this information to be populated? I'm very thankful for every help I can get to resolve this issue or if you can recommend a better library to use with my angular5 application.
Thanks!

**Comment by rohitnarula7176** [comment]
@kov-hans Most likely the wrapper you are using is not updated with the latest code of Adaljs or the wrapper is not written correctly. Can you provide a code repro of this issue?

**Comment by kov-hans** [comment]
Hi!
Thank you so much for helping me with this!
1. Edit src/environments/environment.ts and add configuration needed for the application and the api.
2. npm install
3 ng serve -o
4. Click Login.
5. After successful login click the aquireToken link.
6. In the src/app/header/header.component.ts you can see the call to aquireToken.
7 When the token is received, the ngOnInit method is called in src/app/app.component.ts . In this method handleWindowCallback is called in the wrapper, but at this point of time there is no information about the expected state in the context object, and therefore the token is not stored.
8. If you click the aquireToken link again, the renewal information is back in the context object and there is no further authorize requests sent.


[AdalAngular5Sample.zip](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/1762058/AdalAngular5Sample.zip)

**Comment by JoshSchoen** [comment]
Any resolution to this? I am seeing the same thing.

**Comment by rohitnarula7176** [comment]
@JoshSchoen The adal-angular4 wrapper is not written by Microsoft. Can someone attach a sample code snippet for this issue which we can run on our machine?

**Comment by Ro3A** [comment]
I'm running into this issue as well. I'm running angular 5 in a .net core project, that connects to a .net core web api project. Both on local hosts, different ports. Both are registered in Azure AD and everything works as expected until the token expires. 

WHen I'm using the adal-angular4 wrapper and the interceptor that comes with it, I can confirm that when adal.js enters into getResourceForEndpoint, there is no condition in which it would return a proper clientId - at least for localhost. The port numbers are different, so the redirectUrl and the requested endpoint will never match. In production, this wouldn't be an issue. At least not for us. 

My question, in addition to this, is what should the object look like for endpoints property? I've got an array of strings right now, but when looping through endpoints, var configEndpoint is equal to 0, which is the index of the item in the array which mean  if (endpoint.indexOf(configEndpoint) > -1) will fail. 

 See the highlighted line in the picture (ignore the uri value - I was trying different things while debugging)

![image](https://user-images.githubusercontent.com/19931334/42049992-b5387f3a-7ad5-11e8-8335-e9283af8ed5d.png)

**Comment by nehaagrawal** [comment]
Closing this issue due to lack of response from the user. Please feel free to open it if the issue still exist.
