### ISSUE TITLE
Adal Authentication is working fine for Win 8.1 but nt working on win 8

### ISSUE THREAD

**Issue by shilsmarty** [AzureAD/azure-activedirectory-library-for-js#72]
ADAL working for win 8.1 but not with win 8 
is there any operating system prerequisite for using ADAL ?

**Comment by omercs** [comment]
No. It uses html5 features which is related to the IE version. Is your browser support HTML5 sessionStorage/localStorage.

**Comment by shilsmarty** [comment]
Thanks for your Reply , so if I deploy this application in production ,is thr any prerequisite for the End User in terms of Browser Version before accessing the Site ?

**Comment by omercs** [comment]
Yes, html5 support is related to browser version. You can see the list here: http://caniuse.com/#search=html5

**Comment by omercs** [comment]
There is only html5 support requirement.
