### ISSUE TITLE
I can not complete the authentication flow

### ISSUE THREAD

**Issue by chenxizhang** [AzureAD/azure-activedirectory-library-for-js#724]
Hi there , i just create a simple html page to test adal js library, but i always failure . The browser is always refresh but i can't get back to the page and get the token

It is urgent for me because we need to help our customer to get start with this library, so if you can reply quickly, it will be very important for me.

thank you 

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    
    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.17/js/adal.min.js"></script>
    <script>

        window.config = {
            clientId: '78ebeedb-b860-4260-b3ce-282be39694ce',
            redirectUri: 'http://localhost:8081/'
        }

        var authContext = new AuthenticationContext(config);

        var user = authContext.getCachedUser();
        if (!user) {
            authContext.login();
        }

        authContext.acquireToken("https://graph.microsoft.com", function (error,token) {
            console.log(token);
        });

    </script>
</head>
<body>

</body>
</html>

**Comment by chenxizhang** [comment]
@rohitnarula7176  could you please take a look this issue, thank you very much

**Comment by rohitnarula7176** [comment]
@chenxizhang I sent you the working snippet via email. Please use that to resolve your issue.
