### ISSUE TITLE
Token renewal operation failed due to timeout null ( Azure API call from SharePoint Online)

### ISSUE THREAD

**Issue by brajeshb** [AzureAD/azure-activedirectory-library-for-js#726]
I have requirement to call azure web api from SharePoint online. But no luck till now to get across. Please share any reference, if available.  Check my code as below
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.17/js/adal.min.js"></script>
<script type="text/javascript">

function CallAzureAPI() {
	"use strict";
	// assign variables
	window.accessToken = null;
	window.tokenDefer = $.Deferred();
	var variables = { 
	   // Domain of Azure AD tenant 
	   azureAD: "", 
	   // ClientId of Azure AD application principal 
	   clientId: "" 
	} 

	// Create config and get AuthenticationContext
	window.config = {
		clientId: variables.clientId,
		postLogoutRedirectUri: window.location.origin,
		cacheLocation: 'localStorage'		
	};

	var authContext = new AuthenticationContext(config);
	// Check For & Handle Redirect From AAD After Login
	var isCallback = authContext.isCallback(window.location.hash);

	authContext.handleWindowCallback();

	if (isCallback && !authContext.getLoginError()) 
	{
		window.location = authContext._getItem(authContext.CONSTANTS.STORAGE.LOGIN_REQUEST);
	}
	var cachedToken = authContext.getCachedToken(window.config.clientId);
	if(cachedToken)
	{
		console.log("user already logged in");
		// Logged in already
		authContext.acquireToken(authContext.config.loginResource, function (error, token) {
			if (error || !token) {
				console.log("ADAL error occurred: " + error);
				window.tokenDefer.reject();
			}
			else
			{
				console.log("got the token.. resolving tokendefer");
				window.accessToken = token;
				window.tokenDefer.resolve(token);
			}
		});		
	}
	else
	{
		authContext.login();
	}
}
</script>
<input type='button' value='Call Azure API' onclick="CallAzureAPI();"/>

**Comment by sameerag** [comment]
All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We would recommend to move to `msal js` for any advanced feature asks.
