### ISSUE TITLE
doing Acquire Token with Username and Password

### ISSUE THREAD

**Issue by aboodh95** [AzureAD/azure-activedirectory-library-for-js#728]
Hi

can i perform AquireToken with the user credential, i don't want to redirect him or show pup-op window, 

Is this possible

**Comment by navyasric** [comment]
Adal.js does not have support for acquireToken with username and password. If you can first establish an authenticated user session or context , you can then use acquireToken to obtain tokens silently without interaction by setting the login_hint as extra query parameter in the Adal.js context.
