### ISSUE TITLE
ADAL authentication for web api REST service

### ISSUE THREAD

**Issue by shilsmarty** [AzureAD/azure-activedirectory-library-for-js#73]
ADAL implementation for UI is working fine ,

but my Web Api REST service is separate solution , and will be deployed on another endpoint ,
is ADAL can secure service too ?

**Comment by omercs** [comment]
We have server side libraries to secure that. Please check the sample to see the packages used.
https://github.com/AzureADSamples/SinglePageApp-DotNet/blob/master/TodoSPA/packages.config

**Comment by BenGale** [comment]
I found this really helpful as a jumping off point: https://github.com/AzureADSamples/SinglePageApp-DotNet

**Comment by shilsmarty** [comment]
Thanks Ben and omercs for you reply , but let suppose I tried to deploy Web Application (Angular JS using Adal.js library) on http://localhost:44302 and Web Api on http://localhost:44300 , do you think still this Solution will work and webApi is secured. ?

**Comment by omercs** [comment]
WebApi will accept tokens that is matching the audience after you put Authorize attribute on Controllers. You can check our samples to see the usage.
