### ISSUE TITLE
Bundle Size

### ISSUE THREAD

**Issue by MarkHerhold** [AzureAD/azure-activedirectory-library-for-js#732]
Please consider reducing the number of things bundled with adal in npm. Most people don't need the `tests/*`, `.jshint`, `karma.conf.js`, `Gruntfile.js`, or `changelog.txt` files.

**Comment by rohitnarula7176** [comment]
@MarkHerhold Thank you for the feedback. We have that to ensure that the external contributors can run all the tests before submitting a pull request. We can look at removing that from the bundle.
