### ISSUE TITLE
Not logging in for MFA enabled accounts

### ISSUE THREAD

**Issue by HarshitJn** [AzureAD/azure-activedirectory-library-for-js#733]
I am not able to login to my account which has MFA enabled. On calling login everything works fine but I never get an option for multi factor authentication and the popup just closes leaving me in un-logged in state. I am using angular 5.1.2 and ng2-adal along with angular-adal.

I get the following in hash:
#error=interaction_required&error_description=AADSTS50079%3a+The+user+is+required+to+use+multi-factor+authentication

**Comment by rohitnarula7176** [comment]
@HarshitJn Can you try calling acquireTokenPopup for the resource which require MFA. You will need to consent once for the resource and you can then call acquireToken to get the token silently for subsequent calls.

**Comment by HarshitJn** [comment]
Actually I am using ng2-adal library in my angular project and it doesnt provide any functionality to call acquireTokenPopup(). I tried to call this function explicitly after login by changing some code in that library but it didnt do anything.

**Comment by nehaagrawal** [comment]
@HarshitJn  ng2-adal is not supported by us https://www.npmjs.com/package/ng2-adal. Please open issue on their github repository.
