### ISSUE TITLE
Support a silent renew link for using in the renew Iframe

### ISSUE THREAD

**Issue by Wozbo** [AzureAD/azure-activedirectory-library-for-js#743]
When renewing a token, the site should support a separate renew URL.  This allows us to not have to reload an angular application/ do other processing logic and have a lightweight renewal page.

**Comment by rohitnarula7176** [comment]
@Wozbo You can do that by specifying a separate redirectUrl to just receive the tokens.

**Comment by rohitnarula7176** [comment]
@Wozbo Closing this issue due to lack of response. Please reopen if it is not resolved for you.
