### ISSUE TITLE
unable to login in IE using adal 5

### ISSUE THREAD

**Issue by NiranjanAbb** [AzureAD/azure-activedirectory-library-for-js#745]
I am using Adal 5 for Azure authentication. It works fine in localhost. When I host my website in azure and try to login in IE, it just reloads the page. Popup will not come to enter email id. It works fine in other browsers.

Below is my code snippet. 

this.adalSvc.login();

**Comment by rohitnarula7176** [comment]
@NiranjanAbb This seems to be out of scope for the library and more of a browser issue. We have existing issues with the Edge browser which are listed in the wiki.
