### ISSUE TITLE
Upgrade to Angular 6.0 - Issue due to deprecation of shims

### ISSUE THREAD

**Issue by silver-stack** [AzureAD/azure-activedirectory-library-for-js#747]
Hello, I have recently upgraded one of our projects that uses adal-angular from version 5.2 to 6.0 and we are receiving the following error within browser console:

```
adal.js?5e4c:1 Uncaught ReferenceError: global is not defined 
at Object../node_modules/expose-loader/index.js?AuthenticationContext!./node_modules/adal-angular/lib/adal.js-exposed (adal.js?5e4c:1)
```

After some further investigation I believe that this issue is related to the removal of shims from version 6.0.  There is more information here: [#9827 (comment)](https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814)

To assist a little, we are importing as follows:

```
import {adal, AuthenticationContext} from '../../../../node_modules/adal-angular/lib/adal.js'; 
import 'expose-loader?AuthenticationContext!../../../../node_modules/adal-angular/lib/adal.js'; 
```
I'll admit that I know little about shims, however if there is a work around that you know of it would be much appreciated.

Unfortunately I am not able to update the title, I should have wrote shims being made obsolete (not deprecated).

Kind Regards,
silver-stack

**Comment by evnexus** [comment]
Hi silver-stack,

Have you tried this solution?
https://github.com/angular/angular-cli/issues/8160#issuecomment-386153833

**Comment by rohitnarula7176** [comment]
@silver-stack adal-angular 5.2 is not written by Microsoft and hence it is out of scope for the library. Closing this issue.

**Comment by ErikErkelens** [comment]
Some guidance on how to use the library with Angular 6 would be welcome. The following *was* written by Microsoft and has the same issue described here https://blogs.msdn.microsoft.com/premier_developer/2017/04/26/using-adal-with-angular2/

**Comment by JACrazy** [comment]
This blog post by Microsoft shows how to use adal.js with Angular 4+, the example is done with Angular-CLI 7.0.0-rc.1.
https://blogs.msdn.microsoft.com/premier_developer/2018/10/24/using-adal-js-with-angular4/
