### ISSUE TITLE
Is ADAL works only on javascript clients/SPA running on browser and not desktop office add-in apps?

### ISSUE THREAD

**Issue by prashantharshi** [AzureAD/azure-activedirectory-library-for-js#748]
Hi 

We are creating an add-in for word desktop , and we want to use ADAL. Will it work fully functional there on desktop clients as well ? i have read from many posts that it is designed to work mostly with javascript clients running on browser

**Comment by nehaagrawal** [comment]
@prashantharshi  can you please confirm what language/platform you are using?

**Comment by nehaagrawal** [comment]
@prashantharshi ADAL is a javascript library and we support javascript and angular framework currently. I am closing this issue for now. Feel free to open it again if your question wasn't answered.
