### ISSUE TITLE
getResourceForEndpoint may contain a bug

### ISSUE THREAD

**Issue by Alaiven** [AzureAD/azure-activedirectory-library-for-js#753]
Isn't this code:

` for (var configEndpoint in this.config.endpoints) { ....`

in [adal.js, line 1263](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/49ecdcc655312a111d470858cb424c3c609de4d7/lib/adal.js#L1263) iterating over indices of array, instead of values?

EDIT:

From other examples, I see, that the `endpoints` property has to be an object, and everything works normally.

**Comment by rohitnarula7176** [comment]
@Alaiven endpoints is an object with key-value pair. We are iterating over the keys and then extracting the value from the specific key. This is the correct way of doing it. Closing this issue. Please reopen if you still face issues.
