### ISSUE TITLE
renewToken response with handleWindowCallback calls callback with null token unless acquireToken has been called

### ISSUE THREAD

**Issue by RobPethick** [AzureAD/azure-activedirectory-library-for-js#754]
I am calling renewToken to get my access_token and then using handleWindowCallback to 

From line 1340 
```if ((requestInfo.requestType === this.REQUEST_TYPE.RENEW_TOKEN) && window.parent) {
                if (window.parent !== window) {
                    self.verbose("Window is in iframe, acquiring token silently");
                } else {
                    self.verbose("acquiring token interactive in progress");
                }

                token = requestInfo.parameters[self.CONSTANTS.ACCESS_TOKEN] || requestInfo.parameters[self.CONSTANTS.ID_TOKEN];
                tokenType = self.CONSTANTS.ACCESS_TOKEN;
            } else if (requestInfo.requestType === this.REQUEST_TYPE.LOGIN) {
                token = requestInfo.parameters[self.CONSTANTS.ID_TOKEN];
                tokenType = self.CONSTANTS.ID_TOKEN;
            }
```

The issue is that we need requestInfo.requestType to be RENEW_TOKEN but it isn't set to RENEW_TOKEN in the _renewToken method (it does set it in the acquireToken method).

I think we just need to set the requestType in the renewToken

**Comment by rohitnarula7176** [comment]
@RobPethick You should not call renewToken directly as it is a private method. You should call acquireToken which internally calls renewToken. Can you explain the need to call the private api directly.

**Comment by RobPethick** [comment]
nope - I was unaware this was the wrong method - I have switched to acquireToken and it works fine
I couldn't find docs to explain what the public methods were - am I missing them somewhere?

**Comment by RobPethick** [comment]
NP - it is working great for me now
