### ISSUE TITLE
'prompt=none' not set? Can account selection be omitted?

### ISSUE THREAD

**Issue by MrTiny75** [AzureAD/azure-activedirectory-library-for-js#757]
The parameter prompt get removed from query parameters at adal.js line 504 . For my purpose I need prompt to be set to none. Although the comment at line 502 mentions that prompt get set to none I cannot find any code that really sets prompt to none. Is it missing? When I add "urlNavigate = urlNavigate + '&prompt=none' " by myself less prompts appear. 
Anyway I get offered to select another user account sometimes.  Is it possible to omit this prompt and to use the standard account by default?

**Comment by nehaagrawal** [comment]
@MrTiny75  You can pass the prompt parameter as none(prompt=none) in extraQueryParameter . The recommended value for prompt is 'select_account' for login. The reason for this is if you have multiple accounts in your session/cookie then STS wouldn't know which account to select.

**Comment by nehaagrawal** [comment]
@MrTiny75  The recommended value for prompt is 'select_account' for login. promp=node is not a valid value for login API.

**Comment by sameerag** [comment]
All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We would recommend to move to `msal js` for any advanced feature asks.
