### ISSUE TITLE
clientId is required on init

### ISSUE THREAD

**Issue by CodeTroopers** [AzureAD/azure-activedirectory-library-for-js#763]
When we use a login page with several authentication providers (Azure AD and ADFS for example), the clientId to use could be different.
But we cannot initialize adaljs without clientId.

I want initialize with : 
```
adalAuthenticationServiceProvider.init({
        requireADLogin: true,
        localLoginUrl: "/login",
	anonymousEndpoints: ["login"]
}, $httpProvider);
```

And then login based on selection of configuration in the login view :
```
$scope.externalLogin = function (authenticationProvider) {
	adalAuthenticationService.config.tenant = authenticationProvider.Properties["Tenant"];
	adalAuthenticationService.config.clientId = authenticationProvider.Properties["Audience"];
	adalAuthenticationService.login();
};
```

**Comment by nehaagrawal** [comment]
@navyasric Can you please take a look.

**Comment by navyasric** [comment]
@CodeTroopers ADAL designed to set up an authentication context for an application with Azure AD or ADFS directory before making requests to it and therefore needs a registered application client ID to initialize. Ideally, there is one ADAL authentication context associated with each client ID. 
It is recommended you perform the init of ADAL service provider after the application determines the tenant and client ID.

**Comment by CodeTroopers** [comment]
I need to initialize ADAL in the configuration of my angularjs application to perform redirection on the login view for state requiring authentication.

Here an example of my states configuration:
```
$stateProvider.state('login', {
        url: "/login",
        views: {
            'content': {
                templateUrl: 'App/Views/Login/login.html',
                controller: 'loginCtrl'
            }
        },
        requireADLogin: false
    }).state('selfService', {
        url: "/selfservice",
        views: {
            'content': {
                templateUrl: 'App/Views/SelfService/selfService.html',
                controller: 'selfServiceCtrl'
            }
        },
        requireADLogin: false
    }).state('home', {
        url: "/home",
        views: {
            'content': {
                templateUrl: 'App/Views/Home/home.html',
                controller: 'homeCtrl'
            }
        },
        requireADLogin: true
    });

    //TODO: initialiaze ADAL
```

But at this moment i don't know the clientId because it depends of the user choice : he can chose to authentify on ADFS or on Azure AD and the clientId can be different between the 2

**Comment by sameerag** [comment]
All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We would recommend to move to `msal js` for any advanced feature asks.
