### ISSUE TITLE
Redirect URI should end with /

### ISSUE THREAD

**Issue by MarkHerhold** [AzureAD/azure-activedirectory-library-for-js#769]
Per [this issue](https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/451), ADAL should probably help users out by adding a trailing `/` or error out when one is not provided in the redirect URI.

**Comment by asnow003** [comment]
@MarkHerhold I just did a generic test on my mac using the latest Safari in Sierra.  I tested using one of our basic samples and didn't see an error.  Could you provide your error or a sample that demonstrates the issue?

**Comment by MarkHerhold** [comment]
I used the same environment. I must be wrong or there must also be some other factor at play.
