### ISSUE TITLE
All tabs point to the same page if opened quickly after redirecting from login.microsoft.com

### ISSUE THREAD

**Issue by reddykkk** [AzureAD/azure-activedirectory-library-for-js#771]
We are using adal.js in our site. If we quickly open multiple links in new tabs, after getting token from login.microsoft.com they all point to the same site.

We are setting cacheLocaton: 'localStorage'. We can set it to sessionStorage, but this is causing loops when authentication.

Here is how I can repro it easily - let's say our site www.abcd.com and we have links like www.abcd.com/1, www.abcd.com/2, www.abcd.com/3 etc. I sent a mail myself with these links, clear browser cache and open these links quickly from the mail. After fetching token, all these point to the same url like www.abcd.com/1

We are using adal-angular version 1.0.17

**Comment by nehaagrawal** [comment]
@reddykkk  is there a sample repo that you can share with us to reproduce this issue? 
For the loops issues, which browser are you seeing this issue?

**Comment by jmckennon** [comment]
Closing this issue as there hasn't been a response in some time, and we're assuming this is no longer a problem. 

Additionally, all current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
