### ISSUE TITLE
Should AuthenticationContext.aquireToken() check for "loginError" ?

### ISSUE THREAD

**Issue by cadichris** [AzureAD/azure-activedirectory-library-for-js#772]
Hi there,

While working with [`react-adal`](https://github.com/salvoravida/react-adal/) I faced an issue where I got an infinite login loop for users that are **not authorized** to access my application.

In other words :
 1. User visits `http://myapp/`
 1. Azure authentication window is displayed
 1. User logs in, with a account that **can't access** `http://myapp/`
 1. User is redirected to `http://myapp/#error=access_denied`
 1. Due to `adal` code (that is the topic of this issue) user is redirected to `http://myapp/`
 1. Azure authentication is displayed (2) 💥 there goes the infinite loop

I went for [a bit of digging into the code](https://github.com/salvoravida/react-adal/issues/33#issuecomment-401043119), to see what was causing the redirection to `http://myapp/` at (5).

The result of this investigation is that I don't understand why `adal`, in `acquireToken()`, does not check `getLoginError()` **before** indicating `callback('User login is required', null, 'login required');`

In other words, I don't understand why [this piece of code](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/e9d23e719eccf2341ee38b11323101fb14cb9610/lib/adal.js#L652) doest not check `getLoginError()`:

```js
if (!this._user && !(this.config.extraQueryParameter && this.config.extraQueryParameter.indexOf('login_hint') !== -1)) {
  this.warn('User login is required');
  callback('User login is required', null, 'login required');
  return;
}
```

`this._user` is not set, but it could be due to a login error that occurred after the user actually tried to login...no ?

Would it make sense, in `acquireToken()` to have something like: 

```js
if (!this._user && this.getLoginError()) {
  this.warn('User login failed');
  callback('User login failed', null, 'login failed');
  return;
}

// then, the current code
if (!this._user && !(this.config.extraQueryParameter && this.config.extraQueryParameter.indexOf('login_hint') !== -1)) {
  this.warn('User login is required');
  callback('User login is required', null, 'login required');
  return;
}
```

I _can_ fix my problem by changing code in `react-adal`, but I'd really like to have your opinion on this.

**Comment by miguelemosreverte** [comment]
It truly is a shame that such a detailed post is received like this by the community and collaborators of the project.

**Comment by miguelemosreverte** [comment]
Hey we managed to fix this problem, in a (sadly necessary) work-around way.

Check out *our repo!

**Comment by chan4lk** [comment]
How did you fix this ? I am still getting this error.

**Comment by miguelemosreverte** [comment]
@chan4lk 
I am so sorry I cannot provide you of the repo because the company I worked for decided it would not go the open-source way, and asked for removal.

Now let me tell you, what I did was at most 4 days of work, nothing more. 
Information is out there, just iterate over the proposed solutions until you land a stable solution and then please come back and propose a link to a repo like I did on November 2018.

Again, sorry for not reproducing the solution I made for the company I worked for, it was up to them to censor it to the community. But still, good news are that I did not provide of a new solution: Just a formalization of the StackOverflow answers on the topic.

**Comment by zsid** [comment]
Hi,

I am having the same problem with the infinite loop when working with `react-adal`. Are there any plans to address it soon? Is this repo not supported any more?

**Comment by CadiChris** [comment]
Hi @zsid. I don't know if changes have happen in the `adal` library, but a new version of `react-adal` is now available. Maybe you can try it https://github.com/salvoravida/react-adal/issues/33#issuecomment-536196697

**Comment by salvoravida** [comment]
@zsid it would be great a feedback on your use case!

Salvo

**Comment by zsid** [comment]
I will update to the packages later this week and test it out

**Comment by jmckennon** [comment]
Unfortunately, `adal js` is generally not being updated except for high priority security fixes. You may have to defer to the `react-adal` maintainers for a workaround. Infinite redirect loops are a known bug here.

We also recommend that people move to the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js), as this is the library that is getting all of Microsoft's current support. We have plans for an official react implementation on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap). There is also an active community project called [react-aad-msal](https://www.npmjs.com/package/react-aad-msal) that helps integrate `msal js` into a react app.
