### ISSUE TITLE
feat(storage): ability to pass a custom storage #775

### ISSUE THREAD

**Issue by 4F2E4A2E** [AzureAD/azure-activedirectory-library-for-js#776]
Some apps in the enterprise have the requirement to encrypt all it's client data on the storage.
This is a request for adal-angular to support a custom localStorage or a custom sessionStorage.

For more information, please checkout this PR: https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/775

**Comment by jmckennon** [comment]
Unfortunately, `adal js` is only being updated for security fixes, and we do not intend to support a custom storage option for `adal js` at this time. We recommend using the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) to get new features and bugfixes.

If you are still looking to use a custom storage, we recommend using one of the other msal libraries listed [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-v2-libraries), as `msal@1.2.0` still does not support custom storage options. We are 100% confident in our local storage and caching techniques to keep them secure.
