### ISSUE TITLE
Bower is deprecated, consider using an alternative

### ISSUE THREAD

**Issue by macqm** [AzureAD/azure-activedirectory-library-for-js#785]
During npm install, npm warns about bower being deprecated:
```npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/```

**Comment by nehaagrawal** [comment]
@macqm Thanks for reporting this.
