### ISSUE TITLE
adalRenewFrame iFrame's borderWidth not set correctly

### ISSUE THREAD

**Issue by dlannoye** [AzureAD/azure-activedirectory-library-for-js#788]
It looks like this issues has been previous reported in #682 & #562, but has never been fixed in the library. The root cause is the code setting the borderWidth to "0px" isn't setting it through the element's style property so it is not respected by browsers.

In [adal.js](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/e9d23e719eccf2341ee38b11323101fb14cb9610/lib/adal.js#L1687) this line should be updated:
```
ifr.style.width = ifr.style.height = ifr.borderWidth = '0px';
```
to
```
ifr.style.width = ifr.style.height = ifr.style.borderWidth = '0px';
```

**Comment by dlannoye** [comment]
FYI, I opened PR #789 with a fix for this issue

**Comment by rohitnarula7176** [comment]
@dlannoye Closing this issue. Fixed and merged in dev.
