### ISSUE TITLE
Refused to display  in a frame because it set 'X-Frame-Options' to 'deny'.

### ISSUE THREAD

**Issue by BartVDACodeware** [AzureAD/azure-activedirectory-library-for-js#79]
Hi,
I have implemented the adal library in Visual Studio Hybrid App (Cordova)
When I try to run in in the ripple emulator I got 

"Refused to display 'https://login.microsoftonline.com/login.srf?wa=wsignin1.0&wtrealm=....' 
in a frame because it set 'X-Frame-Options' to 'deny'."

It is working fine on a native device.

Is there a way to allow login.microsoftonline.com to accept rendering in an iFrame?
Also, the page normally redirect to an sts adfs server. Maybe there is a way to redirect directly to the sts uri?

Thanks

**Comment by vibronet** [comment]
The credentials gathering experience cannot be iframes for security reasons. This is not likely to change...

**Comment by vibronet** [comment]
...for skipping the first page, try http://www.cloudidentity.com/blog/2014/11/17/skipping-the-home-realm-discovery-page-in-azure-ad/ but I am. It not sure whether you'll be allowed to go past the frame buster though. I'd suggest giving it a try

**Comment by omercs** [comment]
We have cordova related library: https://github.com/AzureAD/azure-activedirectory-library-for-cordova
