### ISSUE TITLE
if resource is empty, acquireTokenRedirect calls callback before assigning it

### ISSUE THREAD

**Issue by alex3683** [AzureAD/azure-activedirectory-library-for-js#794]
In `adal.js` line [749ff](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal.js#L749-L756):
```js
 AuthenticationContext.prototype.acquireTokenRedirect = function (resource, extraQueryParameters, claims) {
        if (this._isEmpty(resource)) {
            this.warn('resource is required');
            callback('resource is required', null, 'resource is required');
            return;
        }

        var callback = this.callback;
        // ...
```
Here `callback` is called without being set, in case the resource is empty.

**Comment by rohitnarula7176** [comment]
@alex3683 Thank you for pointing out this issue. I apologize for the delayed response. We will release a new version in a couple of weeks with this fix.

**Comment by rohitnarula7176** [comment]
@alex3683 Closing this issue. Fixed and merged in dev.
