### ISSUE TITLE
Selecting wrong account for implicit flow

### ISSUE THREAD

**Issue by lworkman** [AzureAD/azure-activedirectory-library-for-js#795]
I'm trying to use implicit flow in an iframed site to access an API. Everything works fine when the user is only signed into one account, but if a user is signed into multiple Office 365 accounts (under different tenancies) the implicit flow fails and tries to redirect the user asking them to choose the account. However, because this is within an iframe, the redirect fails and no token is generated.

Is there any way to set which account Adal js should be using to login with when the user is logged into multiple accounts?

**Comment by lworkman** [comment]
Any response to this?

**Comment by nehaagrawal** [comment]
@lworkman  can you please paste the error that you are getting? Also I am assuming you are calling the silent version of acquireToken api and not the interactive ones (acquireTokenPopup/acquireToken Redirect).
