### ISSUE TITLE
drop support for node.js 0.10, 0.11 and 5

### ISSUE THREAD

**Issue by Arikael** [AzureAD/azure-activedirectory-library-for-js#799]
Currently PRs are piling up because travis ci tries to run the tests for node.js 0.10 and 0.11 which fails because of ES 6 features used in a dependency (growl).

travis.yml
```
language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "4.7.3"
  - "5.12.0"
  - "6.1.0"
```

node.js 0.10 and 0.11, and 5.0 have been end of life for 2 years.
node.js 4 is deprecated since april 2018.

I think support should be dropped (as well as for v4 and 5)
Before I create a PR I'd like toknow if there is a reason why the project still targets 0.10 and 0.11?

EDIT:
Changed the removal of node.js 4 from maybe to definitly

**Comment by Arikael** [comment]
is adal.js still maintained?
The community is willing but unable to participate because of failing CI
Pull Requests are pilling up for 3 months now.

@navyasric 
@nehaagrawal 
@rohitnarula7176 
@asnow003

**Comment by Arikael** [comment]
still no answer 👎 

Anybody?
The only other solution I see is to fork the repo and create a community driven version of adal.js.

**Comment by rohitnarula7176** [comment]
@Arikael I apologize for the delayed response. We will fix this as part of our next release in a couple of weeks.

**Comment by rohitnarula7176** [comment]
@Arikael Thank you for pointing out this issue. Closing this as it is fixed and merged in dev.
