### ISSUE TITLE
Library does not work on Win 8.0 + IE10 because of "use strict" check SCRIPT1047

### ISSUE THREAD

**Issue by diegodorazio** [AzureAD/azure-activedirectory-library-for-js#801]
When including adal-angular.js on IE10 on Win 8.0, the browser issues a javascript error and fails to load the js file.

The error is: 
_SCRIPT1047: In strict mode, function declarations cannot be nested inside a statement or block. They may only appear at the top level or directly inside a function body._ 

The offending bit of code (which was introduced in v1.0.16) is the following:

```
               if ($injector.has('$transitions')) {
                    var $transitions = $injector.get('$transitions');

                    function onStartStateChangeHandler(transition) {
                        stateChangeHandler(null, transition.to(), transition.params('to'), transition.from(), transition.params('from'));
                    }

                    function onErrorStateChangeHandler(transition) {
                        stateChangeErrorHandler(null, transition.to(), transition.params('to'), transition.from(), transition.params('from'), transition.error());
                    }

                    $transitions.onStart({}, onStartStateChangeHandler);
                    $transitions.onError({}, onErrorStateChangeHandler);
                }
```
The 2 functions onStartStateChangeHandler and onErrorStateChangeHandler use a function declaration inside a code block, and this is not accepted by IE10 on Win 8.0 (see SCRIPT1047 error message above)

It would be quite simple to fix: just change those 2 functions from function declaration to function expression,, e.g.:
```
var onStartStateChangeHandler = function (transition) { ... }
var onErrorStateChangeHandler = function (transition) { ... }
```

**Comment by bobboteck** [comment]
I also had the same problem and solved the same way. The error tells me visual studio when I start debugging. The test is done with Visual Studio 2015, Windows Server 2012 and IE11.

**Comment by m4m4m4** [comment]
This also affects UglifyJS which throws an error

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
