### ISSUE TITLE
Support EditorConfig

### ISSUE THREAD

**Issue by sliekens** [AzureAD/azure-activedirectory-library-for-js#802]
I'm having some trouble with contributing because my editor keeps changing LF line endings to CRLF and spaces to tabs.

Please add support for [EditorConfig](https://editorconfig.org/).

Additionally please add a gitattributes file with line ending normalization enabled.

**Comment by nehaagrawal** [comment]
@StevenLiekens  Thank you submitting the PR! We are currently reviewing it and we will update the state here.

**Comment by sliekens** [comment]
Okay thanks. Let me know if anything needs clarification.

**Comment by jmckennon** [comment]
Since we are generally only making new releases of `adal` for security fixes and it has been some time since this has been brought up, I'll be closing this issue.
