### ISSUE TITLE
How to use 'code' for responseType?

### ISSUE THREAD

**Issue by Taewa** [AzureAD/azure-activedirectory-library-for-js#805]
Hi all,
I am new to ADAL.
I need to use `responseType: 'code'` in order to get `accessToken` and `refreshToken`
However, according to the `adal.js` line `201`, responseType is always 'id_token'.
```
var urlNavigate = this._getNavigateUrl('id_token', null) + '&nonce=' + encodeURIComponent(this._idTokenNonce);
```

Is there a way to use `responseType: code` ?

Thanks.

**Comment by rohitnarula7176** [comment]
@Taewa I apologize for the delayed response. Adal js library only supports implicit flow with possible resoonseType values of 'id_token' and 'token'. Closing this issue as it is not supported by the library.

**Comment by tushard-iprogrammercom** [comment]
> @Taewa I apologize for the delayed response. Adal js library only supports implicit flow with possible resoonseType values of 'id_token' and 'token'. Closing this issue as it is not supported by the library.

Are there any possibilities to have support for 'code' responseType in future?

**Comment by Taewa** [comment]
@tushard-iprogrammer 
In the end, I couldn't use this library.
Just handled manually.

**Comment by tushard-iprogrammer** [comment]
Doing same. :P
------------------------------------------------

Tushar Dahiwale
Senior Software Engineer
tushard@iprogrammer.com

iProgrammer Solutions Pvt. Ltd.
Office 103, 104, 1st Floor Pride Portal,
Shivaji Housing Society, Bahiratwadi,
Near Hotel JW Marriott, Off Senapati Bapat Road,
Pune - 411016, MH, INDIA.
Phone: +91 9595456505 | Skype: tushard_iprogrammer
www.iprogrammer.com  <http://www.iprogrammer.com/>
------------------------------------------------

**Comment by tushard-iprogrammercom** [comment]
> @tushard-iprogrammer
> In the end, I couldn't use this library.
> Just handled manually.

Doing same :smiley:
