### ISSUE TITLE
JSON.stringify in stateChangeHandler throws on circular reference

### ISSUE THREAD

**Issue by ReeseJones** [AzureAD/azure-activedirectory-library-for-js#806]
in [adal-angular.js](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal-angular.js) on line 318 there is the following line:

```
_adal.verbose("State change error occured. Error: " + typeof (error) === 'string' ? error : JSON.stringify(error));
```

The stateChangeErrorHandler  sometimes receives error objects containing circular references which causes the stringify to throw, and obfuscate the errors that are actually happening.

It ends up looking kind of like this.
![image](https://user-images.githubusercontent.com/6557783/45568269-086b3a80-b811-11e8-8fbd-10e025021baa.png)

In our case we had a transition from one state to another while there was an ongoing transition already which produces an error correctly, however it wasn't obvious because because this state change error handler couldnt stringify the error was and throwing in of itself.

**Comment by rohitnarula7176** [comment]
@ReeseJones Thank you for pointing out this issue. I have submitted a PR for this issue. Can you please confirm if it resolves your issue. We will add this fix to our next release in a couple of weeks.

**Comment by nehaagrawal** [comment]
@ReeseJones  Can you please let us know what is the error string that is being passed to JSON.stringify(error) that ended up causing circular reference error?

**Comment by nehaagrawal** [comment]
We have merged the PR. I will update this issue with the version details when we release. Closing this issue for now.
