### ISSUE TITLE
clearCache doesn't clear cached user

### ISSUE THREAD

**Issue by sliekens** [AzureAD/azure-activedirectory-library-for-js#807]
**Expected behavior**
Calls to getCachedUser() should return null after doing clearCache().

**Actual behavior**
clearCache() does not clear the `_user` field.
getCachedUser() continues to return claims information from the deleted id_token.

**Other information**
This seems to be by design because logOut() first does clearCache() and then resets `_user` to null.
https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/e9d23e719eccf2341ee38b11323101fb14cb9610/lib/adal.js#L852-L858

Unfortunately I can't use logOut() because I want to handle navigation myself.

Anyhow, clearCache should probably clear everything including the cached user.

**Comment by rohitnarula7176** [comment]
Closing this issue. Fixed in dev and will be part of our next release.

**Comment by sliekens** [comment]
Nice, thanks.

**Comment by nitrovolnovka** [comment]
@rohitnarula7176 When is next release supposed to be? This issue is closed in Oct 17, 2018 and the latest release was on Feb 27, 2018. (1.0.17)
