### ISSUE TITLE
Will this library be deprecated in favour of MSAL?

### ISSUE THREAD

**Issue by FDMatthias** [AzureAD/azure-activedirectory-library-for-js#817]
Hi,

I'm wondering what the plans are for ADAL.js, will it be deprecated in favour of MSAL?

Thank you

**Comment by navyasric** [comment]
@CauseOfDev The future feature innovation and investments will be made in MSAL.js. But ADAL.js will continue to be maintained for security and bug fixes. This support will continue during the migration period to MSAL.js and until we decide to deprecate ADAL.js later in the future.
