### ISSUE TITLE
npm package is missing

### ISSUE THREAD

**Issue by michaelkruglos** [AzureAD/azure-activedirectory-library-for-js#821]
There's no npm package for non-angular version of this library.

**Comment by nehaagrawal** [comment]
@michaelkruglos  we bundle both adal.js and adal-angular.js in the same npm package. It's in our backlog to create separate package but this work hasn't been prioritized yet. Please use https://www.npmjs.com/package/adal-angular for now.

**Comment by mohamedmansour** [comment]
@nehaagrawal  when can we see adal.js packaged outside of angular? At Microsoft we are using React like crazy and we don't have an official way to use react and latest adal unless we go to a thirdparty which bundles adal.js in their code base `adal-react`
