### ISSUE TITLE
ADFS 2016 X-Frame-Options to deny

### ISSUE THREAD

**Issue by maordadush** [AzureAD/azure-activedirectory-library-for-js#824]
Hi,

I'm using adal.js on my react app (using [react-adal](https://github.com/salvoravida/react-adal#readme) wrapper). I configured my app to work with my ADFS 2016 server (on premise), and the authentication process works fine, but after the ADFS SSO cookie expired, when the client sends the renew token request (in an hidden iframe), the browser shows in the console the following error: `refuse to display 'https://myadfs/adfs/ls/SAMLRequest=...' in a new frame because it set 'X-frame-options' to deny`. 

In order to reauthenticate, the user needs to refresh the page (F5). 

Is there any solution / workaround to this problem?

**Comment by maordadush** [comment]
@rohitnarula7176 is there any solution to this problem? It causes a big issue in my team, any solution would be great

**Comment by navyasric** [comment]
@maordadush Here is an [article](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/single-page-application-with-ad-fs) which demonstrates the use of ADFS 2016 with ADAL.js in AngularJS app for your reference.
The ADAL team does not own the react-adal wrapper and hence cannot troubleshoot or fix the issues when using that wrapper. Please open the issue with the author of the react-adal repo to investigate the wrapper code.
