### ISSUE TITLE
[Question] Custom token cache

### ISSUE THREAD

**Issue by carlosscastro** [AzureAD/azure-activedirectory-library-for-js#828]
ADAL dotnet allows to specify a custom token cache implementation. Does ADAL js provide such a thing? I couldn't find any docs on it.

Thanks!

**Comment by navyasric** [comment]
ADAL.js does not allow a custom token cache implementation. 
ADAL.js caches tokens in the browser storage( i.e. localStorage or sessionStorage). The default is sessionStorage. The library allows you to configure the storage at initialization time as follows:
```
window.config = {
    clientId: '[Enter your client_id here, e.g. g075edef-0efa-453b-997b-de1337c29185]',
    cacheLocation: "localStorage"
};

var authContext = new AuthenticationContext(config);
```
