### ISSUE TITLE
Issue with renew token

### ISSUE THREAD

**Issue by sandipbhavsar** [AzureAD/azure-activedirectory-library-for-js#833]
## Browser:
- [ ] Chrome version XX

## Library Name
- [ ] adal-angula package
angular 6

## Library version
Library version: 1.0.17

## Current behavior
I  am not getting renew token when I call `adalService.acquireToken(clientId)`. the systems gets hang. I am using adal-angular npm package. It will be good if somebody can share code

**Comment by navyasric** [comment]
@sandipbhavsar Please provide any error or logs you are seeing when this issue happens as well as your app's auth code snippets. Here is a [sample](https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi/blob/master/TodoSPA/App/Scripts/Ctrls/todoListCtrl.js#L16) showing how to acquire tokens and you can also refer the code snippet [here](https://github.com/AzureAD/azure-activedirectory-library-for-js#3-get-an-access-token) for the pattern to get and renew tokens.  The acquireToken method silently renews the tokens if there is a valid session.
