### ISSUE TITLE
Multiple issues with latest version of adal-angular

### ISSUE THREAD

**Issue by ms-hkgupta** [AzureAD/azure-activedirectory-library-for-js#835]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX

## Library Name
- [ ] adal.js 1.0.17
- [ ] adal-angular 1.0.17

## Library version
Library version: 1.0.17

## Current behavior
In our project which is a single page web application built on angularjs, we are using adal-angular library. Recently we have upgraded to the latest available version (1.0.17) and we are facing multiple issues since then. These are highly intermitent issues and exact repro steps are not identified for all the issues except blank page issue. First 2 issues are happening when the id token is expired mostly intermittently. 
1) Timeout in fetching the resource tokens. 
2) Failure during silent sign-in request (IDToken requests) which is resulting in blank page since the login is not complete. 
3) Multifactor authentication failure. 
4) Trusted site issues and other errors AADSTS50058, AADSTS50079, AADSTS50001, Nonce received error etc. 

First 2 issues is happening when the user is trying to access the application after few days of gap.

**Comment by dubcdr** [comment]
I'm getting reports of a similar issue in our production app. Like hkgupta mentions its extremely intermittent. I haven't been able to reproduce but a colleague did and not. On the refresh call the server hits a timeout and adal isn't handling it.

**Comment by jmckennon** [comment]
These seemingly intermittent timeouts are a known bug in `adal js`. The timeouts and the rest of these bugs have been fixed in `msal js` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
