### ISSUE TITLE
Better Cordova inappbrowser support

### ISSUE THREAD

**Issue by VeldMuijz** [AzureAD/azure-activedirectory-library-for-js#84]
Hi there,
When developing with the adaljs and angular library on a cordova project the login and logout functions could use some better support.
For the login function there is a displaycall available where I use the inappbrowser plugin so I can close the login page after login is successful. The logout function doesn't have this config option yet. I've worked around that by using the following code:

    /**
    * Logout user will redirect page to logout endpoint. 
    * After logout, it will redirect to post_logout page if provided.
    */
    AuthenticationContext.prototype.logOut = function () {
        this.clearCache();
        var tenant = 'common';
        var logout = '';
        this._user = null;
        if (this.config.tenant) {
            tenant = this.config.tenant;
        }

        if (this.config.instance) {
            this.instance = this.config.instance;
        }

        if (this.config.postLogoutRedirectUri) {
            logout = 'post_logout_redirect_uri=' + encodeURIComponent(this.config.postLogoutRedirectUri);
        }

        var urlNavigate = this.instance + tenant + '/oauth2/logout?' + logout;

        this._logstatus('Logout navigate to: ' + urlNavigate);
        //this.promptUser(urlNavigate);
    
        // Use a hidden inappbrowser view to navigate to the logout url
        var ref = window.open(urlNavigate, '_blank', 'hidden=yes');
        ref.addEventListener('loadstop', ref.Close());
    
    };

I've hidden the frame because it isn't possible to navigate back to the app after the logout redirect has taken place.

Could you build a config option to be able to handle this better or more flexible?

**Comment by omercs** [comment]
postLogoutRedirectUri: You could set this to your app's logout landing page. After successful logout, app will be redirected to that link.

**Comment by VeldMuijz** [comment]
This does require a valid URL and since I'm using the cordova application the complete url to the homepage will not work because the url `file:///` etcetera isn't a valid url

**Comment by softwarejc** [comment]
Same problem here :). Any news regarding this topic?

**Comment by vibronet** [comment]
Hi all,
To add some background to this thread. ADAL JS v1 is designed to support the development of SPA applications: the use of the library in Cordova was not an explicit goal for this version. That said, if there are changes that you think might help you in your scenario without impacting the main library purpose feel free to submit PRs!
Thanks
V.

**Comment by BartVDACodeware** [comment]
Is there a road map for future versions?
Cordova is for me also a +
Can we vote for features?

**Comment by vibronet** [comment]
The use of ADAL JS in Cordova has severe limitations, such as the inability of leveraging any state on the device and other device-specific features that are inaccessible from the sandbox in which JS executes. We are considering the creation of an ADAL Cordova plugin. If we go that route, we won't make feature changes in ADAL JS for accommodating Cordova given that it would remain out of its scope. No timelines to share yet, but I hope to be able to give an update soon.

**Comment by omercs** [comment]
Cordova related library is here: https://github.com/AzureAD/azure-activedirectory-library-for-cordova
