### ISSUE TITLE
Accessing to window.location.hash inside Azure Devops extension 

### ISSUE THREAD

**Issue by sashmen5** [AzureAD/azure-activedirectory-library-for-js#842]
## Browser:
- [ ] Chrome version 71

## Library Name
- [ ] adal.js

## Library version
Library version: 1.0.15

## Issue description
Hello. I develop Azure DevOps extension. And I still want to implement login popup because I want to fetch  some user info from his Microsoft Azure Directory via API. 
1. adal.js fetchs access_token from `window.location.hash` . In regular web apps it works but in azure devops extension apps have not permission to fetch directly this hash. The way it is possible run code 
<code>   VSS.getService(VSS.ServiceIds.Navigation).then(function(navigationService) {
        // Get current hash value from host url
        navigationService.getHash().then(function (hash) {
            console.log("Host hash value: " + hash);                        
        });
    });</code>
This code brings hash from uri successfully but he does it asynchronously unlike adal.js does synchronously.  
Is this library appropriate for my task?
2. My extension already runs in own <iframe> on azure devops web page. Login popup also runs it in his <iframe>. Could this scenario issue some problems?

**Comment by jmckennon** [comment]
I don't believe `adal js` will support your use case here. `msal js`, the more modern project, does support special iframe-in-iframe scenarios and would likely work better here. Can you try installing and using the latest version of [msal js](https://github.com/AzureAD/microsoft-authentication-library-for-js), and reporting on that repo if you are still having issues?

Additionally, all current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
