### ISSUE TITLE
Renew token uses iFrame when `popup` is set to `true`

### ISSUE THREAD

**Issue by maordadush** [AzureAD/azure-activedirectory-library-for-js#843]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ x ] Chrome version 71
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library Name
- [ x ] adal.js XX
- [ ] adal-angular XX

## Library version
Library version: 1.0.17

## Current behavior

When setting `popup=true`, acquiring token works with popup but renewToken tries to use iFrame

## Expected behavior

When setting `popup=true` both acquireToken and renewToken should show a popup

## Minimal reproduction of the problem with instructions

Set `popup` to true, and try to make an authenticated request after cookie (& cache) is expired 

</code></pre>

**Comment by jmckennon** [comment]
This functionality is intended, as `renewToken` is meant to specifically use an iFrame all the time. If you want to popup again, you can use `acquireToken` with `popup=true` as you mention, or `acquireTokenPopup`. These are functionally the same as renewing a token, as you'll just be obtaining a new one instead.

Additionally, all current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
