### ISSUE TITLE
acquireToken does not work if the config.redirectUri different from login page (different ports or domains)

### ISSUE THREAD

**Issue by DmitryZevalev** [AzureAD/azure-activedirectory-library-for-js#844]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 71
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library Name
- [x] adal.js 1.0.17
- [ ] adal-angular XX

## Library version
Library version: 1.0.17

## Expected behavior

</code></pre>

**Comment by jmckennon** [comment]
This is actually possible today, but there are some caveats/risks associated with this, so we generally do not recommend redirecting to another domain. You can set your `redirectURI` in the Azure portal and in `adal js` to be something like `app.domain.com`, but make the original login request from `domain.com`. The risk here is that all responses, errors, etc. will now all be sent to `app.domain.com` and **not** `domain.com`.

Additionally, all current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
