### ISSUE TITLE
1.0.18 not available on CDN

### ISSUE THREAD

**Issue by dennisvintherjensen** [AzureAD/azure-activedirectory-library-for-js#846]
The readme.md states that the latest version 1.0.18 i available at the following URL. But the URL returns "BlobNotFound"

https://secure.aadcdn.microsoftonline-p.com/lib/1.0.18/js/adal.min.js

**Comment by navyasric** [comment]
@dennisvintherjensen The Readme points to the dev branch which has certain updates that have not yet been released. 10.18 will soon be released.

**Comment by MarcTimperley** [comment]
The cdn link https://secure.aadcdn.microsoftonline-p.com/lib/1.0.17/js/adal.min.js is valid currently

**Comment by geekwhocodes** [comment]
Any timeline for releasing version 1.0.18 via CDN?

**Comment by riteshbhoi** [comment]
Any update on this thread on when exactly version 1.0.18 would be released?

**Comment by jmckennon** [comment]
This was done as #839, sorry for the untimely release.

Additionally, all current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
