### ISSUE TITLE
Auth popups incorrectly handled in Microsoft Edge 

### ISSUE THREAD

**Issue by Nican** [AzureAD/azure-activedirectory-library-for-js#848]
## I'm submitting a...

- [x] Bug report

## Browser:
- [x] Edge version 44

## Library Name
- [x] adal.js 1.0.18

## Library version
Library version: 1.0.18

## Current behavior
I am hosting my application inside of an iframe. When the application requests a token, Edge will by default block the authentication popup, and adal will return an error for the token. 
 
Expect that Edge will keep information about the popup it was trying to open so that when the user later allows opening the popup, it will open it anyway. But since Edge already told the application that it failed to open the popup, the authentication is not handled correctly. 

Sometimes Edge will even open multiple authentication popups at once. 

## Expected behavior
ADAL.js could either wait for the user to allow popups.
OR
Not show a delayed pop-up, and allow the application to ask the user to login again. 

## Minimal reproduction of the problem with instructions
Use Adal.js inside of an iframe, with auth popups inside of Edge.

**Comment by navyasric** [comment]
@Nican For the popup flows to work in ADAL.js, you will need to enable popups on the browsers.

Also, please take a look at these [known issues on IE and Edge](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Known-issues-on-Edge). There is a popup issue with using the library on Edge. We recommend using redirect flows for Edge if the suggested workarounds don’t work.

**Comment by Nican** [comment]
Thank you for the information. I had not seen that page on the wiki. 
I still find it quite annoying that Edge will spontaneously open popups, with no way to get confirmation back from the application.
