### ISSUE TITLE
IE10 error "redefining a constant"

### ISSUE THREAD

**Issue by BartVDACodeware** [AzureAD/azure-activedirectory-library-for-js#85]
IE10 has an issue when rewriting constant like window.
This happens in adal.js en adal-anguler.js for testing purpose:

//if (typeof module !== 'undefined' && module.exports) {
//    var window, localStorage, angular, document, sessionStorage; => this line
//    module.exports.inject = function (windowInj, storageInj, documentInj, MathInj, angularInj, conf) {
//        window = windowInj;
//        localStorage = storageInj;
//        sessionStorage = storageInj;
//        document = documentInj;
//        Math = MathInj; // jshint ignore:line
//        angular = angularInj;
//        return new AuthenticationContext(conf);
//    };
//}

For now I'm commenting the lines

**Comment by omercs** [comment]
Fix: Don't rewrite for IE10 version. Check other IE versions for similar issue.

**Comment by nabilbo** [comment]
I have the same issue with IE10, but not with Safari 8, IE11, Chrome 43, and Firefox38...
is there a fix ?

**Comment by omercs** [comment]
Constant declaration issue is addressed in #142
