### ISSUE TITLE
Is there a way to turn off SameSite cookie usage by using ADAL JS?

### ISSUE THREAD

**Issue by nedimsahin** [AzureAD/azure-activedirectory-library-for-js#852]
Hello,

As described in the article below, it is recommended to turn off SameSite cookie as a workaround for the issue of AD login from Safari on iOS 12. 

[https://github.com/aspnet/AspNetCore/issues/4647](https://github.com/aspnet/AspNetCore/issues/4647)

The article describes how to turn it off for ASP.NET Core and some other platforms. However, I haven't seen a similar implementation for ADAL JS. Is there a way to do it?

**Comment by jthoni** [comment]
I just realized that this is going to impact us.  Is there any info on this?

**Comment by jmckennon** [comment]
We now have a wiki page on issues related to Safari [here](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Known-issue-on-Safari). 

Additionally, all current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
