### ISSUE TITLE
Unexpected SSO behaviour with acquireToken and ADFS

### ISSUE THREAD

**Issue by h3rmanj** [AzureAD/azure-activedirectory-library-for-js#854]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe: Chrome uses SSO over specified `id_token`
</code></pre>

## Browser:
- [x] Chrome version 72.0.3626.119
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library Name
- [x] adal.js XX
- [ ] adal-angular XX

## Library version
Library version: 1.0.17

## Current behavior

Please note that we are using ADFS.
In our environment, each employee can have multiple users in AD, with different permission levels. This means that we would like to disable SSO, and let the user them self log in with the correct user.
Disabling SSO and asking for a prompt can be done by adding this to the config:
```json
extraQueryParameter: 'prompt=login'
```
If the user click *Sign on as current user*, the user will be signed in as `UserA` (using SSO). 
However, if the user logs in with another user, such as username `UserB`, this works and the `id_token` returned is correct. When we try to acquire token for an API, SSO seems to take over, and fetches `UserA`'s `access_token`.
This does not occur in Firefox, where the `access_token` is correct, for `UserB`.

## Expected behavior

If signed in as `UserB`, the `access_token` should also be from `UserB` and not `UserA` in Chrome. 

## Minimal reproduction of the problem with instructions

Add this to the config:
```json
instance: 'YOUR_ADFS_INSTANCE',
tenant: 'adfs',
extraQueryParameter: 'prompt=login'
```
Try logging in with another user than your SSO user, then acquire an access token. Check the `access_token`s `winaccountname`.

</code></pre>

**Comment by JonasKs** [comment]
@manoj-rath / @rohitnarula7176  , could you review? Any solutions?

**Comment by JonasKs** [comment]
Workaround:

- Create an iFrame with the ADFS log out link, deleting the cookies from ADFS.
- set `onLoad` to redirect to the `prompt=login` site. 
- Log in
- Profit

**Comment by jmckennon** [comment]
This bug is fixed in `msal js`, or you can use the workaround stated by JonasKs. Closing this as it looks like the problem is solved.

All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
