### ISSUE TITLE
Document in README or wiki how this library is different than microsoft-authenttication-library-for-js

### ISSUE THREAD

**Issue by aappddeevv** [AzureAD/azure-activedirectory-library-for-js#855]
Both this library and the microsoft-authentication-library-for-js are under AzureAD so it would be nice to have a note on how these two are different. As near as I can tell, this library is v1.0 endpoints and MSAL is for v1 and v2 endpoints, or maybe only v2.

**Comment by MariuszKogut** [comment]
Any updates here? I want to integrate OAuth into our react application and I'm not sure, which lib to use.

**Comment by jmckennon** [comment]
Yes, `adal js` supports only v1 endpoints and `msal js` supports both v1 and v2.

All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
