### ISSUE TITLE
Doc typos

### ISSUE THREAD

**Issue by mbaroukh** [AzureAD/azure-activedirectory-library-for-js#858]
## I'm submitting a...
<pre><code>
[x] Documentation issue or request
</code></pre>

## Library Name
- [x ] adal.js XX

## Library version
Library version: last

## Current behavior

When following the doc, the first step is "Instantiate the AuthenticationContext" :

`var authContext = new AuthenticationContext(config);`

then in step 2 "Login the user", the code is 

`var user = authenticationContext.getCachedUser();`

So "authenticationContext" instead of "authContext".

By the way, in step1, the created config has a parameter "callback" that is not in configurable options on https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Config-authentication-context#configurable-options. Which is wrong ?

## Expected behavior

</code></pre>

**Comment by jmckennon** [comment]
These doc issues are now clarified and should be correct according to adal usage in the wiki. 

Additionally, all current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
