### ISSUE TITLE
html5mode not working with adal

### ISSUE THREAD

**Issue by bigerock** [AzureAD/azure-activedirectory-library-for-js#86]
i see the code that looks for the hash tag in the url, however, what if you're using html5mode? (no hashes) 

apologies if if this isn't the case and there's something else going on.

**Comment by omercs** [comment]
Did you try to add $locationProvider.hashPrefix('!') to your config? This should make ngRoute not rewrite the URLs.

**Comment by bigerock** [comment]
i remember seeing something about that. sorry, yes, that solved it. 

thank you very much!
