### ISSUE TITLE
Custom Login with SSO Login

### ISSUE THREAD

**Issue by amanaks** [AzureAD/azure-activedirectory-library-for-js#863]
<pre><code>
stop authentication for custom login.
</code></pre>

## Library Name
- [x] adal.js 1.0.17
- [x] adal-angular 1.0.17

## Current behavior
I need to use my own custom user login with SSO service . SSO login is working fine but when i am trying to call an api it throws an error stating that User login is required|login required.
How can i skip this error and call the api.

i am using angularJs and calling an api from javascript

## Expected behavior
call my api when custom login is clicked with username and password contained in db and stop authentication from adal service.

</code></pre>

**Comment by jmckennon** [comment]
If this is still an issue, can you provide a bit more context with the code you're using? We also have the [SSO wiki page](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Sso) to answer some general SSO questions, which may help.

All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.

**Comment by jmckennon** [comment]
Closing this as we're assuming this is no longer an issue. We recommend that everyone switch to `msal js` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) for advanced features and bugfixes.
