### ISSUE TITLE
page Double refreshing using ADAL.js

### ISSUE THREAD

**Issue by lax-github** [AzureAD/azure-activedirectory-library-for-js#865]
I am trying to call Secured Azure Function App(OAuth 2.0) using ADAL js. I am getting the token but it redirects twice to https://login.microsoftonline.com (refreshing page twice.). It’s a bad user experience. Did anyone had same experience using ADAL.js? 

Please provide some suggestion/solution. Thank you in advanced.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version 74
- [ ] Firefox version XX
- [ ] IE version 11
- [ ] Edge version XX
- [ ] Safari version XX

## Library Name
- [ ] adal.js 12
- [ ] adal-angular XX

## Library version
Library version: 1.0.12

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by nvigne** [comment]
Can you share a code example? From what you are describing, it looks like you are not correctly checking if the user is already authenticated.

```
var user = authenticationContext.getCachedUser();
if (user) {
    // Use the logged in user information to call your own api
    onLogin(null, user);
}
else {
    // Initiate login
    authenticationContext.login();
}
```

**Comment by jmckennon** [comment]
If you're still having issues, please comment here or open a new ticket, though we recommend moving to `msal js`.

All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
