### ISSUE TITLE
@tushargupta51 I am trying to renew the token with a custom expiration offset value from config.

### ISSUE THREAD

**Issue by abhaygitty** [AzureAD/azure-activedirectory-library-for-js#867]
@tushargupta51 I am trying to renew the token with a custom expiration offset value from config.
But I don't think, that the acquireToken() method works as expected.
I meant, the expiration time of the token doesn't get updated after being reset to 0 in the getCachedToken()
` /**
     * Gets token for the specified resource from the cache.
     * @param {string}   resource A URI that identifies the resource for which the token is requested.
     * @returns {string} token if if it exists and not expired, otherwise null.
     */
    AuthenticationContext.prototype.getCachedToken = function (resource) {
        if (!this._hasResource(resource)) {
            return null;
        }

        var token = this._getItem(this.CONSTANTS.STORAGE.ACCESS_TOKEN_KEY + resource);
        var expiry = this._getItem(this.CONSTANTS.STORAGE.EXPIRATION_KEY + resource);

        // If expiration is within offset, it will force renew
        var offset = this.config.expireOffsetSeconds || 300;

        if (expiry && (expiry > this._now() + offset)) {
            return token;
        } else {
            this._saveItem(this.CONSTANTS.STORAGE.ACCESS_TOKEN_KEY + resource, '');
            this._saveItem(this.CONSTANTS.STORAGE.EXPIRATION_KEY + resource, 0);
            return null;
        }
    };`

Further the renewIdToken() function is called due to the null token returned from the getCachedToken() function.
![image](https://user-images.githubusercontent.com/22489833/57414636-8e802b00-71be-11e9-8c45-c75e20e64a68.png)

Here in the above function, the RENEW_STATUS doesn't change to complete.
Therefore, I tried invoking the handleWindowCallBack() funtion (within which there's a call to the saveTokenFromHash() function which writes the token and the expiration Epochs to the sessionStorage and also does switch the status from "In progress" to "Completed" as seen below) which again fails to run as the window.location.hash is empty.

![image](https://user-images.githubusercontent.com/22489833/57414979-fdaa4f00-71bf-11e9-9189-4519a1577549.png)

In addition to the above problem, I would also like to know, "when does the window.location.hash field get its value written?"

Please do guide me on what's wrong with what I am doing. 
Thanks in advance.

_Originally posted by @abhaygitty in https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/290#issuecomment-490687297_

**Comment by jmckennon** [comment]
cc @sameerag @jasonnutter - can we provide some guidance here?

**Comment by pramodpadmanabhi** [comment]
@tushargupta51  Facing the same issue as above mentioned, AcquireToken() always returns cached Token even after expireOffSetSeconds is reset 

@abhaygitty Have U found any workaround?

**Comment by jasonnutter** [comment]
Closing, as assuming this has been resolved. ADAL.js is no longer actively maintained, so we highly recommend moving to MSAL.js.

If you have further questions, please open a new issue in the MSAL.js repo: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues
