### ISSUE TITLE
AADSTS50132: The session has expired or has been revoked - AngularJS 1.7.6 and Adal 1.0.17

### ISSUE THREAD

**Issue by venkatgude90** [AzureAD/azure-activedirectory-library-for-js#871]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 74
- [ ] Firefox version XX
- [x] IE version 11
- [ ] Edge version XX
- [ ] Safari version XX

## Library Name
- [x] adal.js 1.0.17
- [x] adal-angular 1.0.17
- [x] angular 1.7.6

## Library version
Library version: 1.0.17

## Current behavior
I have accessed application and left browser without closing window and revisited the page after token expiry then refresh page causing infinite loop to login with renew status InProgress and Cancelled. Able to see below errors in console. Where as if I close and reopen window is wor
1. "AADSTS50132: The session has expired or has been revoked.
2. Set-Cookie header is ignored in response from url: <URL>. Cookie length should be less than or equal to 4096 characters.

## Expected behavior
Application either need to prompt for login or allow to access pages by renewing token.

## Minimal reproduction of the problem with instructions
1. Configure ADAL in application and login.
2. Wait for token to expire (in my case it is 5 hours)
3. Refresh page

**Comment by jmckennon** [comment]
This infinite loop in `adal js` is a known bug and is fixed in `msal js`. All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
