### ISSUE TITLE
adal.js client side/off perm calling SP rest api, what am I missing?

### ISSUE THREAD

**Issue by jkyoungchoi** [AzureAD/azure-activedirectory-library-for-js#872]
I'm trying to retrive SP site,list,items from off-perm with JS.

Got id_token with adal.js and its sample code. So with the id_token that I received
made various calls to endpoints (including SP Site's api endpoint), something like below
<pre><code>
$.ajax({
type: "GET",
url: "https://graph.microsoft.com/v1.0/me/",
headers: {
 'Authorization': 'Bearer ' + token,
},
});
</code></pre>
whatever I try keep getting 401.

Azure app has permission for Graph api and SP.

I feel like I'm missing something but reading manuals keeps getting me somewhere else.

Can anyone guide me what I did wrong?

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library Name
- [x ] adal.js XX
- [ ] adal-angular XX

## Library version
Library version: current

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by jmckennon** [comment]
It's a bit hard to debug your code and usage without more information. If you're still unable to fix the 401s, do you think you could provide the exact error and the exact code usage, including what's happening before that ajax request?

Additionally, all current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.

**Comment by jkyoungchoi** [comment]
> It's a bit hard to debug your code and usage without more information. If you're still unable to fix the 401s, do you think you could provide the exact error and the exact code usage, including what's happening before that ajax request?
> 
> Additionally, all current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.

Thanks for reply, it worked out afterwords.
