### ISSUE TITLE
Redirecting to Homepage with homepage/ADAL# in URL

### ISSUE THREAD

**Issue by Kavya06** [AzureAD/azure-activedirectory-library-for-js#875]
Hi

I am using ADAL-4 for angular 6. But when we redirect the page after Microsoft.Login, it is redirecting to homepage with Adal# in the URL. How to redirect the page without Adal# in the URl.

Please provide some solution

**Comment by jmckennon** [comment]
Can you provide a bit more context here about how you're using the library? You can set custom a `redirectUri` in the config passed to `AuthenticationContext`, which also needs to be registered in the Azure portal. By default, that redirect is `window.location.href`. Refer to the [wiki](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Config-authentication-context).

**Comment by jmckennon** [comment]
Closing this as we're assuming this is no longer an issue. We recommend that everyone switch to `msal js` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) for advanced features and bugfixes.
