### ISSUE TITLE
authContext.getCachedUser() is not working in safari Ios 12.1

### ISSUE THREAD

**Issue by sksarath** [AzureAD/azure-activedirectory-library-for-js#876]
I am using adal.min.js version (1.0.11) and authContext.getCachedUser() works perfectly fine in chrome, safari. But not working on any versions less that IOS 12.2 authContext.getCachedUser() gives null value.

works in ios 12.2 safari, chrome, firefox.
not works in ios versions less than 12.2 (eg. v12.1 safari) authContent.getCahcedUser() gives null.

<pre><code>
var authContext = new AuthenticationContext({
        tenant: tenantId,
        clientId: clientId,
        postLogoutRedirectUri: window.location.origin,
        redirectUri: window.location.origin,
        cacheLocation: 'localStorage'
      });
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library Name
- [*] adal.js (1.0.11)
- [ ] adal-angular XX

## Library version
Library version: 1.0.11

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by jennyf19** [comment]
FYI: @sameerag @pkanher617 @jasonnutter @DarylThayil Can one of you please take a look at this? Customer would like a response, or know if a support case should be opened. Thanks so much.

**Comment by sameerag** [comment]
@sksarath The last release on `adal js` is `1.0.17` and I see the version you are using is `1.0.11`. Is it possible to move to the latest and let us know if this issue persists?

On a more general note, we are currently focusing all our efforts on [`msal js`](https://github.com/AzureAD/microsoft-authentication-library-for-js) which is an advanced version of `adal js`. We recommend all our customers to move to `msal js` and we can help with the migration as needed. Please let us know if this is something you want to pursue.

**Comment by jmckennon** [comment]
Closing this as it's been some time since we've seen a response and we're assuming that this is no longer an issue. If problems persist, we recommend making the jump to [msal js](https://github.com/AzureAD/microsoft-authentication-library-for-js) or opening further tickets.
