### ISSUE TITLE
feature to extend expiry time silently on click of button (microsoft-adal-angular6)

### ISSUE THREAD

**Issue by vinay-sowdri** [AzureAD/azure-activedirectory-library-for-js#878]
I would like the user to provide a feature to show popup and allow him to extend session. 
Right now i would be showing pop up 15 min before token expiry. If the user accepts token expiry, i need to extend the expiry time of token. But right now since the token isn't expired , its getting same token. Even if i expire token using **expireOffsetSeconds** , when the request tries to process , it works successfully but doesn't redirect to exact page which it had to redirect. 

Also we can see token refresh redirection, cant we do it silently?
how can we use renewtoken, because it always comes back with isauthenticated set to false.
## Library Name
adal.js
adal-angular XX
microsoft-adal-angular6

## Current behavior
after all the operation, it doesn't redirect to successfull page if token is expired .
## Expected behavior
Continue with  all the operations and redirect to successfull page

## Minimal reproduction of the problem with instructions

1. have some form on page and make changes on form .
2. on successfull save show toastr message and redirect to some other page. 
3. expire the token in local storage or using expireOffsetSeconds. click save button.
4. on save it shud save, show toastr message and redirect to that particular page.

-

**Comment by sameerag** [comment]
All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We would recommend to move to `msal js` for any advanced feature asks.
