### ISSUE TITLE
Question about Nonce

### ISSUE THREAD

**Issue by manfredsteyer** [AzureAD/azure-activedirectory-library-for-js#88]
Hi,

I’ve noticed, that you create the nonce with JavaScript using Math.rand(). Therefore, the nonce is not random in a cryptographic way. However, as Crypto-API is quire young and not widely supported, there is no other way to do this in JavaScript. One alternative would be to contact a Web API for creating a nonce in a cryptographic random way. 

Now I’m curious, whether you considered this solution and why you choose to use Math.rand().

Wishes,
Manfred

**Comment by omercs** [comment]
Thank you for feedback. Adal is generating GUID version4 and it is not crypto random. We are looking into that.

**Comment by tushargupta51** [comment]
We now use window.cyrpto api to generate guids, if it is supported by browser. If not, we fall back to Math.random. Fixed in 1.0.12.
