### ISSUE TITLE
new React app sample using GatsbyJS

### ISSUE THREAD

**Issue by ferantivero** [AzureAD/azure-activedirectory-library-for-js#880]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Library Name
- [ ] adal.js XX
- [X] adal-angular XX

## Library version
Library version: 1.0.17

## Current behavior

the [wiki samples](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Code-samples) doesn't list any sample for a React App using adal-agular.

## Expected behavior
Please let's consider incorporating the following sample for a React App using GatsbyJS: 

[A React App authenticating users with Azure AD and calling its own Azure Api Management Gateway backed with Azure Functions](https://github.com/mspnp/serverless-reference-implementation/tree/master/src/ClientApp)
</code></pre>

**Comment by sameerag** [comment]
All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We would recommend to move to `msal js` for any advanced feature asks.
