### ISSUE TITLE
ADAL.js Popup sign in failure in Edge/IE with error message “Popup Window is null.”

### ISSUE THREAD

**Issue by harryhaomsft** [AzureAD/azure-activedirectory-library-for-js#881]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [X ] Edge version 44
- [ ] Safari version XX

## Library Name
- [X ] adal.js 1.0.17
- [ ] adal-angular XX

## Current behavior

Our teamrecently started using ADAL.js for authentication. And we are seeing a lot of customers using Edge are seeing problems signing in with popup window.

We can also repro the problem on our side - when ADAL.js try to open the popup window, Edge instead opens up a full browser window. And ADAL.js will fail signin, with error message "Error opening popup: Popup Window is null. This can happen if you are using IE".

Is this a bug with ADAL.js or EDGE/IE? What's the cause of this issue? Is there a work around for this? And is there going to be a fix for this?

Is this known issue related to this issue? https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Known-issues-on-Edge

## Expected behavior
The popup window should be a popup window instead of a full browser window. And user should be able to do sign in in the popup window.

**Comment by sameerag** [comment]
Can you try moving to `msal js`?

All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We would recommend to move to `msal js` for any advanced feature asks.

**Comment by jmckennon** [comment]
Closing this as we're assuming this is no longer an issue. We recommend that everyone switch to `msal js` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) for advanced features and bugfixes.
