### ISSUE TITLE
How to set Access Token Lifetime (session time) and Refresh Token Max Inactive Time?

### ISSUE THREAD

**Issue by nikhil-mahirrao** [AzureAD/azure-activedirectory-library-for-js#883]
How to config **AccessTokenLifetime**, **MaxInactiveTime** from **AuthenticationContext** ?

`var authContext = new AuthenticationContext({
        clientId: 'someId',
        postLogoutRedirectUri: 'someURL',
        redirectUri: 'someURI',
});`

As bellow link shows some more config params,

**Configurable token lifetimes in Azure Active Directory:**
[https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes](url)

**Comment by sameerag** [comment]
This cannot be achieved from `msal`. This has to be configured in app portal. As far as I know, `accessToken` in implicit flow cannot be extended beyond an hour. @hpsin can you add anything here?

**Comment by hpsin** [comment]
You need to use the policy that's described in the article, via powershell.  There's nothing that indicates that implicit flow tokens can or cannot be edited, so I assume they can be.

**Comment by jmckennon** [comment]
Closing this as we're assuming this is no longer an issue. We recommend that everyone switch to `msal js` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) for advanced features and bugfixes.
