### ISSUE TITLE
Support Microsoft identity platform (v2.0) endpoints

### ISSUE THREAD

**Issue by sgsouris** [AzureAD/azure-activedirectory-library-for-js#887]
## I'm submitting an enhancement request so adal.js can support the Microsoft identity platform (v2.0) endpoints which is described in https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-app-types

i.e.
https://login.microsoftonline.com/common/oauth2/v2.0/authorize
https://login.microsoftonline.com/common/oauth2/v2.0/token

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library Name
- [x ] adal.js XX
- [ ] adal-angular XX

## Library version
Library version: X.Y.Z

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by jasonnutter** [comment]
@sgsouris We have no plans to add support for v2 endpoints in ADAL.js, as we have released MSAL.js which has support for both v1 and v2 AAD endpoints. 

https://github.com/AzureAD/microsoft-authentication-library-for-js
https://www.npmjs.com/package/msal

Please let us know if you have any questions or concerns with moving from ADAL to MSAL.

Thanks!

**Comment by sgsouris** [comment]
That's awesome news, thanks Jason!
