### ISSUE TITLE
html5 mode - another issue

### ISSUE THREAD

**Issue by bigerock** [AzureAD/azure-activedirectory-library-for-js#89]
sorry if this is similar to the experience i opened a ticket for previously, but i'm havign another issue.

i'm finding that after the initial login to azure ad, it redirects back to the url with a hash at the end...

http://myurl.com/home# - which is causing my page not to load properly. there's no errors logged in the console. i am running in html5 mode like so:

$locationProvider.html5Mode(true).hashPrefix('!');

i am also setting a base href tag in the header just in case.

<base href="/" />

**Comment by omercs** [comment]
What does it save to "adal.start.page" in storage before login?

It could be related to https://github.com/angular/angular.js/issues/2833

Can you define base add <base href="/your-angular-app-path/"  to  <head>.

**Comment by bigerock** [comment]
sorry i'm not understanding your first or second questions. first, it doesn't save anything to 'adal.start.page' as far as i know. second, i'm not sure if you're asking what base tag i'm setting but if so, i've added a base href tag in the head of the main page like so: <base href="/" />

**Comment by omercs** [comment]
Adal.js saves the redirect link to local storage with keyname as 'adal.start.page'.

Linked angular issue suggested to add base tag for similar problem.

**Comment by bigerock** [comment]
i think i can see where the issue is coming from. in the response to this call, there's a response to my page with an 'id_token' which starts with a hash tag.

it's in a call similar to like this:
https://login.windows.net/erisimaent.onmicrosoft.com/oauth2/authorize?response_type=id_token&client_id=de8e0856-2576-443d-9d61-4746048a4a34&redirect_uri=http%3A%2F%2Fmyurl.com%2Fdashboard&state=0117e047-f251-44ed-95e9-5b4d3e86dea3&nux=1&x-client-SKU=Js&x-client-Ver=1.0.0&nonce=17a8aa4b-0a47-44c0-babc-7dad5b8ef1e9

there's a response header like this:
(see the beginning part here: .../dashboard#token_id:)
http://myurl.com/dashboard#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1uQ19...........&state=0117e047-f251-44ed-95e9-5b4d3e86dea3&session_state=6a0b068a-4beb-407c-a055-54702de57693
P3P:CP="DSP CUR OTPi IND OTRi ONL FIN"

then it redirects and basically removes everything after the # tag, so http://myurl.com/dashboard#

it seems to persist the hash tag here.

**Comment by bigerock** [comment]
ok. sorry i didn't see your base href tag before - i think there was something going on with the display in the browser. anyway, i do not see anything in local storage (using Chrome F12 developer tools). could this be the issue? perhaps it's throwing an error before going to login and that's causing this whole thing?

i can send you an example (a zip file of my project) if you wish to see it in action.

**Comment by omercs** [comment]
If you have the base tag in the header and your link is without '#', it should work normally. Sample code here is setting to html5 mode. 

```html
<head>
    <title>Angular Adal Sample v3</title>
    <base href="/mySPA.html" >
</head>
<body ng-app="adalDemo" ng-controller="homeController as hmCtl" ng-init="hmCtl.init()" ng-strict-di>
    <a href="/home">Home</a>
    <a href="/todoList">ToDo List</a>
    ....

```
sample js to use
```js
'use strict';
var app = angular.module('adalDemo', ['ngRoute', 'AdalAngular']);

app.config(['$httpProvider', '$routeProvider', 'adalAuthenticationServiceProvider', '$locationProvider', function ($httpProvider, $routeProvider, adalAuthenticationServiceProvider, ) {
    $locationProvider.html5Mode(true).hashPrefix('!');
    $routeProvider.when('/home', {
        controller: 'homeController',
        templateUrl: '/App/Views/landingPage.html',
    }).   
    when('/todoList', {
        controller: 'todoListController',
        templateUrl: '/App/Views/todoList.html',
        requireADLogin: true
    }).
    otherwise({ redirectTo: '/home' });
```

**Comment by bigerock** [comment]
ok. i do have it just like that. there must be something else going on. right before it does the redirect to the azure logon, it throws an error that the page i'm trying to go to (which is protected by adal) is failing to load. then it goes on to the azure logon without issue, except it comes back with that hash. also local storage is empty.

i click a link that takes me to the protected url (/dashboard) and...
this is the error it gets before redirecting to azure:

Error: [$compile:tpload] Failed to load template: app/dashboard/dashboard.html
http://errors.angularjs.org/1.3.0/$compile/tpload?p0=app%2Fdashboard%2Fdashboard.html
    at REGEX_STRING_REGEXP (angular.js:80)
    at handleError (angular.js:15773)
    at processQueue (angular.js:12914)
    at angular.js:12930
    at Scope.$get.Scope.$eval (angular.js:14123)
    at Scope.$get.Scope.$digest (angular.js:13939)
    at Scope.$get.Scope.$apply (angular.js:14227)
    at bootstrapApply (angular.js:1487)
    at Object.invoke (angular.js:4152)
    at doBootstrap (angular.js:1485)

do you think this is what's affecting it?

**Comment by bigerock** [comment]
local storage came back. still don't know where that error is coming from. it's a routechange error that happens right before the redirect to login.

**Comment by omercs** [comment]
I suggest to follow the sample from the start and then add the sample code above for html5 mode. You can play with the routing settings.  If all of those does not work for you, send me your sample project to my github account email.

https://github.com/AzureADSamples/SinglePageApp-DotNet

**Comment by bigerock** [comment]
hi - i sent you a copy of my project. i did notice the following. upon return to my site from azure authentication, it removes the hash (plus the info) in the url, but it keeps the hash itself.

i've narrowed it down to the code in adal-angular.js
line 88:
 var requestInfo = _adal.getRequestInfo(hash);
_adal.saveTokenFromHash(requestInfo);
$window.location.hash = '';

before the last line the url is this: http://myurl.com//dashboard#id_token=eyJ0eXA......i[MY TOKEN ABBREVIATED].......&session_state=864cad12-b20e-4080-8dc0-28a3c0d4f763

and then it's this: http://myurl.com//dashboard#

notice the hash at the end. if i remove it and reload the page (/dashboard), then everything works fine.

the hash is causing this infinite loop issue. maybe there's something else going on in my code which is affecting it? but if i remove adal angular itself from my code, everything works fine.

**Comment by omercs** [comment]
Can you send that again with subject line as the issue title?

I think problem is with routing setup. Did you build your sample using our samples?

**Comment by bigerock** [comment]
sure. i'll send you what i have at this moment. i've reverted back to not using html5 mode and it works fine. i'd still like to use html5 mode however. i'll resend. and no, i didn't exactly use your sample project, but mine is extremely simple and should illustrate the issue.

**Comment by omercs** [comment]
Url change is getting into loop for html5mode if you append '#' to the path and try to visit the page. This is related to the angular. MVC type page is getting into this issue. Samples we have are serving single html page and working fine in html5mode. I made a small fix to avoid this fragment. Please try https://github.com/AzureAD/azure-activedirectory-library-for-js/tree/prevent_digest_html5 

and let me know.

**Comment by bigerock** [comment]
success! that works perfectly. i had a similar solution, but couldn't get it working. thank you!

**Comment by bigerock** [comment]
This probably shouldn't be closed yet since it redirects to undefined.

**Comment by aryanreddy** [comment]
Hi Friends,

Need quick help on adal-angular authentication.

i'm using html5 mode routing along with adal.js latest version 1.0.14 and NgRoute.

1. in index.html page added the base page like 
      <base href="http://localhost/index.html" />

2. in app routing

  $locationProvider.html5Mode(true).hashPrefix('!');

 let endpoints: any = {};
            endpoints[webApiUrl] = clientId;
 adalAuthenticationServiceProvider.init({
                instance: 'https://login.microsoftonline.com/',
                tenant: 'microsoft.onmicrosoft.com',
                clientId: "************************************",
                cacheLocation: 'localStorage', // to support IE
                extraQueryParameter: 'nux=1',
                endpoints: endpoints,
                anonymousEndpoints: [
                    "App/Header/header.html",
                    "App/Footer/footer.html",
                    "App/Home/Views/Home.html"
                ]
            }, $httpProvider);


after user is authenticated from active directory we are redirecting the user to "/home".
but it is showing page is not found for the first time. from second time  on wards it is redirecting to "/home" without any issues.

please guide me what i missed other than this config.




Thanks & Regards,
Dharma Reddy B.
