### ISSUE TITLE
Not able to set AAD token AUD field

### ISSUE THREAD

**Issue by sagnikm95** [AzureAD/azure-activedirectory-library-for-js#890]
Hi, i am not able to to set the AUD field in the token I am acquiring.
![image](https://user-images.githubusercontent.com/25024356/68880734-d2d22200-0731-11ea-8506-fee425e0c6f4.png)
When I decrypt the AAD token I am getting , the AUD is set to the client iD, whereas I was expecting it to be the uri I am specifying in the end points property.
As a result when I am using the acquired token to call the above endpoint I am getting a authorization error.
Please let me know where I am going wrong

**Comment by sameerag** [comment]
@hpsin for `id_token` claims.

**Comment by hpsin** [comment]
The ID token always has the client ID as the audience. The audience is who the token is for. ID tokens are always for the client.

If you want a token for another audience, request an access token for that resource.

**Comment by jmckennon** [comment]
Closing this as we're assuming this is no longer an issue. We recommend that everyone switch to `msal js` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) for advanced features and bugfixes.
