### ISSUE TITLE
Change Locale

### ISSUE THREAD

**Issue by ranouf** [AzureAD/azure-activedirectory-library-for-js#892]
Hi,

It seems possible to specify which locale we want in azure AD using ui_locales, do you know how to specify it using your library?

Thanks

**Comment by sameerag** [comment]
Can you try passing this in `extraQueryParameters`? Usage is [here](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Acquire-tokens)

**Comment by jmckennon** [comment]
Closing this as we're assuming this is no longer an issue. We recommend that everyone switch to `msal js` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) for advanced features and bugfixes.
