### ISSUE TITLE
AADSTS50058: Silent Sign-in fails on Safari browser in Angular 7 app

### ISSUE THREAD

**Issue by hiteshtare** [AzureAD/azure-activedirectory-library-for-js#894]
## I'm submitting a...
[ ] Bug report

## Browser:
- [ ] Safari version 13.0.4

## Library Name
- [ ] adal-angular 1.0.17
- [ ] angular/core 7.1.0

## Library version
Library version: 1.0.17

## Current behavior
Throws the following error in console:
_[Error] AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com).
Trace ID: f7d44d7c-aa81-4071-9d37-e659a1c54900
Correlation ID: 0a29cef7-2645-480c-a468-d6c4a7aa4a15
Timestamp: 2020-01-10 09:34:42Z
    (anonymous function) (polyfills.20ab2d163684112c2aba.js:1:3046)_

## Expected behavior
**Silent sign-in request should be completed successfully.** 

## Minimal reproduction of the problem with instructions
1.Create Angular 7 app using angular cli.
2.Install adal-angular npm module.
3.Create Adal authentication login page.
4.Test this application on on Safari Browser (13.0.4) on MacOS (Catalina 10.15.2).
5.Authentication fails stating error AADSTS50058 has occured
![sso_error](https://user-images.githubusercontent.com/2217802/72154487-c3402400-33d6-11ea-9a0c-454b21644448.png)

</code></pre>

**Comment by jasonnutter** [comment]
@hiteshtare Is Safari Intelligent Tracking Protection enabled? If so, it is a known issue that this will break login with our libraries. This will be addressed in `msal` by switching from the Implicit Flow to the Auth Code Flow, but will not be addressed in ADAL.

**Comment by gavrielsl** [comment]
@jasonnutter we also have this problem.

did you know how to solve it ?

**Comment by jasonnutter** [comment]
@gavrielsl Are third-party cookies disabled? If so, the workaround is to enable third-party cookies (and disable ITP). Otherwise, you will need upgrade the next version of MSAL (currently in development, not ready for production yet) which will mitigate Safari (in most scenarios) by switching to the Auth Code Flow w/ PKCE.
