### ISSUE TITLE
Is there any work is happening to solve Samesite cookie issue fro google chrome browser?

### ISSUE THREAD

**Issue by niravkanakhara** [AzureAD/azure-activedirectory-library-for-js#895]
Is there any work is happening to solve Samesite cookie issue for google chrome browser?

I know the expectation is to migrate existing application from adal-angular to msal-angular, but considering the seriousness of production application, would it be possible for adal-angular team to provide intermediate fix on adal-angular for Samesite cookie issue?

Meanwhile I am trying to ask my team stretch little to upgrade the existing application to msal-angular?

Thanks,
Nirav

**Comment by jasonnutter** [comment]
We have made the necessary updates in AAD to solve the Samesite cookie changes coming to Chrome (no updates are needed to the library itself).

**Comment by sandysandajan** [comment]
Hi, 

Does this mean that there would be no updates on the library to handle the issue? Currently we are experiencing the samesite issue. 
![image](https://user-images.githubusercontent.com/34727891/73730485-c8905480-4771-11ea-9dbe-371853faaa18.png)

We are using v1.0.10. 

Regards,
Sandy

**Comment by jasonnutter** [comment]
@sandysandajan The cookies that are causing that message have no impact on authentication for the library, as the necessary cookies have been properly updated. Closing.
