### ISSUE TITLE
Questions regarding SameSite Chrome 80 Issue

### ISSUE THREAD

**Issue by sandysandajan** [AzureAD/azure-activedirectory-library-for-js#896]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x ] Chrome version 80
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library Name
- [x] adal.js XX
- [ ] adal-angular XX

## Library version
Library version: 1.0.10

## Current behavior
When accessing the adal request using office385, this shows in the developer tools. 
![image](https://user-images.githubusercontent.com/34727891/73803823-e1921780-47fc-11ea-823d-7dada928970d.png)

## Expected behavior
No warning when opening the developers tools.

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by sandysandajan** [comment]
To add, https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/895, it says in this issue that there would be no updates on the library for this one. If none, what would be the work around or alternative solution so that there would be no error/warning to be found when opening the developer tools.

**Comment by jasonnutter** [comment]
@sandysandajan Some cookies were intentionally not marked as `SameSite`, but those do not impact the functionality of the library. So any warnings for `login.microsoftonline.com` can be ignored. More: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1037#issuecomment-578345613

**Comment by jasonnutter** [comment]
Closing, as no further action. Let us know if you have further questions.
