### ISSUE TITLE
Login with client secret

### ISSUE THREAD

**Issue by lingfeidiewu** [AzureAD/azure-activedirectory-library-for-js#905]
Is there any way to login by the client secret string with ADAL.js?

**Comment by jasonnutter** [comment]
@lingfeidiewu No, there is not. ADAL.js implements the Implicit Flow, which is for public client applications. Public client applications are for scenarios where the client application cannot keep a secret (e.g. web browsers), such as a secret key.  

ADAL Node will support authentication via secret key: https://github.com/AzureAD/azure-activedirectory-library-for-nodejs
