### ISSUE TITLE
Resource Owner Password Credential Grant in browser

### ISSUE THREAD

**Issue by cclauson** [AzureAD/azure-activedirectory-library-for-js#908]
Is it possible to do an [ROPC grant](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc) in the browser using ADAL? I'm fully aware of all of the OAuth caveats surrounding this grant, but it would actually be extremely useful in my situation for the purposes of automated testing.

Thanks

**Comment by jasonnutter** [comment]
@cclauson It is not currently possible to do ROPC with ADAL.js, and we have no plans to add it to ADAL or MSAL.
