### ISSUE TITLE
Calling acquireToken after login

### ISSUE THREAD

**Issue by andreesteve** [AzureAD/azure-activedirectory-library-for-js#91]
So for my scenario I had to do this:

0. setup cache storage as local storage
1. call login
2. call handleWindowCallback after AAD redirect
3. call adquireToken to another resource (other app)

The problem is that inside adquireToken method, it tries to get the user from memory (this._user). However, login() has navigated to AAD webpage and redirected back to my web page. So in this case, the memory of my web page is fresh new, meaning that this._user is undefined - thus adquireToken doesn't work.

As a workaround, I had to do something like this:

0. setup cache storage as local storage
1. call login
2. call handleWindowCallback after AAD redirect
3. call getUser (this is the workaround - this will read the user from local storage and populate this._user inside the context)
4. call acquireToken

My suggestion is that, in the acquireToken code would call getUser internally so I don't need to do that myself.

**Comment by omercs** [comment]
We have sample here for using adal.js without angular https://github.com/AzureADSamples/SinglePageApp-jQuery-DotNet/blob/master/TodoSPA/App/Scripts/app.js

handleWindowCallback sets the user to the memory and this should be the page that you were redirected. Next api calls will have token and user. Is this single page app?

**Comment by andreesteve** [comment]
Hi Omer,

Thanks for the reply.
In my scenario, I actually want to call acquireToken on another page (other than the one AAD redirects me back to).

I think what is going on is that handleWindowCallback navigates to a different page (line 741: 
        window.location = this._getItem(this.CONSTANTS.STORAGE.LOGIN_REQUEST); ) - this is why the user is not in memory when I try to call acquireToken on my other page.

Something like:

Page A -> AAD login Page -> Redirected Page B (handleWindowCallback is called here) -> Page A

This is why I believe calling getUser() inside of acquireToken, instead of using the in-memory one, would add support to this scenario.

**Comment by omercs** [comment]
We could consider adding that or you can send pull request. We mainly target single page apps.

**Comment by tushargupta51** [comment]
Closing this issue as a low value fix.
