### ISSUE TITLE
Acquire token silently fails when MFA code is required

### ISSUE THREAD

**Issue by XI1687-kapilmittal** [AzureAD/azure-activedirectory-library-for-js#912]
InteractionRequiredAuthError: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access.

I am getting this issue when trying to get token silently.

**Comment by jasonnutter** [comment]
@XI1687-kapilmittal Apologies for the delay. Silent token acquisition can fail for many reasons, including for MFA challenges due to conditional access, which this error appears to be. You can resolve this by invoking one of the interactive methods, acquireTokenPopup or acquireTokenRedirect.
