### ISSUE TITLE
CDN Links from the README don't work

### ISSUE THREAD

**Issue by Aymkdn** [AzureAD/azure-activedirectory-library-for-js#923]
Hi,

FYI the links provided in the README dont' work:
```html
<!-- Latest compiled and minified JavaScript -->
<script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.18/js/adal.min.js"></script>
<script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.18/js/adal-angular.min.js"></script>
```

The link returns:
```xml
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:b90997cc-501e-0021-380d-a2234b000000 Time:2020-10-14T09:33:41.2681132Z
</Message>
</Error>
```

**Comment by jasonnutter** [comment]
@Aymkdn Apologies, there has been a delay in getting the latest build uploaded to the CDN. I'll update when that has been resolved.

**Comment by MikaBerglund** [comment]
I noticed the same when adding the CDN URL to my app. The previous version 1.0.17 is available at https://secure.aadcdn.microsoftonline-p.com/lib/1.0.17/js/adal.min.js, but you probably figured that our already.

**Comment by jasonnutter** [comment]
Closing, as the cdn has been updated, apologies for the delay.
