### ISSUE TITLE
Optimize for better minification

### ISSUE THREAD

**Issue by rbrundritt** [AzureAD/azure-activedirectory-library-for-js#925]
I noticed that this library was fairly large. When looking through the source code I noticed there is a lot of room for optimizations that will help with the minification process. A couple of tips:

- If you use the keyword "this" more than 3 times in a function, create a local variable for it and reference that. For example `var self = this;` The variable will be minified to a single character and save you 3 characters per use of the "this" keyword. 
- Create local variables of repeative variable paths to improve minifications but also reduce the variable lookup time. for For example:
     - For `this.config` cache like `var config = self.config;` This will save 10 characters per per use. 
     - For `this.CONSTANTS.STORAGE` cache like `var = this.CONSTANTS.STORAGE;` This will save 19 characters per use.

I'm sure there are some additional optimizations that can be made to help reduce the file size. I wouldn't be surprised if this could the file size could be cut by 30% or more.

**Comment by jasonnutter** [comment]
@rbrundritt Thanks for the feedback. Given ADAL.js is no longer under active development, we won't be prioritizing enhancements like this. We highly suggest apps to move to MSAL.js: https://www.npmjs.com/package/@azure/msal-browser
