### ISSUE TITLE
Logout Error On Safari

### ISSUE THREAD

**Issue by zachcarroll** [AzureAD/azure-activedirectory-library-for-js#93]
When using the exposed adalAuthenticationService.logOut(); method to log a user out in Safari, the user ends up on a microsoft page that states: "Sorry, but we are having trouble logging you out" Screenshot below:
![screen shot 2015-03-05 at 1 15 30 pm](https://cloud.githubusercontent.com/assets/4523019/6511277/c7ba3fa6-c339-11e4-8609-fcc038d4b544.png)

**Comment by omercs** [comment]
Is this consistent?

Do you specify post_logout_redirect_uri?

**Comment by zachcarroll** [comment]
It is 100% consistent across desktop and mobile for Safari.  I have not specified a post_logout_redirect_uri.  I'm happy to try to specify a redirect, where can I do this?

**Comment by omercs** [comment]
Inside the config where you specify clientid.

**Comment by zachcarroll** [comment]
Even with the postLogoutRedirectUri set (which I confirmed was working on Chrome), I still get the same error as posted above when trying in Safari.

I also noticed that when using a private browsing window in Safari, the redirect for logging in does not seem to work either, and I am able to get to a page in my app that should be behind the authentication wall.

**Comment by zachcarroll** [comment]
@omercs any update on this issue?

**Comment by omercs** [comment]
I am able to repro that on safari. I will follow up with server side for potential solutions.

**Comment by zachcarroll** [comment]
@omercs has there been any progress on this server side?

**Comment by omercs** [comment]
Lets keep open until we resolve this. I will ping them again.

**Comment by zachcarroll** [comment]
hey @omercs do you know if there has been any movement on this? Is there someone I can follow up with on the server side?

**Comment by omercs** [comment]
Issue looks like related to the thirdparty cookies. I dont have resolution yet. I will update here for this issue.

 This request is failing:

```
GET https://login.microsoftonline-p.com/ThirdPartyCookieCheck.srf?tpc=97766091&lc=1033 HTTP/1.1
Host: login.microsoftonline-p.com
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/534.57.2 (KHTML, like Gecko) Version/5.1.7 Safari/534.57.2
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US
Referer: https://login.microsoftonline.com/logout.srf?wa=wsignout1.0&lc=1033
Connection: keep-alive
Proxy-Connection: keep-alive
```

**Comment by omercs** [comment]
You can add extraQueryparameter : "nux=1" to work around this issue.

```js
 adalAuthenticationServiceProvider.init(
        {
            // Config to specify endpoints and similar for your app
            tenant: '0fd15.....f80',
            clientId: 'cb6....a5c',
            extraQueryParameter : "nux=1",
            //instance: 'https://login.windows-ppe.net/',
            //redirectUri : 'your site', optional
           //endpoints: endpoints,  // optional
           // cacheLocation: 'localStorage' // optional cache location default is sessionStorage
        },
        $httpProvider   // pass http provider to inject request interceptor to attach tokens
        );
```

**Comment by zachcarroll** [comment]
okay, thanks, that worked.

**Comment by omercs** [comment]
Ok. Closing this issue.

**Comment by zachcarroll** [comment]
Thanks for this. Can you just briefly explain what adding that nux=1 is
actually doing?
