### ISSUE TITLE
Can ADAL.js point to v2.0 endpoints

### ISSUE THREAD

**Issue by nominds** [AzureAD/azure-activedirectory-library-for-js#930]
I read from the documentation MSAL supports both v1.0 and v2.0 endpoints. ADAL supports only requesting tokens from v1.0 endpoint. URL: [https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-compare-msal-js-and-adal-js](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-compare-msal-js-and-adal-js) 

If I update the endpoints in the config (configuration file) and point it to v2.0 endpoints - I can continue to use ADAL and support only Work/School/Guests accounts.

Is that advisable or raise any risks ?

**Comment by jasonnutter** [comment]
@nominds We do not recommend continuing to use ADAL, and highly suggest moving to MSAL, especially if you need to use the v2 endpoints, as ADAL.js is not tested with the v2 endpoints.

**Comment by jasonnutter** [comment]
Closing, please let us know if you have further questions by posting in the MSAL.js repo: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues
