### ISSUE TITLE
Renew token fails with "Refused to display ... in a frame because it set 'X-Frame-Options' to 'DENY'."

### ISSUE THREAD

**Issue by andreesteve** [AzureAD/azure-activedirectory-library-for-js#94]
Configuration: save tokens to local storage.
Repro:
1) Perform a successful login()
2) Perform  a successful acquireToken for a different resourceId than your client's
3) Close the browser (so logout() is not called)
4) Wait until the token expires
5) Open the web site and try to perform same steps again.

Expected result: user is redirected to the AAD login page
Actual result: access token is requested in iframe

---------------------

I believe the problem spawns the adaljs and my app.
On my side, I try to check if I need to call login() by calling getUser(). If I get a valid user, then I proceed and call acquireToken() - otherwise I call login().

However, I believe, in the scenario above, both the ID token and access token are expired, so trying to get the access token can only be done if we get a new ID token first (for that, I believe AAD service silently redirects the iframe request to the AAD login page, which has X-Frame-Options to block iframes).

Is there a way I call tell if the ID token is expired or not (pretty much, is there a way I can tell if I should call login or not?).

On the other hand, shouldn't getUser() fail with error (as it does if no ID token exists) if the ID token is expired?

(sorry for any confusion if I got the wrong meaning of access and ID tokens)

---
Bellow is the console log:

LoadFrame: adalRenewFrame
adal.min.js:2 Add adal frame to document:adalRenewFrame
adal.min.js:2 LoadFrame: adalRenewFrame
about:blank:1 Refused to display 'https://login.windows.net/common/oauth2/authorize?response_type=token&clien…n_hint=[omited].onmicrosoft.com&nonce=c4edc064-8252-4c89-9e08-3a58cf388f6e' in a frame because it set 'X-Frame-Options' to 'DENY'.
adal.min.js:2 Add adal frame to document:adalRenewFrame

**Comment by omercs** [comment]
Are you testing this in IE with localhost? IE iframe only works with full domain names.

**Comment by andreesteve** [comment]
Hi,
I saw this problem with Chrome, actually.
Yes, I'm using a full domain name.
I'll try on IE and update this thread.
Thanks.

**Comment by andreesteve** [comment]
Hi,
this repros on IE as well with a full domain name.

Also the problem happens despite it is a renew token call or not.
If you get your id token, then wait for a long time and ask for an access token, the browser will fail the request due to X-Frame-Options, but the library will never call the error callback.

Same thing for the renew flow.

**Comment by vood** [comment]
I'm having exactly the same problem. Any news?

**Comment by tushargupta51** [comment]
@andreesteve @vood Do you still have this issue? Is the iFrame in the same domain as the app? Can you share logs at verbose level? You can add this to your app.js:

Logging = {
    level: 3,
    log: function (message) {
        console.log(message);
    }
};

**Comment by tushargupta51** [comment]
This issue occurs because of nested iframes. We have released 1.0.11 with the fix. Please use those bits have a look here: https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs#q4-i-get-this-error-refused-to-display--in-a-frame-because-it-set-x-frame-options-to-deny
