### ISSUE TITLE
State Param routing fails with parameterized states

### ISSUE THREAD

**Issue by whein** [AzureAD/azure-activedirectory-library-for-js#95]
Hello! This is my first issue log ever, so feel free to give me tips.

In our application, we make heavy use of $stateProvider's ability to use parameterized routes - ie /Car/{carId}. However, we noticed our application failed to load the correct page after authentication.

For example, we navigate to www.example.com/Car/23. ADAL correctly finds we are not authenticated. We authenticate and return to the app. The application navigates incorrectly to www.example.com/Car/{carId}.

Investigating this issue, I found that the stateChangeHandler of adal-angular.js assumes non-parameterized routes.

CODE:

     var resolveUrl = function (templateUrl, parameters) {
         var url = templateUrl;
             for (var key in parameters) {
                 if (parameters.hasOwnProperty(key)) {
                     url = url.replace("{" + key + "}", parameters[key]);
                 }
              }
          return url;
       }
                
    var stateChangeHandler = function (e, nextRoute, nextRouteParams) {
        if (nextRoute && nextRoute.requireADLogin) {
            if (!_oauthData.isAuthenticated && !_adal._renewActive) {
            console.log('Route change event for:' + nextRoute.url);
            if (_adal.config && _adal.config.localLoginUrl) {
            $location.path(_adal.config.localLoginUrl);
            } else {
                _adal._saveItem(_adal.CONSTANTS.STORAGE.START_PAGE, resolveUrl(nextRoute.url, nextRouteParams));
                    console.log('Start login at:' + window.location.href);
                    $rootScope.$broadcast('adal:loginRedirect');
                    _adal.login();
                    }
                }
            }
        };

As you can see, the call to resolveUrl replaces the url parameters (denoted by braces) with the parameters given to the stateChange event.

**Comment by omercs** [comment]
Yes, it looks like a bug. nextRoute.url needs to be changed to "$location.$$path"

**Comment by omercs** [comment]
You can send us a pull request to fix this if you want. You need to read the contribution and sign cla form.
