### ISSUE TITLE
Use Promises instead of callbacks

### ISSUE THREAD

**Issue by mattmazzola** [AzureAD/azure-activedirectory-library-for-js#98]
It looks like this library is using the node-style of passing in callbacks with signature of 
`(error, result) => { }` to chain a function as opposed to using promises.

From my understanding this library is designed to work on the client and does not have use on the server therefore it should be following client side javascript practices instead of node style practices. The callback design leads to worse quality of code when people attempt to chain and seems only beneficial to people who don't understand promises.  I could see callback design to be viewed as having lower conceptual complexity for newcomers but it is at the cost of the library's apis quality.  
Maybe you could argue the state machine in promises introduce unnecessary overhead and force extra delay as the chained methods are forced to execute on the next event loop, but they seem like a more semantic way to handle these conditional results, if you choose not to just return values.

The Promise spec is finalized and already in Chrome and other modern browsers so I assume it should be trivial to do feature detection and only include the extra library for promise implementation if needed. 90% of the time people would already be using jQuery or another framework which includes promise implementation anyways.

**Comment by omercs** [comment]
We did not add promises to adal javascript since our focus was angular layer which have support for that. It makes sense to add support to adal.js since we separated them.

**Comment by alrouen** [comment]
+1

**Comment by brphelps** [comment]
+1

**Comment by jwooley** [comment]
+1 

Also voting for this request. I'm trying to retrofit a site that leverages jQuery ajax requests and returns the resulting promise to callers that can then extend the success/error pipeline externally to the data request. Trying to chain this strategy within the constraints of the current adal.js implementation (1.0.9) is challenging.

**Comment by tushargupta51** [comment]
The support for promises will appear in next generation of adal library - MSAL. We do not plan to add this support to adal at the moment.
