### ISSUE TITLE
ADAL.JS sign on fails only in IE

### ISSUE THREAD

**Issue by eiximenis** [AzureAD/azure-activedirectory-library-for-js#99]
Hi. I use ADAL JS to use sign on of an angular web against Azure Active Directory.
In Firefox and in Chrome everything works as expected, and following message is printed in the console:

"The returned id_token is not parseable."
"State: dd217b75-7a49-41ae-aef5-49e028274641
"State status:true"
"State is right"

But the same application in IE, prints the following:
"The returned id_token is not parseable."
"State: 3cb8de63-74a9-468d-af78-091a3a512bce"
"State status:false"

And if i try to go to any protected route (i am using adal-angular) i just got a redirection to the otherwise route of my application (so, i can't go to any protected route).

Why appears the message "The returned id_token is not parseable."?
And also, why (even the message) the behavior in Chrome and in FF is as expected but not in IE? 

Please note that i don't access to any protected webapi, just doing login stuff.

**Comment by eiximenis** [comment]
My fault... sorry... i did NOT put the line  cacheLocation: 'localStorage' when configuring ADAL.

Greetings!

**Comment by sergsalo** [comment]
i also started to see this issue, but i have localStorage in place for ADAL configuration. Sample also fails. Here is the issue for the sample: https://github.com/AzureADSamples/SinglePageApp-WebAPI-AngularJS-DotNet/issues/3#issuecomment-79172963. Confirmed by couple other people

**Comment by sergsalo** [comment]
eiximenis, were you able to get this working?

**Comment by omercs** [comment]
Sample is related to Cors API usage. CORS API calls uses iframe to get access token for your endpoint. iframe only works for fully qualified domain name in IE. It does not work for localhost in IE.

**Comment by eiximenis** [comment]
Hi, Sorry for the delay,
Yes, i get the sample working with AAD authentication and WebApi authorization.

Greetings

**Comment by omercs** [comment]
I will close this and update Readme file for this.
